### ISSUE TITLE
Entropy length error on Mnemonic.cs is misleading

### ISSUE THREAD

**Issue by bitcoinbrisbane** [MetacoSA/NBitcoin#1000]
I think this is a bit confusing.  Perhaps the error should be length / 8? given the exception message is _The length for entropy should be 128_ and my code is:

```csharp
            byte[] entropy = new byte[128];
            Org.BouncyCastle.Security.SecureRandom secureRandom = new Org.BouncyCastle.Security.SecureRandom();
            secureRandom.NextBytes(entropy);
            Mnemonic mnemo = new Mnemonic(Wordlist.English, entropy);
```

Where as the below is valid.

```csharp
byte[] entropy = new byte[32];

```

https://github.com/MetacoSA/NBitcoin/blob/master/NBitcoin/BIP39/Mnemonic.cs#L53

**Comment by DanGould** [comment]
May be best to include the measure word

**Comment by bitcoinbrisbane** [comment]
> May be best to include the measure word

I think throwing an exception is fine just with the correct byte array length.

**Comment by lontivero** [comment]
Entropy is measured in bits so, the error message is correct.

**Comment by bitcoinbrisbane** [comment]
> Entropy is measured in bits so, the error message is correct.

Not really, the error specifically says length and does not mention bits, which is normally inferred as length of the array you're passing. How about just adding " bits" to the end of the error message?  As a dev, when I see `byte[64]` and the error saying `length should be 64` its confusing

**Comment by NicolasDorier** [comment]
make sense, can create a PR
