### ISSUE TITLE
#931 Disable input shuffling broken again?

### ISSUE THREAD

**Issue by nwasiq** [MetacoSA/NBitcoin#1001]
So this is my code:

` var txBuilder = network.CreateTransactionBuilder();

            txBuilder.ShuffleInputs = false;
            txBuilder.ShuffleOutputs = false;

            foreach (Coin coin in inputCoins)
            {
                txBuilder.AddCoins(coin);
            }
`
This should stop the shuffling but everytime I get a different order of inputs. Am I missing something? Disable shuffling outputs works fine.

This was previously fixed here: [https://github.com/MetacoSA/NBitcoin/pull/932](url)

I even updated NBitcoin but no luck. 

Edit: I'm using the LTC network

**Comment by NicolasDorier** [comment]
mmh that's indeed strange. Taking a look.

**Comment by NicolasDorier** [comment]
I checked about it, the randomness come from the coin selector.

Basically the way transaction is built by default is :

1. Coin selection
2. Input shuffling
3. Output shuffling

2 and 3 are disabled, but coin selection is inherently random.
You can remove the randomness with

This still shuffle it, but it will be shuffled the same time every time 

`txBuilder.CoinSelector = new DefaultCoinSelector(0);`

**Comment by nwasiq** [comment]
@NicolasDorier thank you for looking into it. I bypassed this issue by manually resetting the inputs to the correct indices for the created transaction (by looping over the inputs of the transaction).

**Comment by NicolasDorier** [comment]
@nwasiq you also have another possibility if you requires exact ordering: Just create your own CoinSelector.
I think it should be straightforward.

**Comment by knocte** [comment]
@NicolasDorier but @nwasiq's last comment says that his workaround is about adjusting inputs, so seems the bug is not related to coin selection?

**Comment by NicolasDorier** [comment]
It is, because he expect a specific certain order of input.
The coin selection select the coins at random, and thus the resulting input will be ordered randomly.

By doing `txBuilder.CoinSelector = new DefaultCoinSelector(0);` you make sure that the random generator always use the same seed, so your input will always be ordered the same given you have the same set of coin.

But afaik, he wants a specific order, not a deterministic one. If that's the case, making your own CoinSelector seems the best.

**Comment by knocte** [comment]
> By doing txBuilder.CoinSelector = new DefaultCoinSelector(0);

Shouldn't this allow passing null rather than 0? With 0 there is still randomness, even if it's a deterministic randomness.
I've proposed this as a PR here: https://github.com/MetacoSA/NBitcoin/pull/1012
