### ISSUE TITLE
Success Boradcase, but INVALID, Unknow Response

### ISSUE THREAD

**Issue by TesoraFinancial** [MetacoSA/NBitcoin#1002]
"Hey, it is possible the problem comes from QBitNinja for this. Can you try to push with https://www.smartbit.com.au/txs/pushtx ? and tell me if it works?"

Nicholas, you replied to a previous post with the above response.  I did this, after using the transaction builder, The sequence of calls after building the transaction with the transaction builder was to first call tx. Verify, and it did not show any errors, I then called Broadcast and it replied with success, but in the response, it had INVALID and Unknown.  

So just prior to the broadcast, I did the tx.ToHex() and posted on smarbit.com.au.  It was successful on smartbit.com.au and sent the coins to the receiving address.

Is this something you can look into or need me to do?  I would like to use QBitNinjaClient(Network.Main) to broadcast the transaction.

Thanks,

**Comment by NicolasDorier** [comment]
@TesoraFinancial sorry for late reply. I am retiring slowly QBitNinja, it is not fully working, and I won't fix it.

I advise you to use https://github.com/dgarage/NBXplorer/ instead with your own full node if you want to track a wallet.
NBXplorer has the advantage to work in pruned mode and does not require a full rescan of the blockchain.

If all you want is to broadcast, you can use your own bitcoin full node and use RPCClient class in NBitcoin to broadcast it.
