### ISSUE TITLE
error dogecoin fee

### ISSUE THREAD

**Issue by maede71** [MetacoSA/NBitcoin#1010]
I use NBitcoin.Altcoins.Dogecoin,
I create a dogecoin transaction and don't verify

when stimatefee:
!txBuilder.Verify(tx, out TransactionPolicyError[] errors)
with error:
"Fee too high, actual is 1.10000000, policy maximum is 0.04360000"
The transaction is not approved for a long time when use blockcypher api, how i can calculate it?

**Comment by maede71** [comment]
resolve it : transactionBuilder.StandardTransactionPolicy.MaxTxFee = null;
help:
https://github.com/MetacoSA/NBitcoin/blob/master/NBitcoin.Tests/transaction_tests.cs

**Comment by NicolasDorier** [comment]
I will fix this, I am surprised nobody had this problem before.

**Comment by NicolasDorier** [comment]
Pushed NBitcoin.Altcoins 2.0.34 which should fix it, can you try and close the issue if that solve the issue?

**Comment by maede71** [comment]
thank you
