### ISSUE TITLE
Track taproot PRs in NBitcoin

### ISSUE THREAD

**Issue by dangershony** [MetacoSA/NBitcoin#1015]
Hi all,
I wanted to start a discussion about what we need in order to get any taproot components implemented in NBitcoin 
for example P2TR, or any Script changes etc...

Has anything been done in that direction already?

**Comment by NicolasDorier** [comment]
I actually started it in a private PR one sec, need to publish it

**Comment by NicolasDorier** [comment]
It is still in process, let's move discussion there.

https://github.com/MetacoSA/NBitcoin/pull/1016

**Comment by dangershony** [comment]
@NicolasDorier I propose to keep this issue open (or create a new one) where we can track all the taproot changes (there will probably be a series of PRs)

**Comment by dangershony** [comment]
Another PR to track
https://github.com/MetacoSA/NBitcoin/pull/1019

**Comment by NicolasDorier** [comment]
Support for taproot address support is done #1016
I'd like to implement at least signature for single sig taproot and the interpreter.

**Comment by dangershony** [comment]
Another PR to the list https://github.com/MetacoSA/NBitcoin/pull/1024

**Comment by NicolasDorier** [comment]
need also integration to the transactionbuilder.

**Comment by NicolasDorier** [comment]
Can validate keyspend (done) https://github.com/MetacoSA/NBitcoin/pull/1026

**Comment by dangershony** [comment]
One more to the list #1037

**Comment by NicolasDorier** [comment]
Closing this one, will need probable changes to better support tapscripts in the transaction builder. But everything has been done.
