### ISSUE TITLE
Qbitninja : client.GetBalance returns NULL

### ISSUE THREAD

**Issue by AbdulSidd** [MetacoSA/NBitcoin#1055]
Hi there,

I am trying to read the balance from a multisig address, that contains 1 transaction; can be viewed with the following url:
https://www.blockchain.com/btc-testnet/address/2MxUbkAaNJGEeS57a4iazqQquHetn642YzZ
but, when i am trying fetching it with ""; it always returns NULL.
![image](https://user-images.githubusercontent.com/90469238/132885101-1a89fc70-1348-435e-8301-16db40b6cf97.png)

**Comment by NicolasDorier** [comment]
QBitNinja is quite deprecated right now, I will not fix it.

I advise you to use [NBXplorer](https://github.com/dgarage/NBXplorer)  instead, you can easily run it on your machine as long as you have a full node.

Here is a multi sig wallet [example](https://github.com/dgarage/NBXplorer/blob/master/Examples/MultiSig/Program.cs).

**Comment by knocte** [comment]
> QBitNinja is quite deprecated right now, I will not fix it.

Nicolas, your "Programming the blockchain with C#" book is plagued with references to QBitNinja. We should remove them then.

**Comment by NicolasDorier** [comment]
@knocte I should write a new book with NBXplorer. Problem is that QBitNinja is too deeply integrated into the book sadly.
