### ISSUE TITLE
Is NBitcoin suitable for building a blockchained social media platform?

### ISSUE THREAD

**Issue by dorkerdev** [MetacoSA/NBitcoin#1065]
Hello -

I am looking to build a social media platform as a personal project. I am brand new to blockchain tech and have only a minimal understanding of all that goes into it, but I figure diving right into it with some hands-on experience would be the best way to learn.

My platform would follow the standard formula of all social media platforms: Post content, like, share, comment, follow, block users... all the basic features you'd find on Facebook or Twitter basically. Would NBitcoin would be suitable for this endeavor?

Thanks.

**Comment by plasticalligator** [comment]
The guy asked a really simple question whose answer is "no". There is absolutely no reason to answer him with some half-assed snarky tone instead of just two letters.

**Comment by knocte** [comment]
I can't see how the answer can be no. You could perfectly build a social media which requires Lightning to create or view posts.

**Comment by plasticalligator** [comment]
>brand new to blockchain tech
>only a minimal understanding
>all the basic features you'd find on Facebook or Twitter
>Would NBitcoin would be suitable

Don't be disingenuous. NBitcoin doesn't even have up to date examples.

**Comment by knocte** [comment]
The question is if you can, not if it is easy.

**Comment by plasticalligator** [comment]
It'd be like asking if a senior citizen with the intellectual capacity of an eight year old can effectively lead the country during the worst economic turndown in history and saying sure he can.

**Comment by knocte** [comment]
Didn't you just describe Biden or Trump?

**Comment by dangershony** [comment]
> The guy asked a really simple question whose answer is "no". There is absolutely no reason to answer him with some half-assed snarky tone instead of just two letters.

Ha yeah I do agree but are you new to Bitcoin community or this space? 

> I am looking to build a social media platform as a personal project. I am brand new to blockchain tech and have only a minimal understanding of all that goes into it, but I figure diving right into it with some hands-on experience would be the best way to learn.

If I may intercept, you probably want to look at https://github.com/block-core/blockcore
There you can build your own blockchain on top of (a fork of) NBitcoin.

NBitocin is a library to interact with a blockchain node not exactly a node on its own.
