### ISSUE TITLE
Method `PubKey.GetSegwitAddress` removed without marking obsolete

### ISSUE THREAD

**Issue by su8898** [MetacoSA/NBitcoin#1068]
Public method `PubKey.GetSegwitAddress` was removed in commit https://github.com/MetacoSA/NBitcoin/commit/364677b9f5603950a189b3e5e257f123135b59f2 but it was not marked as `obsolete` in any of the previous versions. Do we have any other alternatives? 

Thanks

**Comment by NicolasDorier** [comment]
Yes, `Pubkey.GetAddress(ScriptPubKeyType.Segwit, Network.Main)` I should have been more careful put it obsolete for a while.

**Comment by knocte** [comment]
And BitcoinAddress.GetScriptAddress() has also disappeared?

**Comment by NicolasDorier** [comment]
Yeah, I don't even remember what this one did.

**Comment by knocte** [comment]
We finally migrated to 6.x in this commit: https://github.com/nblockchain/geewallet/commit/a16ef649386e59f5f3c3da25933ba5ed6e198886 . This issue can be closed.
