### ISSUE TITLE
Some Problem in Set Network AltCoins

### ISSUE THREAD

**Issue by erfan132** [MetacoSA/NBitcoin#1081]
Hello
Thanks For Publish NBitcoin
I have some Problem With Altcoins 
{"Method not found: 'NBitcoin.NetworkBuilder NBitcoin.NetworkBuilder.AddDNSSeeds(System.Collections.Generic.IEnumerable`1<NBitcoin.DNSSeedData>)'."}
When i set the Network to 
 NBitcoin.Network networks = NBitcoin.Altcoins.Ufo..Testnet;
and every single Altcoins made this error 
Any Idea? 
![Altcoins](https://user-images.githubusercontent.com/22941805/149493842-810cf4fc-db9c-445f-91d1-b10f5c0cbdb5.PNG)
![Altcoinssd](https://user-images.githubusercontent.com/22941805/149493843-153461bb-bda3-4562-a83d-de1865518196.PNG)

**Comment by erfan132** [comment]
This Problem is Only on Last Version of Nbitcoin when i changed to pervious version its work

**Comment by knocte** [comment]
Check that you upgraded your NBitcoin version in all projects of the solution.

**Comment by erfan132** [comment]
thats solved thanks
