### ISSUE TITLE
Security Alaret 

### ISSUE THREAD

**Issue by erfan132** [MetacoSA/NBitcoin#1084]
Hi 
Thanks for Developing Nbitcoin 
I think we have some security issues 
From memory because nbitcoin dosent support securestring and every private key and password not disposed from memory 
I think it can make some issues in feature because it can make memory leaks 
I konw securestring is not available for 
.netcore
But its just for netcore 
So I think it’s time to add securestring to .netfreamwork version 
Please Add this into developing tasks

**Comment by lontivero** [comment]
`securestring` is one of those brain farts that find its way into .net but fortunately it was removed.

**Comment by erfan132** [comment]
Ok
Thanks for you reply 
And developing this amazing library god bless you
