### ISSUE TITLE
SignMessage

### ISSUE THREAD

**Issue by lpcurcio** [MetacoSA/NBitcoin#1094]
I upgraded the NBitcoin version from 6.x to 7.x.
But the BitcoinSecret.PrivateKey.SignMessage property no longer exists.
Has this property been removed or renamed?

**Comment by NicolasDorier** [comment]
Yes, support has been removed.

**Comment by NicolasDorier** [comment]
@sheindel no it doesn't prove knowledge either.

Imagine Alice ask to Bob to "prove knowledge" of a coin that really belongs to Carol.

* Alice: Prove you own the coin by signing "Me, Bob, I own this coin" with the private key
* Bob: Ok
* Bob to Carol: Carol can you sign "Me, Bob, I own this coin" with the private key
* Carol: Ok Bob.
* Bob to Alice: Here is the proof!
* Alice: OK you may enter

Note that Carol doesn't pay any cost for signing whatever Bob is asking. And that at no point Bob need to know about the private key.

**Comment by ChrisLomont** [comment]
That still proves the message was signed by someone with knowledge of the private key. There is not a single signature protocol that would not fail if the private key holder signs arbitrary messages for anyone. 

Removing the API means people will try to implement it on their own on top of the library, resulting in more, not less, mistakes.

How should one use the private key now to sign a message? Is there a better way?

**Comment by lpcurcio** [comment]
In my case, I use an exhange API to make buy and sell requests. The exchange enforces that the data that is sent in each request must be signed.
I haven't looked into other solutions yet. For now I will continue using version 6.x.

**Comment by sheindel** [comment]
@NicolasDorier thanks for your work on the library, certainly don't mean to pile one. Really appreciate it :-) 

In regards to this issue, I think it's valid to think about abuse/misuse, but we're talking about a library that has financial AND security implications. I think it's rife for misuse by those who don't understand cryptography. 

And I think we can think about valid use cases for arbitrary signatures. If Alice is sending money to Bob, Alice just wants to know that SOMEONE knows the private key, so she can't be accused of sending money to nowhere. Whether Bob signed it himself or Carol signed it for him, that's not necessarily Alice's problem and it's for Bob and Carol to sort out. So there are valid use cases for signing even inside normal crypto transactions. The fact that it's even described in detail in a BIP ((https://github.com/bitcoin/bips/blob/master/bip-0137.mediawiki) and mentioned with potential use cases in other BIPs (https://github.com/bitcoin/bips/blob/master/bip-0322.mediawiki) makes it entirely valid functionality to have within a Bitcoin library.

**Comment by NicolasDorier** [comment]
@sheindel

Note that the core of this feature still exists with `Key.SignCompact` and `PubKey.RecoverCompact`, the `CompactSignature` type enclose the data that was before formatted in the Bitcoin core's signature string.

**Comment by sergeibystrov** [comment]
Hello Great programmer Nicholas🤔
Are you sure you are not Satoshi Nakomoto?
Because you understand the in and out of Bitcoin than any? Just saying..🧐🤨

**Comment by Kukks** [comment]
BIP322 has been merged which brings back supports through it (it is backward compatible) See [#1224 (files)](https://github.com/MetacoSA/NBitcoin/pull/1224/files#diff-7a7679ce5e15cbfe8fcf1bfdf8afa147e91bde233e73c080c2d5b2649f8bfbf7R10) for examples

**Comment by NicolasDorier** [comment]
https://github.com/MetacoSA/NBitcoin/pull/1224
