### ISSUE TITLE
Why is the VerifyMessage method no longer available?

### ISSUE THREAD

**Issue by yanjustino** [MetacoSA/NBitcoin#1107]
Hi! I'm following the Guid [Programming The Blockchain in C#](https://www.gitbook.com/book/programmingblockchain/programmingblockchain/details)! But in [Proof of ownership as an authentication method](https://programmingblockchain.gitbook.io/programmingblockchain/bitcoin_transfer/proof_of_ownership_as_an_authentication_method) section I noted that `VerifyMessage()` method no longer available. Is there any alternative to this method? Thanks!!!

```c#
var message = "I am Craig Wright";
var signature = "IN5v9+3HGW1q71OqQ1boSZTm0/DCiMpI8E4JB1nD67TCbIVMRk/e3KrTT9GvOuu3NGN0w8R2lWOV2cxnBp+Of8c=";

var address = new BitcoinPubKeyAddress("1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa", Network.Main);
bool isCraigWrightSatoshi = address.VerifyMessage(message, signature);

Console.WriteLine("Is Craig Wright Satoshi? " + isCraigWrightSatoshi);
```

**Comment by NicolasDorier** [comment]
Closing this, but long story short, I removed the feature https://github.com/MetacoSA/NBitcoin/issues/1107
