### ISSUE TITLE
SigningOptions not being applied on transactionbuilder

### ISSUE THREAD

**Issue by Jossec101** [MetacoSA/NBitcoin#1112]
Hey, amazing lib, couldn't be easier to work with it!

I found a potential bug, we are playing with SIGHASH_NONE PSBTs but it looks like the txBuilder is not applying it in the code below:

```csharp
            var channelFundingPSBT = txBuilder
                .AddCoin(multisigUTXOs.First().Value.ToScriptCoin(multisigScriptPubKey))
                .SetChange(multisigScriptPubKey)
                .SetSigningOptions(SigHash.None)
                .SendFees(feesCoins)
                .BuildPSBT(false);

```

If you inspect the object, you will find that: **_channelFundingPSBT.SigningOptions.SigHash = SigHash.All_** instead of **_SigHash.None_**.

Workaround:

Set the settings by hand

```
            channelFundingPSBT.Settings.SigningOptions.SigHash = SigHash.None;
```

Hope it helps anyone with this issue until the fix is done.

BR,

**Comment by Jossec101** [comment]
The workaround did not really work, the Sighash is not serialized until you explicility set it like:

````csharp

                 var builder = txBuilder;

                builder.AddCoins(multisigCoins);

                builder.SetSigningOptions(SigHash.None)
                    .SendAllRemainingToChange()
                    .SetChange(changeAddress.Address)
                    .SendEstimatedFees(feeRateResult.FeeRate);

                result.Item1 = builder.BuildPSBT(false);

                result.Item1.Settings.SigningOptions = new SigningOptions(SigHash.None);
                foreach (var input in result.Item1.Inputs)
                {
                    input.SighashType = SigHash.None;
                }
````

**Comment by NicolasDorier** [comment]
Hey, checking now

**Comment by NicolasDorier** [comment]
@Jossec101 so I checked, the signature have SigHash.None applied to it. But indeed, PSBT doesn't.

`input.SighashType = SigHash.None;` shouldn't be set imho, but yeah the SigningOptions should be. Fixing it

**Comment by Jossec101** [comment]
Yes,  perhaps when a SighHash different than SigHash.All a console warning message could be printed (disabled by a env-var or any global config) so users are aware of miners attack, we need to use it for a special transaction, then we apply SigHash.All to the whole transaction. We will release a new open source software that the lightning network community will like (hope so!).

Thanks for checking it

**Comment by NicolasDorier** [comment]
Awesome! :)
I don't know if that help you but https://github.com/dgarage/NBXplorer/ provide a block explorer which work on pruned node. It tracks UTXOs and is quite flexible. Built on NBitcoin, so you may inspire from the code as well.

**Comment by NicolasDorier** [comment]
@Jossec101 I am wondering if it makes sense to propagate the `SetSigningOptions`, as you don't sign with the transaction builder at all.
I opened a PR, I am not sure if it will break something.

**Comment by Jossec101** [comment]
> @Jossec101 I am wondering if it makes sense to propagate the `SetSigningOptions`, as you don't sign with the transaction builder at all. I opened a PR, I am not sure if it will break something.

I've check the PR and the propagation of the `SetSigningOptions` would be required for two use cases even if you are not signing on the transaction buliding.

- If you want to sign a PSBT with a hardware wallet (.e.g. Ledger) you need to detail the SigHash type if you are not using SIGHASH_ALL. 
- In terms of UX, if you detail the SigHash of the PSBT and you use a software wallet (I've tested in Sparrow), the SigHash type is automatically selected.

Best,

**Comment by NicolasDorier** [comment]
@Jossec101 I think in those case, the correct way is to manually set `SigHash` to PSBT. This is an optional field, I can't decide from `SigningOptions` alone if I should leave it empty or not.

**Comment by NicolasDorier** [comment]
I am closing this as any bug I saw while looking this issue has been fixed, and I think `TransactionBuilder.SetSigningOptions`  shouldn't try to change the PSBT's SigHash, as this is an optional field. Once can just set them directly on the `PSBTInput`.

Feel free to reopen if you think there is still issues.
