### ISSUE TITLE
bip32 address for DASH

### ISSUE THREAD

**Issue by arahimi1996** [MetacoSA/NBitcoin#1113]
Hi,
I am trying to generate HD addresses from a DASH wallet public key (xpub) using NBitcoin.

Here it is the code I use to successfully generate Bitcoin addresses from BTC wallet xpub:

> var network = Network.Main;
> var pubkey = ExtPubKey.Parse(xpub, network);
> var address = pubkey.Derive(0).Derive(0).PubKey.GetAddress(pubkeyType, network).ToString();

Also it is the code I use to successfully generate dogeCoin addresses from DOGE wallet xpub:

> var network = NBitcoin.Altcoins.AltNetworkSets.Dogecoin.Mainnet;
> var pubkey = ExtPubKey.Parse(xpub, network);
> var address = pubkey.Derive(0).Derive(0).PubKey.GetAddress(pubkeyType, network).ToString();

And using this code to generate Dash Address from DASH wallet xpub but an error occurs :

> var network = NBitcoin.Altcoins.AltNetworkSets.Dash.Mainnet;
> var pubkey = ExtPubKey.Parse(xpub, network);
> var address = pubkey.Derive(0).Derive(0).PubKey.GetAddress(pubkeyType, network).ToString();

Here it is my sample and valid Dash wallet xpub:

> var xpub = "drkvjJe5sJgqomjLnD39LKGdme64zzL4d38fDEhkveYsjvqDZzEZSoq6VEE5znetSRvSB6pYAxhTViXJdZ5QygKogD4nsa31hQ8aVuW6psczteC"

Here it is an error occurs:

Exception Message =>

> Invalid base58 string

Exception Stack Trace =>

> at NBitcoin.Network.Parse(String str, Type targetType)
> at NBitcoin.Network.Parse[T](String str)
> at NBitcoin.ExtPubKey.Parse(String wif, Network expectedNetwork)

Any suggestion about how to derive a DASH compatible address?

Thanks in advance.

**Comment by kiarash3012** [comment]
I have the same exact problem, the error is the same as when you add the wrong network (like adding a bitcoin network for doge),
can anyone help?

**Comment by kiarash3012** [comment]
Ping @bazooka70 , @bdangh , @snogcel , somebody can fix it pls?

**Comment by arahimi1996** [comment]
@NicolasDorier help me to fix this exception please

**Comment by NicolasDorier** [comment]
strange, checking

**Comment by NicolasDorier** [comment]
the prefix for dash xpub is `0x04, 0x88, 0xB2, 0x1E` and I see a different one.

**Comment by arahimi1996** [comment]
Thanks a lot @NicolasDorier.
