### ISSUE TITLE
Please I know this is not the right place to ask this but I guess this discussion thread seems to be getting quick response that's why I asked this here.

### ISSUE THREAD

**Issue by sergeibystrov** [MetacoSA/NBitcoin#1130]
Please I know this is not the right place to ask this but I guess this discussion thread seems to be getting quick response that's why I asked this here.

I am using the latest version of NBitcoin and it seems to be different from the previous version of 4.1.1 which is easy as taking the message string parameter to sign a message and verify but it's kind of difficult to sign a message in latest version 7.* Please how do I sign a message and verify a message. Thank you.
Bar m = key.privatekey.signmrssage(message.text);
Above code is for NBitcoin 4.1.1.86

I am using latest stable version which is different. Don't know how

_Originally posted by @sergeibystrov in https://github.com/MetacoSA/NBitcoin/issues/1126#issuecomment-1250188438_

**Comment by NicolasDorier** [comment]
See conversation on https://github.com/MetacoSA/NBitcoin/issues/1094
