### ISSUE TITLE
Support for `feefilter` message

### ISSUE THREAD

**Issue by vlada-cz** [MetacoSA/NBitcoin#1135]
I would like to use (de)serialization of NBitcoin library for `feefilter` message. However I found out, that it is not present in supported messages (no `FeeFilterPayload` type) in NBitcoin. **So I suggest to add support for `feefilter` message.**

[FeeFilter](https://developer.bitcoin.org/reference/p2p_networking.html#feefilter) message was added in Bitcoin Core 0.13 (protocol 70013) and is described in [BIP133](https://github.com/bitcoin/bips/blob/master/bip-0133.mediawiki).

Quote from BIP133 specification:
> 2. Upon receipt of a "feefilter" message, the node will be permitted, but not required, to filter transaction invs for transactions that fall below the feerate provided in the feefilter message interpreted as satoshis per kilobyte.

So from point of view of implementation, it seems pretty straightforward - we do not need to implement _real filtering_ of TX to send.

I can make PR, if you are also interested in this feature.

**Comment by NicolasDorier** [comment]
@vlada-cz yes, I am interested in a PR for that!
