### ISSUE TITLE
Support for `MSG_WTX` from BIP339

### ISSUE THREAD

**Issue by torx-cz** [MetacoSA/NBitcoin#1144]
Bitcoin Core uses WTXID-based transaction relaying described in [BIP339](https://github.com/bitcoin/bitcoin/blob/a97791d9fb977cf2a0d19268253238b0fee173f6/src/protocol.h#L467), it uses `MSG_WTX` (0x00000005) inv type (in inventory vector) see [src](https://github.com/bitcoin/bitcoin/blob/a97791d9fb977cf2a0d19268253238b0fee173f6/src/protocol.h#L467).

So I suggest to add `MSG_WTX` into [InventoryType](https://github.com/MetacoSA/NBitcoin/blob/ce7c86ab04bf32d69a4ef1065b7c5a287b764809/NBitcoin/Protocol/InventoryVector.cs#L9).

Is it suitable?

**Comment by torx-cz** [comment]
@NicolasDorier  some info?

**Comment by NicolasDorier** [comment]
Hey @torx-cz sorry I just saw this

**Comment by NicolasDorier** [comment]
Released in 7.0.20

**Comment by torx-cz** [comment]
Thanks a lot @NicolasDorier.
