### ISSUE TITLE
HexEncoder fails to decode valid encoded string

### ISSUE THREAD

**Issue by lontivero** [MetacoSA/NBitcoin#1148]
The HexEncoder says the following is an invalid hex string. That's not true, this is a raw transaction.

https://pastebin.com/Yj1HMHG3

**Comment by knocte** [comment]
> https://pastebin.com/Yj1HMHG3

404

**Comment by lontivero** [comment]
Sorry, the tx was huge and that didn't let me see that the IDE was adding `\r\n` at the end of the line.
