### ISSUE TITLE
VerifyMessage does not exist

### ISSUE THREAD

**Issue by robotlovecoffee** [MetacoSA/NBitcoin#1172]
I'm trying to do a simple verification of an address and the samples provide code that will not compile.

'BitcoinPubKeyAddress' does not contain a definition for 'VerifyMessage' and no accessible extension method 'VerifyMessage' accepting a first argument of type 'BitcoinPubKeyAddress' could be found (are you missing a using directive or an assembly reference?) [NBitcoinTraining]

I just want to provide a message, have the user sign and return back to the program and then verify that it is correct.

**Comment by TylerOlsen** [comment]
It seems this method was removed starting with version 7 - I too was wondering how to validate a signature via NBitcoin, specifically from a segwit bech32 address - does the library currently not support this? If not, can anyone recommend any alternatives?

Been working on something custom in the meantime, but it's been tough (new to bc and crypto in general)

**Comment by knocte** [comment]
You could fork the repo and go back to version previous to 7?

**Comment by Cadey** [comment]
@TylerOlsen Did you get an alternative for this. I just had the same issue

**Comment by Cadey** [comment]
Your uses case is exactly the same as mine :) Need to validate messages signed with a taproot address :)

**Comment by Cadey** [comment]
@TylerOlsen sorry to bother you again, I did try to validate the message with a node but it keeps rejecting it.

Ive tried making sure the "Magicbytes" are included in the message which did catch me out at first, but its like the verifyMessage function doesn't support taproot addresses or something.....

**Comment by Cadey** [comment]
Ohhhh sorry, I see what you did. You compiled a node from that branch.... sorry, didnt read what you said properly

**Comment by Kukks** [comment]
BIP322 has been merged which brings back supports through it (it is backward compatible) See https://github.com/MetacoSA/NBitcoin/pull/1224/files#diff-7a7679ce5e15cbfe8fcf1bfdf8afa147e91bde233e73c080c2d5b2649f8bfbf7R10 for examples

**Comment by NicolasDorier** [comment]
https://github.com/MetacoSA/NBitcoin/pull/1224
