### ISSUE TITLE
Sign a text message with NBitcoin

### ISSUE THREAD

**Issue by aboimpinto** [MetacoSA/NBitcoin#1187]
Hello, 

I could not find a way to sign a simple text message with NBitcoin.

Can you point me in the right direction so I can sign the message and verify?

thanks
Paulo Aboim Pinto

**Comment by dangershony** [comment]
You can't its been deleted on main repo, use a fork of NBitcoin like blockcore or something

**Comment by aboimpinto** [comment]
Why this feature was removed?

**Comment by dangershony** [comment]
https://github.com/MetacoSA/NBitcoin/issues/1094

**Comment by dangershony** [comment]
You are totally right imo, but for the sake of keeping politics out of code (unfortunately this is not always the case) just use a fork of NBitcoin or implement yourself the message signing, it's not that hard.  

https://github.com/block-core/blockcore/blob/master/src/Blockcore/NBitcoin/Key.cs#L121

**Comment by aboimpinto** [comment]
I agree ... politics should be out of the code ... 
thanks!!

**Comment by Kukks** [comment]
BIP322 has been merged which brings back supports through it (it is backward compatible) See [#1224 (files)](https://github.com/MetacoSA/NBitcoin/pull/1224/files#diff-7a7679ce5e15cbfe8fcf1bfdf8afa147e91bde233e73c080c2d5b2649f8bfbf7R10) for examples

**Comment by NicolasDorier** [comment]
https://github.com/MetacoSA/NBitcoin/pull/1224
