### ISSUE TITLE
Install failed on Windows Universal

### ISSUE THREAD

**Issue by quartsystem** [MetacoSA/NBitcoin#120]
NuGet no longer able to install the package on a Windows Universal project with VS2015

**Comment by NicolasDorier** [comment]
was it able before ? I can't compile on windows universal so I don't know. What error do you have ? (sorry for the delay)

**Comment by NicolasDorier** [comment]
Can you also try the "NBitcoin For Mono" package ?

**Comment by quartsystem** [comment]
NuGet / Visual Studio 2015 is now able to perform the update to new release(2.1.4.7). All very strange.
The error message was "Unable to find metadata of NBitcoin xxxx".
Thanks anyway for the answer.

**Comment by NicolasDorier** [comment]
By the way, I am interested to know if it the lib works fine on Univeral Project, since I did not tried. Let me know.
I don't think you have access to the Node class (to connect to network) on Universal project, can you confirm ?

If it is a problem for you, you can try NBitcoin For Mono package which include everything and should also works fine on Universal.

**Comment by quartsystem** [comment]
I'm developing a client for Windows 10 in my spare time.
I'll keep you updated on the tests that will.

**Comment by quartsystem** [comment]
On universal Windows (app for Windows 10) NBitcoin.Mono fails installation with NuGet.
With NBitcoin, when launching the following code is generated an exception:

var k = new NBitcoin.Key();

System.InvalidOperationException: You must set the RNG (RandomUtils.Random) before generating random numbers
   at NBitcoin.RandomUtils.GetBytes(Byte[] output)
   at NBitcoin.Key..ctor(Boolean fCompressedIn)
   at NBitcoin.Key..ctor()
   at TestInstallNBitcoin.MainPage..ctor()
   at TestInstallNBitcoin.TestInstallNBitcoin_XamlTypeInfo.XamlTypeInfoProvider.Activate_0_MainPage()
   at TestInstallNBitcoin.TestInstallNBitcoin_XamlTypeInfo.XamlUserType.ActivateInstance()
   at Windows.UI.Xaml.Controls.Fra

**Comment by quartsystem** [comment]
On Windows 10, PRNG uses the CryptographicBuffer. I solved this code:
   
    public class CryptographicBufferRandom : IRandom
    {
        #region IRandom Members
        public void GetBytes(byte[] output)
        {
            // https://msdn.microsoft.com/en-us/library/windows.security.cryptography.cryptographicbuffer.aspx
            IBuffer buffer = CryptographicBuffer.GenerateRandom((uint)output.Length);
            buffer.CopyTo(output);
        }
        #endregion
    }
	
To generate the key
NBitcoin.RandomUtils.Random = new CryptographicBufferRandom();
var newKey = new NBitcoin.Key();

**Comment by NicolasDorier** [comment]
thanks, will be useful when I'll make a specific version for universal

**Comment by GoldNRoll** [comment]
Hello,

Any chance this will be solved for Windows 10?
Any code fails with this error:

using System;
using NBitcoin;

namespace Blockchain
{
    class Program
    {
        static void Main(string[] args)
        {
            Key privateKey = new Key();
            Console.WriteLine("Private Key: {0}", privateKey);
            PubKey publicKey = privateKey.PubKey;
            Console.WriteLine("Public Key: {0}", publicKey);
        }
    }
}

**Comment by NicolasDorier** [comment]
@GoldNRoll set `RandomUtils.Random` to an instance of `CryptographicBufferRandom` made by @quartsystem just above.

Windows Universal will soon support .NETStandard 2.0, so it will soon be not needed.

Actually I think this is supported, in fall creator update https://blogs.windows.com/buildingapps/2017/05/19/introducing-xaml-standard-net-standard-2-0/

**Comment by GoldNRoll** [comment]
Perfect, thanks!!

**Comment by NicolasDorier** [comment]
@GoldNRoll sorry I incorrectly diagnotised your problem, turns out you were not using UWP so my response does not apply. 

I fixed the problem, now you can reference NBitcoin without the issue.

**Comment by GoldNRoll** [comment]
Hi Nicolas,

Perfect, I upgraded to 4.0.0.15 and now it works in console application :)
Visual Studio 2017 fresh install still comes with framework 4.5.2

Thank you!!
