### ISSUE TITLE
`Network.GetNetworks()` Method Returns Duplicates

### ISSUE THREAD

**Issue by kataklinger** [MetacoSA/NBitcoin#1234]
`Network.GetNetworks()` method returns duplicates of main, testnet and regtest. [This change](https://github.com/MetacoSA/NBitcoin/commit/8c7066157180c5c562a7572446c08e0fd0339758#diff-12355e5baf374196ed9c5a0708f16632568b4bfc9139c8daff9aca066fd9f8e1R18-R20) is most likely the reason for this behavior. It is registering these three networks, but `Network.GetNetworks()` method is [hardcoded](https://github.com/MetacoSA/NBitcoin/blob/db86ab33629e8f2efbad1a952862189091936e51/NBitcoin/Network.cs#L1282-L1284) to always return them.

**Comment by kataklinger** [comment]
The same commit also breaks `Network.GetNetwork(string)` methods. The method now relies exclusively on aliases dictionary which is initialized by `Bitcoin` class' static constructor. If `Network.GetNetwork` method is invoked before querying any static properties, or invoking static methods of `Bitcoin` class `Network.GetNetwork` will always return `null`. 

This can be reproduced by running `NetworkTests.CanGetNetworkFromName` test in isolation, ironically because arguments to the assertion methods are provided in incorrect order for that test.

Here's the proposed fix:

```diff
diff --git a/NBitcoin.Tests/NetworkTests.cs b/NBitcoin.Tests/NetworkTests.cs
index d5998eac9..a140e3058 100644
--- a/NBitcoin.Tests/NetworkTests.cs
+++ b/NBitcoin.Tests/NetworkTests.cs
@@ -1,25 +1,38 @@
-﻿using System.IO;
+﻿using System;
+using System.IO;
 using System.Linq;
 using System.Threading;
-using NBitcoin;
 using Xunit;
-using System;
 
-namespace NBitcoin.Tests
-{
+namespace NBitcoin.Tests {
 	public class NetworkTests
 	{
+		[Fact]
+		[Trait("UnitTest", "UnitTest")]
+		public void NetworkListIsInitialized()
+		{
+			Assert.NotEmpty(Network.GetNetworks());
+		}
+
+		[Fact]
+		[Trait("UnitTest", "UnitTest")]
+		public void NetworkListHasNoDuplicates()
+		{
+			var uniqueNetworkCount = Network.GetNetworks().DistinctBy(n => n.ChainName).Count();
+			Assert.Equal(Network.GetNetworks().Count(), uniqueNetworkCount);
+		}
+
 		[Fact]
 		[Trait("UnitTest", "UnitTest")]
 		public void CanGetNetworkFromName()
 		{
-			Assert.Equal(Network.GetNetwork("main"), Network.Main);
-			Assert.Equal(Network.GetNetwork("reg"), Network.RegTest);
-			Assert.Equal(Network.GetNetwork("regtest"), Network.RegTest);
-			Assert.Equal(Network.GetNetwork("testnet"), Network.TestNet);
-			Assert.Equal(Network.GetNetwork("testnet3"), Network.TestNet);
-			Assert.Equal(Network.GetNetwork("signet"), Bitcoin.Instance.Signet);
-			Assert.Equal(Network.GetNetwork("mutinynet"), Bitcoin.Instance.Mutinynet);
+			Assert.Equal(Network.Main, Network.GetNetwork("main"));
+			Assert.Equal(Network.RegTest, Network.GetNetwork("reg"));
+			Assert.Equal(Network.RegTest, Network.GetNetwork("regtest"));
+			Assert.Equal(Network.TestNet, Network.GetNetwork("testnet"));
+			Assert.Equal(Network.TestNet, Network.GetNetwork("testnet3"));
+			Assert.Equal(Bitcoin.Instance.Signet, Network.GetNetwork("signet"));
+			Assert.Equal(Bitcoin.Instance.Mutinynet, Network.GetNetwork("mutinynet"));
 			Assert.Null(Network.GetNetwork("invalid"));
 		}
 
diff --git a/NBitcoin/Network.cs b/NBitcoin/Network.cs
index 27bfae370..e367fb7fc 100644
--- a/NBitcoin/Network.cs
+++ b/NBitcoin/Network.cs
@@ -715,10 +715,10 @@ namespace NBitcoin
 	}
 	public partial class Network
 	{
-
-
-
-
+		static Network() {
+			// ensures that network list is initialized
+			_ = Bitcoin.Instance;
+		}
 
 		readonly uint magic;
 
@@ -1279,10 +1279,6 @@ namespace NBitcoin
 
 		public static IEnumerable<Network> GetNetworks()
 		{
-			yield return Main;
-			yield return TestNet;
-			yield return RegTest;
-
 			if (_OtherNetworks.Count != 0)
 			{
 				List<Network> others = new List<Network>();

```

**Comment by knocte** [comment]
> Here's the proposed fix:

This is not how to contribute a fix, please propose a PR.

**Comment by kataklinger** [comment]
> This is not how to contribute a fix, please propose a PR.

I don't have that kind of access to the repo. So this is the best I can do.

**Comment by knocte** [comment]
> I don't have that kind of access to the repo. So this is the best I can do.

What are you talking about? Anyone can create a PR. You need to fork first, create branch, push to your fork's branch, and then create PR.

**Comment by NicolasDorier** [comment]
Hey sorry, I just fixed this
