### ISSUE TITLE
Remove BouncyCastle

### ISSUE THREAD

**Issue by lontivero** [MetacoSA/NBitcoin#130]
@NicolasDorier, I've been working hard for days now trying to remove BC but I hit the wall because I didn't follow a refactoring plan and it was a lot harder than what I thought. However, I think it could worth the effort (I really don't like to have two projects: BC and BC portable in NBitcoin).

There is a very little library that we could use: [Secp256k1](https://github.com/TangibleCryptography/Secp256k1) It has all what NBitcoin needs.

Do you think it is a good idea and worth? If so, do you have any idea about how could we start the refactoring?

**Comment by NicolasDorier** [comment]
I would like also to be honest. But I don't think it is possible, don't forget that the portable lib depends even more of BC for some encryption/hash purposes. I don't think it will be easy.

**Comment by NicolasDorier** [comment]
Secp256k1 is not enough sadly.
Secp only check signatures, Bitcoin need other stuff like SHA calculation, DES, AES, and need to work in portable lib where you can't use MS security layer.

**Comment by bitcoinbrisbane** [comment]
I too like the idea.  However, its a big risk.  Bouncy is has been in the wild for a long time.  Before this project, I tried to code everything myself (just for the challenge) and found myself just using BC in the end.

**Comment by lontivero** [comment]
I agree with you both. A lot of risky work just to end writting our own crypto library. It doesn't worth. Thank you.

**Comment by andbene72** [comment]
I have noticed Legion of Bouncycastle release a
*Release 1.8.1, 28th December 2015*

A verification of fixed bug/issue should be done against feature used by
NBitcoin.

Andrea
