### ISSUE TITLE
Can you allow set array of transactions hashes for GetMempoolTransactions?

### ISSUE THREAD

**Issue by lampego** [MetacoSA/NBitcoin#133]
This method was public:

Transaction[] GetMempoolTransactions(uint256[] txIds, CancellationToken cancellationToken = default(CancellationToken))

Can you do this as PUBLIC?

NBitcoin/NBitcoin/Protocol/Node.cs
Line: 1243

**Comment by NicolasDorier** [comment]
Yes, I just did on fded0b13debe9561b0f394e6a9b2e2f74a2683e8. It will be in the next nuget package.
Meanwhile, in your project, you can copy the method and use it as a extension method of Node. There is no dependency on other internal/private methods normally.

**Comment by lampego** [comment]
Ok. Thanks :)

**Comment by NicolasDorier** [comment]
I will push a new nuget package before monday normally. I added BIP65 (OP_CLTV) support, but I'm waiting my build server catch up the block chain for running the tests. It crashed, the blocks became corrupted so I had to reindex everything.

**Comment by NicolasDorier** [comment]
@lampego I just pushed version 2.1.5.3 on nuget. https://github.com/MetacoSA/NBitcoin/releases/tag/v2.1.5.3

**Comment by lampego** [comment]
Cool :) Thank you very much!
