### ISSUE TITLE
Question regarding signature verification

### ISSUE THREAD

**Issue by graffen** [MetacoSA/NBitcoin#134]
Hi, 

I'm trying to implement Trezor Connect on my blog. For that, I need to verify a signature of a message to check that it was generated by a given Trezor device (thus, private key). 

I have tried to use the parameters provided for testing from here: https://github.com/trezor/connect/blob/gh-pages/examples/server.py

And my (stripped down) code as follows: 

``` 
string visual_challenge = "2015-03-23 17:39:22";
string random_challenge = "cd8552569d6e4509266ef137584d1e62c7579b5b8ed69bbafa4b864c6521e7c2";
string signature = "20f2d1a42d08c3a362be49275c3ffeeaa415fc040971985548b9f910812237bb41770bf2c8d488428799fbb7e52c11f1a3404011375e4080e077e0e42ab7a5ba02";

SHA256 sha = SHA256Managed.Create();
var hiddenChallenge_Sha = BitConverter.ToString((sha.ComputeHash(TrezorUtils.HexStringToByteArray(random_challenge)))).Replace("-", "").ToLower();
var visualChallenge_Sha = BitConverter.ToString((sha.ComputeHash(new ASCIIEncoding().GetBytes(visual_challenge)))).Replace("-", "").ToLower();

string message = hiddenChallenge_Sha + visualChallenge_Sha;
var m2 = TrezorUtils.HexStringToByteArray(message);
PubKey pubKey = new PubKey("023a472219ad3327b07c18273717bb3a40b39b743756bf287fbd5fa9d263237f45"); //new PubKey(ConfigurationManager.AppSettings["TrezorPublicKey"]);
bool verified = pubKey.VerifyMessage(new ASCIIEncoding().GetString(m2), TrezorUtils.ConvertHexStringToBase64(signature));
```

The call to pubKey.VerifyMessage always returns false with this code. I have verified that the SHA256's returned are identical to what the Python code generates for the same values, as well as the base64 of the signature. So all the input to the VerifyMethod is the same as in the Python example. However, verification of the signature still fails.

Any ideas?

**Comment by graffen** [comment]
I just performed a byte-for-byte comparison of the messages passed in to the pubKey.VerifyMessage and the what the Python example uses (see my test here: http://goo.gl/VkAea8). They are, indeed, the same.

**Comment by NicolasDorier** [comment]
I am verifying with bitcoin core verifymessage rpc

**Comment by NicolasDorier** [comment]
mmh bitcoin core verifymessage from rpc returns me also false... VerifyMessage from NBitcoin replicate Core fuctionalities, I'm trying to make your code pass in another way

**Comment by graffen** [comment]
Here's my TrezorUtils class if you need it: 
```
public static class TrezorUtils
{
    public static byte[] HexStringToByteArray(String hex)
    {
        int NumberChars = hex.Length;
        byte[] bytes = new byte[NumberChars / 2];
        for (int i = 0; i < NumberChars; i += 2)
            bytes[i / 2] = Convert.ToByte(hex.Substring(i, 2), 16);
        return bytes;
    }

    public static string ConvertHexStringToBase64(string hexString)
    {
        byte[] buffer = new byte[hexString.Length / 2];
        for (int i = 0; i < hexString.Length; i++)
        {
            buffer[i / 2] = Convert.ToByte(Convert.ToInt32(hexString.Substring(i, 2), 16));
            i += 1;
        }
        string res = Convert.ToBase64String(buffer);
        return res;
    }
}
```

**Comment by NicolasDorier** [comment]
I don't manage to make your sig work, neither with bitcoincore, nor by using Bouncy castle directly... can you try to make verification pass with bitcoin rpc verifymessage ? did not managed to.

**Comment by NicolasDorier** [comment]
Your code seems correct, and the format used of the signature and message (from https://github.com/trezor/connect/blob/gh-pages/examples/server.php) match with bitcoin core verifymessage implementation and NBitcoin VerifyMessage you are using.

My sole explanation is that the example they give have a wrong signature, is that possible ?

**Comment by NicolasDorier** [comment]
You can verify with coinig.com/ I converter pubkey in address, and it does not check.

**Comment by NicolasDorier** [comment]
Well, even in code, if I check the signature with the pubkey directly (not using the address) it does not pass...  I don't think they are using a good signature, can you ask them about it ?

**Comment by graffen** [comment]
I just tried with the values from my Trezor, using the same challenges as before. 

The public key is 02fb9ea3f2388128cf2001170795e7a05936f61427955e8d4f9c82ae6eb29c8522
and the signature comes out of the Trezor as 1feef0718b6c5d9331de4cb5eb54085d19e387da29df9bb339248160738472013419c4916f0a65c656f4e73daed6034fea94d491c107723edeb2045929b5239fea

This signature is returned from the Trezor. It's all a bit weird if you ask me :) I'm converting the sha array to ASCII bytes, giving all sorts of weird characters. The example Python script gives me the exact same message byte sequence as my C# code. I'm kind of thinking it's something to do with how I convert the byte array back to ASCII before passing it into VerifyMessage...

**Comment by NicolasDorier** [comment]
you are just using the python script of trezor documentation... trying with your value one moment

**Comment by NicolasDorier** [comment]
Are you using same visual and random challenge ?

**Comment by graffen** [comment]
Yes

**Comment by graffen** [comment]
Just checked the ascii values of the message from my code against the python version and they come out identical again, with the new signature and public key.

**Comment by NicolasDorier** [comment]
No more luck with your sig  :/

**Comment by graffen** [comment]
This is too weird! Funny thing is my Trezor works fine when I log in to coinmap.org, so I know the functionality should work :)

How are you testing the signature on my data? The message results in all sorts of funny byte sequences that aren't that easy to enter into the form on coinig.com?

**Comment by NicolasDorier** [comment]
So basically, verifymessage from bitcoincore, NBitcoin, and coinig wants the same thing: Your address, the message you are signing, and the signature, and tell you if it is ok.

The message you are signing is the concatenation of the 2 hashes, and the signature is the base64 string of the sig.

For having the address you need to convert the pubkey to an address: pubkey.GetAddress(Network.Main).ToString()

**Comment by NicolasDorier** [comment]
To be sure the problem was not in the "conversion to address", I modified VerifyMessage of NBitcoin where I did the conversion, into a version where I did not. And still, it does not validate.

**Comment by NicolasDorier** [comment]
Can you give me an entire new set of pubkey, sig, and challenges, without special character (like punctuation) for the visual challenge ?

**Comment by graffen** [comment]
Sure, just a sec :)

**Comment by graffen** [comment]
visual challenge: 123456
hidden challenge: abcdef
pubkey: 02fb9ea3f2388128cf2001170795e7a05936f61427955e8d4f9c82ae6eb29c8522
signature: 205222527c10407211576b15ef59ddd1a83eae4cd25ef1680d5484ac2583ecbade47f86609463dc5ea2d1de08ccc07516e7650e96a14261d262efca38f26d9c576

**Comment by graffen** [comment]
Oh wait... something is weird with the pubkey I'm using it seems. Just give me a sec.

**Comment by graffen** [comment]
Hmm weird, the Trezor returns the public key I posted, but the key it's actually using to sign with is another one. 

When I do a GetAddress on the pubkey I posted I get 1FhoECMfPK4XU1jELuxxtSb8HovBdrQi4n
But the key in the returned signature is 1ABJsytP6iJkbHiiUbodVLA7LANxa9AhCD, according to coinig.org. 

Guess I'll have to dig a bit and find out what's going on...

**Comment by graffen** [comment]
Thanks for your help so far! :)

**Comment by NicolasDorier** [comment]
Well, I have the same result with NBitcoin that coinig.org, and you can try to validate with bitcoin core, will be same error... but the thing that is surprising, is that I also have the error on the sample data of trezor in their server implemenation.

Can you ask to trezor if it is possible to validate with verifymessage of bitcoincore or coinig ? (or whatever desktop wallet can do that)

Maybe they are using a different format, but they are not documenting...

**Comment by graffen** [comment]
![capture](https://cloud.githubusercontent.com/assets/151152/11817489/6091f376-a355-11e5-81e9-9a1452aa670f.PNG)

Notice the error message here... the Addresses are different.

**Comment by NicolasDorier** [comment]
I know... NBitcoin is running the same algorithm, and indeed if I verify the message/sig with this address, it returns true. You should ask to Trezor how to verify with bitcoincore their signature, so we understand better how they are doing. Let me know.

**Comment by graffen** [comment]
When I get home I'll post our findings on the Trezor Github page and we'll see what they say. 






On Tue, Dec 15, 2015 at 9:01 AM -0800, "Nicolas Dorier" <notifications@github.com> wrote:












I know... NBitcoin is running the same algorithm, and indeed if I verify the message/sig with this address, it returns true. You should ask to Trezor how to verify with bitcoincore their signature, so we understand better how they are doing. Let me know.

**Comment by graffen** [comment]
@NicolasDorier it seems the verification needs to happen on the raw bytes and not on a hex string. Any chance you can overload PubKey.VerifyMessage to take a byte array? 

See here: 
https://github.com/trezor/connect/issues/12#issuecomment-165076588

**Comment by graffen** [comment]
I just did the implementation locally, I'll send you a PR once it's cleaned up :)

**Comment by NicolasDorier** [comment]
I am curious, because this is what I tried, but I still had false.

**Comment by NicolasDorier** [comment]
Ok I pushed a commit that makes things a bit better.
I also added a test which show how to use trezor with nbitcoin based on the issue.

Look at: https://github.com/MetacoSA/NBitcoin/commit/e32a52890f57bd5cdb9c004940bbc1f7d168bffc#diff-206198143ffd19de2bb2ff239b980abbR92

I'm closing this, thanks for the contribution, I'll push that to nuget when I have some connectivity. (later today)

**Comment by NicolasDorier** [comment]
I just push 2.1.5.11 here is how to use :  e32a528#diff-206198143ffd19de2bb2ff239b980abbR92

**Comment by graffen** [comment]
Much appreciated. Thanks! :+1:

**Comment by NicolasDorier** [comment]
Made a PR on trezor : https://github.com/trezor/connect/pull/13

**Comment by graffen** [comment]
You beat me to it :D

**Comment by NicolasDorier** [comment]
I'm on fire today !!!
