### ISSUE TITLE
BIP-0021 Payment URI builder

### ISSUE THREAD

**Issue by Avalaxy** [MetacoSA/NBitcoin#138]
As far as I'm aware there's currently no builder that allows us to generate BIP-0021 payment URIs (please point it out if I'm wrong, I haven't found it though). Is there any interest for this? I'd like to fork the project and submit a PaymentUriBuilder as a pull request.

**Comment by NicolasDorier** [comment]
There is already : BitcoinUrlBuilder :)

**Comment by Avalaxy** [comment]
@NicolasDorier awesome, didn't know about it. It's not in the documentation. Saves me some work then! Open ended question: are there any specific things you'd like people to contribute to NBitcoin?

**Comment by NicolasDorier** [comment]
Some documentation in my book : https://blockchainprogramming.azurewebsites.net/ but indeed, payment url is not mentioned.
Nothing in particular, but if you think something is missing I'm open to suggestions. Right now I'm working on segwit implementation.

**Comment by Avalaxy** [comment]
Cool, thank you so much for your work.

**Comment by kristapsk** [comment]
> There is already : BitcoinUrlBuilder :)

That is wrong naming, as it is [URI](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier) not [URL](https://en.wikipedia.org/wiki/URL), but guess that cannot be changed anymore due to backwards compatibility issues...

**Comment by knocte** [comment]
> guess cannot be changed anymore due to backwards compatibility issues...

It could be changed, so long as you leave a BitcoinUrlBuilder type that inherits from the (renamed)BitcoinUriBuilder and has an `[Obsolete("Use BitcoinUriBuilder instead")]`. Want to propose a PR?
