### ISSUE TITLE
HD Master Key seed length?

### ISSUE THREAD

**Issue by bitcoinbrisbane** [MetacoSA/NBitcoin#139]
Not so much as an issue but a question.  Is there a min or max length the byte array needs to be in the ExtKey constructor?

If so, Ill add to the comments and perhaps a check / exception throw if not correct in a pull request.

```
public ExtKey(byte[] seed)
```

**Comment by NicolasDorier** [comment]
there is no limitation on the seed. Can be whatever you want.

**Comment by bitcoinbrisbane** [comment]
Thanks mate.

**Comment by NicolasDorier** [comment]
btw if you are still using your fork, you should sync with my repo. Segwit brought a lot of change in NBitcoin (mostly internally)
