### ISSUE TITLE
RPCClient authorization fails against Bitcoin Core v0.11+

### ISSUE THREAD

**Issue by dthorpe** [MetacoSA/NBitcoin#140]
All NBitcoin RPCClient requests now fail with a server response of 401 - Not Authorized. 

Bitcoin core recently changed its RPC authorization code slightly.  FTP username/password in the URI is no longer supported, for one thing, but there may be other behavioral changes. I think this started with release v0.11 or so.  

I tried adding 			
````
webRequest.PreAuthenticate = true;
````

to RPCClient.SendCommandAsync, but that didn't fix it.

**Comment by NicolasDorier** [comment]
I'll take a look when I can migrate on the new RPC on my CI server.

**Comment by NicolasDorier** [comment]
https://github.com/MetacoSA/NBitcoin/commit/c6ed7dcf08527ab94c48969d6bfcc5d954c8836b fixed it
