### ISSUE TITLE
Segnet for Network.GetNetwork()

### ISSUE THREAD

**Issue by Chaz27** [MetacoSA/NBitcoin#141]
Got a drop down of available networks in our application that saves as a string, segnet missing from the GetNetwork() method :)

https://github.com/MetacoSA/NBitcoin/blob/b74dbc79337dc84bb606db55e9aba33ebf03a6e3/NBitcoin/Network.cs#L802

**Comment by NicolasDorier** [comment]
good catch thanks, it is merged!
