### ISSUE TITLE
Getting list of first 100 addresses derived from ExtKey

### ISSUE THREAD

**Issue by Alex-Jaeger** [MetacoSA/NBitcoin#152]
Hi!

Just started looking into your library and I'm finding it amazing to do a few operations on a project in C#, without depending on an ugly interface to a python script.

I need to do what I mention in the subject, basically get the first 100 addresses from a HD key (either xpub or xprv).
Been looking into the relevant classes but I can't find a way.

Could you help me out? I'm pretty new at OO programming still.

Thank you!

**Comment by jspri3** [comment]
Assuming you're familar with this: https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki
 You just need to provide your path.

```c#
            string _basePath = $"m/44'/1'/0'";
            bool isChangeAddress = false
            int change = isChangeAddress ? 1 : 0;
            int currentIndex = 0;
            while (true)
            {
                string path = $"{_basePath}/{change}/{currentIndex}";
                ExtKey derivedKey = key.Derive(new KeyPath(path));
                BitcoinAddress address = derivedKey.PrivateKey.PubKey.GetAddress(_networkFactory.GetNetwork());
                Debug.WriteLine($"New address: {address}.");
                currentIndex++;
                //check index number if you want to exit..
           }
```

**Comment by Alex-Jaeger** [comment]
Wow, that was perfect! I adapted it in a few minutes and had it ready!
Thanks a lot.
This adaptation of the reference implementation is very impressive work.

**Comment by NicolasDorier** [comment]
Thanks, you should take a look at my book on http://n.bitcoin.ninja/ it is the most complete documentation about this library.
