### ISSUE TITLE
Issues signing a transaction

### ISSUE THREAD

**Issue by Alex-Jaeger** [MetacoSA/NBitcoin#154]
Hey guys, hope you can help me out. I'm trying to construct a transaction on testnet using the libraries and been getting into trouble.
Been trying for several hours, re-read the chapter on transactions several times, but I can't seem to find the mistake (obviously it's a misconception on my part).
Hope you might be able to point it out!

`ExtKey _xprvKey = ExtKey.Parse("tprv8ZgxMBicQKsPdf3eLfgjbCxeGSep73nvrgA6eSRq9t4X4SoQ9DYGXeetjpbQ9qu5fd55k1VEADkre66Cfib1xD9P72qb8VzGTnC1vpVPmXV");
			ExtKey extKey = _xprvKey.Derive(new KeyPath("m/0/0"));//this is the source address, the receiver of the TxIn
			BitcoinSecret secret = extKey.PrivateKey.GetBitcoinSecret(Network.TestNet);

			BitcoinAddress sourceAddress = BitcoinAddress.Create("mx4SSmJXaeqrDGwxWmnd6KWk68P6GjLbvf", Network.TestNet);
			BitcoinAddress destAddress = BitcoinAddress.Create("mgdkszxePH9RT7C6aEbv7j3DdTXgCTwaTL", Network.TestNet);//this is m/0/1

			var blockr = new BlockrTransactionRepository();
			blockr.Network = Network.TestNet;
			Transaction fundingTransaction =
			blockr.Get("3f9f7e004430ffc9072afe2730b041d705af35db9be3e2b0342010364b08230c");
			int index = 1;

			var tx = new NBitcoin.Transaction();
			var txIn = new TxIn(new OutPoint(fundingTransaction, index));
			tx.AddInput(txIn);

			var amount = new Money(1240000000, MoneyUnit.Satoshi);//total in source address is 12.5 BTC, keeping 0.1 for the fee
			tx.AddOutput(amount, destAddress);
			txIn.ScriptSig = sourceAddress.ScriptPubKey;
			tx.Sign(secret.PrivateKey, false);`

I think the problem might be the signing or the ScriptPubKey for the input. I'm getting the error "Error sending transaction: Rejected script for input 0 referencing 3f9f7e004430ffc9072afe2730b041d705af35db9be3e2b0342010364b08230c at 1.. " when trying to broadcast the hex of the Tx using https://live.blockcypher.com/btc-testnet/pushtx/
The hex is:
01000000010c23084b36102034b0e2e39bdb35af05d741b03027fe2a07c9ff3044007e9f3f010000001976a914b57667ec0af6f55ebe15047ac17dc1beddfe53f388acffffffff0100e6e849000000001976a9140c41824ce507d3819b3c2c3fa89e5d9e77e8678588ac00000000

**Comment by NicolasDorier** [comment]
you are using the wrong child key, with m/0/0/0 instead of m/0/0 it works.

Be careful, you are sending lots of fee to the user. Please take a look later in the book how to use the TransactionBuilder for signing a transaction instead, it will prevent you from shooting yourself in the foot by doing a transaction with too much fee or incorrect change.

**Comment by Alex-Jaeger** [comment]
Great! That was the issue.
I tried the builder and it's much simpler, will stick to it for now.

Thanks again for the help! I greatly appreciate it.
