### ISSUE TITLE
Deleting INodeBehavior

### ISSUE THREAD

**Issue by plimxx** [MetacoSA/NBitcoin#158]
I am not an expert at all, but only a person very interested in NBitcoin.
Perhaps this is idiot, but don't you think that "INodeBehavior" Interface is redundant?
(It seems to me that we only need to delete it and make minor changes in the abstract class NodeBehavior and in NodeBehaviorsCollection)

**Comment by lontivero** [comment]
It is not redundant, IMO. The `abstract class ClassName : IInterface` is a very convenient pattern that gives you the flexibility to change your code with less pain. It also allows you to create your own INodeBehavior implementation directly without using the abstract class, if you want/need to.

**Comment by NicolasDorier** [comment]
Even though I don't use it in my code, the main problem is that changing that now can break lots of code for not a lot of upside.
Looking back I would probably not have used an interface as it makes things more complicated to change in the future, but well... at least we can have any class be a behavior as lontivero said.

**Comment by plimxx** [comment]
OK, we can maintain INodeBehavior if we want -it does not hinder-, but  this question appeared for me thinking of 'NodeBehaviorsCollection'.
If NodeBehaviorsCollection is a collection of Nodes... I think it has nothing to do to do with INodeBehavior, which is for "another uses we want/need" as lontivero says.
So, in my humble opinion, a collection of Nodes must have exactly Nodes and must exactly inherits a ThreadSafeCollection of NodeBehavior, not a ThreadSafeCollection of INodeBehavior, which may have little -or somewhat stranges- relationships with NodeBehaviorsCollection in a future.
I suggest making at least this little change in NodeBehaviorsCollection. I think this will make the code more accurate.

**Comment by Varmetric** [comment]
Peleando!!

**Comment by NicolasDorier** [comment]
We can't make a NodeBehaviorsCollection a collection of NodeBehavior without breaking lots of existing code for little upside. I don't think it is worth changing it for only easthetic reasons. Especially that users never deal directly deal with the interface and always ends up using `Find<TBehavior>`. 

I don't think changing to collection of NodeBehavior will make their life easier, and at worse my break some of their code.

**Comment by plimxx** [comment]
Thanks Nicolas. I understand and agree.
