### ISSUE TITLE
Fully Validating Node

### ISSUE THREAD

**Issue by 21E14** [MetacoSA/NBitcoin#159]
Not an issue per se; rather, a question. NBitcoin is advertised as a Bitcoin **library** for the .NET platform. Any plans on turning it into a fully validating **client**, ala Bitcoin Core P2P layer?

**Comment by NicolasDorier** [comment]
My main issue with it is that you should consider impossible to have a 100% compliant full node with Core. So I would not advise using such full node in production. (only for testing)
I'm also concerned about whether it can process 7 transaction per seconds.

Nevertheless several people asked me for a full node despite my recommendation against it. I guess I will end up making one if someone can finance that.

**Comment by 21E14** [comment]
From the perspective of an individual node, what particular risk worries you the most with a full node implementation? In your view, does employing bitcoind at the edge defeat the purpose? What do you think it would take to implement a full node?

**Comment by NicolasDorier** [comment]
bitcoind is one of the most reviewed and battle tested open source piece of code. I can't expect NBitcoin full node to be at such level.

This mean that there will likely have more bug and DDOS opportunity on my full node. The least important bug would crash the node and provoke downtime for a depending service. A more important one would provoke a fork, and money would be lost.
Which is why I advise people to get their own trusted bitcoind node and connect to it with NBitcoin.

Making a full node should not be so complicated. One of the big question mark is also whether it can process 7tx/s, even if I use libconsensus for script validation.

**Comment by 21E14** [comment]
You're not referring to the block size debate: Is the performance concern .NET/CPU related?

* https://en.bitcoin.it/wiki/Scalability: Bitcoin is currently able ... to perform around 8000 signature verifications per second on an quad core Intel Core i7-2670QM 2.2Ghz processor. The average number of inputs per transaction is around 2, so we must halve the rate. This means 4000 tps is easily achievable CPU-wise with a single fairly mainstream CPU. ... Of course Bitcoin does other things beyond signature checking, most obviously, managing the database. We use LevelDB which does the bulk of the heavy lifting on a separate thread, and is capable of very high read/write loads. Overall Bitcoin's CPU usage is dominated by ECDSA.

**Comment by NicolasDorier** [comment]
.NET/CPU but also IO throughput read/write is very intensive in bitcoin, Pieter Wuille mostly and other core devs did an impressive job to optimize code to make it possible. Part of it is black magic to me. I may run into problem matchin bitcoind performance.

**Comment by 21E14** [comment]
Thanks for sharing your thoughts. It'd be an interesting experiment.

**Comment by NicolasDorier** [comment]
interesting yes. I think you are right on CPU. NBitcoin has binding on libconsensus which should use sipa's secp256k1 so I think the script verification should not take so much time.
I expect, significant more serialization/deserialization though, which should hit the garbage collector. But frankly this is pure speculation, maybe you are right and 7tps is largely doable.

I'm not sure though about the good database to use. I don't see how to easily use LevelDB. I was thinking about Azure Storage it should support high throughput, but I'm not sure what would be the impact of latency.

**Comment by 21E14** [comment]
With respect to I/O, consider the average incoming bandwidth usage (Bps) by message type on, say, the statoshi node: "tx" and "inv" are, relatively speaking, the top hitters with ~14 KBps and ~7 KBps respectively, and maxing at ~250 KBps and ~17KBps each. 

The outgoing bandwidth usage is dominated by  "block" and "tx" at ~250 KBps and ~40 KBps respectively, and maxing at ~3 MBps and ~1.5MBps each.

The node ( https://statoshi.info/ ) averages more than a 100 peers.

**Comment by NicolasDorier** [comment]
The outgoing and incoming bandwidth figures you sent is the averege or sum of the traffic of 100 peer ?

Azure would support well such kind of figure still not sure about impact of latency. Anyway if I do it, there will be an interface to provide one own db implementation.

Given your figures I'm rather confident it can work.

**Comment by 21E14** [comment]
The average node totals by message type across all peers. These are, of course, a function of the block size, including witness data, and the number of peers. For the 100p statoshi node this translates to 25 KBps incoming and 172 KBps outgoing, below 25% CPU utilization, ~3.5GB RAM, and a generally dormant disk that tends to peak at 20 Mbps both read and write.

**Comment by bdangh** [comment]
I guess with SegWit, request to storage may be reduced, so latency will be not a problem. I think DocumentDb and Table Storage good candidates for DB provider.

Redis also good for memory pool, peer management and throttling.

**Comment by NicolasDorier** [comment]
Interesting. I guess for now I'll not work on it as I have other priority. But it seems very doable indeed.
