### ISSUE TITLE
An item with the same key has already been added

### ISSUE THREAD

**Issue by ademar** [MetacoSA/NBitcoin#162]
I am getting the following crash in Linux and OSX

```text
Ademars-MacBook-Pro:Debug ademar$ mono testing.exe

Unhandled Exception:
System.TypeInitializationException: The type initializer for 'NBitcoin.Network' threw an exception. ---> System.TypeInitializationException: The type initializer for 'NBitcoin.Op' threw an exception. ---> System.ArgumentException: An item with the same key has already been added.
  at System.ThrowHelper.ThrowArgumentException (ExceptionResource resource) <0x1950820 + 0x00036> in <filename unknown>:0 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].Insert (System.Collections.Generic.TKey key, System.Collections.Generic.TValue value, Boolean add) <0x7d6898 + 0x000f3> in <filename unknown>:0 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (System.Collections.Generic.TKey key, System.Collections.Generic.TValue value) <0x7d6860 + 0x00027> in <filename unknown>:0 
  at NBitcoin.Op..cctor () <0x70c3b0 + 0x002bb> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at NBitcoin.Network.CreateGenesisBlock (UInt32 nTime, UInt32 nNonce, UInt32 nBits, Int32 nVersion, NBitcoin.Money genesisReward) <0x70bff0 + 0x0004f> in <filename unknown>:0 
  at NBitcoin.Network.InitMain () <0x707018 + 0x0032f> in <filename unknown>:0 
  at NBitcoin.Network..cctor () <0x6ff050 + 0x051bb> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at testing.MainClass.Main (System.String[] args) <0x6feec8 + 0x0000b> in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'NBitcoin.Network' threw an exception. ---> System.TypeInitializationException: The type initializer for 'NBitcoin.Op' threw an exception. ---> System.ArgumentException: An item with the same key has already been added.
  at System.ThrowHelper.ThrowArgumentException (ExceptionResource resource) <0x1950820 + 0x00036> in <filename unknown>:0 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].Insert (System.Collections.Generic.TKey key, System.Collections.Generic.TValue value, Boolean add) <0x7d6898 + 0x000f3> in <filename unknown>:0 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (System.Collections.Generic.TKey key, System.Collections.Generic.TValue value) <0x7d6860 + 0x00027> in <filename unknown>:0 
  at NBitcoin.Op..cctor () <0x70c3b0 + 0x002bb> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at NBitcoin.Network.CreateGenesisBlock (UInt32 nTime, UInt32 nNonce, UInt32 nBits, Int32 nVersion, NBitcoin.Money genesisReward) <0x70bff0 + 0x0004f> in <filename unknown>:0 
  at NBitcoin.Network.InitMain () <0x707018 + 0x0032f> in <filename unknown>:0 
  at NBitcoin.Network..cctor () <0x6ff050 + 0x051bb> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at testing.MainClass.Main (System.String[] args) <0x6feec8 + 0x0000b> in <filename unknown>:0 
```

**Comment by ademar** [comment]
Test program

```csharp
using System;
using NBitcoin;

namespace testing
{
	class MainClass
	{
		public static void Main (string[] args)
		{
			var tx = new Transaction ();
			Console.WriteLine (tx.ToString());
		}
	}
}

```

**Comment by lontivero** [comment]
I couldn't reproduce this with the latest version (i cloned the repo 10 mins ago). What version are you @ademar using? 
BTW, i don't think this is a race condition because the exception is thrown by a static ctor (..cctor) and because there is no concurrency.

**Comment by ademar** [comment]
@lontivero You are correct it is not a race condition but a different bug. 

Just to confirm, are you running on Unix/Mono ? I am asking because I have found what I think is the bug which I will describe below and it seems this routine could behave differently on Windows.

My test case is crashing here https://github.com/MetacoSA/NBitcoin/blob/3dd167e367f14804a3cff2764a3662ecb3c990ad/NBitcoin/ScriptReader.cs#L303 with "An item with the same key has already been added"

The duplicated key is `OpcodeType.OP_1`.

The expression `Enum.GetName(typeof(OpcodeType), OpcodeType.OP_1)`  on mono returns  `OpcodeType.OP_TRUE`

Running on F# interactive:

```text
> Enum.GetName(typeof<OpcodeType>, OpcodeType.OP_1);;

val it : string = "OP_TRUE"
```
I think this happens because of this definition here https://github.com/MetacoSA/NBitcoin/blob/3dd167e367f14804a3cff2764a3662ecb3c990ad/NBitcoin/Script.cs#L156

Since `OP_TRUE` was added earlier in the initialization routine it crashes when it goes on to add `OP_1`.

Perhaps the simplest fix is not adding `OP_1` but I don't know if that will have consequences.

**Comment by lontivero** [comment]
@ademar, i didn't test it on linux, i did it on windows and I think the problem is this one:

[MSDN - Enum.GetName Method (Type, Object)](https://msdn.microsoft.com/en-us/library/system.enum.getname(v=vs.110).aspx)

> Remarks
> If multiple enumeration members have the same underlying value, the GetName method guarantees that it will return the name of one of those enumeration members. However, it does not guarantee that it will always return the name of the same enumeration member. As a result, when multiple enumeration members have the same value, your application code should never depend on the method returning a particular member's name.
> 

We have to change the implementation, it seems.

**Comment by NicolasDorier** [comment]
@ademar thanks for reporting this bug. I have tested on mac it worked fine. But I will fix it and push a new package today.

**Comment by NicolasDorier** [comment]
Ok I fixed on ee64cefb61cb58e09196d08cffa1899c48206455 and push a new nuget package @ademar can you update the package and check the bug is solved ?

**Comment by ademar** [comment]
Looks good! Thanks!

**Comment by knocte** [comment]
> The expression Enum.GetName(typeof(OpcodeType), OpcodeType.OP_1) on mono returns OpcodeType.OP_TRUE

What version of mono are you using Ademar? I don't reproduce this problem in Mono 4.2.1.

**Comment by ademar** [comment]
```text
Ademars-MacBook-Pro:~ ademar$ mono -V
Mono JIT compiler version 4.2.3 (explicit/832de4b Thu Mar  3 19:24:57 EST 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug 
	LLVM:          yes(3.6.0svn-mono-(detached/a173357)
	GC:            sgen
```

**Comment by NicolasDorier** [comment]
@knocte are you using the right NBitcoin package ? I fixed it and released the package you might be running the fixed version.

**Comment by knocte** [comment]
> @knocte are you using the right NBitcoin package ? I fixed it and released the package you might be running the fixed version.

I'm not interested (for now) in the fixed NBitcoin, but in the Mono bug :)

> @knocte the issue was that `Enum.GetName(typeof(OcpcodeType), OpcodeType.OP_TRUE)` was returning OP_1 on Windows, but OP_TRUE on mono. (or the reverse). Both are not wrong, because OP_TRUE == OP_1. In the original issue, it seems that indeed Enum.GetName behavior is undefined in such case.

True that .NET may not define a true spec for this so the behaviour may be undefined, however Mono should behave as closely as possible to .NET to avoid incompatibilities. And all of incompatibilities should be reported as bugs in http://bugzilla.xamarin.com/.

> Ademars-MacBook-Pro:~ ademar$ mono -V
> Mono JIT compiler version 4.2.3 (explicit/832de4b Thu Mar  3 19:24:57 EST 2016)

It's really strange that you find the bug in a newer version than mine! Can you try my attempt to create a self-contained minimal testcase of the issue? It is:

https://gist.github.com/knocte/c2d64f1692ad225e1ef42dcb70943825

What does that print for you?

**Comment by ademar** [comment]
![Image of mono bug](https://raw.githubusercontent.com/ademar/ademar.github.com/master/blog/Screen%20Shot%202016-05-18%20at%2010.39.37%20PM.png)

**Comment by NicolasDorier** [comment]
@knocte my dev env is in lambo right now, what this print in your version ?

**Comment by knocte** [comment]
> @knocte my dev env is in lambo right now, what this print in your version ?

Already said that I can't reproduce the bug :) (so my version prints "OP_1", so this is either a regression or a bug that only affects the Mac.

@ademar since you're the one experiencing the bug, do you mind filing the bug yourself in http://bugzilla.xamarin.com/ please? (Adding the testcase from my gist, and adding the prefix "[regression]" to the title.)

If I find time in the weekend I may try to fix it myself.

**Comment by ademar** [comment]
FYI: https://bugzilla.xamarin.com/show_bug.cgi?id=41178
