### ISSUE TITLE
Segwit address calculation for different networks

### ISSUE THREAD

**Issue by bijakatlykkex** [MetacoSA/NBitcoin#163]
Hello,

Thanks for adding support for SegWit.

As I have tested

For pubkey: 02ef43bcd42dd7dd37015e8bc76312e4c52c2d3920c16cab185499f12b02740458
1- GetSegwitAddress(Network.Main) returns p2xtf4PnGQFMtEgRREb3UcNLDHx3YwzdNjLW
2- GetSegwitAddress(Network.TestNet) returns p2xtf4PnGQFMtEgRREb3UcNLDHx3YwzdNjLW
3- GetSegwitAddress(Network.SegNet) returns QWywvQ6dAwCfEM8yRJew4Z98X7SgtCcUoxZN

As I understand from https://github.com/bitcoin/bips/blob/master/bip-0142.mediawiki the return values should be:
1- GetSegwitAddress(Network.Main): p2xtf4PnGQFMtEgRREb3UcNLDHx3YwzdNjLW
2- GetSegwitAddress(Network.TestNet): QWywvQ6dAwCfEM8yRJew4Z98X7SgtCcUoxZN

**Comment by lontivero** [comment]
@bijakatlykkex Yes, TestNet and SegNet have to use the same base58Prefix. I think the following lines are missing for the testnet initialization:

```
base58Prefixes[(int)Base58Type.WITNESS_P2WPKH] = new byte[] { 0x3 };
base58Prefixes[(int)Base58Type.WITNESS_P2WSH] = new byte[] { (40) };
```

**Comment by NicolasDorier** [comment]
Indeed. Actually BIP142 will likely not be used in the future, but I'll fix it nevertheless.

Problem is that my current dev environment is in limbo and I need to install visual studio 2015. But my msdn account is bugged and microsoft fixing it... long story short, I'll fix it in 1 or 2 days :p

**Comment by bijakatlykkex** [comment]
Thanks for the comments. But actually as I understand, SegWit is not a different network. We either have main or testnet; and segwit addresses are just one type of address in these networks.

**Comment by NicolasDorier** [comment]
There is the Segnet network right now (https://segnet.smartbit.com.au/)
It will probably disappear at one point.

Yes, Testnet addresses should be the same than Segnet one, this is a bug I need to fix.

**Comment by NicolasDorier** [comment]
fixed it
