### ISSUE TITLE
Xamarin Studio 6 doesn't load NBitcoin(Mono)

### ISSUE THREAD

**Issue by andbene72** [MetacoSA/NBitcoin#167]
Just installed XS6, it does not load anymore NBitcoin(Mono)
This is the error
"Project doesn't support framework '.Net Framework, Version=v4.5'"

Andrea

**Comment by NicolasDorier** [comment]
It is not supposed to open it actually. NBitcoin(Mono) is meant to be compiled on VS.
Does Xamarin support shared projects ? if so I may need to migrate to this system instead of my home grown msbuild hacks.

**Comment by andbene72** [comment]
Unhh... I was using XS (5.5) and it work before the upgrade.
I was using XS because when I try to open the portable solution with VS, it went wrong loading NBitcoin(Mono), even before this upgrade of XS. Probably I have missed some step after installing Mono to let VS see it.

"Target framework not installed" this happen in VS, the strange thing is the v6.0 (???) but in the original project file there is v4.5.
![image](https://cloud.githubusercontent.com/assets/6141792/15955567/82af8ffe-2ee2-11e6-9164-013088ceb155.png)

Xamarin Studio support shared project but in incredibly doesn't support iOS on Windows

**Comment by NicolasDorier** [comment]
If I update to 4.5.2 would it work ? I think 4.5 is deprecated anyway.

**Comment by andbene72** [comment]
The issue seem to be linked to the fact that to build the project the latest Xamarin require
`<TargetFrameworkVersion>v6.0</TargetFrameworkVersion>`
(it's android version)
and 
`<Import Project="$(MSBuildExtensionsPath)\Xamarin\Android\Xamarin.Android.CSharp.targets" />`
That is caused by
`<ProjectTypeGuids>{EFBA0AD7-5A72-4C68-AF49-83D382785DCF};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>`
**EFBA0AD7-5A72-4C68-AF49-83D382785DCF  is GUID for Android.**
FAE04EC0-301F-11D3-BF4B-00C04F79EFBC is windows c# project type.

I have now a modified solution that load correctly on VS2015 AND Xamarin Studio 6 but I'm not sure that (Mono) project is intended in that way as Mono.Android already exist in the solution. But on the other side what is the right GUID for the generic mono project ? I have missed something ?

Also the reference to NBitcoin.Bouncycastle seem broken, as it is missed in the solution.
Just for curiosity, on your VS it load and compiles the current version ? Have you upgraded or uninstalled/reinstalled on a pc that had installed a previous version of VS ?

Andrea

**Comment by NicolasDorier** [comment]
@andbene72 sorry, I got late on this one.
I think I will take the time this week to merge your change about BouncyCastle inclusion in the lib, as well as fixing my weird custom msbuild stuff with shared project, as well as adding real .NET core support.
I guess things will work way better after that !

**Comment by NicolasDorier** [comment]
I removed NBitcoin(Mono), not NBitcoin should work and compile out of the box for mono.

**Comment by knocte** [comment]
I guess you meant "now", not "not"? ;) (You can edit comments in github FYI.)
