### ISSUE TITLE
CoinJoin Contract Implementation

### ISSUE THREAD

**Issue by hu53yin** [MetacoSA/NBitcoin#168]
Hello, 

I want to learn, how can I implement CoinJoin contract with NBitcoin?

https://bitcoin.org/en/developer-guide#coinjoin

Thanks.

**Comment by NicolasDorier** [comment]
I've not implemented Coinjoin, but you can do it with NBitcoin.
Please look https://www.gitbook.com/book/programmingblockchain/programmingblockchain/details for introduction.
