### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by bluj** [MetacoSA/NBitcoin#170]
Hello Nicolas!

I have a question. I would have prefered to ask the question on some NBitcoin-subreddit or NBitcoin slack-channel, but those doesn't seem to exist, and you've written to post questions on this github as an issue... so I am doing that.

My question: Why have you prefixed the title of one chapter of http://www.codeproject.com/Articles/784519/NBitcoin-How-to-scan-the-Blockchain with Obsolete ? Ok I understand that it is obsolete, but is there no scanner at all anymore, and if yes why (was to complex/hard to maintain), or is there a replacement?

**Comment by bluj** [comment]
Oh... maybe this is the replacement?
http://www.codeproject.com/Articles/819567/NBitcoin-Indexer-A-scalable-and-fault-tolerant-blo

**Comment by NicolasDorier** [comment]
Hi, yes, the NBitcoin.Indexer project is still maintained by me (although not documented), it is the indexer behind QBitNinja block explorer I'm using in [my book](https://www.gitbook.com/book/programmingblockchain/programmingblockchain/details).

The *manual scanning* part of the article your linked is still supported though. (might be enough for making stats of the blockchain or ponctual search)

I made the rest obsolete as it was not really scalable nor easy to use.

**Comment by bluj** [comment]
Ok, thanks for your answer!

Do you have any ideas where I could be helpful?
Do you have little tasks (for a start to get my hands dirty) where you could need help?
I am an engineer, and know how to code, even though it is more of a tool in my job, than the main thing I do, so I have to improve on the clean code side of things. I have recently learned some C#, but need to get serious with it. So do you have any ideas for a win-win situation? 
Thanks!

**Comment by NicolasDorier** [comment]
I am interested into making NBitcoin working fine with .NET Core 1.0.
However, I have no idea how to do it, does it interest you ?

**Comment by bluj** [comment]
First of all, I am not sure if this is a good starting point for me to gain more knowledge in C# (and Bitcoin) and I am doubtful I have the required knowledge in this area to contribute much to solve the porting issues... so unfortunately I am not that interested...

Having said that... if this is what you need the most, I might look into it... and who knows maybe with the contribution of some devs here we might come along...

Link for me to continue next time, if I feel motivated for this topic:
https://github.com/microsoft/dotnet-apiport

If you have other ideas, just tell me. But they might also be too Hard-Core... who knows.
Maybe I need an easy start, like writing some testCases or just fiddle around on my own.

**Comment by NicolasDorier** [comment]
if you want to learn C# maybe doing an application would be better (wallet, or other service)

**Comment by NicolasDorier** [comment]
Hey, @tom-corwin is already working on .NET Core portability on https://github.com/MetacoSA/NBitcoin/issues/176 .

I advise you to try to make an application like a simple wallet with QBitNinja and NBitcoin to get used to the library.
