### ISSUE TITLE
unique bitcoin address from xpub

### ISSUE THREAD

**Issue by Amly7** [MetacoSA/NBitcoin#171]
Is there any way to create unique BTC address from xpub (like payment address)?
Thanks in advance!

**Comment by NicolasDorier** [comment]
Yes, read my book to know how: https://www.gitbook.com/book/programmingblockchain/programmingblockchain/details

> extPubKey.PublicKey.GetAddress(Network.Main)

**Comment by NicolasDorier** [comment]
> ExtPubKey.Parse("xpub...").PubKey.GetAddress(Network.Main)

**Comment by Amly7** [comment]
I get the same address every time

**Comment by NicolasDorier** [comment]
That's expected, please look https://www.gitbook.com/book/programmingblockchain/programmingblockchain/details to see how HD key works.

**Comment by NicolasDorier** [comment]
let me know if any other problem
