### ISSUE TITLE
how to use this lib for other coins based on bitcoin??

### ISSUE THREAD

**Issue by frndxyz** [MetacoSA/NBitcoin#172]
any guide regarding it??

**Comment by NicolasDorier** [comment]
This lib works only for bitcoin. Each crypto currency is different.

**Comment by NicolasDorier** [comment]
I am accepting pull request if there is a way to add extensibility in NBitcon to support other coins easily.
For now, only Bitcoin is supported.

**Comment by frndxyz** [comment]
Sure,if NBitcoin is like clone of bitcoinj(JAVA) then there is possibilities to use it for other crypto that is based on bitcoin protocol.

**Comment by NicolasDorier** [comment]
can you provide some example of such use ?
