### ISSUE TITLE
TransactionBuilder#SendAsset with 0 quantity of asset

### ISSUE THREAD

**Issue by bijakatlykkex** [MetacoSA/NBitcoin#175]
Hello,

When the SendAsset function is called with an AssetMoney which has 0 quantity of an asset, a 0 output is created in marker and also the bearer coin appears in output. The specification of protocol ( https://github.com/OpenAssets/open-assets-protocol/blob/master/specification.mediawiki ) says such outputs are uncolored.

So in this scenario, what SendAsset actually does, is to create an uncolored output, and no asset is sent.

Should this behavior be changed and such SendAsset calls be ignored?

Thanks

**Comment by bijakatlykkex** [comment]
This is such a transaction: tapi.qbit.ninja/transactions/14427b91721cf077532f9293ad72bfa5feb67903d19fc797e48e1942aa8559bf?colored=true

**Comment by NicolasDorier** [comment]
I don't see downside nor upside to ignore 0 amount asset. Why should it be changed ?

**Comment by bijakatlykkex** [comment]
Thanks for your reply.

Because I feel the function does something, which its name does not imply (Generating uncolored output).

**Comment by NicolasDorier** [comment]
It all boils down in whether NBitcoin's ColoredTransaction calculation consider such output as uncolored or as colored of 0. If that's the former then you are right.
If it is the later, then we should probably fix both ColoredTransaction and the SendAsset.

**Comment by bijakatlykkex** [comment]
Thanks for the detailed analysis.

I think OpenAssets protocol is better to be followed. The protocol ( https://github.com/OpenAssets/open-assets-protocol/blob/master/specification.mediawiki ) specifically says: "Outputs with an asset quantity of zero are always considered uncolored." (in section "Asset transfer outputs")

Also as far as I checked the QBit.Ninja output considers this as uncolored output and not colored of 0. (output index 2 of http://tapi.qbit.ninja/transactions/14427b91721cf077532f9293ad72bfa5feb67903d19fc797e48e1942aa8559bf?colored=true )

So it seems the correct approach, would be to consider such output as uncolored.

**Comment by NicolasDorier** [comment]
QBit.Ninja uses NBitcoin logic for getting the colors of the transaction.
Happy to have implemented right. So yes, SendAsset 0 should be a no op.

**Comment by NicolasDorier** [comment]
I just tested current behavior, doing a SendAsset(0) does not create an output.

**Comment by NicolasDorier** [comment]
fixed by 5bc0a7a
