### ISSUE TITLE
NBitcoin port for .NET Core (WIP)

### ISSUE THREAD

**Issue by tom-corwin** [MetacoSA/NBitcoin#176]
Hi!

I'm currently porting this project to .NET Core. Since you use GitHub Issues for feedback, I figured I'd announce it here to let you and others know about the project.

I could use all the help I can get since I have limited experience with C# and .NET Core is relatively new and incomplete.

~~Project URL: [http://github.com/tom-corwin/NBitcoin-NETCore](http://github.com/tom-corwin/NBitcoin-NETCore)~~
Project Temporary URL: [http://github.com/tom-corwin/NBitcoin](http://github.com/tom-corwin/NBitcoin)

If this type of issue post isn't acceptable, my apologies in advance!

**Comment by NicolasDorier** [comment]
cool, you should take a look at what @andbene72 did. https://github.com/MetacoSA/NBitcoin/pull/174

**Comment by NicolasDorier** [comment]
ping @andbene72  @flavien I knew you both where playing recently around that as well.

**Comment by NicolasDorier** [comment]
https://github.com/MetacoSA/NBitcoin/pull/174#issuecomment-235501965

**Comment by tom-corwin** [comment]
So I'm sort of stuck right now with the port, since I cannot figure out how to correctly workaround the 4 errors remaining in the solution. They are all in NBitcoin/Protocol/Node.cs, if anyone would like to take a look at it. Build instructions are in the README.md file.

@NicolasDorier, I've also decided to keep the NewtonSoft.Json package rather than the source code in the portable directory due to ease of porting, for now.

**Comment by NicolasDorier** [comment]
You should use NewtonSoft package anyway. I'm embedding it only for profiles where it is not available.
I'll take a look at it.

**Comment by tom-corwin** [comment]
Due to some issues with the project format used by .NET Core (which will be fixed in either the 1.0.1 or 1.1.0 version of the framework), I cannot add a working solution file for the NETCore port. (.NET Core tooling for Visual Studio will not let me add external files as links [[Issue 147 in ASP.NET Tooling](https://github.com/aspnet/Tooling/issues/147)]). I will hopefully be adding a pull request with a branch named 'netcore' tonight using a working [workaround](https://github.com/aspnet/Tooling/issues/147#issuecomment-235704620) to reference the files without making a copy of them in the project directory, if the workaround works. 

**NOTE**: The NETCore port is best to be edited and built with Visual Studio Code until this issue is fixed with the ASP.NET Tooling for VS..

**Comment by NicolasDorier** [comment]
@tom-corwin one note: I'm using tabs for indent, I see in your branch it is spaces.

**Comment by tom-corwin** [comment]
@NicolasDorier okay. I will fix that in the next commit.

**Comment by tom-corwin** [comment]
@NicolasDorier I didn't mean to close the issue. Completely pressed the wrong button.

**Comment by NicolasDorier** [comment]
with which

**Comment by tom-corwin** [comment]
After you install the .NET Core SDK, Runtime, and Tooling for Visual Studio (more info [here](https://www.microsoft.com/net/core)), you can either compile with Visual Studio, or using the command `dotnet build` in the NBitcoin.NETCore directory.

**Comment by tom-corwin** [comment]
I just pushed a commit ([link](https://github.com/tom-corwin/NBitcoin/commit/20aeb1ab6e06647eb1c1165a7f292bff3eb2b83d) with a VS Solution and Project so it can be built in Visual Studio 2015 with Update 3.

**Comment by tom-corwin** [comment]
Until the `netcore` branch is merged into this repository, all issues regarding the branch should be submitted into my fork, just to keep everything organised.

**Comment by NicolasDorier** [comment]
```
-------------------
A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.
Decompressing 100% 4322 ms
Expanding 100% 15236 ms
log  : Restoring packages for E:\Sources\NBItcoinNetCore\NBitcoin\NBitcoin.NETCore\project.json...
error: Unable to resolve 'System.Net.Requests (>= 4.0.12-beta-24329-03)' for '.NETStandard,Version=v1.6'.
error: Unable to resolve 'System.Net.NameResolution (>= 4.0.1-beta-24329-03)' for '.NETStandard,Version=v1.6'.
error: Unable to resolve 'System.Threading.Tasks.Parallel (>= 4.0.2-beta-24329-03)' for '.NETStandard,Version=v1.6'.
error: Unable to resolve 'System.Threading.Thread (>= 4.0.1-beta-24329-03)' for '.NETStandard,Version=v1.6'.
error: Unable to resolve 'System.Threading.Tasks (>= 4.0.12-beta-24329-03)' for '.NETStandard,Version=v1.6'.
error: Unable to resolve 'System.Collections.NonGeneric (>= 4.0.2-beta-24329-03)' for '.NETStandard,Version=v1.6'.
error: Unable to resolve 'System.Globalization.Extensions (>= 4.0.2-beta-24329-03)' for '.NETStandard,Version=v1.6'.
error: Unable to resolve 'NETStandard.Library (>= 1.6.1-beta-24329-03)' for '.NETStandard,Version=v1.6'.
log  : Writing lock file to disk. Path: E:\Sources\NBItcoinNetCore\NBitcoin\NBitcoin.NETCore\project.lock.json
log  : E:\Sources\NBItcoinNetCore\NBitcoin\NBitcoin.NETCore\project.json
log  : Restore failed in 3537ms.

Errors in E:\Sources\NBItcoinNetCore\NBitcoin\NBitcoin.NETCore\project.json
    Unable to resolve 'System.Net.Requests (>= 4.0.12-beta-24329-03)' for '.NETStandard,Version=v1.6'.
    Unable to resolve 'System.Net.NameResolution (>= 4.0.1-beta-24329-03)' for '.NETStandard,Version=v1.6'.
    Unable to resolve 'System.Threading.Tasks.Parallel (>= 4.0.2-beta-24329-03)' for '.NETStandard,Version=v1.6'.
    Unable to resolve 'System.Threading.Thread (>= 4.0.1-beta-24329-03)' for '.NETStandard,Version=v1.6'.
    Unable to resolve 'System.Threading.Tasks (>= 4.0.12-beta-24329-03)' for '.NETStandard,Version=v1.6'.
    Unable to resolve 'System.Collections.NonGeneric (>= 4.0.2-beta-24329-03)' for '.NETStandard,Version=v1.6'.
    Unable to resolve 'System.Globalization.Extensions (>= 4.0.2-beta-24329-03)' for '.NETStandard,Version=v1.6'.
    Unable to resolve 'NETStandard.Library (>= 1.6.1-beta-24329-03)' for '.NETStandard,Version=v1.6'.

E:\Sources\NBItcoinNetCore\NBitcoin\NBitcoin.NETCore>
```

Got this error, any idea ?

**Comment by NicolasDorier** [comment]
Ok I did have to create Nuget.config in the project folder.
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="dotnet-core" value="https://www.myget.org/F/dotnet-core/api/v3/index.json"/>
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```

**Comment by NicolasDorier** [comment]
Now
```
E:\Sources\NBItcoinNetCore\NBitcoin\NBitcoin.NETCore>dotnet run
Can not find runtime target for framework '.NETStandard,Version=v1.6' compatible with one of the target runtimes: 'win10-x64, win81-x64, win8-x64, win7-x64'. Possible causes:
1. The project has not been restored or restore failed - run `dotnet restore`
2. The project does not list one of 'win10-x64, win81-x64, win8-x64, win7-x64' in the 'runtimes' section.
3. You may be trying to publish a library, which is not supported. Use `dotnet pack` to distribute libraries.
```

**Comment by NicolasDorier** [comment]
ho it was "dotnet pack"... it works now.

What do you want to get done before making a PR ? seems good to me once you fixed the indent.

**Comment by NicolasDorier** [comment]
The Socket Begin stuff can be fixed later. I think we can do it easily by making some shim using the Async methods.

**Comment by tom-corwin** [comment]
Alright. I will work on the indents in just a bit and will submit a pull request to the master branch.

**Comment by NicolasDorier** [comment]
About the Begin/End, they are not going to come back: https://github.com/dotnet/corefx/issues/3913
I guess I need to use Async now instead of Begin.
However, my reason for using Begin/End was efficiency I benchmarked long time ago... I need probably to revise that.

**Comment by tom-corwin** [comment]
Okay. Then for now we will just keep the `NOSOCKET` symbol until then. I will be getting to the final revisions tomorrow afternoon sometime. I got caught up in some family issues today and never got to it.

**Comment by NicolasDorier** [comment]
@tom-corwin can you rebase on my master ?

```
git checkout master
git pull https://github.com/MetacoSA/NBitcoin.git master
git checkout netcore
git rebase master
#Fix Utils to use #if !NOSOCKET
git add Utils.cs
git rebase --continue
git push --force
```

**Comment by NicolasDorier** [comment]
@tom-corwin and remove NOSOCKET symbol, it now compiles ! :)

**Comment by tom-corwin** [comment]
I made a pull request, but I could not get it to compile without the NOSOCKET symbol.

**Comment by tom-corwin** [comment]
I'm closing this issue since the PR has been merged. Anything else about it can be [posted into my fork](http://github.com/tom-corwin/NBitcoin).

**Comment by NicolasDorier** [comment]
I need to do the nuget package still though.

**Comment by tom-corwin** [comment]
Okay. Then I will leave it open until then.

**Comment by NicolasDorier** [comment]
Officially supported on Nuget from now on https://nuget.org/packages/NBitcoin
