### ISSUE TITLE
Stiring away from portable library

### ISSUE THREAD

**Issue by NicolasDorier** [MetacoSA/NBitcoin#180]
With the release of NBitcoin on .NETStandard 1.6, I intend to get rid of the portable libraries.
I will probably try to lower to .NETStandard 1.4 for adding more support.

This should fix https://github.com/MetacoSA/NBitcoin/issues/167 as we won't need a separate Mono package anymore.

Some links:

What are standard plateform: https://docs.microsoft.com/en-us/dotnet/articles/standard/library
A way to make plateform specific DLL while having a single library for compilation purpose: https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#package-authoring

@andbene72 @flavien might interest you.

**Comment by Flavien** [comment]
Trying to remove while referencing NBitcoin 3.0.0.43:

```
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win+wpa81+wp80+Xamarin.iOS10+MonoAndroid10+MonoTouch10"
      ]
```

I get the following errors:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1002	The dependency System.Threading.Tasks.Parallel 4.0.0 does not support framework .NETStandard,Version=v1.6.
Error	NU1002	The dependency NBitcoin 3.0.0.43 does not support framework .NETStandard,Version=v1.6.
```

**Comment by NicolasDorier** [comment]
@Flavien have you tried to update dotnet tool ? (1.0.0-preview2-003121)

**Comment by NicolasDorier** [comment]
and for System.Threading.Tasks.Parallel try version 4.0.1

**Comment by Flavien** [comment]
That's the SDK version I am running.

**Comment by NicolasDorier** [comment]
what happen if you try to make a project from scratch referencing NBitcoin package with dotnet new ? (tried that yestersday on ubuntu, it worked fine)

**Comment by Flavien** [comment]
This works:

```
{
  "version": "1.0.0-*",
  "dependencies": {},
  "frameworks": {
    "netstandard1.6": {
      "dependencies": {
        "NBitcoin": "3.0.0.43"
      },
      "imports": "dnxcore50"
    }
  }
}
```

This doesn't:

```{
  "version": "1.0.0-*",
  "dependencies": {},
  "frameworks": {
    "netstandard1.6": {
      "dependencies": {
        "NBitcoin": "3.0.0.43"
      }
    }
  }
}
```

``dotnet restore`` returns ``Package NBitcoin 3.0.0.43 is not compatible with netstandard1.6``.

**Comment by NicolasDorier** [comment]
what about:

```
{
  "version": "1.0.0-*",
  "dependencies": {
  "NBitcoin": "3.0.0.43"
},
  "frameworks": { }
  }
}
```

**Comment by NicolasDorier** [comment]
@Flavien can you try with 3.0.0.45 I pushed some changes ?

**Comment by Flavien** [comment]
It works now, thanks.

**Comment by NicolasDorier** [comment]
Portable libraries got removed.
