### ISSUE TITLE
ReadEx bug and other improvements

### ISSUE THREAD

**Issue by GSPP** [MetacoSA/NBitcoin#183]
There's a bug in ReadEx (which I'm willing to fix). Also, there is some confusion there I think. So before addressing that I wanted to check with the project owners.

The bug is that Stream.Read never returns -1. So the [special case](https://github.com/MetacoSA/NBitcoin/blob/b591359ea3ff7ed3b9d439d1dadb7ddfd8eb8abe/NBitcoin/Utils.cs#L151) never hits. It should trigger based on zero which signals the end of the stream.

This signal is universal. It is not necessary to special case certain stream types. Therefore, all type checks in [this line](https://github.com/MetacoSA/NBitcoin/blob/b591359ea3ff7ed3b9d439d1dadb7ddfd8eb8abe/NBitcoin/Utils.cs#L153) should be removed.

The [cancellation handling](https://github.com/MetacoSA/NBitcoin/blob/b591359ea3ff7ed3b9d439d1dadb7ddfd8eb8abe/NBitcoin/Utils.cs#L137) is dubious: In case of cancellation the IO will continue to run. It will continue to consume bytes from the stream and write into the buffer. Therefore, the only safe thing to do in case of cancellation is to discard the stream (the caller must do that). IOs in .NET are not cancellable.

Is it possible to use the `public virtual Task<int> ReadAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)` overload? That would be the best fix. In newer .NET Framework versions all common streams should have an efficient implementation for this.

Alternatively, I'd suggest creating a Task for the read using `FromAsync`. Tasks are composable more easily and faster. Implementing cancellation with them should be faster than the double-WaitHandle approach.

[This](https://github.com/MetacoSA/NBitcoin/blob/b591359ea3ff7ed3b9d439d1dadb7ddfd8eb8abe/NBitcoin/Utils.cs#L139) is a bug because it fails to call `EndRead`. This violates the contract of `Stream`. The bug probably is of no practical consequence since the stream must be discarded after cancellation anyway.

What are your thoughts?

**Comment by NicolasDorier** [comment]
Frankly, I hate this piece of code, it grew organically by fixing strange bugs and performance problems I hit in the past.

Stream.Read returns -1 in the case of NetworkStream for example. (if I remember, it is 
The special case of Network stream type was because of a big performance issue when you read a lot. (You can try that yourself by downloading all the blocks from one of your nodes and timing the speed)

I did not used ReadAsync also because of huge performance issue. So I say, you can try to rewrite it in a less dubious way, I would be glad. But you should really benchmark to the perf problems.

**Comment by NicolasDorier** [comment]
You can show in real time the download speed of a node by using the PerformanceCounter of Node.

**Comment by NicolasDorier** [comment]
PS: I just checked on MSDN about -1 returns by Stream.Read, and it seems I am wrong... but there should be a reason why I used that...

**Comment by NicolasDorier** [comment]
Ah be careful, indentation is TAB in NBitcoin. I missed that in your last PR.

**Comment by GSPP** [comment]
`ReadByte` returns -1. I'll fix the -1 bug and maybe other issues as well. I'm personally only concerned with the -1 thing which would be triggered by an early ending stream.

Will observe the tab setting next time. Actually, did you ever consider switching to spaces? It seems that's where most code bases are these days. I find them easier to handle.

**Comment by GSPP** [comment]
I don't have experience with non-Desktop .NET Frameworks. I'm not sure I'm qualified to switch over to the ReadAsync version given that I don't know on what platforms it will be present and fast. What platforms are supported by this library?

**Comment by NicolasDorier** [comment]
I guess I'll have to at one point, but it is kind of painful as I have so much projects using TAB :(

**Comment by GSPP** [comment]
I had the same experience. A mass replace with GrepWin and Visual Studio settings took care of it. The breakage potential is low.

**Comment by NicolasDorier** [comment]
Plateform are https://www.nuget.org/packages/NBitcoin so basically, all of them.

**Comment by knocte** [comment]
> A mass replace with GrepWin and Visual Studio settings took care of it. The breakage potential is low.

If you do that, you basically remove/pollute all commit history, you would render `git blame` tool useless.

**Comment by NicolasDorier** [comment]
@knocte I think you can ask to ignore whitespaces when you make a diff.

**Comment by GSPP** [comment]
@knocte that is a concern but it's a one-time break in history. If you find that your blame stops at that revision you can run a 2nd blame with the max revision below the mass changes. I had this experience as well and in my case the number of blames that were run was rather small. After 1-2 years of additional history the problem went away. The earlier this is done the less painful it is.

**Comment by knocte** [comment]
I know projects that have TAB instead of spaces as indentation and they are just fine. Note: I'm not defending any particular style, I personally don't care one or the other, what I care is about having a consistent style across all files and across all history.

> @knocte that is a concern but it's a one-time break in history.

Talking about history, you could automate this to be changed with `git filter branch` in order to rewrite history as if the new policy had been there all the time.

**Comment by NicolasDorier** [comment]
I merged @GSPP PR after having tested on NETCore and Mono/Desktop. I also managed to find out why tests were hanging in command line.
