### ISSUE TITLE
Basic SPV address tracking

### ISSUE THREAD

**Issue by djpnewton** [MetacoSA/NBitcoin#186]
I am trying to get a basic example of tracking a bitcoin address (see https://github.com/djpnewton/NBitcoin.SPV.TrackAddressBasic/blob/master/NBitcoin.SPV.TrackAddressBasic/Program.cs ) 

I am connected to a trusted local peer, downloading all the headers trying to get notifications of all relevant txs to but I seem to get too many false positives and disconnecting the peer (TrackerBehaviour.cs:CheckFPRate()). I think the problem is the program is going around in circles continuously reprocessing the same false positive txs but I am not sure why

**Comment by NicolasDorier** [comment]
The wallet class encapsulate those behaviors to use them correctly in a privacy maximizing way. (https://github.com/NicolasDorier/NBitcoin.SPVSample) 

It is normal that a node get kicked after a while, scanning make the filter "dirty" which raise the FP Rate and so the bandwidth, so the filter need to be reset time to time, and the most privacy friendly way of resetting the filter is to drop the connection and find a new node.

Anyway, to fix your particular example, what you need to do is save the TrackerBehavior.CurrentProgress (which is a BlockLocator, same type as scanLocation) of the Tracker, so when it reconnects, it does not start all over again.

**Comment by djpnewton** [comment]
Thanks for the tips.

When TrackerBehavior gets into this high false positive state TrackerBehavior.CurrentProgress is **null**. I have looked through the code and done some debugging but I cant see why that should be so (it *seems* to be a bug)

**Comment by NicolasDorier** [comment]
The other bug is: You should not use Attach/Detach on behavior. The behavior you are manipulating in this code is not the same than the one really attach.

When you attach a behavior to the node through the NodeParameters, then, when the node start, the behavior will be cloned the clone attached to the node.

**Comment by djpnewton** [comment]
Thanks again.

Ok I modified my code to use the tracker behavior from Node.Behaviors after called Node.Connect().

I have modified the TrackerBehavior not to disconnect when getting too many false positives (I will try and submit a PR to make this configurable in the future)

I get lots of 'merkleblock' and 'tx' messages but none of them generate tracker operations unless the transaction I want to track is in my peers memory pool, I do not get tracker operations from transactions that are confirmed in the block chain (which is more important to me)

**Comment by NicolasDorier** [comment]
> I have modified the TrackerBehavior not to disconnect when getting too many false positives 

Don't do that. If you do, eventually your SPV client will download full blocks.

> k I modified my code to use the tracker behavior from Node.Behaviors

Should be ok, but the practice is to put it in the NodeParameters and pass the parameter at Node.Connect.

>  I want to track is in my peers memory pool, I do not get tracker operations from transactions that are confirmed in the block chain (which is more important to me)

Can I see your code now ?

**Comment by djpnewton** [comment]
>Can I see your code now ?

https://github.com/djpnewton/NBitcoin.SPV.TrackAddressBasic/blob/2be2dd47e6d3d8fc10ea135a13751bc888b4049b/NBitcoin.SPV.TrackAddressBasic/Program.cs

**Comment by NicolasDorier** [comment]
will try to debug that, thanks.

**Comment by NicolasDorier** [comment]
The problem is that when you are asking for MerkleBlocks, the peer is already busy responding to your GetHeaders requests. Your code is fine, you just have to wait it sync all the chain.

I advise you for your tests to download all the chain and save it somewhere. (using chain.ToBytes()/chain.ToLoad)

Pro tip:
```
	<system.diagnostics>
		<sources>
			<source name="NBitcoin.NodeServer" switchValue="Verbose">
				<listeners>
					<add name="def" type="System.Diagnostics.ConsoleTraceListener"></add>
				</listeners>
			</source>
		</sources>
	</system.diagnostics>
```

Will show you message sent and received by NBitcoin.

**Comment by NicolasDorier** [comment]
@djpnewton Here an example about how to use the NodeGroup class to keep reconnecting automatically when your node is kicked because of FP:

https://gist.github.com/NicolasDorier/a3e3025ebcdd186504aab03ad7ea97b8

**Comment by djpnewton** [comment]
Cheers Nicolas,

I think your gist forgot to update scan location on node disconnect though.

I now am able to successfully get information about confirmed transactions relating to my address.

Some thoughts (under the context of using a trusted peer):

  - If starting TrackerBehaviour.Scan() using old date time offset for skipBefore param the scanning takes a **long** time
  - It would be nice to be able to not disconnect peer on high false positive event and instead reset bloom filter somehow
  - I wonder if there could be a more efficient way using bitcoind REST api + zeromq

**Comment by NicolasDorier** [comment]
@djpnewton why are you not using my Wallet class ? (or you can do your own one by copying the code)
It does exactly what you do + deals with saving the ScanLocation and Tracker operations in JSON.

I should actually use a lower FPRate if the sync is far from the hear of main chain to speed up the sync as well. I agree that this kind of logic is good to add in the TrackerBehavior.

I don't have any dependency on zeromq. You can access bitcoind API with RestClient or RPCClient though. You can also configure bitcoind for firing up a command line when if find a block or transaction.

It would be more efficient, knowing you have a trusted peer I would use this way instead of SPV which is always less efficient and hard to code.

**Comment by NicolasDorier** [comment]
If you are not against some infrastructure, I coded a block explorer called qbit ninja. (http://api.qbit.ninja/) which you can setup on a VM on Azure, it also has its own package (QBitNinja.Client)

**Comment by djpnewton** [comment]
>@djpnewton why are you not using my Wallet class ? (or you can do your own one by copying the code)
It does exactly what you do + deals with saving the ScanLocation and Tracker operations in JSON.

I just wanted to try and make my own wallet and also start looking at the NBitcoin library. Also I dont think the NBitcoin SPV wallet is setup for using a single trusted node

At the moment I am trying to resurrect the UXTO address index feature in bitcoind. I think it would be useful to have it query-able from the REST interface. Then  I can make an NBitcoin based wallet that uses that.

How big of a database does Qbit Ninja create?

**Comment by NicolasDorier** [comment]
well, the cost of my database for example now is about 30€ a month of storage. You also need a VM. (around 40€)
If you are a business with bizpark you can have free azure storage so it is free.
QBit is not done to optimize size, but to optimize availability and indexing speed.

**Comment by NicolasDorier** [comment]
@djpnewton did I responded to your problem ?

Your way of using NBitcoin was fine, it is just that you need to wait for the chain to sync, which can take a while. (it is around 32MB)

I sent you a simpler way to use NodesGroup for maintaining connection.

**Comment by djpnewton** [comment]
Yes my example is working and uses the NodesGroup (https://github.com/djpnewton/NBitcoin.SPV.TrackAddressBasic/blob/master/NBitcoin.SPV.TrackAddressBasic/Program.cs)

I think SPV is not ideal for my case though.

What I would like is to have a trusted peer act as a border router and also give me any information I need to implement a wallet:

`P2P Network <----> Trusted Peer <----> My Wallet`

Thanks for your help

**Comment by NicolasDorier** [comment]
Yes, so in this case you can use QBitNinja there is a package for it "QBitNinja.Client" the service is on http://api.qbit.ninja/, I am using it for myself.

**Comment by djpnewton** [comment]
the problem is my SSD is not so big, the blockchain is 80GB and then something like qbit adds another ~80GB and I start running out of space and it gets slow on the laptop I am developing on.

I am working on reviving the "txoutsbyaddress index" feature (https://github.com/bitcoin/bitcoin/pull/5048/). So far I have updated it to work with the last year of code changes and moved it to a separate database, now I am adding a REST interface.

With this and txnotify/blocknotify I think I will have enough to implement a reliable wallet and only add about 1GB of extra space used.

**Comment by NicolasDorier** [comment]
No, QBitNinja is using Azure Storage. You need to run a server on Azure though so all in all it can cost you around 70 USD.

**Comment by djpnewton** [comment]
You cant run it on your own server?

**Comment by NicolasDorier** [comment]
the server need at least to be on Azure in the same datacenter as the storage for initial indexing or it will take very long. I advise you to keep running the server after on Azure datacenter, else, latency might make your server slower.
