### ISSUE TITLE
Removing UWP specific code

### ISSUE THREAD

**Issue by NicolasDorier** [MetacoSA/NBitcoin#187]
@andbene72 I plan to remove the UWP define you added, as now NBitcoin run .NET Standard 1.1 (limited features) and 1.3 (full feature) which should work fine with UWP.

Do you have a project you are developing now to test the new package of NBitcoin ?

**Comment by andbene72** [comment]
You can remove it. I had little time last month to test the support of net.standard introduced in NBitcoin but I think that I will follow this path, it seems to me the most practical.

**Comment by NicolasDorier** [comment]
I'm waiting you give a try just in case... got some surprises with Mono, might have in UWP as well.

**Comment by NicolasDorier** [comment]
@andbene72 any feedback ?

**Comment by andbene72** [comment]
Hi Nicolas,

still have not tested, but proceed, I will not have time in the next month as I have just started a new bitcoin related job, finally fully enganged in the tecnology. :D

**Comment by NicolasDorier** [comment]
Nice I hope you are using NBitcoin in the new job :D
