### ISSUE TITLE
SPV Tracker GetSpendableCoins() Exception

### ISSUE THREAD

**Issue by JetJet13** [MetacoSA/NBitcoin#189]
Hey there, 
I ran into this exception today regarding `NBitcoin.SPV.Tracker.GetWalletTransactions(chain).GetSpendableCoins()` [source](https://github.com/MetacoSA/NBitcoin/blob/master/NBitcoin/SPV/WalletTransactionsCollection.cs#L68-L76)
The exception message: `An item with the same key has already been added.`

I haven't quite figured out what I did to raise the exception, but the message is clear as to what broke.

Thanks.

PS. Thank you for making this library, its fantastic.

**Comment by JetJet13** [comment]
Alright, so after a little tinkering, I was able to repeat the error. 

I first built a transaction (with transaction builder) using the `Coin` elements found in `GetSpendableCoins()`. Then I used `BroadcastTransactionAsync(myTx)` to send the tBTC. I then waited a little while for the `Tracker` to pick up the transaction. It didn't, so I shutdown the program and tried rerunning it thinking it would pick up the transactions with fresh nodes. Instead, it crashed and I got the error I mentioned above. 

I imagine it has something to do with the tracker picking up new wallet transactions and inserting the new wallet change outputs into the `GetSpendableCoins()` enum. 

Cheers.

**Comment by NicolasDorier** [comment]
Thanks, I will try to reproduce.

**Comment by NicolasDorier** [comment]
I pushed version 3.0.0.54. Can you Update-Package NBitcoin and see if the bug still exist ?

**Comment by NicolasDorier** [comment]
@JetJet13 did 3.0.0.54 fixed this issue ?

**Comment by JetJet13** [comment]
Yes. Since the update, the error has not come up when I tried to reproduce the exception. Thank you for taking the time to address this bug. 

Cheers.
