### ISSUE TITLE
Bearer coin amount for Open Assets

### ISSUE THREAD

**Issue by bijakatlykkex** [MetacoSA/NBitcoin#195]
Hello,

It seems the default BTC amount for bearer coin for open assets colored coin is 2700 satoshis in NBitcoin while generating transaction, for example: https://www.blocktrail.com/BTC/tx/223f564d0c1220cd85dc36b9c47827158fc08ef65fc2c6bc8cc8587380a9ff0f

The default value seems to be dust as it is under 2730 satoshis (and for example the above mentioned explorer displays). As I think this value should be at least 2730 satoshis, can be alerted by NBitcoin library user, or it is hard coded?

Thanks very much

**Comment by NicolasDorier** [comment]
Normally 2700 is calculated correctly, dust is a function of the size of the ScriptPubKey. P2SH is a bit smaller than P2PKH. (which is 2730)
Blocktrail has a bug.

**Comment by bijakatlykkex** [comment]
Thanks very much for the explanation.

**Comment by NicolasDorier** [comment]
If you want to modify the dust amount, change the value of `txbuilder.StandardTransactionPolicy.MinRelayTxFee`.
