### ISSUE TITLE
CSV support for TransactionBuilder

### ISSUE THREAD

**Issue by nopara73** [MetacoSA/NBitcoin#197]
Is there CHECKSEQUENCEVERIFY support for TransactionBuilder?

**Comment by NicolasDorier** [comment]
The TransactionBuilder supports natively only those scripts: https://github.com/MetacoSA/NBitcoin/tree/master/NBitcoin/BuilderExtensions

However, you can easily create your own extension, and use `tbuilder.Extensions.Add(yourextension)` for more complex script.

**Comment by nopara73** [comment]
Not succeeding, but we'll probably have to revisit this during TumbeBit implementation so I close it for now.
