### ISSUE TITLE
Bug with RPCClient.ListUnspent ?

### ISSUE THREAD

**Issue by barrylloyd** [MetacoSA/NBitcoin#203]
When I try to call the RPCClient.ListUnspent method like...

```
var from = BitcoinAddress.Create("1EL79jW8QAzvxLiHGCKwsZKMhSErTGQZ7x");
var unspent = rpcClient.ListUnspent(0, 999999, from);
```
I get the exception (on the second line)...

> An exception of type 'Newtonsoft.Json.JsonWriterException' occurred in mscorlib.dll but was not handled in user code
> Additional information: Unsupported type: System.String[]. Use the JsonSerializer class to get the object's JSON representation. Path 'params'.

The problem seems to be in the RPCRequest.WriteJSON method, which doesn't handle an array param.
In that method if I change the for-loop code from...

```
for (int i = 0; i < Params.Length; i++)
{
    if (Params[i] is JToken)
    {
        ((JToken)Params[i]).WriteTo(writer);
    }
    else
    {
        writer.WriteValue(Params[i]);
    }
}
```

to 

```
    for (int i = 0; i < Params.Length; i++)
    {
        if (Params[i] is JToken)
        {
            ((JToken)Params[i]).WriteTo(writer);
        }
        else if (Params[i] is Array)
        {
            writer.WriteStartArray();
            foreach (var x in (Array)Params[i])
            {
                writer.WriteValue(x);
            }
            writer.WriteEndArray();
        }
        else
        {
            writer.WriteValue(Params[i]);
        }
    }
```

...then it works ok 
But I'm just surprised that no-one else has seen this before. I'm using Bitcoin Core 0.13.0

**Comment by NicolasDorier** [comment]
I could reproduce, I'm very surprised myself, as other RPC method which has params works without any problem.

**Comment by NicolasDorier** [comment]
Thanks, fixed by https://github.com/MetacoSA/NBitcoin/commit/b270c850f5b06ff2c4d48b65b49ffe548cab173f

**Comment by NicolasDorier** [comment]
(3.0.0.70 was pushed)
