### ISSUE TITLE
Featue request: Uncolor colored coins

### ISSUE THREAD

**Issue by bijakatlykkex** [MetacoSA/NBitcoin#206]
Hello,

Is it possible to add the function uncolor of open assets colored coins to the library? 

Something like SendAsset but with a functionality like Uncolor feature of coinprism.com.

Thank you

**Comment by NicolasDorier** [comment]
why not just spending the ColoredCoin as a Coin ? It would do the trick.

**Comment by bijakatlykkex** [comment]
At least there is one reason, that we may require partial uncoloring from a single output. For example a single output with 300 Assets and we want to uncolor 150 assets, in a single transaction.

**Comment by NicolasDorier** [comment]
mmh I don't think the protocol allows that.
For destructing the coins, you need to spend them in a uncolored transaction, there is no other way.

What we can do though is to spend the coins we want to destroy to the OP_RETURN. However, I wonder if coinprism will show those coins as effectively destroyed. (even if they objectively are)

Would it suit your needs?

**Comment by bijakatlykkex** [comment]
- I mean for example if we have 1000 colored coins, and we want to uncolor two of them; A transaction is generated which inputs 1000 and outputs 998 (The following transaction is generated using coinprism):

http://tapi.qbit.ninja/transactions/5ba4529223bd6842b93c0848ee00c23b20dd5c0e34fdd90c2945084b71a7349a?colored=true

https://testnet.coinprism.info/tx/5ba4529223bd6842b93c0848ee00c23b20dd5c0e34fdd90c2945084b71a7349a

- As a temporary solution, I have created a code that first generates an unsigned transfer for the desired amount, and changes that colored amount to 0 in the marker and manually signs the transaction: https://github.com/LykkeCity/WalletBackEnd/blob/40360720ca1ee68c3e2a3e9490d90307290ad674/LykkeWalletServices/Transactions/TaskHandlers/SrvUncolorTask.cs#L50

**Comment by NicolasDorier** [comment]
I have a simple idea: making it possible for the user of TransactionBuilder to not set a change address.
Your code would looks like:

```
tbuilder
.AddCoins(1000asset)
.Send(myself, 998asset)
.SetChange(myself)
.NoChange(ChangeType.Colored)
```
How is that?

**Comment by bijakatlykkex** [comment]
Thanks. I like the idea, but I am not sure it is general enough to be included in the library or not, seems so in my eyes. 

This is enough for our application, for sure.

Thank you very much for your attention.

**Comment by NicolasDorier** [comment]
Closing, open since last year. Can reopen if you feel working on it.
