### ISSUE TITLE
RPC methods EstimateFee/Async change proposal/discussion

### ISSUE THREAD

**Issue by lontivero** [MetacoSA/NBitcoin#209]
The RPCClient class contains sync and async methods which are very consistent in their signatures, what is valid for most of the methods with the exception of `EstimateFee` and `EstimateFeeAsync` methods because one of them returns a `FeeRate` instance and the other one returns a `Money` instance. _IMO both should retrun a FeeRate instance_. We can see the signatures below:

```c#
public FeeRate EstimateFee(int nblock)
public async Task<Money> EstimateFeeAsync(int nblock)
```

On the other hand, the synchronous version return `new FeeRate(Money.Zero)` when it receives a _-1_ as response. This forces the caller to check the returned value:

```c#
var fee = rpcClient.EstimateFee(6);
if(fee.FeePerK == Money.Zero){
   // do something
}
```

If programmer forget to check the value something wrong could happen. Probably the less dangerous thing could be to broadcast a transaction with no enough fee to be mined. This could, or not, be a problem.

On the other hand, the synchronous version return `Money.Parse(response.Result.ToString())` without validating the _special case -1_ and again this is, IMO, not okay because the **-1 value is an error code** and not a valid value. Again, IMO, this could end in an unexpected behaviour if the programmer doesn't check teh returned value. Think about scenarios like the follow one:

```c#
var fee = await rpcClient.EstimateFeeAsync(6); // returns -1
var valueOut = valueIn - fee; // unexpected behavior that can pass unnoticed for a long time
TxOut.Value = valueOut;
```

There is a reason why .NET developers don't check the returned values and it is because there is an unwritten rule in all methods' contracts: **if they cannot return what they have to, they have to throw an exception**. (bold is just to highligh what i think is important)

IMO this is specialy important when we handle money. 

I didn't send a PR before having a discussion about this and because these are breaking changes. I would like to know your opinion about this.

**Comment by NicolasDorier** [comment]
Good catch on the signature which is obviously wrong, and I agree that both method should behave the same.

I don't agree with throwing an exception though. Not having fee estimation is an expected result, on which the user might decide to try again with a different nblock. Exception handling should not be used for processing this sort of logic.

I think that if it returns -1, then we should returns null.

**Comment by lontivero** [comment]
I don't agree. Not having a fee estimation is an exceptional result, not an expected one. The same could be applied to other exceptional situations like not finding a file. 

In .NET there are very very few methods that return null (i cannot remember anyone in this moment) and that's one of the big differences with java where you can see an `if(returnedValue == null)` a millon times in a method.

**Comment by NicolasDorier** [comment]
having no estimation is actually happening often, I expect code among the lines of:

```
int target = 30;
while(FeeRate rate = rpc.EstimateFee(target) == null)
{
    target--;
}
```
For having good estimation for late blocks, your node must be running for a while.
Also, in NBitcoin, I always adopted the convention of 'if not present, returns null'.

**Comment by NicolasDorier** [comment]
What I propose is to nuke the two EstimateFee method and add a new one TryEstimateFee so it is more obvious it returns null, and I don't break code silently.

**Comment by NicolasDorier** [comment]
bool TryEstimateFee(target, out rate)

**Comment by knocte** [comment]
I like the `TryEstimateFee` approach, this way the developer knows, by convention (because its method starts with `Try`) that the method should not throw any exception, and just return false if it fails.

However, the convention also says that, if there's a method TryFoo(), there should be a Foo() one that, when failing, gives enough context about what failed. And in .NET, the way to pass error codes to the callers is via exceptions.

**Comment by NicolasDorier** [comment]
@knocte but the thing is, it is not an error to not have estimation.

You can try starting your node, the older the target is, the less chance you have to get and estimation.
It is not a bug from Core, and not a bug of the caller.

**Comment by knocte** [comment]
I'm not claiming that not having an estimation is an error or a bug.

I'm claiming that if you call a method called GetFoo() and the Foo cannot be done/retreived by some reason, then GetFoo should signal the reason why it couldn't succeed. And in C# you signal these result/nonValidResult dichotomy via exceptions, not via special magic values (because -1 is not a valid estimation, it's not a value valid in the domain of estimations).

**Comment by knocte** [comment]
You're maybe in your mind mapping exceptions to the concept of non-recoverable errors. It's interesting to note that other languages have this distinction, for example, in Go the unrecoverable ones are called panics (in M#, the language of the Midori project from Microsoft, there was this distinction as well). However, unfortunately in .NET there's no distinction between recoverable errors and not-recoverable errors (e.g. OutOfMemoryException and FileNotFoundException both inherit from Exception base class, but the former is irrecoverable, and the latter is not).

So, agreeing with @lontivero, IMO estimation methods should throw recoverable errors that the caller can intercept to know when an estimation could not happen.

**Comment by NicolasDorier** [comment]
-1 is obviously a bad idea.

@knocte but what if the user wants to try several target until one succeed. This should be very common scenario. If you use exception, then you would start piloting your logic through exception which is a bad thing.

**Comment by lontivero** [comment]
In that case @NicolasDorier he/she should use the TryEstimateFee:

```c#
var attempts = 3;
while(attemps >=0 && !TryEstimateFee(attempts--))
```

**Comment by knocte** [comment]
Exactly.

**Comment by NicolasDorier** [comment]
ok, I will remove the existing methods and create GetEstimatedFee()/TryEstimatedFee(). I hesitate with GetEstimatedFeeOrDefault

**Comment by knocte** [comment]
>  create GetEstimatedFee()/TryEstimatedFee()

EstimateFee()/TryEstimateFee() sounds better to me.

**Comment by knocte** [comment]
(To be consistent with, e.g. Parse()/TryParse() )

**Comment by NicolasDorier** [comment]
My problem is that if I keep EstimateFee I will silently break people who update NBitcoin, and I don't want that.

**Comment by knocte** [comment]
Ah ok, so how about FeeEstimation and TryFeeEstimation, and mark EstimateFee() as Obsolete.

**Comment by NicolasDorier** [comment]
or better TryEstimateFeeRate and EstimateFeeRate. We can remove FeeEstimate. I am more concerned about silently breaking something, than breaking it.

**Comment by knocte** [comment]
Yeah ok. Although I would be more worried about a -1 than a new exception :)

**Comment by NicolasDorier** [comment]
@knocte that's not the point. The point is that current user are checking for -1 in their code. If I change to exception without renaming the method their code will break.

That's why I need to change the name, so at least when they recompile the compiler will tell them something changed instead of crashing at runtime.

**Comment by knocte** [comment]
> That's why I need to change the name, so at least when they recompile the compiler will tell them
> something changed instead of crashing at runtime.

Understood that part, but I was more referring to the devs that are not checking for -1 ;)

**Comment by NicolasDorier** [comment]
@lontivero tl;dr: kind of all agree on TryEstimateFeeRate/EstimateFeeRate and removal of current EstimateFee and EstimateFeeAsync

**Comment by lontivero** [comment]
I agree with that. If you want, I can do it and send the PR for your review probably this week.

**Comment by NicolasDorier** [comment]
cool, yep.

**Comment by sgryphon** [comment]
On the topic of breaking changes to the API, does NBitcoin use "semantic versioning", i.e. is there a guarantee of backwards compatibility for minor versions / break changes on major versions? (i.e. http://semver.org/)

In this case, obsoleting the method is a good idea for a minor version, then remove when you bump major version. 

(Apart from that, yes, the Xxx (throws exception when exceptional) and TryXxx (returns false, with an out param) is a good pattern to follow in .NET.)

**Comment by NicolasDorier** [comment]
@sgryphon I am following semantic versioning loosely. If I break code of a method not used a lot, I don't create a new major. But I agree, for this one it is better to mark as Obsolete.
