### ISSUE TITLE
Operator overloading for Money

### ISSUE THREAD

**Issue by nopara73** [MetacoSA/NBitcoin#215]
I think it would make sense. Any objection?

**Comment by NicolasDorier** [comment]
what do you mean there is already operator overloading

**Comment by nopara73** [comment]
Indeed. My bad.  
I got the false impression by (this line)[https://programmingblockchain.gitbooks.io/programmingblockchain/content/bitcoin_transfer/transaction.html]:  
`spentAmount = (Money)spentCoin.Amount.Add(spentAmount);`
