### ISSUE TITLE
Ebook intro analogy

### ISSUE THREAD

**Issue by xanadont** [MetacoSA/NBitcoin#219]
Is not quite right, at least for a native English speaker anyways.

> The Blockchain is to gold what Bitcoin is to jewelry.

Native English speakers would most likely phrase this as

> The Blockchain is to Bitcoin as gold is to jewelry.

BTW, NBitcoin is absolutely amazing. Thank you so much for doing this great work!

**Comment by NicolasDorier** [comment]
Thanks a lot, the book has its own repo on https://github.com/ProgrammingBlockchain/ProgrammingBlockchain .
I will fix it.
