### ISSUE TITLE
Try to get testnet bit coin

### ISSUE THREAD

**Issue by VenkateshSrini** [MetacoSA/NBitcoin#222]
Hi,
I'm new to bit coin. When I try to get the bitcon for test net it is asking for TestNet address. What should I provide there? what  ever I Provide in https://tpfaucet.appspot.com/. I get 500 Error. Please help

**Comment by NicolasDorier** [comment]
try to use another faucet

**Comment by VenkateshSrini** [comment]
which faucet

**Comment by NicolasDorier** [comment]
I do not know, search google there should have others

**Comment by amjadDev** [comment]
@VenkateshSrini  seems you are using mainnet address for testnet  .
use this code to receive your testnet address if you are using this library
BitcoinPubKeyAddress bitcoinPubicKey = publicKey.GetAddress(Network.TestNet);

to check your testnet address ledger use this link
https://www.blocktrail.com/tBTC
