### ISSUE TITLE
Serializing BitcoinAddress throws StackOverflowException

### ISSUE THREAD

**Issue by bokobza** [MetacoSA/NBitcoin#226]
The following throws an exception:
``` csharp
string ser = JsonConvert.SerializeObject(bitcoinAddress, Newtonsoft.Json.Formatting.Indented);
```
with `bitcoinAddress `being of type `NBitcoin.BitcoinAddress`.
I think the reason for that is because there is a little redundancy between ScriptPubKey and Hash where the following is a valid statement:
`bitcoinAddress.ScriptPubKey.Hash.ScriptPubKey.Hash.ScriptPubKey.Hash.ScriptPubKey...`

Is that expected?

**Comment by NicolasDorier** [comment]
You need to tell about the serializer of NBitcoin types to JsonNet, here is how to do:

```
var settings = new Newtonsoft.Json.JsonSerializerSettings();
JsonConverters.Serializer.RegisterFrontConverters(settings);
var str = Newtonsoft.Json.JsonConvert.SerializeObject(bitcoinAddress, settings);
```

**Comment by bokobza** [comment]
Great, tat works, thank you.
What about this: `bitcoinAddress.ScriptPubKey.Hash.ScriptPubKey.Hash.ScriptPubKey.Hash.ScriptPubKey...`
is that intended?

**Comment by NicolasDorier** [comment]
yes. `bitcoinAddress.ScriptPubKey.Hash` gives you a p2sh hash of your p2pkh.
`bitcoinAddress.ScriptPubKey.Hash.ScriptPubKey` give you the Script of this p2sh hash.
`bitcoinAddress.ScriptPubKey.Hash.ScriptPubKey.Hash.ScriptPubKey` give you the p2sh hash of the script of the p2sh hash of your p2pkh. 

This last one is not useful, but I can't prevent to do that with POO.
