### ISSUE TITLE
Getting the balance associated with a private key ?

### ISSUE THREAD

**Issue by appsolutegeek** [MetacoSA/NBitcoin#232]
Hi,

Does anyone know how to get the balance associated with a private key.

For example, I have a private key, and I know it has transaction i.e. money stored and associated with the private key but how do I obtain this ?

I checked the ebook but couldn't find the info ?

Any ideas or pointers ?

Thanks

**Comment by NicolasDorier** [comment]
hey, with QBitNinja you can do that.
Take a look at https://programmingblockchain.gitbooks.io

**Comment by HellsChicken** [comment]
I'm looking for this as well, and don't really see it in the ebook.  I see the part at the top of the "Transaction" chapter which shows using QBitNinja to get the results of a transaction given the transaction ID.  I also see the part under "Spend your coin" that uses a transaction ID from a previous receive transaction, and finds the correct outpoint.

My question though I think is similar to appsolutegeek's which is, given a private key, is there a quick way to find all money associated with it and any derived child addresses?  I followed your example under the BIP-32 section to use a master key to create multiple child keys with their own addresses.  Is there any way to use that master key to check the balance at - and easily spend - any/all coin received at all those addresses?

Or would we have to do something like sweep through all of our addresses to find transactions and outpoints?  My ultimate goal is to create a new child address to give to everyone who is going to send me some bitcoin, but then when I want to check my balance or spend, it would be great if there was an easy way to do it just using the private key.  Not sure if this is possible or not, though :)

**Comment by NicolasDorier** [comment]
Ah got it you want balance from a HD PubKey.
Actually yes you can, did not documented it because I have not tested it myself enough.

Check out my test: https://github.com/MetacoSA/QBitNinja/blob/master/QBitNinja.Tests/CanDo.cs#L1741

You can use QBitNinjaClient to do approximately the same requests:

You create a wallet, then you create a KeySet  in the wallet with the extpubkey and derivation of your choice.
Then you can use `qbit.GetBalance(...)` with the wallet name to query it.

**Comment by masiur3** [comment]
can u need balance these privet key,
contact me,
vabi.cm88@gmail.com

**Comment by nhutcmos** [comment]
I have the same issue. I tried your test but I can not get balance from ExtPubKey
Do you have any update on this issue?

**Comment by kirubadev** [comment]
Regarding Private key balance issues please contact me at 
dkiruba1979@gmail.com

I can get you the balance associated with it

**Comment by NicolasDorier** [comment]
@nhutcmos takes a look at https://programmingblockchain.gitbooks.io/programmingblockchain/content/wallet/web-api.html and the nbxplorer project.

**Comment by kirubadev** [comment]
Regarding Private key balance issues please contact me at
dkiruba1979@gmail.com
I can get you the balance associated with it

**Comment by masiur3** [comment]
I made it!
