### ISSUE TITLE
Refactor list for major, breaking version update

### ISSUE THREAD

**Issue by NicolasDorier** [MetacoSA/NBitcoin#233]
[] Removing the Base58Data class
[] Obsolete calls to methods using Base58Data (change types to `object`)
[] Implement `SegwitAddress` class which derive from `BitcoinAddress`.
[] Updating to latest Visual Studio 2017 tooling. (removing separate project.json)

@lontivero anything else on the wishlist ?

**Comment by lontivero** [comment]
I think that's all, also remember to remove the `Base58DataJsonConverter` from the `Serializer` class?

**Comment by knocte** [comment]
Is the update to VS2017 going to break users of VS2015?

**Comment by NicolasDorier** [comment]
@knocte I think so. Microsoft broke the tooling for .NET Core. I would like one unified project for all.
I can postbone later maybe.

**Comment by dangershony** [comment]
Will this break any existing functionality?

**Comment by lontivero** [comment]
@dangershony no, that's not the idea. It is important to respect the current contracts as much as posible (interfaces, abstract classes and methods' signature).

Something i thing worth to clarify is that `Base58Data` class will not be removed, we simply want to break the hierarchical relationship between `Base58Data` and `BitcoinAddress` classes. Sure, that is a breaking change anyway and that means that, in some cases, developers could have to make little changes in their code. Anyway, as i said in the first paragraph, the idea is this change has to be as transparent as possible.

**Comment by dangershony** [comment]
I am all for separation of logic.
Is this for the introduction of Scrypt in the header hash?

**Comment by lontivero** [comment]
No, this is because the is a new encoding (bech32) format for segwit addesseses.

**Comment by NicolasDorier** [comment]
@dangershony I think supporting Litecoin or other PoW does not require breaking changes.
The issue is the bech32 format as @lontivero point out.

**Comment by dangershony** [comment]
Ok thanks I will check out betch32 better in that case

**Comment by NicolasDorier** [comment]
Done
