### ISSUE TITLE
Default MerkleBlock FromBytes bug

### ISSUE THREAD

**Issue by nopara73** [MetacoSA/NBitcoin#238]
Expected behaviour:  `merkleBlock.FromBytes(merkleBlockBytes);` works properly even if the `merkleBlock` is default.  
  
Currently I have to do this in order to get the original merkle block if that's default:  
  
```
// Bypass NBitcoin bug
var merkleBlock = new MerkleBlock();
if(!merkleBlock.ToBytes().SequenceEqual(merkleBlockBytes)) // if not default MerkleBlock
{
	merkleBlock.FromBytes(merkleBlockBytes);
}

return new SmartMerkleBlock(height, merkleBlock);
```  
I'm not sure what's the right way to fix this in NBitcoin.

**Comment by NicolasDorier** [comment]
I can't reproduce:

```
var b1 = new MerkleBlock();
var b2 = new MerkleBlock();
b2.ReadWrite(b1.ToBytes());
b2.ReadWrite(b2.ToBytes());
```

**Comment by nopara73** [comment]
Cannot reproduce it anymore. Sorry about it, it's old code (you know going through todo comments once a year).
