### ISSUE TITLE
Share Visual Studio Settings

### ISSUE THREAD

**Issue by ArturKarbone** [MetacoSA/NBitcoin#246]
Hi Team as a newcomer I just faced issues formatting my code in VS and creating a pull request.

To be more specific I messed with tabs/spaces, spaces after if()/for() issue in this pull request https://github.com/MetacoSA/NBitcoin/pull/244

My suggestion is that someone of core contributors can to share their Visual Studio settings for the project ( with a link/short description somewhere in Read.ME), to avoid such situations for newcomers.

What do You think?
Thanks

**Comment by knocte** [comment]
I think this has already addressed in #245

**Comment by ArturKarbone** [comment]
Bummer :)

Let's close it then
