### ISSUE TITLE
Adding some parameters to the consensus class

### ISSUE THREAD

**Issue by dangershony** [MetacoSA/NBitcoin#247]
I would like to add  this parameters to the consensus class.
https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/Stratis.Bitcoin/Consensus/ConsensusOptions.cs#L64
Or consider a way to make consensus more flexible.

Any ideas?

**Comment by NicolasDorier** [comment]
I think a better solution is just to make Consensus.Clone virtual so that you can implement your own.

**Comment by dangershony** [comment]
Yeah this is probably the simplest way, forget a Dictionary.
Then I could also make an extension method ```Of<T>() where T: Consensus``` to make it easy to extend
I will submit a PR
