### ISSUE TITLE
Node.GetMempoolTransactions(...) returns only 500 transactions, even if requested > 500

### ISSUE THREAD

**Issue by vonzepp** [MetacoSA/NBitcoin#250]
Bug is located at this line:
https://github.com/MetacoSA/NBitcoin/blob/master/NBitcoin/Protocol/Node.cs#L1393
**result.Count** is 500 after processing of the first batch, so
```
result.Count < batch.Count
```
is always false for all other batches.

**Comment by NicolasDorier** [comment]
fixed on https://github.com/MetacoSA/NBitcoin/commit/db36ad22707b5e88f80e489b87df040e05b779c0 version pushed

**Comment by NicolasDorier** [comment]
Please can you try again with last verison and close the issue if it is indeed solved ?

**Comment by vonzepp** [comment]
Yes, it's fixed in 3.0.2.21.
I used 3.0.2.18 before.
