### ISSUE TITLE
P2SH-P2WPKH output spending transaction

### ISSUE THREAD

**Issue by bijakatlykkex** [MetacoSA/NBitcoin#262]
Hello,

Thank you for adding segwit support to NBitcoin, and doing this early.

By the following code, I am trying to spend an output from a P2SH-P2WPKH address, and I except the transaction id of the unsigned version (hash01_) should be the same as the signed version (hash02_) but I get different hash, and the hash02_ for the signed version is correct one and the transaction is broadcast able. I would appreciate to know what I am missing, if I am doing so.

Thank you

The code (I expect hash01_ and hash02_ be the same, which are not):

          string[] reservedPrivateKey = new string[] {
            "cQMqC1Vqyi6o62wE1Z1ZeWDbMCkRDZW5dMPJz8QT9uMKQaMZa8JY",
            "cQyt2zxAS2uV7HJWR9hf16pFDTye8YsGL6hzd9pQzMoo9m24RGoV",
           };

            var txToSpend = "02000000010ef3cb888f62bc6bdb67e3fb2662272d26fb441f4e9697f67d4b5ec453967325000000004847304402203838a0e4332502746b92410aab25638c801c284d138ea592da90f992d4e6e52002201fb48873abba22f564c8d14e04e3a568ac693772c7d6714a2be0f827c7c0630f01feffffff0228021024010000001976a914d12c5949bef2a5569c87b6a86012a1c28477005388ac00e1f5050000000017a9140e5dc4e4220eb9faab37514f176e46456230d3d68703000000";
            uint txOutputNumber = 1;

            BitcoinSecret destinationSecret = new BitcoinSecret(reservedPrivateKey[1], Network.TestNet);
            var destAddr = destinationSecret.PubKey.GetSegwitAddress(Network.TestNet);

            BitcoinSecret secret = new BitcoinSecret(reservedPrivateKey[0], Network.TestNet);
            var segwitScriptPubKey = secret.PubKey.GetSegwitAddress(Network.TestNet).ScriptPubKey;

            var p2shSegwitTemplate = new PayToScriptHashTemplate();
            var p2shSegwitScript = p2shSegwitTemplate.GenerateScriptPubKey(segwitScriptPubKey);
            var p2shSegwitAddr = p2shSegwitScript.GetDestinationAddress(Network.TestNet);
            var coinToSpend = new ScriptCoin(new Coin(new Transaction(txToSpend), txOutputNumber), segwitScriptPubKey);

            TransactionBuilder builder = new TransactionBuilder();
            var tx = builder.AddCoins(coinToSpend).Send(destAddr, new Money(90000000)).SendFees(new Money(100000)).SetChange(p2shSegwitAddr).BuildTransaction(true);
            var hash01 = tx.GetWitHash();
            var hash01_ = tx.GetHash();

            tx = builder.AddKeys(secret).BuildTransaction(true);
            var hash02 = tx.GetWitHash();
            var hash02_ = tx.GetHash();

            var verify = builder.Verify(tx);
`

**Comment by NicolasDorier** [comment]
In case of P2SH-P2WPKH then your `ScriptCoin` redeem script should be the P2WPKH program.

So basically:
```
var coinToSpend = new ScriptCoin(new Coin(new Transaction(txToSpend), txOutputNumber), destinationSecret.PubKey.WitHash.ScriptPubKey);
```
It is probably the same that you already have.

hash01_ abd hash02_ can't be the same, since it is P2SH, the P2SH redeem script is inserted into your signed transaction's scriptSig which change the hash.

Plain P2WPKH would indeed not change the hash.

**Comment by bijakatlykkex** [comment]
Thanks for the explanation.

I managed to get the same txId by adding the line `tx01.Inputs[0].ScriptSig = new Script(Op.GetPushOp(segwitScriptPubKey.ToBytes()));` before getting hashes.

Actually our use case is building and exchanging commitments over a yet unsigned channel setup transaction like what described in lightning protocol, so we need to have a finalized txId before signing the transaction.

I started with a simpler scenario of getting hash for an unsigned P2SH-P2WPKH spending instead of probably more complex P2SH-P2WSH (Multisig).  Also as described in https://bitcoincore.org/en/segwit_wallet_dev/ it seems there is no standard address format for native P2WPKH and P2WSH yet, which I can use and wallets understand.

Thank you for the help

**Comment by NicolasDorier** [comment]
Why using P2SH segwit and not plain segwit?

**Comment by NicolasDorier** [comment]
> it seems there is no standard address format for native P2WPKH and P2WSH yet, which I can use and wallets understand

Yes, NBitcoin support Bech32 address format through `BitcoinAddress.Create` though. But it is indeed not widly supported at the moment.

**Comment by NicolasDorier** [comment]
P2SH-P2WSH is not more complex than P2SH-P2PKH. In the script coin, instead of giving the `WitHash.ScriptPubKey`, you just have to give the multi sig script.

All the rest is the same code.

**Comment by NicolasDorier** [comment]
From NBitcoin point of view, `ScriptCoin` is smart enough, from its `ScriptPubKey`, to understand if the RedeemScript is P2SH, P2SH-P2WSH or simple P2WSH.

**Comment by bijakatlykkex** [comment]
Thanks. Now using NBitcoin I was able to create a P2SH-P2WSH spending transaction, with the same txId for both signed and unsigned version.
