### ISSUE TITLE
Feature request: UAHF support

### ISSUE THREAD

**Issue by aleksey-baryshnikov** [MetacoSA/NBitcoin#264]
Hello, 

Your project is really awesome ! It makes bitcoin and litecoin related projects much simpler.

Due to forthcoming uahf it would be great to add some changes to prevent double spending and add replay protection. 

Please have a look at https://github.com/Bitcoin-UAHF/spec/blob/master/uahf-technical-spec.md
Especially REQ-6-2 

Thanks in advance

**Comment by knocte** [comment]
Typo: I think you meant MAHF, not UAHF.

**Comment by NicolasDorier** [comment]
Double spending has to be prevented by the forking chain, this is not a concern for NBitcoin.

If you are talking about using the new SIGHASH of Bitcoin Cash, I will make an alternate branch with only a change to sign with this SIGHASH. It will not be merged to main branch though.

**Comment by NicolasDorier** [comment]
Created a branch for signing with Bitcoin Cash on https://github.com/MetacoSA/NBitcoin/tree/BCCtemp I will not integrate on main branch though as Bitcoin Cash change might conflict later with Bitcoin.

**Comment by aleksey-baryshnikov** [comment]
Thank you
