### ISSUE TITLE
Build bitcoin cash transaction

### ISSUE THREAD

**Issue by aleksey-baryshnikov** [MetacoSA/NBitcoin#270]
Hi and thanks again for your great project!

I am trying to build bitcoin cash (bcc / bch) transaction.

I cloned BCCTemp branch and use TransactionBuilder.BuildTransaction(true, SigHash.ForkId) to build and sign transaction.

But when I try to broadcast this transaction I receive 16: mandatory-script-verify-flag-failed (Signature hash type missing or not understood). Code:-26 

You can broadcast bitcoin cash transaction using http://blockdozer.com/insight/tx/send

An example of tx hex I receive with transaction builder and which I am trying to broadcast is given below

010000000223c5b5b8ea31f5548d23e8fd1f63fc9a127b31f8fc67b2f46a5c889b5ed32882040000006a47304402200381bcdb29fbf75ab5f6b8362ed51a9c4910fcd5c310a640b1b3ee9f638ef4b802204428f70c00395d630a8bd888bf4613c81857f6fd29aa87ac7a90d4d5e97328e540210204dd499f6e9c15ff62be099aae1af1940ed8b0fa1f1094b5d378df145193875bffffffff23c5b5b8ea31f5548d23e8fd1f63fc9a127b31f8fc67b2f46a5c889b5ed32882030000006a47304402200b60735ed49cef9cd01adf775e101f228f36ef7938989593c0bc03e63d55978702204337bde8fbf00120a563407fc8ea93287e522c8473b6d02da28dcef15f82f0354021029dbce5469e4be680e575919a4e6ee18a0baa74d7cb4c9619859108945673e4cfffffffff02f0921100000000001976a91402faa8bfdff9e5583605c42c7569779a53f1c63e88ac785f0c00000000001976a914a57da413e709105b0e128b0912d8c29a6104833e88ac00000000

Do I need to use some different method or param value ? 
What can be the problem ?

Thanks for your help in advance

**Comment by NicolasDorier** [comment]
you need to sig with SigHash.ForkId | SigHash.All

**Comment by aleksey-baryshnikov** [comment]
Thanks mate, it did the trick

**Comment by pozdnyakovasp** [comment]
Hello.

I can't submit signed BCash transaction to network.
I created address: 
 ```
address: bchtest:pql8vc6kldxfkhwna7kw0knrq5ze8jkz0s0u52dh7w
privKey: cPZq9ktoDqowL7fa6rbiog8UDPja8MCsAdofT5t7QGGsr7jj8dqH

```

Have one Unspent transaction ->
```
        txId: "e44619b84ca03e28e2b4bee8eb895e9d41d4522737ef18755a586b05fd686f5f",
        amount: 0.22996573,
        vout: 0,
```

In code create TransactionBilder
```
var builder = Network.CreateTransactionBuilder();
// in
var scriptPubKey = Network.CreateBitcoinSecret(addressKey).PubKey.WitHash.ScriptPubKey
var key = Key.Parse(secret.ToWif());
var coin = new Coin(txInHash, (uint)vout, amount, scriptPubKey.Hash.ScriptPubKey).ToScriptCoin(scriptPubKey);
builder.AddKeys(key);
builder.AddCoins(coin);

// out
 var amount = Money.FromUnit(0.2299, MoneyUnit.BTC);
 builder.Send(BitcoinAddress.Create(outAddress, Network), amount);

// fee
builder.SendFees(Money.FromUnit(sendFee, MoneyUnit.BTC));

var signedTransaction = builder.BuildTransaction(true);

await RpcClient.SendRawTransactionAsync(signedTransaction); 

```
builder.Verify - return true

I get  "TX decode failed"

But i can use this code for LTC, BTC.  
What could be the problem?
