### ISSUE TITLE
Altcoin support

### ISSUE THREAD

**Issue by utarn** [MetacoSA/NBitcoin#271]
I'm trying to generate HD wallet for an altcoin. Could it be done in this library?
I found altcoin version mapping from https://github.com/libbitcoin/libbitcoin/wiki/Altcoin-Version-Mappings

or maybe I can just change some parameter in the source to do this.

Regards,
Utharn

**Comment by NicolasDorier** [comment]
Yes, take a look at how I support Litecoin https://github.com/MetacoSA/NBitcoin.Litecoin

**Comment by utarn** [comment]
I'm trying to port to Digibyte. Could you please guide me for Litecoin where you could obtain lot of information out there.  Actually, my first step is trying to generate HD wallet.

**Comment by NicolasDorier** [comment]
NBitcoin is only a framework there is a SPVWallet class, but it has not been tested a lot you can try to use it.

Please read all of that to get more info on how to use NBitcoin for HD wallets:

https://github.com/ProgrammingBlockchain/ProgrammingBlockchain/
https://github.com/NicolasDorier/NBitcoin.SPVSample
https://github.com/MetacoSA/NBitcoin.Litecoin

There is no step by step way of doing it though, you need to learn how to do it.

**Comment by utarn** [comment]
Thank a lots.

**Comment by michael-kokorin** [comment]
@NicolasDorier when I use LiteCoin in the following code

`NBitcoin.LiteCoin.Networks.Register();
            NodeSettings nodeSettings = NodeSettings.FromArguments(args, "lite-coin", NBitcoin.LiteCoin.Networks.Testnet);
            var node = new FullNodeBuilder()
                .UseNodeSettings(nodeSettings)
                .UseConsensus()
                .UseBlockStore()
                .UseMempool()
                .AddMining()
                .UseWallet()
                .AddRPC()
                .Build();

            node.Run();`

I receive null reference exception in BlockStoreLoop class on line 120.

`public async Task InitializeAsync()
        {
            this.logger.LogTrace("()");

            if (this.storeSettings.ReIndex)
                throw new NotImplementedException();

            this.StoreTip = this.Chain.GetBlock(this.BlockRepository.BlockHash);

            if (this.StoreTip == null)
            {
                var blockStoreResetList = new List<uint256>();
120:                Block resetBlock = await this.BlockRepository.GetAsync(this.BlockRepository.BlockHash);
                uint256 resetBlockHash = resetBlock.GetHash();`

Here resetBlock is null.
What's wrong in my code?

**Comment by NicolasDorier** [comment]
The code below is from stratis full node. You should open an issue [there](https://github.com/stratisproject/StratisBitcoinFullNode/). From what you sent me, the code seems correct.

Please link the issue there to this issue, the underlying problem might still come from NBitcoin.

**Comment by NicolasDorier** [comment]
Ah an open a new issue on NBitcoin, this is a different issue.

**Comment by Mike-EEE** [comment]
Woohoo!  Thank you for making this, and this project.  I am currently investigating this space, and am looking to make something like [CryptoKitties](https://www.cryptokitties.co/), but through [Coinbase's ecommerce solution](https://commerce.coinbase.com) instead.  This supports BTC, ETH, BCH, and LTC.  Your altcoin solution here seems to address 3 out of 4 of these, which puts me in the right direction.

Some questions here:

1. Are there plans to support ETH?  Any recommendations here if not?
1. CryptoKitties uses ETH exclusively and its asset tracking is done through ETH's blockchain, obviously.  If I am supporting multiple blockchains as above, what is the recommended way of tracking assets?  Does each blockchain have its own tracking?  Or do I use one as the official source?  If I use one then it would seem I am promoting one over the other which is something I would like to avoid if possible.

Any thoughts around this would be greatly appreciated.  Thank you in advance. 👍
