### ISSUE TITLE
Money type operator div overloading

### ISSUE THREAD

**Issue by maddin123** [MetacoSA/NBitcoin#272]
Hi,

when using:

var bobInput = Money.Coins(1.1M);
            var aliceInput = Money.Coins(0.275M);
            var spend = (bobInput + aliceInput) / 2;

"spend" is falsely calculated due to false boxing/type conversions.

The Money class needs:

		public static Money operator / (Money left, Money right)
		{
			if (left == null)
				throw new ArgumentNullException("left");
			if (right == null)
				throw new ArgumentNullException("right");
			return new Money(checked(left._Satoshis / right._Satoshis));
		}

Regards
martin

**Comment by NicolasDorier** [comment]
Thanks a lot. For this report, will fix it.

**Comment by NicolasDorier** [comment]
Mh dividing money by money makes no semantic sense though... I see the problem, and if you use `Money spend` instead of `var spend`, you don't have issue. But yes, this is tricky and should be fixed.

**Comment by NicolasDorier** [comment]
fixed by https://github.com/MetacoSA/NBitcoin/commit/79d83ff112d2f08db25aa7cb35b5c123f17d5f13 thanks a lot, version 4.0.0.18 pushed
