### ISSUE TITLE
How to run a BCC full node?

### ISSUE THREAD

**Issue by yushizhao** [MetacoSA/NBitcoin#273]
I want to build a BCC full node. Is there any guide or wiki?

**Comment by knocte** [comment]
What does this have to do with NBitcoin?

**Comment by yushizhao** [comment]
@knocte Well, there is a branch called BCCTemp which is listed on https://www.bitcoincash.org/developers.

**Comment by NicolasDorier** [comment]
NBitcoin is a library, the BCCTemp branch is for signing in C# a valid BCC transaction, this is not for users, it is for developers.
