### ISSUE TITLE
Underlying API, Blockr.IO, has been out of sync for more than a month

### ISSUE THREAD

**Issue by PeterParker1234** [MetacoSA/NBitcoin#275]
All my blockchain transactions are failing. I previously ran an older version of NBitcoin, but now am running the latest version. Still failing.

I am running Fiddler and have identified that the underlying API used by NBitcoin is btc.blockr.io.

Blockr.IO has not updated their node in more than 1 month. Thus all new transactions or queries on tx's older than this period are failing.

This renders NBitcoin as not working. What I don't understand is that there have been many updates to NBitcoin in the last month. 

Is NBitcoin looking at changing API's to a different provider? How are new updates being developed when the underlying API is not working?

https://twitter.com/lopp/status/896219990696878082

**Comment by NicolasDorier** [comment]
You can use `QBitNinja.Client`.  See https://programmingblockchain.gitbooks.io/programmingblockchain/

**Comment by NicolasDorier** [comment]
NBitcoin never really use blockr.io. There is a class for using it, but most never touched it.

**Comment by NicolasDorier** [comment]
You can use the `QBitNinjaTransactionRepository` in place of the blockr.io. stuff.

**Comment by NicolasDorier** [comment]
Closing, Blockr.io does not exist anymore, and support has been removed from NBitcoin.
