### ISSUE TITLE
How to get a Asset Quantity List from Open Asset Protocol?

### ISSUE THREAD

**Issue by VuongVu** [MetacoSA/NBitcoin#276]
I have a problem with Open Asset Protocol. How can I decode a OAP like that "4f4101000180c2d72f00" to get Asset Quantity List "80c2d72f"? Please give me a solution?

**Comment by NicolasDorier** [comment]
```
var marker = ColorMarker.TryParse(new Script("OP_RETURN 4f4101000180c2d72f00"));
```

**Comment by VuongVu** [comment]
Thank you very much!
