### ISSUE TITLE
Detecting deposits

### ISSUE THREAD

**Issue by lugrugzo** [MetacoSA/NBitcoin#277]
Hello

I want to detect new deposits using SPV Wallet. I want to **aware** of received transactions and want to store them(tx, address, amount...) in a database. Is it possible with NBitcoin?

Thanks

**Comment by lugrugzo** [comment]
Since you didn't reply, I guess it's not possible using SPV, so I will download the whole blockchain and will use `blocknotify`.

**Comment by lontivero** [comment]
It is possible using SPV. In fact, that's the main idea behind SPV client. Your SPV client, after handshaking with peer nodes, sends them a message letting them known that it is not interested in every transaction but in the ones of its own. So, peer nodes only relay those transactions in which the client is interested.

In other words: your spv client only receives those deposits that are important to you. NBitcoin provides a spv client implementation that you can use. Take a look at the SPV folder and read the bip37

**Comment by NicolasDorier** [comment]
@lugrugzo I was in holiday.
I indeed do not advise you to use the SPV wallet.
If it is on the table, use blocknotify and txnotify.

Another way is to directly listen a trusted node and parse/notify yourself. You can see an example here:

https://github.com/dgarage/NBXplorer/blob/master/NBXplorer/ExplorerBehavior.cs
