### ISSUE TITLE
mandatory-script-verify-flag-failed (Operation not valid with the current stack size) after broadcast transaction.

### ISSUE THREAD

**Issue by VuongVu** [MetacoSA/NBitcoin#280]
I have a problem with broadcast my transaction. This error: "mandatory-script-verify-flag-failed (Operation not valid with the current stack size)".  My code follows https://programmingblockchain.gitbooks.io/programmingblockchain/content/other_types_of_asset/transfer_an_asset.html.
This is my dummy data: 
```
AssetId assetId = new AssetId(BitcoinAddress.Create("muTacWdEpBQZA3X7DWMTYjJEGboELoyPPC")).GetWif(network);

Coin coin = new Coin(
    fromTxHash: new uint256("3c00cb76dd442d7a8202e6a05bd0dfed45f34cd58afcfec83a5f754e442da79a"),
    fromOutputIndex: 0,
    amount: Money.Satoshis(2730),
    scriptPubKey: new Script(Encoders.Hex.DecodeData("76a9140ea3d783da828f2015add0cfffbf39345b40325488ac"))
);

ColoredCoin coloredCoin = coin.ToColoredCoin(assetId, 100000000);

Coin forFees = new Coin(
    fromTxHash: new uint256("2cc2e1086bee333d935c9c6d188ced632861339b60874722399a41a759029016"),
    fromOutputIndex: 0,
    amount: Money.Satoshis(27500000),
    scriptPubKey: new Script(Encoders.Hex.DecodeData(76a9143a596b8073bf0e40ec1273e4d4b4e6df1e84907388ac))
);

BitcoinAddress book = BitcoinAddress.Create("mvgFVde726uBNA7Y2ebCBZ6xkoqyPaf3xD");
BitcoinSecret sendSecret = new BitcoinSecret("cNr9THruPa5SVHt9BmVdKzguKTXDUtH3tKBrJTbZmgTgHgfWQ1iv");
BitcoinPubKeyAddress sendAddress = sendSecret.GetAddress();

TransactionBuilder builder = new TransactionBuilder();
Transaction tx = builder
    .AddKeys(sendSecret)
    .AddCoins(coloredCoin, forFees)
    .SendAsset(book, new AssetMoney(assetId, data.quantity))
    .SetChange(sendAddress)
    .SendFees(Money.Coins(0.0001m))
    .BuildTransaction(true);

BroadcastResponse broadcastResponse = 
    new QBitNinjaClient(network).Broadcast(tx).Result;
```

Please give me a solution for this. Thank you.

**Comment by NicolasDorier** [comment]
your forFee is using the wrong scriptPubKey.

The address of your `forFee` is `mkqUcBj9FhPWKtUJ5GLEMxGAC9mH9muUQi`, while you try to sign with `mgrN2ftggVKj2QYPEHq2bLDaMcuHJWoHZq` private key.

You can see it by yourself by printing `tx` on the console, the input scriptSig is empty.

**Comment by VuongVu** [comment]
@NicolasDorier  with my scriptPubKey, i get it from vout after decoderawtransaction of address  `mgrN2ftggVKj2QYPEHq2bLDaMcuHJWoHZq ` : 
`{
  "value": 0.275,
  "n": 0,
  "scriptPubKey": {
    "asm":
      "OP_DUP OP_HASH160 3a596b8073bf0e40ec1273e4d4b4e6df1e849073 OP_EQUALVERIFY OP_CHECKSIG",
    "hex": "76a9143a596b8073bf0e40ec1273e4d4b4e6df1e84907388ac",
    "reqSigs": 1,
    "type": "pubkeyhash",
    "addresses": ["mkqUcBj9FhPWKtUJ5GLEMxGAC9mH9muUQi"]
  }
}`

Is it wrong to get from this? Sorry if I misunderstood you.

**Comment by NicolasDorier** [comment]
You are spending 2 outputs. One of which is using the private key of mgrN2ftggVKj2QYPEHq2bLDaMcuHJWoHZq  and is correctly signed.

The other output (2cc2e1086bee333d935c9c6d188ced632861339b60874722399a41a759029016) is using another private key, and you are setting the wrong scriptPubKey. (check with a block explorer)

**Comment by VuongVu** [comment]
Thank a lot. This is a mistake of me.
