### ISSUE TITLE
Sign SegWit Transaction

### ISSUE THREAD

**Issue by sipsorcery** [MetacoSA/NBitcoin#281]
I'm trying to get a grip on segwit transactions using NBitcoin and am struggling with the signing mechanisms.

I am using the example from https://github.com/bitcoin/bips/blob/master/bip-0143.mediawiki#Native_P2WPKH as the starting point and am trying to get from the unsigned transaction to the signed one using NBitcoin. 

My signing attempt is below. So far I haven't been able to get the correct witness data to generate. Is there a flag I am missing on the Coin object or transaction?

```csharp
HexEncoder hex = new HexEncoder();

Key txInKey0 = new Key(hex.DecodeData("bbc27228ddcb9209d7fd6f36b02f7dfa6252af40bb2f1cbc7a557da8027ff866"));
Key txInKey1 = new Key(hex.DecodeData("619c335025c7f4012e556c2a58b2506e30b8511b53ade95ea316fd8c3286feb9"));

var p2wpkhTx = Transaction.Parse("0100000002fff7f7881a8099afa6940d42d1e7f6362bec38171ea3edf433541db4e4ad969f0000000000eeffffffef51e1b804cc89d182d279655c3aa89e815b1b309fe287d9b2b55d57b90ec68a0100000000ffffffff02202cb206000000001976a9148280b37df378db99f66f85c95a783a76ac7a6d5988ac9093510d000000001976a9143bde42dbee7e4dbe6a21b2d50ce2f0167faa815988ac11000000");

var txIn0 = p2wpkhTx.Inputs.First();
txIn0.ScriptSig = new Script("2103c9f4836b9a4f77fc0d81f7bcb01b7f1b35916864b9476c241ce9fc198bd25432ac");
var coin0 = new Coin(p2wpkhTx, 0);
coin0.Amount = Money.Parse("6.25");

var txIn1 = p2wpkhTx.Inputs.Last();
//txIn1.ScriptSig = new Script("00141d0f172a0ecb48aee1be1f2687d2963ae33f71a1");
txIn1.WitScript = new Script("00141d0f172a0ecb48aee1be1f2687d2963ae33f71a1");
var coin1 = new Coin(p2wpkhTx, 1);
coin1.Amount = Money.Parse("6");

p2wpkhTx.Sign(new Key[] { txInKey0, txInKey1 }, new ICoin[] { coin0, coin1 });

Console.WriteLine(p2wpkhTx.ToHex());
Console.WriteLine(p2wpkhTx.ToString(RawFormat.BlockExplorer));

string correctSignedTx = "01000000000102fff7f7881a8099afa6940d42d1e7f6362bec38171ea3edf433541db4e4ad969f00000000494830450221008b9d1dc26ba6a9cb62127b02742fa9d754cd3bebf337f7a55d114c8e5cdd30be022040529b194ba3f9281a99f2b1c0a19c0489bc22ede944ccf4ecbab4cc618ef3ed01eeffffffef51e1b804cc89d182d279655c3aa89e815b1b309fe287d9b2b55d57b90ec68a0100000000ffffffff02202cb206000000001976a9148280b37df378db99f66f85c95a783a76ac7a6d5988ac9093510d000000001976a9143bde42dbee7e4dbe6a21b2d50ce2f0167faa815988ac000247304402203609e17b84f6a7d30c80bfa610b5b4542f32a8a0d5447a12fb1366d7f01cc44a0220573a954c4518331561406f90300e8f3358f51928d43c212a8caed02de67eebee0121025476c2e83188368da1ff3e292e7acafcdb3566bb0ad253f62fc70f07aeee635711000000";

Console.WriteLine($"P2WPKH correct serialisation ? {p2wpkhTx.ToHex() == correctSignedTx}."          
```

**Comment by knocte** [comment]
I think that when you're using the Coin approach way of signing, you don't need to set ScriptSig like you do here:
```
txIn0.ScriptSig = new Script("...")
txIn1.WitScript = new Script("...");
```
See https://bitcoin.stackexchange.com/questions/59231/how-to-sign-a-segwit-transaction-via-nbitcoin

Also you should make sure to use latest version of NBitcoin, as a recent change has been introduced (https://github.com/MetacoSA/NBitcoin/commit/56bfd1cbca535424b160d8a40688a79de4800630) so that you don't need to call ToScriptCoin() method.

**Comment by knocte** [comment]
@NicolasDorier can we mark the ScriptSig setter method as deprecated or something?

**Comment by sipsorcery** [comment]
The example I'm working is P2WPKH so I shouldn't need to use ScriptCoin's should I?

I found Script.SignatureHash which seems to be what I need but I haven't managed to get it to spit out the correct hash yet.

`Script scriptCode = new Script("1976a9141d0f172a0ecb48aee1be1f2687d2963ae33f71a188ac");
            var sigHash = Script.SignatureHash(scriptCode, p2wpkhTx, 1, SigHash.All, Money.Parse("6"), HashVersion.Witness);`

**Comment by NicolasDorier** [comment]
@sipsorcery take a look at https://bitcoin.stackexchange.com/questions/59231/how-to-sign-a-segwit-transaction-via-nbitcoin the only difference is that you don't need the `ToScriptCoin` part.

You should not attempt to fill any `scriptSig` or `witScript` manually, `Sign` will do it given you use the correct Coin and keys.

You are correct: If you use P2WPKH, then you have no need of `ScriptCoin`.

**Comment by sipsorcery** [comment]
Got it now, thx.
