### ISSUE TITLE
Can't install NBitcoin with Nuget Package

### ISSUE THREAD

**Issue by sacromentus** [MetacoSA/NBitcoin#282]
I get this error when I try to add NBitcoin into a new project:

Error		Could not install package 'NBitcoin 4.0.0.38'. You are trying to install this package into a project that targets 'native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by NicolasDorier** [comment]
What project have you created ?

**Comment by sacromentus** [comment]
I created a Visual C++ console application. I understand it is a C# library but I don’t see any relevant projects to start under C#. Sorry for my Visual Studio n00b status; I’m not super familiar with this interface and how it works. I’m used to opening up vi or vim and just using g++ from the terminal to compile

**Comment by NicolasDorier** [comment]
NBitcoin is a C# library, you can't use it in C++.

**Comment by NicolasDorier** [comment]
Sorry I think I have closed a bit too fast

Please read https://github.com/ProgrammingBlockchain/ProgrammingBlockchain/
