### ISSUE TITLE
WitHash is not the same as WitHash.ScriptPubKey.WitHash

### ISSUE THREAD

**Issue by nopara73** [MetacoSA/NBitcoin#285]
Is it correct like this? If so why?

```
var sk = new BitcoinSecret("L4LDNWrzAaeCKaUn2ZhWDSVD1NiJvtVtJCJVogTSGD4aHmXgHwJ7");
PubKey pk = sk.PubKey;
WitKeyId wpkh = pk.WitHash;

WriteLine(wpkh); // 1138e6014a275135680b5429b7b9ba305d168fe0
WriteLine(wpkh.ScriptPubKey.WitHash); // 11395eeaf359798b3798094dfbcf6ac4e8f60204174dfeab9fe50c7b73db5f74
WriteLine(wpkh == wpkh.ScriptPubKey.WitHash); // false, why?
```

**Comment by NicolasDorier** [comment]
`wpkh.ScriptPubKey.WitHash.ScriptPubKey` is the p2wpkh script. 
`wpkh.ScriptPubKey.WitHash` WitHash is the P2WSH of the P2WPKH script. This should not be done, as anybody would be able to spend such coin given the redeem script. (the redeem script would be two push on the stack, which evaluate to true without passing argument)

`(wpkh == wpkh.ScriptPubKey.WitHash)` this is the equivalent of `pk.Hash == pkh.ScriptPubKey.Hash` in non segwit world. `pk.Hash` represents the redeem script, while `pk.Hash.ScriptPubKey.Hash` represent the P2SH address of the redeem script. 

There is no reason to do such a thing in Bitcoin, both case need a signature over the same pubkey + the pubkey to redeem. The P2SH version take just more space.

For the P2WSH version of your example, as I said above, it must not be done, as it would essentially give the money to the minrers.

**Comment by nopara73** [comment]
I"m still little confused here.  
> `wpkh.ScriptPubKey.WitHash.ScriptPubKey` is the p2wpkh script.  

Do you mean " `wpkh.ScriptPubKey.WitHash.ScriptPubKey` is **A** p2wpkh script". And "`wpkh.ScriptPubKey` is **THE** p2wpkh script"?

**Comment by NicolasDorier** [comment]
Ah sorry I am wrong. This is confusing indeed.

`wpkh.ScriptPubKey` is the P2WPKH script.

If you want to be compatible with P2SH wallet, you use `wpkh.ScriptPubKey.*Hash*.ScriptPubKey` as the txout scriptPubKey.

`wpkh.ScriptPubKey.WitHash.ScriptPubKey` has no sense, it is a P2WSH of P2WPKH. In reality this would be spendable by anyone.

**Comment by nopara73** [comment]
Thanks, now all clear.  

For the record to late arrivals to this thread, these issues are also helpful understanding it:   
https://github.com/MetacoSA/NBitcoin/issues/284  
https://github.com/MetacoSA/NBitcoin/issues/286
