### ISSUE TITLE
Many different script addresses with the introduction of SegWit

### ISSUE THREAD

**Issue by nopara73** [MetacoSA/NBitcoin#286]
All `WriteLine`s outputs different script addresses.  
1. Is my P2SH and P2SH-P2WPKH identification correct?  
2. What are the ones I denoted with `???`.  

```
var n = Network.Main;
var sk = new BitcoinSecret("L4LDNWrzAaeCKaUn2ZhWDSVD1NiJvtVtJCJVogTSGD4aHmXgHwJ7");
PubKey pk = sk.PubKey;

KeyId pkh = pk.Hash;
WitKeyId wpkh = pk.WitHash;

WriteLine(pkh.ScriptPubKey.GetScriptAddress(n)); // P2SH
WriteLine(wpkh.ScriptPubKey.Hash.ScriptPubKey.GetScriptAddress(n)); // P2SH-P2WPKH
WriteLine(wpkh.ScriptPubKey.GetScriptAddress(n)); // ???
WriteLine(wpkh.ScriptPubKey.WitHash.ScriptPubKey.GetScriptAddress(n)); // ???
```

**Comment by NicolasDorier** [comment]
`WriteLine(wpkh.ScriptPubKey.Hash.ScriptPubKey.GetScriptAddress(n)); // P2SH-P2WPKH` 

No this is actually a P2SH-P2SH-P2WPKH. (which is no sense)

Should be
`WriteLine(wpkh.ScriptPubKey.Hash.GetAddress(n)); // P2SH-P2WPKH` 

`WriteLine(wpkh.ScriptPubKey.GetScriptAddress(n)); // ???` it is //P2SH-P2WPKH (equal to above)

`WriteLine(wpkh.ScriptPubKey.WitHash.ScriptPubKey.GetScriptAddress(n)); // ???` this is none sense. Would be P2SH-P2WSH-P2WPKH. As explained in another of your issue `P2WSH-P2WPKH` should never be done, as it is equivalent to everybody can spend.

**Comment by nopara73** [comment]
For the record, this three equals:
```
WriteLine(wpkh.ScriptPubKey.Hash.GetAddress(n));
WriteLine(wpkh.ScriptPubKey.Hash.ScriptPubKey.GetDestinationAddress(n));
WriteLine(wpkh.ScriptPubKey.GetScriptAddress(n));
```
Where `wpkh.ScriptPubKey.Hash.ScriptPubKey` is [documented](https://programmingblockchain.gitbooks.io/programmingblockchain/content/other_types_of_ownership/p2w_over_p2sh.html) in the book.

**Comment by NicolasDorier** [comment]
yes. I am wondering if I should deprecate some stuff. Or maybe just adding comment ?

**Comment by nopara73** [comment]
I'd just comment. Also writing a KeyManager class, that implements BIP44 and BIP49 could make sense, similar to my Safe: https://github.com/nopara73/HiddenWallet/tree/master/HiddenWallet/KeyManagement  

I was long planning to write it and will eventually, just always got off track by the small inconsistencies of BIP44.
