### ISSUE TITLE
Incorrect index at KeyPath.Indexes when derivation is hardened

### ISSUE THREAD

**Issue by nopara73** [MetacoSA/NBitcoin#287]
# Example:  

```
foreach(var i in new KeyPath("1'/2/3/4'/5").Indexes)
{
    WriteLine(i);
}
```

# Output:

```
2147483649
2
3
2147483652
5
```

**Comment by NicolasDorier** [comment]
this is actually correct. Indexes is a `uint` and more of the BIP is talking about using `uint`.
You can easily convert to one another by `Console.WriteLine((int)i)`;
