### ISSUE TITLE
RPCOperations.listtransactions is not implemented

### ISSUE THREAD

**Issue by Rexota** [MetacoSA/NBitcoin#290]
`RPCOperations.listtransactions` is not implemented including some other methods. Is this intended?

Thanks

**Comment by NicolasDorier** [comment]
Yes I did not implemented it.
If you want to make a PR for it, I will merge it.

Otherwise, you can make an extension method in your project on the `RPCClient` type. Then follow how I implemented the existing methods, it is not very difficult.

**Comment by Rexota** [comment]
Thanks for quick response!
