### ISSUE TITLE
How to get the uncompressed wif key?

### ISSUE THREAD

**Issue by ChristopherJoerg** [MetacoSA/NBitcoin#294]
Thank's for NBitcoin! Finally i'm able to try it out on Unity since supporting experimental .NET 4.6 
I'm struggling trying to get the uncompressed wif key. Thanks for your help!

**Comment by NicolasDorier** [comment]
Please do not use uncompressed keys, this is deprecated. If you really need, use `BitcoinSecret.Compress()`.
For what reason do you need that?

**Comment by ChristopherJoerg** [comment]
Thank's for your answer Nicolas. I was not able to run the defintion Compress() on BitcoinSecret, however i managed to get the uncompressed key this way:

var privateKey = new Key();
var bitcoinPrivateKeyCompressed = privateKey.GetWif(NBitcoin.Network.Main);
var bitcoinPrivatKeyUncompressed = bitcoinPrivateKeyCompressed.Copy(false);

Is that also a correct way?

@NicolasDorier 
I am not going to send coins to an WIF uncompressed address, at this point i'm not sure if i will ever send a selfmade transaction... cause this approach to get the uncompressed data took me more than a day.

For what reason do you need that?
What comes in my mind is: if i wanted to create something similar like bitaddress.org with gyro input instead of mouse AddEntropy for mobile platforms, i would like to display the wallet details to the user as well. Personally, i like to check my generated addresses there to see how random all important formats feel.

or if i make a wallet, and a user imports an old key format with coins on that address, i could give the option to import both addresses, which would allow to send the coins to the compressed address by keeping the same privatekey using that wallet.

Thank's NicolasDorier for your great work!

**Comment by ChristopherJoerg** [comment]
Thank's,
i realized that this works before.
Bye
