### ISSUE TITLE
How to verify a witness input is signed?

### ISSUE THREAD

**Issue by nopara73** [MetacoSA/NBitcoin#300]
I can verify a partially signed transaction's input the following way:  

```cs
var itxi = new IndexedTxIn();
itxi.Index = 0;
itxi.Transaction = tx;
itxi.VerifyScript(scriptPubKey);
```

However when the input is native segwit and signed accordingly, this method does not work anymore. (Nor changing to anything the `ScriptVerify` optional parameter works.)

**Comment by nopara73** [comment]
In the meantime I figured `Script.Verify()` is a nicer way to do this, nevertheless it same issue.

**Comment by nopara73** [comment]
By trying the `TransactionBuilder`'s `Verify()` function, it gives me more verbose errors at segwit:  
`Script error on input 0 (NullFail)`.  

For reference when you sign it deliberately with wrong key, it will say: `Script error on input 0 (EqualVerify)` as expected.

**Comment by NicolasDorier** [comment]
Nullfail happens when CheckSig fails. (Also happen in Bitcoin Core, and I don't want to change it, as it is decided by the ScriptEvaluator, which is just a copy/paste of Bitcoin Core)

This probably mean that the TX is not signed correctly or does not have witnesses.

**Comment by nopara73** [comment]
I figured the problem. My dummy data at verification differed from my dummy data at transaction signing in the amount of the txout.
