### ISSUE TITLE
new BitcoinWitPubKeyAddress fails without expected network

### ISSUE THREAD

**Issue by nopara73** [MetacoSA/NBitcoin#304]
Sorry for not fixing it myself, should be something trivial, I am just in the middle of something. Will get back to it if I don't forget.  

```cs
new BitcoinWitPubKeyAddress("tb1qr5d68t6qm8t2n7ch4nph3ha4prztteuw98ewda", Network.TestNet); // SUCCESS
new BitcoinWitPubKeyAddress("tb1qr5d68t6qm8t2n7ch4nph3ha4prztteuw98ewda"); // System.NullReferenceException
```

**Comment by NicolasDorier** [comment]
good catch, might take a look today

**Comment by NicolasDorier** [comment]
There was the same bug a few line below https://github.com/MetacoSA/NBitcoin/commit/5ca39bf8d031c4e288f0a2c0f33305bbd476ff98
