### ISSUE TITLE
QbitNinja not return Balances

### ISSUE THREAD

**Issue by Ashish81** [MetacoSA/NBitcoin#305]
Hi Nicolas, My 5 stars. Its totally a wondrous wrapper besides some glitches. Enjoyed playing with it. 👍 
see below urls
Qbitninja goes out of sync??
https://tapi.qbit.ninja/balances/mpqChjGscZ5GqZX5XjSiDojvCmcuQLC7WT
blocktrail 
https://www.blocktrail.com/tBTC/address/mpqChjGscZ5GqZX5XjSiDojvCmcuQLC7WT/transactions.

Planning to use qbitninja for mainnet transactions. should i rely on qbit.ninja or should i deploy qbitninja server on my own azure services. Can i deploy it on other windows vps (not azure/ storage or VM)?

**Comment by NicolasDorier** [comment]
yes it seems qbit ninja testnet is out of sync, restarting the indexer, something seems off.

**Comment by NicolasDorier** [comment]
Restarted it. Seems fine now.

**Comment by NicolasDorier** [comment]
Ok so the public qbitninja server have no guarantee of reliability, so for anything in prod, you should host your own.

You need at least to run the indexer on Azure (good latency needed for indexing things fast enough). You can run front end anywhere you like though.

**Comment by Ashish81** [comment]
Indexer is hard coupled with azure, I think  can it be modified ( in code/ clases) to make use of sql server as back end storage n indexing . And How much  effective it ll be if done so as compared to azure. 

I need to index a few thousands collection of address n transactions , need brodcast function .Not to be exposed publicly. Gone through nbxplorer , it also doesnt fit in here. Own my privte server to want tohost there.

**Comment by NicolasDorier** [comment]
modifying it to work fast enough on a SQL database is major work. The index schema is very coupled with internal implementation details of Azure so that queries are fast.

NBXplorer is lightweight, while still have bugs to iron out, it HD keys, and you can retrieve transactions which got tracked.

**Comment by Ashish81** [comment]
Thanks a lot.

**Comment by Ashish81** [comment]
It seems Qbit ninja is down again????

**Comment by NicolasDorier** [comment]
it seems so, checking it.

**Comment by NicolasDorier** [comment]
Should be good now, can you check?

**Comment by Ashish81** [comment]
Yes synced n running Thanks :)
