### ISSUE TITLE
Spending Unconfirmed Transaction not propogated

### ISSUE THREAD

**Issue by Ashish81** [MetacoSA/NBitcoin#307]
Tried spending  unconfirmed transaction ( change address ) on Mainnet using Transactionbuilder , the Broadcast was successful but not Txid not found on qbit.ninja or other explorer.??

e22b0cf820e53826f569f11e5c5e5d1bf9286476318f6a4ab7137ebddbd0e0f

**Comment by NicolasDorier** [comment]
Can come from several reason, do you have the full tx hex ?

**Comment by Ashish81** [comment]
Yes I have, It was an issue of double spending, Broadcast function doesnt seem to catch it with proper error message.

**Comment by NicolasDorier** [comment]
yeah I really need to fix the broadcast, it is causing lots of headache to people.

**Comment by Ashish81** [comment]
Yeah and we all need pizza and coffee, :) so it is the address **1KF8kUVHK42XzgcmJF4Lxz4wcL5WDL97PB**, i m pleased to send some support.

**Comment by NicolasDorier** [comment]
Ah :) Can you post the full transaction hex so I can look what is going wrong ?

**Comment by Ashish81** [comment]
Mainnet, double spending. verification succeed broadcast succeed..

010000000148145566e177277f417917d9880aa01010e3abb47925fb4c07f0aef507dbb2c5010000006a473044022002243c8e1225031f1638d117234c1af35fa1ec3c5b28260792ddff1a7cd39091022056d986a3300a992aede3f61aeb72d29b57553460d70d7eda79f3dfa49d655ea4012103e4dee1b4d33d3060701166f7c4d76025cdf7dabc1546f74bc0c964670969414cffffffff02eba7c404000000001976a9143a0780feed0192c64a2139ccd28a2e22410dfb1c88ac000e2707000000001976a914083f2c378f636bb7705e81d95564a69ab8ff2bbf88ac00000000

**Comment by Ashish81** [comment]
Pushing tx on smartbit throws below error which is correct catch

18: BAD-TXNS-INPUTS-SPENT

**Comment by Ashish81** [comment]
I understand it that i am trying a spent outpoint,  but Qbitninja broadcast  does not seem to catch it, I think broadcast should suppose to catch it the way smartbit does.

**Comment by NicolasDorier** [comment]
Agreed @Ashish81 I must really make QBitNinja better for returning errors.

**Comment by Ashish81** [comment]
:) Thanks
