### ISSUE TITLE
Network class should have Blockchain and APIPort properties

### ISSUE THREAD

**Issue by andrasfuchs** [MetacoSA/NBitcoin#309]
Looking at the Stratis source code, it would be good to extend the [Network class](https://github.com/MetacoSA/NBitcoin/blob/master/NBitcoin/Network.cs) with two properties:

string/enum Blockchain - indicating if the network is Bitcoin, Stratis, or something else (Main and Testnet would have the same value)

int RESTAPIPort - indicating the default port number where the daemon's REST API is published (similarly to RPCPort for RPC)

Both would benefit any future forks as well.

**Comment by andrasfuchs** [comment]
The extensions sound good!

Well, I probably used a wrong property name, but I thought that it would be beneficial, if BitcoinMain and BitcoinTestNet and BitcoinRegTest networks had a property to indicate that they are Bitcoin networks. So they all have a enum property telling that they are Bitcoin networks. 

Similarly the Stratis networks would have different names for main,testnet and regtest, but they had a property with the same enum value "Stratis".

**Comment by NicolasDorier** [comment]
I am busy on some other thing so if you want to work on it, I would merge.
The best would be a `Network.GetExtensions<T>() where T new()` internally it would use a `ConcurrentDictionary` which use `GetOrAdd` to be sure the extensions are singleton.

If you need that for the stratis project, you would then create an extension called `NetworkFamily` with a property `Value` which resolve to an enum of all family supported by Breeze. Such class would not be needed inside NBitcoin.

**Comment by andrasfuchs** [comment]
Thank you @NicolasDorier!

Alright, I'll continue with my project, and we'll see. If I really need to implement it, I'll create a pull request for NBitcoin too.

**Comment by NicolasDorier** [comment]
@andrasfuchs worth mentioning that you can work around that now by having a global dictionary doing it for you, and then you can add extension methods to Network.
