### ISSUE TITLE
Tests broken

### ISSUE THREAD

**Issue by NicolasDorier** [MetacoSA/NBitcoin#319]
@nopara73 
https://ci.appveyor.com/project/NicolasDorier/nbitcoin/build/4.0.0.92

**Comment by nopara73** [comment]
Looking at it.

**Comment by nopara73** [comment]
Reference: https://github.com/MetacoSA/NBitcoin/pull/320

**Comment by NicolasDorier** [comment]
still broken CanGetUTXOsMempool

**Comment by NicolasDorier** [comment]
ok it was unrelated to you
