### ISSUE TITLE
Segwit P2SH-P2WPKH address derivation based on an xpub-key

### ISSUE THREAD

**Issue by simonpfeifhofer** [MetacoSA/NBitcoin#322]
I would like to derive P2SH- and P2SH-P2WPKH-addresses based on a given xpub-key.

Given the following code:

var extPubKey = ExtPubKey.Parse("xpub...");
var btcAddress = extPubKey.Derive(0).PubKey.GetAddress(Network.Main);
var btcSegwitAddress = extPubKey.Derive(0).PubKey.GetSegwitAddress(Network.Main);

"btcAddress" is the first P2SH-address.
"btcSegwitAddress" ist the first segwit-address. It's the bench32-native-variant. How can I achieve to derive the first base58-encoded P2SH-P2WPKH-address?

**Comment by NicolasDorier** [comment]
```
var btcP2SHSegwitAddress = btcSegwitAddress.GetScriptAddress();
```

Should be equivalent to the more efficient

```
var extPubKey = ExtPubKey.Parse("xpub...");
            var btcP2SHSegwitAddress = extPubKey.Derive(0).PubKey.WitHash.ScriptPubKey.Hash.GetAddress(Network.Main);
```

**Comment by simonpfeifhofer** [comment]
@NicolasDorier: Thank you for the fast answer.
