### ISSUE TITLE
Obsolate first, then start removing blocking sync looking methods?

### ISSUE THREAD

**Issue by nopara73** [MetacoSA/NBitcoin#325]
Of course, also make sure its async version is available.

[Channel 9: Async Library Methods Shouldn't Lie](https://channel9.msdn.com/Series/Three-Essential-Tips-for-Async/Async-Library-Methods-Shouldn-t-Lie)  

> Libraries shouldn't lie. That's not why they're called "lie-braries"...

For example it is really confusing that I had sync and async RPC methods. In order to became clear to me which ones was the clean implementation, I had to look into the source code.  

@NicolasDorier What do you think?

**Comment by NicolasDorier** [comment]
There is no lie, the async methods are really async.  The sync methods are using `.GetAwaiter().GetResult()` but this can't provoke a deadlock in an event loop because I use `ConfigureAwait(false);` everywhere.

The synchronous versions are convenience methods I use in unit test because it makes my life easier to write and debug.

**Comment by nopara73** [comment]
Stephen Toub: [Should I expose synchronous wrappers for asynchronous methods?](https://blogs.msdn.microsoft.com/pfxteam/2012/04/13/should-i-expose-synchronous-wrappers-for-asynchronous-methods/)

> If you expose an asynchronous endpoint from your library, avoid exposing a synchronous method that just wraps the asynchronous implementation. Doing so hides from the consumer the true nature of the implementation, and it should be left up to the consumer how they want to consume the implementation. If the consumer chooses to block waiting for the asynchronous implementation to complete, that’s up to the caller, and they can do so with their eyes wide open.
> This is even more important for the “sync over async” case than it is for the “async over sync” case, because for “sync over async,” it can lead to significant problems with the application, such as hangs.

Btw This is perfectly valid: 

```cs
[Fact]
async Task FooTestAsync()
{
  await BarAsync();
}
```

**Comment by NicolasDorier** [comment]
and take lot's of keystroke compared to the sync version. In my experiences, tests are painful to debug with async everywhere, as you can't easily see the stack trace and debugger get step bugs.

I think the synchronous versions are very useful for tests and showing simple code to people who don't understand well C#. This is useful convenience methods.

**Comment by nopara73** [comment]
Alright.
