### ISSUE TITLE
What is the hex value in NetworkBuilder.SetMagic( ) ?

### ISSUE THREAD

**Issue by silvestre22** [MetacoSA/NBitcoin#329]
I am curious about the hex value passed to the NetworkBuilder.SetMagic( ) in line 746 Network.cs. What sorcery is that? What will happen if I edit the magic value?

    // The message start string is designed to be unlikely to occur in normal data.
    // The characters are rarely used upper ASCII, not valid as UTF-8, and produce
    // a large 4-byte int at any alignment.
    magic = 0xD9B4BEF9;
    vAlertPubKey = Encoders.Hex.DecodeData("04fc9702847840aaf195de8442ebecedf5b095cdbb9bc716bda9110971b28a49e0ead8564ff0db22209e0374782c093bb899692d524e9d6a6956e7c5ecbcd68284");
    nDefaultPort = 8333;
    nRPCPort = 8332;

Thanks.

**Comment by NicolasDorier** [comment]
it is a 4 bytes marker used by Bitcoin P2P protocol messages to make sure peers use the same chain. This is defined in Bitcoin by `chainparams.cpp`. (I am using big endian)
