### ISSUE TITLE
Should NBitcoin rather use BouncyCastle's SecureRandom by default?

### ISSUE THREAD

**Issue by knocte** [MetacoSA/NBitcoin#330]
I see that the random number generator used depends on the platform...
Nethereum however, uses (BouncyCastle's)SecureRandom in every platform.

Shouldn't NBitcoin also depend on BouncyCastle for this by default?

**Comment by NicolasDorier** [comment]
@knocte I prefer using the RNG of the platform. What we can do is adding entropy using the BC castle SecureRandom with RandomUtils.AddEntropy through.

**Comment by knocte** [comment]
> I see that the random number generator used depends on the platform...

When upgrading from 3.x to 4.0.0.38 I've noticed that this is not true anymore, I got an exception saying that I didn't set RandomUtils.Random property. Was this intended? (It was even when compiling and running in Windows.)

(FYI I solved it on my end with https://github.com/knocte/gwallet/commit/0dd3dbe1307f14e39953738277024ceea304d38b .)

> I prefer using the RNG of the platform.

Thing is, I think BouncyCastle's is kinda doing the same thing: using the best approach depending on the platform. So I don't think NBitcoin should be trying to fix this problem, but delegate into BouncyCastle for solving it.

**Comment by NicolasDorier** [comment]
@knocte please do not use BC one and, or if you do, do not use the only this one. This is calling for a disaster.

NBitcoin does not set default Random if you are using netstandard1.1. Which plateform do you target?

**Comment by NicolasDorier** [comment]
Ah target 4.5.2 at least (instead of 4.5.1), you will not have any issue.

**Comment by knocte** [comment]
> This is calling for a disaster.

Why a disaster? If BouncyCastle's random class wasn't secure, they wouldn't call it SecureRandom. (FYI it only uses DateTime.Now.Ticks as entropy addition, see https://crypto.stackexchange.com/a/18208 )

> Ah target 4.5.2 at least (instead of 4.5.1), you will not have any issue.

Can you elaborate what do you mean by this? My wallet actually targets .NET Standard when running with the Xamarin.Forms frontends.

**Comment by NicolasDorier** [comment]
Calling it Secure does not make it secure. OS randomness has better chance of being really secure than SecureRandom, as it has been more attacked and everything depends on it being secure... BouncyCastle, not so much. Please do not use SecureRandom, or if you do, mix it with other source of entropy before people loose money.

I saw your project is targetting .NET 4.5.1.

I think you are using old version of xamarin forms, it supports netstandard2.0 as per https://developer.xamarin.com/guides/xamarin-forms/under-the-hood/net-standard/ so if your project is well configured, you should use NBItcoin netstandard1.6, which support OS level randomness.

To know if you are targetting .netstandard1.6, hit F12 on a class of NBitcoin and look at the top in what folder is the referenced library.

**Comment by knocte** [comment]
> Calling it Secure does not make it secure

Really?? :)

I know, but I'm giving some weight to the BouncyCastle guys. Do you think you know more cryptography than them? Just curious, because in my case of course I don't. Looking at their commits, they seem to be very knowledgeable, and as I already said in my 2nd comment on this issue, they seem to be already using the specific RNGs of the platform underneath.

> OS randomness has better chance of being really secure than SecureRandom

If SecureRandom uses OS randomness, plus more added entropy, I guess this is not true.

> I saw your project is targetting .NET 4.5.1.

My master branch does. Why is .NET 4.5.2 better in this regard?

> I think you are using old version of xamarin forms, it should support netstandard2.0

My 'frontend' (not master) branch is the one that is using Xamarin.Forms+.netStandard, and as it's F#, my only option has actually been to use 2.0, as F# is not compatible with .netStandard 1.x.

Why is .netStandard 2.0 better than .netStandard 1.x in this regard?

**Comment by knocte** [comment]
>> OS randomness has better chance of being really secure than SecureRandom

> If SecureRandom uses OS randomness, plus more added entropy, I guess this is not true.

And to back this with info, look at how the last version of BouncyCastle's SecureRandom uses "CryptoApiRandomGenerator" class (in all cases except CompactFramework):

https://github.com/bcgit/bc-csharp/commit/b494cecf549016c5db4493d50f3a738963a2eeb6?w=1#diff-1ff2251cd1dbcfafe59db10af1c49672

And this class uses System.Security.Cryptography.RandomNumberGenerator underneath:

https://github.com/bcgit/bc-csharp/blob/master/crypto/src/crypto/prng/CryptoApiRandomGenerator.cs

**Comment by NicolasDorier** [comment]
> Do you think you know more cryptography than them?

I don't but I believe that OS developers knows better cryptography than them, and there is just zero reason to not use the randomness of the OS.

> If SecureRandom uses OS randomness, plus more added entropy, I guess this is not true.

Add your own randomness just to be sure by using the OS one directly in addition.

> My master branch does. Why is .NET 4.5.2 better in this regard?

4.5.1 resolve NBitcoin netstandard 1.1 which does not have OS level API.
4.5.2 resolves NBitcoin 4.5.2 which has OS level API.
netcoreapp2.0 resolves to NBitcoin netstandard 1.3 which has OS level API.
