### ISSUE TITLE
Can't get balance of address

### ISSUE THREAD

**Issue by mathis1337** [MetacoSA/NBitcoin#332]
I have been working on this all weekend and have the issue of getting a balance with a public address. So far all I can get are amounts received to an address, but I can not find in the outputs any spend transactions. Perhaps I am doing something wrong. I eventually want to use this to index the blockchain and then query new blocks to add to a database to make things faster, but I want to first understand how to just query from my local copy. Can any help? here is the code i have current.

```
//NBitcoin Attemps
var node = Node.ConnectToLocal(Network.Main);

node.VersionHandshake();

var chain = node.GetChain();

BlockStore store = new BlockStore(@"D:\Bitcoin\blocks", Network.Main);

var index = new IndexedBlockStore(new InMemoryNoSqlRepository(), store);

//Important or block index returns null
index.ReIndex();

//Using a headers tied to just 1 day for speed purposes. 
//var headers = chain.ToEnumerable(false).ToArray();

//This is where unspent balance went to of 0.86544710
//byte[] byteArray = Encoders.Base58.DecodeData("17dvTpgdJHL9tQDTCkyMCk9AvGkutUZNWV");

//This is where I sent .1337 to 1QCfEaS6NKaHUA1vXKfPzzpVbY4QScz9yx and unspent went to above address
byte[] byteArray = Encoders.Base58.DecodeData("1AjoFjQjqxss1Jgt7Hz9KnrNiX8TnBemrf");
string address = Encoders.Base58.EncodeData(byteArray);

BitcoinPubKeyAddress bob = new BitcoinPubKeyAddress(address);

DateTime tom  = new DateTime(2018,1,14);

var to = new DateTimeOffset(tom);

DateTime localTime1  = new DateTime(2018,1,13);

localTime1  = DateTime.SpecifyKind(localTime1 , DateTimeKind.Local);

DateTimeOffset from = localTime1 ;

var headers =
	chain.ToEnumerable(false)
		.SkipWhile(c => c.Header.BlockTime < from)
		.TakeWhile(c => c.Header.BlockTime < to)
		.ToArray();

var target = Money.Parse("1100");
var margin = Money.Parse("1");
var en = new CultureInfo("en-US");



var lines = from header in headers
			let block = index.Get(header.HashBlock)
			from tx in block.Transactions
			from txout in tx.Outputs
			//This can be used to find a range with margin targets
			//where target - margin < txout.Value && txout.Value < target + margin
			//This is used to find all receives for a particular address
			where txout.ScriptPubKey.GetDestinationAddress(Network.Main) == bob 
			//where header.Height == 504099
			select new
			{
				Block = block,
				Height = header.Height,
				Transaction = tx,
				TxOut = txout,
				Balance = txout.Value.ToDecimal(MoneyUnit.BTC)
			};


lines.ToList().ForEach(x =>
{
	x.Block.Header.BlockTime.ToString(en).Dump();
	x.Height.Dump();
	x.Balance.Dump();
	x.Transaction.Outputs.Where(y => y.ScriptPubKey.GetDestinationAddress(Network.Main) == bob).Dump();
	
});
```

**Comment by mathis1337** [comment]
I am sure I am missing something simple, just not sure what it is and not sure why I can't see any type of sends an address pushes out.

**Comment by NicolasDorier** [comment]
Please read https://programmingblockchain.gitbooks.io/programmingblockchain/content

The code is also deprecated. Getting the balance of an address is hard, unless you depends on a block explorer or on bitcoin core wallet. I advise you against backing your own solution.

**Comment by mathis1337** [comment]
Normally I would, but the project I am working on we are going to do a fork, and therefore current explorers won't work, and we can't just rely on the wallet right? The wallet can't tell us the balance of other addresses, just addresses within that wallet right?

**Comment by NicolasDorier** [comment]
You might be interested by this project https://github.com/dgarage/NBxplorer 
This is a JSON API to track wallet and unused address.

I show how to use it on https://youtu.be/liOUTqBUi_g , if you have your own coins you might need to fork it, or add the code to support your alt (check how I did for Litecoin)

**Comment by NicolasDorier** [comment]
@mathis1337 JS and Python have the same issue, this is not a language issue, but a technological one.
