### ISSUE TITLE
Derive from Multi sig

### ISSUE THREAD

**Issue by Kukks** [MetacoSA/NBitcoin#338]
Heya, I am messing around a bit, trying to see what I can come up with to use.

Is there a way to bip32 derive  from a multsig address?  
I can't seem to figure out how to derive from a Script 
```
            var mnemomincs = new Mnemonic[3];
            var extKeys = new ExtKey[3];
            Script multsigScript;
            for (int i = 0; i < mnemomincs.Length; i++)
            {
                mnemomincs[i] = new Mnemonic(Wordlist.English, WordCount.Twelve);
                Console.WriteLine(string.Join(" ",mnemomincs[i].Words));
                extKeys[i] = mnemomincs[i].DeriveExtKey();

                Console.WriteLine("Address:{0}  Segwit: {1}", extKeys[i].PrivateKey.PubKey.GetAddress(Network.Main), extKeys[i].PrivateKey.PubKey.WitHash.GetAddress(Network.Main));
            }
            multsigScript = PayToMultiSigTemplate
                .Instance
                .GenerateScriptPubKey(2, extKeys.Select(key => key.PrivateKey.PubKey).ToArray());
            var multiSigAddress = multsigScript.GetScriptAddress(Network.Main);
            var multiSigSegwitAddress = multsigScript.GetWitScriptAddress(Network.Main);
            Console.WriteLine("Master wallet 2-of-3 multisig address:"  +multiSigAddress);
            Console.WriteLine("Master wallet 2-of-3 multisig segwit address:"  + multiSigSegwitAddress);
```

**Comment by nopara73** [comment]
Without taking a look at the code, there is a conceptual problem. You derive addresses from extended keys. A script may hold only one, but it may hold multiple keys, therefore simply from a script you cannot derive keys. In fact you cannot derive a key from a key, either you need an extended key, which is a key + a chain code.

**Comment by Kukks** [comment]
@nopara73 I read somewhere( [here](https://bitcoin.stackexchange.com/questions/37777/multi-sig-sub-keys)) called HDM. I'm not an expert by any means so I'm not doubting you. :)

**Comment by nopara73** [comment]
@Kukks Looks like you are more knowledgeable in this topic, than me. I've never heard of it, although looking at the link it's not standard, nor used anywhere, so I'm not that hard on myself for this:)

**Comment by Kukks** [comment]
@nopara73 It seems its usage is just hidden away by some wallet providers such CoPay and never got proposed as a BIP :) Ethereum's crowdsale funds were saved in an HDM style way back in 2014.

**Comment by NicolasDorier** [comment]
I think they are just deriving each key individually then combining them in a mutli sig script.

**Comment by NicolasDorier** [comment]
Your code seems correct, what is the issue ?

**Comment by Kukks** [comment]
@NicolasDorier No issue witht he code, I just cou;dn't figure out how they were deriving from a multisig address, but you cleared it for me! Thanks!

**Comment by NicolasDorier** [comment]
Ah ok I understand. No, in bitcoin you have no way to go from the address to the multisig. Only one way. (Because addresses are hashes, they prevent the reverse operation)

**Comment by Kukks** [comment]
@NicolasDorier What do you mean by ordering my public keys for privacy?

**Comment by NicolasDorier** [comment]
`GenerateScriptPubKey(2, extKeys.Select(key => key.PrivateKey.PubKey).ToArray())` 

Imagine you have a 2-3, Alice, Bob, Satoshi and the extKeys are in the same order.

When you will spend coin from a `scriptPubKey` generated like that, then the `scriptSig` will reveal which identity signed the transaction.

From an outsider pespective, he can induce some chain analysis for example that every single time only Alice and Bob are signing, so that maybe Satoshi is just a cold storage key. So not sorting leaks some information.

This is why [BIP45](https://github.com/bitcoin/bips/blob/master/bip-0045.mediawiki) is [asking](https://github.com/bitcoin/bips/blob/master/bip-0045.mediawiki#cosigner-index)

> the indices can be determined independently by lexicographically sorting the purpose public keys of each cosigner

**Comment by Kukks** [comment]
@NicolasDorier So I should randomly sort the public keys when generating a multi signature address? That generates a different address each time. Would I be able to track the same balance to any of the possible generated addresses?

```
 static void Main(string[] args)
        {
            var mnemomincs = new Mnemonic[3]
            { 
                new Mnemonic("tornado exercise awesome indoor ghost chuckle coast opera educate work decorate cloud"),
                new Mnemonic("shaft miss credit damage lemon bachelor inside example depend record puppy twice"),
                new Mnemonic("tongue trim credit situate woman lion defense believe accuse notable holiday large"),
            };
            var extKeys = new ExtKey[3];
            Script multsigScript;
            for (int i = 0; i < mnemomincs.Length; i++)
            {
                mnemomincs[i] = mnemomincs[i]??new Mnemonic(Wordlist.English, WordCount.Twelve);
                Console.WriteLine(string.Join(" ",mnemomincs[i].Words));
                extKeys[i] = mnemomincs[i].DeriveExtKey();

                Console.WriteLine("Address:{0}  Segwit: {1}", extKeys[i].PrivateKey.PubKey.GetAddress(Network.Main), extKeys[i].PrivateKey.PubKey.WitHash.GetAddress(Network.Main));
            }
            Console.WriteLine();

            while (Console.ReadKey().KeyChar == 'a')
            {
            
            multsigScript = PayToMultiSigTemplate
                .Instance
                .GenerateScriptPubKey(mnemomincs.Length-1, Shuffle(extKeys).Select(key => key.PrivateKey.PubKey).ToArray());
            var multiSigAddress = multsigScript.GetScriptAddress(Network.Main);
            var multiSigSegwitAddress = multsigScript.GetWitScriptAddress(Network.Main);
            Console.WriteLine("multisig address:"  +multiSigAddress + "segwit address:" + multiSigSegwitAddress);

                Console.WriteLine();
            }
            Console.ReadLine();
        }
        private static Random rng = new Random();
        public static IList<T> Shuffle<T>(IList<T> list)
        {
           var res =  list.ToList();
            int n = res.Count;
            while (n > 1)
            {
                n--;
                int k = rng.Next(n + 1);
                T value = res[k];
                res[k] = res[n];
                res[n] = value;
            }
            return res;
        }
```

**Comment by NicolasDorier** [comment]
You need to sort them deterministically so all co signers just have to know the keypath of the address you are generating.

**Comment by Kukks** [comment]
@NicolasDorier If I understood correctly, this should be it then:
```
 var mnemomincs = new Mnemonic[3]
            {
                new Mnemonic("tornado exercise awesome indoor ghost chuckle coast opera educate work decorate cloud"),
                new Mnemonic("shaft miss credit damage lemon bachelor inside example depend record puppy twice"),
                new Mnemonic("tongue trim credit situate woman lion defense believe accuse notable holiday large"),
            };
            var extKeys = new ExtKey[3];
            Script multsigScript;
            for (int i = 0; i < mnemomincs.Length; i++)
            {
                mnemomincs[i] = mnemomincs[i] ?? new Mnemonic(Wordlist.English, WordCount.Twelve);
                Console.WriteLine(string.Join(" ", mnemomincs[i].Words));
                extKeys[i] = mnemomincs[i].DeriveExtKey();

                Console.WriteLine("Address:{0}  Segwit: {1}", extKeys[i].PrivateKey.PubKey.GetAddress(Network.Main), extKeys[i].PrivateKey.PubKey.WitHash.GetAddress(Network.Main));
            }
            Console.WriteLine();

            var publicExtKeys = extKeys.Select(key => key.Derive(45, true)).Select(key => key.Neuter()).ToList();

            while (true)
            {
                Console.Write("Derivation Path(<change>/<index>):");
                var derivationPath = Console.ReadLine();
                var derivedMasterKeys = publicExtKeys.OrderBy(key => key.ToString())
                    .Select((key ,index)=> key.Derive(new KeyPath($"{index}/{derivationPath.Trim('/')}")));


                var pubKeys = derivedMasterKeys.Select(key => key.PubKey).ToArray();
                multsigScript = PayToMultiSigTemplate
                    .Instance
                    .GenerateScriptPubKey(mnemomincs.Length - 1, pubKeys);
                var multiSigAddress = multsigScript.GetScriptAddress(Network.Main);
                var multiSigSegwitAddress = multsigScript.GetWitScriptAddress(Network.Main);
                Console.WriteLine("multisig address:" + multiSigAddress + " segwit:" + multiSigSegwitAddress);

                Console.WriteLine();
            }
```

**Comment by Kukks** [comment]
It seems like BIP45 was abandoned a while ago by CoPay and they went back to BIP 44.

**Comment by NicolasDorier** [comment]
you need to order the public keys, not the ExtKeys.
The fact that BIP45 is abandoned does not mean the reason for sorting the public key is not valid anymore though.

By the way https://github.com/dgarage/NBXplorer is a block explorer which can track multi sigs if you want.

**Comment by Kukks** [comment]
@NicolasDorier Yes, I'm eyeing the NBXPlorer as soon as I have a complete strategy for how I will be storing dozens/hundreds of different coin in an automatic cold storage deposit system. Then I'll be looking to create an interface on top of NBXplorer to deviate between btc family coins and eth based coins. 

Which brings me to my next question which is probably better suited for another issue but I'll keep it short. Are there any docs to how the Litecoin compat package was made? I would need to create keys for quite a few forked coins but I'm unsure of how to go about it.

**Comment by Kukks** [comment]
@NicolasDorier That would mean to do
`publicExtKeys.OrderBy(key => key.PubKey).Select((key ,index)=> key.Derive(new KeyPath($"{index}/{derivationPath.Trim('/')}")));`
instead of 
`publicExtKeys.OrderBy(key => key.ToString())
                    .Select((key ,index)=> key.Derive(new KeyPath($"{index}/{derivationPath.Trim('/')}")));`

Thanks for all the help so far Nicolas.

**Comment by NicolasDorier** [comment]
I mean here

```
multsigScript = PayToMultiSigTemplate
                    .Instance
                    .GenerateScriptPubKey(mnemomincs.Length - 1, pubKeys)
```
to
```
multsigScript = PayToMultiSigTemplate
                    .Instance
                    .GenerateScriptPubKey(mnemomincs.Length - 1, pubKeys.OrderBy(p=>p.ToHex()).ToArray());
```

**Comment by Kukks** [comment]
Ah ok, so the sorting isn't on the master pub key but after they are derived to the correct path

**Comment by Kukks** [comment]
Closing since all the goodnes needed to do it is already possible from above. :)
