### ISSUE TITLE
TransactionBuilder.Verify fails but transaction is successful on the blockchain

### ISSUE THREAD

**Issue by bazooka70** [MetacoSA/NBitcoin#339]
What could cause **TransactionBuilder.Verify**  to return false? This transaction is successfully signed, and I'm able to broadcast it to the blockchain, but for some reason it always returns "false". e.g.

```
var builder = new TransactionBuilder();
            var tx = builder
                .AddCoins(coinsToSpend)
                .AddKeys(signingKeys.ToArray())
                .Send(addressToSend, amountToSend)
                .SendFees("0.00001008")
                .SetChange(changeScriptPubKey)                
                .BuildTransaction(true);

Console.WriteLine(builder.Verify(tx)); // always false
```

The result transaction looks like:

```
{
  "hash": "b7090c8a07059d1e469e95b73deb42daaa2e1d7e4c9aa4d04ad16de13351a5c5",
  "ver": 1,
  "vin_sz": 1,
  "vout_sz": 2,
  "lock_time": 0,
  "size": 223,
  "in": [
    {
      "prev_out": {
        "hash": "53911e43ec41e5a3b74aed43c3f1368514ac366ac6fc7b4b991853012058adac",
        "n": 1
      },
      "scriptSig": "30440220602d34b8bc0547732753f9251bb8dcbe9dbf039e3af8e88017472d6684e2287b022016c79e734cdad383cf504a079068b1a111bd6715fda164b7bb6e4a1c0bc1da3101 02312d1962a3c7626228c555684971f84e0008fd364e6646303885099be9b69af1"
    }
  ],
  "out": [
    {
      "value": "0.29998992",
      "scriptPubKey": "OP_DUP OP_HASH160 33ab50867662afb080281e0bdb389751bb2c8a08 OP_EQUALVERIFY OP_CHECKSIG"
    },
    {
      "value": "0.20000000",
      "scriptPubKey": "OP_HASH160 f46ba62dc8063b6e798076609d69b1e6803be6e9 OP_EQUAL"
    }
  ]
}
``` 

The amounts and fee seems OK, and the fact that the transaction is accepted on the blockchain just drives me crazy. Please assist. I am currently using a single  Testnet address for my transactions (including the change address) 

Here are all the successful transactions I made:

https://live.blockcypher.com/btc-testnet/address/mkE9yyrgdttSRY7UYQLVUHVY9g7Saqh2Qv/

**Comment by knocte** [comment]
@NicolasDorier Verify() should probably return void (instead of bool), and throw exceptions for each verification failure.

**Comment by NicolasDorier** [comment]
@bazooka70 there is probably a good reason, which would make it not work on testnet.

```
Policy.TransactionPolicyError[] errors =  = null;
builder.Verify(tx, out errors);
```
check `errors` then.

**Comment by bazooka70** [comment]
@NicolasDorier , Thanks. 
I got an error: "Fee too low, actual is 0.00001008, policy minimum is 0.00001120".  I changed the Fee to  0.00001120 and now it returned True. 

I actually used 0.00001008 from Bitcoin Core "estimatesmartfee(6)" when I was testing. so why is the builder complains and **where** does it gets that Fee number?

**Comment by NicolasDorier** [comment]
You should use `SendEstimatedFee` not `sendfee`.

**Comment by bazooka70** [comment]
@NicolasDorier , I think I'm lost... :(
```

           FeeRate feeRate = new FeeRate(new Money(0.00001264m, MoneyUnit.BTC));
           
            var builder = new TransactionBuilder();
            var tx = builder
                .AddCoins(coinsToSpend)
                .AddKeys(signingKeys.ToArray())
                .Send(addressToSend, amountToSend)
                .SetChange(changeScriptPubKey)
                .SendEstimatedFees(feeRate)                                                
                .BuildTransaction(true);

```

Returns error 

> Fee too low, actual is 0.00000283, policy minimum is 0.00001120

**Comment by NicolasDorier** [comment]
```
FeeRate feeRate = new FeeRate(new Money(0.00001264m, MoneyUnit.BTC), 1000);
```

**Comment by NicolasDorier** [comment]
does `0.00001264m` come direclty from bitcoin core ?

**Comment by NicolasDorier** [comment]
Ok so I checked, it turned out that bitcoin core dropped down the `minTxRelayFee` for the network, thus your fee estimation was below what NBitcoin consider safe.

You code is fine, try version `4.0.0.56` which should fix your issue.
There is a way to disable this check `TransactionBuilder.Policy.MinRelayTx` (or something like that), but please do not remove it.

**Comment by bazooka70** [comment]
@NicolasDorier , Thanks.
`estimatesmartfee(6)` returns 0.00004990 for MainNet; 
`estimatesmartfee(6)` returns 0.00001016 for TestNet

So the formula I need to use is (Pseudo): 
`FeeRate feeRate = new FeeRate(new Money(estimatesmartfee(6), MoneyUnit.BTC), 1000);`
? 

Does the 1000 (size) represent the KB?

**Comment by NicolasDorier** [comment]
Yes, @bazooka70 just update the package your code as before should work.
By default the second parameter is 1000 so I don't think it will change anything.

**Comment by bazooka70** [comment]
```
Policy.TransactionPolicyError[] errors =null;
builder.Verify(tx, out errors);
if (errors != null)
{
    foreach (var e in errors)
    {                             
        Console.WriteLine("builder error-> " + e.ToString());
    } 
}
```

@NicolasDorier I think it is important to add something like `e.ErrorCode` (enumerator?) so we can know what the error refers to, and return our **own error message** based on the `ErrorCode`.
What do you think? Please don't ask me to make a PR... :-P

**Comment by NicolasDorier** [comment]
Well you can already do that, all errors are strongly typed so you can use the type of the error to print the right message.

**Comment by bazooka70** [comment]
I'm not sure what you mean by strongly typed since all errors in the collection are  of type `TransactionPolicyError`. BTW, I didn't have the chance to thank you on issues #20, you are the god! :100:

**Comment by NicolasDorier** [comment]
This is only the base type. Look in NBitcoin.Policy for all different type of errors.

**Comment by bazooka70** [comment]
Got it! thanks.
