### ISSUE TITLE
Allow override of sent protocol version

### ISSUE THREAD

**Issue by Kukks** [MetacoSA/NBitcoin#342]
I'm attempting to integrate some other coins with NBitcoin, however these coins have a different protocol version and have also implemented a minimum version check which kicks off connecting to their node. 

Example: 
```
2018-02-21 18:36:43 peer=73 using obsolete version 70012; disconnecting
2018-02-21 18:36:43 ProcessMessages(version, 115 bytes) FAILED peer=73
```
while they've defined theirs as
```

static const int PROTOCOL_VERSION = 70100;

//! initial proto version, to be increased after version/verack negotiation
static const int INIT_PROTO_VERSION = 209;

//! In this version, 'getheaders' was introduced.
static const int GETHEADERS_VERSION = 31800;

//! disconnect from peers older than this proto version
static const int MIN_PEER_PROTO_VERSION = 70100;
```
Can we have a way to override the broadcast version via the Network config class?

**Comment by NicolasDorier** [comment]
Yes, when you connect you can pass the NodeConnectionParameters which allow you to decrease the node requirement.

**Comment by Kukks** [comment]
Just saw it now, that would work however their is a limitation imposed by
`ProtocolVersion` being an enum. Can I open a PR to convert it a regular
class and make its predefined values as static readonly properties?
ᐧ

**Comment by nopara73** [comment]
@Kukks That's problematic, because it may break existing softwares. Eg. someone types ProtocolVersion.Whatever, it'll still work, but it'll be a class instead of enum, which will work mos of the time, but what if there are casting or typeof check in softwares running on top of NBitcoin? Then it'll silently change and may break software.  

Since this is not Bitcoin related, I'd not like to see such change. I think you should either make sure to completely break existing softwares, so syntax error is thrown or work around it somehow.

**Comment by Kukks** [comment]
Agreed @nopara73, let me experiment a bit

**Comment by Kukks** [comment]
The change does have some warrant of change for bitcoin though. For example a protocol bump restriction being applied to mainnet before anyone available is able to update NBitcoin forcing people to use forks instead. 
Still a breaking change is a big deal so I'll see if there is a way around it.

**Comment by Kukks** [comment]
@nopara73 I'm trying out this route:
https://github.com/MetacoSA/NBitcoin/compare/master...Kukks:feature/protocolversion

Essentially I created a struct with implicit conversion operators for `uint` and `ProtocolVersion` so that the new struct instance can be used as  `uint` and `ProtocolVersion`. 

I'll see what the limitations are of this approach and if anything would break later.

**Comment by nopara73** [comment]
Oh well, concept ACK, I don't want to be too nit-picky. @NicolasDorier will make the final decision of course.

**Comment by nopara73** [comment]
@NicolasDorier In sum: it's not Bitcoin related:

> I'm attempting to integrate some other coins with NBitcoin, however these coins have a different protocol version and have also implemented a minimum version check which kicks off connecting to their node.

**Comment by NicolasDorier** [comment]
I don't understand the problem: It is possible to broadcast any version you want as well as accept any minimum version you want already.

**Comment by Kukks** [comment]
You're right @NicolasDorier  We can easily override the protocol version even though it's an enum. I will open a PR on NBXplorer to allow us to specify the protocol version though.
