### ISSUE TITLE
Change Address is ignored

### ISSUE THREAD

**Issue by mjwaddell** [MetacoSA/NBitcoin#343]
I'm using the following code to create a transaction:
            TransactionBuilder bldr = new TransactionBuilder();
            bldr.AddKeys(secret);
            var PublicFromKey = secret.GetAddress();
            //calc balance, calc fee, AddCoins .......

            bldr.Send(ToAddr, Money.Satoshis(SendAmt));
            bldr.SetChange(PublicFromKey.ScriptPubKey, ChangeType.All);
            bldr.SendFees(Money.Satoshis(fee)); 
            Transaction tx = bldr.BuildTransaction(true);

The raw tx has only one output. The change address is ignored and most of the bitcoin goes to the fee, leaving a zero balance. Note that I've also tried using a separate change address with the same result.

Why is SetChange ignored?

Thanks
Mike

**Comment by NicolasDorier** [comment]
Yes it happens when the output is so small that it has been stripped from the transaction and attached to fees. This is done to ensure your transaction get propagate through the network.

You can disable this with `TransactionBuilder.DustPrevention=false;` but it is unadvised.

**Comment by mjwaddell** [comment]
I made the change, but there is still only one output. Here are the values in Satoshis:

Balance = 32500000   SendAmt = 10000    Fee = 1017     Total Send = 11017      Change = 32488983

In the raw tx (tx.ToString), I see only one output:
{{
  "hash": "d00c4cfda30a8e7ae60b24601bcb5da8ab812a362ea8aa82f890272af14c0efa",
  "ver": 1,  "vin_sz": 1,  "vout_sz": 1,  "lock_time": 0,  "size": 190,
  "in": [ {
      "prev_out": { 
"hash": "90b28320873133243f7962507b2339da019a631b7dd8fd7e7217ace6e70a6103",  "n": 0  },
      "scriptSig": "304502............"
    } ],
  **"out": [ {
      "value": "0.00010000",
      "scriptPubKey": "OP_HASH160 a9974100aeee974a20cda9a2f545704a0ab54fdc OP_EQUAL"
    } ]**
}}

Am I doing something wrong? 

Thanks
Mike

**Comment by mjwaddell** [comment]
Found the problem. When I created the coin object, I only specified the amount needed for the transaction. The full coin amount must be specified for SetChange to work correctly.

Thanks for your help.
