### ISSUE TITLE
Default RegTest port changed in Bitcoin 0.16

### ISSUE THREAD

**Issue by nopara73** [MetacoSA/NBitcoin#348]
https://github.com/bitcoin/bitcoin/pull/10825

I am not really sure how to tackle this. This'll break a bunch of software test and devs will be looking for what's going on for hours (like me.)  

Of course, the easiest solution is to change it silently, like Core devs did. Any ideas?

**Comment by NicolasDorier** [comment]
shit :/

**Comment by NicolasDorier** [comment]
I think yes the best is to change the default port used by NBitcoin as well.... that suck but well....
