### ISSUE TITLE
Need help creating a local indexed chain

### ISSUE THREAD

**Issue by oldbaker** [MetacoSA/NBitcoin#352]
Need help creating a local scanned repository using https://github.com/MetacoSA/NBitcoin/blob/master/NBitcoin/CachedNoSqlRepository.cs

https://stackoverflow.com/questions/41027747/query-local-bitcoin-blockchain-with-c-sharp-net

**Comment by NicolasDorier** [comment]
What do you want to do exactly? There are many way to scan, the way to choose depends on your end goal.

**Comment by nopara73** [comment]
Take a look at our IndexBuilderService: http://github.com/nopara73/MagicalCryptoWallet/Services/IndexBuilderService.cs
