### ISSUE TITLE
What is new about version  4.0.0.59?

### ISSUE THREAD

**Issue by bazooka70** [MetacoSA/NBitcoin#353]
Sorry for the noob question: What is new about version 4.0.0.59?
Is there a history log for this project somewhere I missed?
Thanks :)

**Comment by nopara73** [comment]
Bitcoin Core 0.16.0.

**Comment by NicolasDorier** [comment]
if you run `git log` you will see where the tags are placed and see which commit got included. But yeah, basically 0.16.0 changes.

**Comment by bazooka70** [comment]
Thanks all!
