### ISSUE TITLE
Issue serializing tx for offline signing

### ISSUE THREAD

**Issue by mjwaddell** [MetacoSA/NBitcoin#354]
I need to sign a transaction offline. When I use the tx.ToHex() and Transaction.Parse(), I think some coin data is getting lost:

 ```
// .... do all build steps here online except adding secret key

Transaction tx = bldr.BuildTransaction(false); // build tx, don't sign
WriteTextFile(tx.ToHex()); // serialize
```
 ```
// ..... go offline (separate machine)

bldr = new TransactionBuilder();
bldr.ContinueToBuild(Transaction.Parse(ReadTextFile()));  // deserialize
bldr.AddKeys(new BitcoinSecret(".... MySecretKey ....")); // add private key
tx = bldr.BuildTransaction(true); //build and sign - Why is tx scriptSig empty?

// ..... serialize tx again for broadcast online .....
```

If I sign the Tx before ToHex(), the scriptSig field is populated, but signing after ToHex\Parse doesn't work. My current workaround is to serialize the coins then re-add them offline, but that step should be unnecessary. Is there another step I need to do before calling ToHex ?

Also - Is there a way to serialize\deserialize transactions using JSON format? Tx.ToString() shows JSON, but I don't see any way to read it.

**Comment by NicolasDorier** [comment]
The coins are not serialized inside the transaction. Your workaround is the correct approach. (There are JsonConverter in the NBitcoin project to make it easy to serialize the Coins in JSON)

You should use `tx.ToHex()` and `new Transaction(string hex)` to roundtrip transactions. JSON representation are only useful for debugging purpose.
