### ISSUE TITLE
NodeBehavior AttachCore on RegTest never gets hit

### ISSUE THREAD

**Issue by nopara73** [MetacoSA/NBitcoin#358]
I have class (MempoolBehavior) that inherits from NodeBehavior and it works perfectly on mainnet and testnet, but on RegTest, it doesn't get the messages.  

I'm using your NodeBuilder to create the node, then add them to a NodesGroup like this:

```cs
nodesGroup.ConnectedNodes.Add(regTestNode.CreateNodeClient());
nodesGroup.Connect();
```

The problem: the overridden AttachCore never gets hit (neither invs arrive): `protected override void AttachCore()`.  

However things like `nodesGroup.ConnectedNodes.First().GetBlock` works fine.  

I'm stuck on this. Any hints what should I look for? Maybe such NodeBehavior also requires an `AddressManagerBehavior` to be added to the `connectionParameters.TemplateBehaviors`? Which similarly doesn't work though.

**Comment by NicolasDorier** [comment]
wait never use `nodesGroup.ConnectedNodes.Add` this is not done for this.

**Comment by NicolasDorier** [comment]
`NodesGroup` is responsible for connecting.

**Comment by NicolasDorier** [comment]
Take a look at [this](https://github.com/dgarage/NBXplorer/blob/master/NBXplorer/BitcoinDWaiter.cs#L360).

This will correctly reconnect your group if your node is temporarily offline.

**Comment by nopara73** [comment]
# 1. Thank you

I may did not understand exactly what you meant, but I solved the problem by removing the `NodesGroup` and its pals altogether and manually doing the node stuff:

```cs
Node node = SharedRegTestNode.CreateNodeClient();
node.Behaviors.Add(new MemPoolBehavior(memPoolService));
node.VersionHandshake();  
```

# 2. Note

> wait never use `nodesGroup.ConnectedNodes.Add` this is not done for this.

I don't do it here anymore, but I do it at one other place, where I need to test my block downloader with the `RegTest` and my block downloader class wants a `NodesGroup` in the constructor (so to simulate I add my local regtest node manually in the way you advise against.) It's not production, but unit testing. That's fine, isn't it?

# 3. Question

I see you add `new PingPongBehavior()`, should I do that, too? What does it do? Does it make a difference?

**Comment by NicolasDorier** [comment]
Don't use manual node connection, it won't reconnect automatically, check https://github.com/dgarage/NBXplorer/blob/master/NBXplorer/BitcoinDWaiter.cs#L360 instead.

**Comment by NicolasDorier** [comment]
PingPongBehavior is to reply and send ping pong message to the node. If you don't respond to pong, the node will drop connection.
I am adding this by default though so you never knew it.
