### ISSUE TITLE
What is the final exact fee that will be used by TransactionBuilder in the blockchain?

### ISSUE THREAD

**Issue by bazooka70** [MetacoSA/NBitcoin#360]
I have this code:

```
var fallbackFeeRate = new FeeRate(Money.Satoshis(100), 1);
var feeRate = client.GetFeeRate(6, fallbackFeeRate).FeeRate;

var builder = new TransactionBuilder();
var tx = builder
  .AddCoins(coinsToSpend)
  .AddKeys(signingKeys.ToArray())
  .Send(addressToSend, amountToSend)
  .SetChange(changeScriptPubKey)
  .SendEstimatedFees(feeRate)                                                
  .BuildTransaction(true);

bool builderVerify = builder.Verify(tx);
```
All is good. transaction signed and verified. 

Now, what is the final **exact** fee (and size) that will be used by TransactionBuilder, before I broadcast it?

I see 
`tx.GetFee(coins)`
and 
`feeRate.GetFee(tx)`

But they are slightly different.
And the size is `builder.EstimateSize(tx)`?

My objective is to show the real transaction fee and size before the transaction is broadcast, same as in Bitcon Core (where it will **initially** show the estimated fee per KB, and then the actual fee that would be used)

Thanks in advanced

**Comment by NicolasDorier** [comment]
Just use 

```
var fee = tx.GetFee(builder.FindSpentCoins(tx));
```

**Comment by bazooka70** [comment]
Just to be sure I call
var fee = tx.GetFee(builder.FindSpentCoins(tx));
**after** the transaction is build `.BuildTransaction(true)` **AND** Verified?

**Comment by NicolasDorier** [comment]
Yes

**Comment by NicolasDorier** [comment]
and the transaction is signed.

**Comment by nopara73** [comment]
To be fair, this is very common Bitcoin programmer dilemma.

1. You don't know the transaction fee until you build the transaction.
2. But you cannot build the transaction until you know the transaction fee.

Think about it.

**Comment by bazooka70** [comment]
Thanks for explaining.

> Think about it.
I am thinking about this for over a week now... Its kinda complicates the whole process of sending funds.
To get the real transaction fee, I need the **private** keys which is kind of a bummer.
blockchain.info display the final transaction fees **before** they broadcast it, so they must be knowing the private keys in advanced.

other wallet providers show estimated fees **per KB** - this might not be an easy to understand for the common wallet holder since he/she/it might think the fee is too high... it a real pain in the ass if you coe to think about it  :/

How about the final transaction **size**?

**Comment by NicolasDorier** [comment]
@bazooka70 you have `TransactionBuilder.EstimateSize` worth mentioning that you have 2 types of size in bitcoin: Real Size and Virtual Size. Virtual size is used for fee calculation and discount segwit bytes.

**Comment by bazooka70** [comment]
@NicolasDorier , But you have the final HEX of the transaction, which you actually product. isn't the HEX block represents exactly what the final transaction size is?

**Comment by NicolasDorier** [comment]
Yes, you can get it with `tx.GetSerializedSize()`, but this is not what is used for fee calculation. Fee calculation is using `tx.GetVirtualSize()`.

**Comment by NicolasDorier** [comment]
If you want to know what the virtual size will be before building the transaction then you need to use `TransactionBuilder.EstimateSize`.

**Comment by NicolasDorier** [comment]
There is simply no way to know what will be the transaction size exactly before it is actually signed.
The `TransactionBuilder` with `EstimateSize` is however around 1% near.

**Comment by bazooka70** [comment]
@NicolasDorier, Yes i realize that. I want the size **after** it is signed.

**Comment by NicolasDorier** [comment]
```
Yes, you can get it with tx.GetSerializedSize(), but this is not what is used for fee calculation. Fee calculation is using tx.GetVirtualSize().
```

**Comment by NicolasDorier** [comment]
There is two kind of size, I already gave you above how to get both of them.

**Comment by bazooka70** [comment]
@NicolasDorier , OK, Many thanks! :+1:

**Comment by bazooka70** [comment]
@nopara73 
I'm kinda lost at how _blockchain.info_ display the **real** Fee (not in KB) before any amount is even specified (0 BTC) and the size is unknown yet.

The real Fee keeps changing while I change the amount (based on "regular" or "priority" fee rate).

Do they divide the estimated fee per KB by a constant factor on 1 input (or 2 or 3? - how do they know?) and 2 outs (lets say a 256 bytes)?

What could be the analog of doing the same in NBitcoin?

**Comment by NicolasDorier** [comment]
I guess without amount they just assume your transaction have a fixed size.

The "regular"/"priority" configure the number of block you expect to be. 

NBXplorer give you a parameter to specify this. (20 blocks target would be low priority)

**Comment by sigHash** [comment]
> Just use
> 
> ```
> var fee = tx.GetFee(builder.FindSpentCoins(tx));
> ```
> This are the real fees.
> 
> The estimated and the real fee are different because it is near impossible to know the fees before having signed, but to sign you need the fees... So the transaction builder is internally trying to do its best so the two match, but they might be a bit different.

How about calculating fee for a successfully published transaction from its txHex?

I do:

```
var tx = Transaction.Parse(txHex, network.NBitcoinNetwork);
var noBuilder = network.NBitcoinNetwork.CreateTransactionBuilder().ContinueToBuild(tx);
var spentCoins = noBuilder.FindSpentCoins(tx);
 var fee = tx.GetFee(spentCoins);
```

and spentCoins returns null coins.

**Comment by NicolasDorier** [comment]
You can't you need to fetch the parent transaction's output.

**Comment by sigHash** [comment]
Perhaps something like this:
```
private async Task<Money> CalculateTransactionFeeAsync(Transaction transaction, BTCPayNetwork network)
        {
            Dictionary<uint256, Transaction> parentTransactions = new Dictionary<uint256, Transaction>();
            var parentHashes = transaction.Inputs.Select(i => i.PrevOut.Hash).ToHashSet();
            var explorer = ExplorerClientProvider.GetExplorerClient(network);
            var getTransactionAsyncs = parentHashes.Select(h => (Op: explorer.GetTransactionAsync(h), Hash: h)).ToList();
            foreach (var getTransactionAsync in getTransactionAsyncs)
            {
                var tx = (await getTransactionAsync.Op);
                if (tx == null)
                    throw new Exception($"Parent transaction {getTransactionAsync.Hash} not found");
                parentTransactions.Add(tx.Transaction.GetHash(), tx.Transaction);
            }

            Money totalIn = Money.Zero;
            foreach (var txIn in transaction.Inputs)
            {
                var output = parentTransactions[txIn.PrevOut.Hash].Outputs.AsIndexedOutputs().Where(io => io.N == txIn.PrevOut.N).FirstOrDefault();
                totalIn = totalIn + output.TxOut.Value;
            }

            return (totalIn - transaction.TotalOut);
        }
```

**Comment by NicolasDorier** [comment]
just use

```csharp
var tx = Transaction.Parse(txHex, network.NBitcoinNetwork);
var allParentCoins = parentTransactions.Values.SelectMany(p => p.Outputs.AsCoins());
 var fee = tx.GetFee(allParentCoins);
```
