### ISSUE TITLE
Are there any plans to support Bitcoin cash or Bitcoin gold?

### ISSUE THREAD

**Issue by bazooka70** [MetacoSA/NBitcoin#361]
Are there any plans to support Bitcoin Cash (Bitcoin ABC) or Bitcoin gold (BTCGPU)?
Seems like they both are close relatives (and forks?) of Bitcoin Core,

**Comment by NicolasDorier** [comment]
If their dev do the work yes. But both project lacks developers.

**Comment by NicolasDorier** [comment]
Closing this. Supporting BCH and BTCG is easy, but I won't do the work for them freely.
