### ISSUE TITLE
You must set the RNG (RandomUtils.Random) before generating random numbers

### ISSUE THREAD

**Issue by AStarBoy** [MetacoSA/NBitcoin#362]
when i “Key key = new Key();”，it throw an exception You must set the RNG (RandomUtils.Random) before generating random numbers，what‘s wrong？

**Comment by NicolasDorier** [comment]
You are using an old version of visual studio and create a project .NET 4.5

Please use 4.5.2 at least.

**Comment by AStarBoy** [comment]
Ok，it works，thanks for NicolasDorier very much！
