### ISSUE TITLE
Can not get balance of HD Wallet from BitcoinExtPubKey

### ISSUE THREAD

**Issue by nhutcmos** [MetacoSA/NBitcoin#364]
I tried alot of way to get the balance of HDWallet with QBitNinjaClient
My code as below for some test, could you please help to point it out for the correct one? Thanks
`BitcoinExtPubKey BIP32ExtendedPubKey = hdRoot.Neuter().GetWif(Network.TestNet); 
var client = new QBitNinjaClient(Network.TestNet);
            var result = client.GetBalanceSummary(BIP32ExtendedPubKey).Result;
            var test = client.GetWallet("tpubD94Jz5t82qma5VYXHkg3tbWKHVPFbhUmrhB1sK6TwghpAyDLiej1i7bLmaee7Rfx2qDVzQuzst2MgrZ9WcLvkgePmXBJ6oq1ETYXhkNVjX5").Result;
            var test2 = client.GetBalance("tpubD94Jz5t82qma5VYXHkg3tbWKHVPFbhUmrhB1sK6TwghpAyDLiej1i7bLmaee7Rfx2qDVzQuzst2MgrZ9WcLvkgePmXBJ6oq1ETYXhkNVjX5").Result;

            var walletName = Guid.NewGuid().ToString().Replace("-", "").Substring(0, 10);
            var keysets = client.Send<HDKeySet>(HttpMethod.Post, null, "wallet/"+walletName+"/keysets", new HDKeySet()
            {
                Name = "SingleNoP2SH",
                ExtPubKeys = new BitcoinExtPubKey[] { BIP32ExtendedPubKey },
                P2SH = false
            }).Result;
            var balance = client.GetBalance(walletName);
            var walletinfo = client.GetWallet(walletName);
            var postresult = client.Post<BalanceModel>("wallet/" + walletName + "/balance", new HDKeySet()
            {
                Name = "SingleNoP2SH",
                ExtPubKeys = new BitcoinExtPubKey[] { BIP32ExtendedPubKey },
                P2SH = false
            }).Result;
            var keyset = client.Send<KeySetData>(HttpMethod.Get, null, "wallets/" + walletName + "/keysets/SingleNoP2SH");`

**Comment by NicolasDorier** [comment]
Hey, this is a bit outdated way of doing, please prefer [the following way](https://programmingblockchain.gitbooks.io/programmingblockchain/content/wallet/web-api.html) which depends on this [blockexplorer](https://github.com/dgarage/NBXplorer). You will need a full node though.

**Comment by nhutcmos** [comment]
Thank you for your update. I will check it out.

**Comment by NicolasDorier** [comment]
If you have questions on NBXplorer, come on gitter or open issues on NBXplorer.
