### ISSUE TITLE
NBitcoin Test Framework

### ISSUE THREAD

**Issue by lontivero** [MetacoSA/NBitcoin#365]
As a developer that uses NBitcoin many times I need to deploy an short-live network of nodes in regtest in order to test different things. NBitcoin test library has the NodeBuilder class and others to achieve exactly that but it is not released as an reusable library or package.

My suggestion (or feature request) is to have the NBitcoin Test Framework available as a nuget package in order to make it easy for the rest to use. I think it could add even more value to the NBitcoin ecosystem.

**Comment by NicolasDorier** [comment]
It is, NBitcoin.TestFramework (it is normally more advanced than the Test project though) https://nuget.org/packages/NBitcoin.TestFramework

**Comment by lontivero** [comment]
I didn't know it. Awesome!
