### ISSUE TITLE
Key.PubKey NullReferenceException

### ISSUE THREAD

**Issue by GSPP** [MetacoSA/NBitcoin#367]
There seems to be a bug with `key.PubKey`:

```
var key = new Key(Encoders.Base58.DecodeData("JEKNVnkbo3jma5nREBBJCD7MJVUPAg5THBwPPejEsG9v"));
Console.WriteLine(key.PubKey); //NullReferenceException
```

As a library user I'd have expected `new Key(...)` to throw if invalid data is provided. If that is not feasible `Key.PubKey` should not crash with a forbidden exception type.

**Comment by nopara73** [comment]
Isn't that a testnet Bitcoin address you want to parse as a key?

**Comment by knocte** [comment]
In .NET it's impossible that the result of calling a constructor is null. Are you sure your sample is correct? Maybe your original code has a try-catch block that you missed when pasting here.

**Comment by nopara73** [comment]
@knocte The property is null, not the `key`: the `PubKey`.

**Comment by nopara73** [comment]
@GSPP By the way this is the correct way of doing what you want:

`var key = Key.Parse("JEKNVnkbo3jma5nREBBJCD7MJVUPAg5THBwPPejEsG9v");`

And it throws this:

`System.FormatException Invalid string`

And so figured it's indeed not a valid key (as I suspect, it's a testnet address.)

Yet, it'd be nicer if format exception would be thrown when calling `new Key(bytes)` too.

**Comment by knocte** [comment]
> The property is null, not the key: the PubKey.

Mmm, what? Console.WriteLine() can print a null string without problems without throwing NullReferenceException, do the test ;-)

**Comment by nopara73** [comment]
@knocte Indeed, I know what you mean. The trick is, the `PubKey` is more like a function than a property 😄 

```cs
public PubKey PubKey
{
	get
	{
		if(_PubKey == null)
		{
			ECKey key = new ECKey(vch, true);
			_PubKey = key.GetPubKey(IsCompressed);
		}
		return _PubKey;
	}
}
```

**Comment by knocte** [comment]
Ah, fuck! didn't think about this, of course.

But if that's the implementation of PubKey property, it cannot throw NRE, unless GetPubKey() function can throw a NRE?

**Comment by knocte** [comment]
Oh, the ECKey() ctor could throw as well. Even if what @GSPP could be done in a better way, I think this is a valid report that should be fixed. NREs are always bugs.

**Comment by nopara73** [comment]
There are two issues here:

1. Properties should rarely, preferably never throw exceptions.
2. `new Key(bytes)` should throw a format exception just like Key.Parse does.

**Comment by NicolasDorier** [comment]
This is a bug, Pubkey should never be null.

**Comment by NicolasDorier** [comment]
Ha interesting, I thought all 32 bytes could be a private key, but this is not the case ?!

**Comment by NicolasDorier** [comment]
Wow, `JEKNVnkbo3jma5nREBBJCD7MJVUPAg5THBwPPejEsG9v` is actually the N parameter of the curve.

**Comment by NicolasDorier** [comment]
Ok so it was a bug, NBitcoin was not checking correctly if the Key was valid.
