### ISSUE TITLE
How to get balance of all derived ExtPubKey at once?

### ISSUE THREAD

**Issue by ArtjomP** [MetacoSA/NBitcoin#372]
I generate public addresses the next way:
`
var mnemonic = new Mnemonic(mnemonicStr);
var extPrivateKey = mnemonic.DeriveExtKey(passphrase);
var extPubKey = extPrivateKey.Neuter();
`
**var bitcoinPubAddress = extPubKey.Derive(counter++).PubKey.GetAddress(Network.TestNet);**

And now I can get balance only separately for every derived ExtPubKey. Something like this:
`
var client = new QBitNinjaClient(network);
`
**var bitcoinAddress = extPubKey.Derive(counter).GetAddress(Network.TestNet);
var balanceModel = await client.GetBalance(bitcoinAddress, true);**
`
var unspentCoins = new List<Coin>();
foreach (var operation in balanceModel.Operations)
      unspentCoins.AddRange(operation.ReceivedCoins.
                        Select(coin => coin as Coin));
var balance = unspentCoins.Sum(x => x.Amount.ToDecimal(MoneyUnit.BTC));
`

Is there is an option to get balance for any derived ExtPubKeys? 
Or should I know my **counter** and manually get balance for every ExtPubKey up to the **counter**?

And about spending.
Will I be available to sign a transaction with my root extPrivateKey for coins sent to a derived ExtPubKey or I should derive the same (by the counter) ExtKey?

By the way how they get all transactions for a root ExtPubKey [get transactions for delivered keys](https://blockchain.info/xpub/xpub6CUGRUonZSQ4TWtTMmzXdrXDtypWKiKrhko4egpiMZbpiaQL2jkwSB1icqYh2cfDfVxdx4df189oLKnC5fSwqPfgyP3hooxujYzAu3fDVmz)

Sorry for the long post & thank you in advance

**Comment by NicolasDorier** [comment]
@ArtjomP no, there is no way to get balance for any derived ExtPubKey.

> Or should I know my counter and manually get balance for every ExtPubKey up to the counter?

Yes.

This approach though does not scale very well as you may imagine.

This is why I created [NBXplorer](https://github.com/dgarage/NBXplorer). It easily allow you to track a extpubkey with very simple API. (it has a nuget package for the client part)

The only downside is that you need a full node.

**Comment by NicolasDorier** [comment]
Here is a code sample of [NBXplorer](https://programmingblockchain.gitbooks.io/programmingblockchain/content/wallet/web-api.html) usage.

**Comment by ArtjomP** [comment]
Thank you!
One more question please:
Will I be available to sign a transaction with my root extPrivateKey for coins sent to a derived ExtPubKey or I should derive the same (by the counter) ExtKey?

**Comment by NicolasDorier** [comment]
Yes. NBXplorer basically tells you for each coin what is the `KeyPath` of the child key which is needed to sign. So only the root key is needed.

**Comment by NicolasDorier** [comment]
The full API description is [here](https://github.com/dgarage/NBXplorer/blob/master/docs/API.md). Everything is implemented in the `NBXplorer.Client` nuget package.

You also have websocket notifications for payments.
