### ISSUE TITLE
CI for Linux & OSX

### ISSUE THREAD

**Issue by lontivero** [MetacoSA/NBitcoin#373]
@NicolasDorier I'm working on adding CI with Travis for Linux. Currently I have only a few failing tests that I would like to "fix". Three of those failing tests depends on the `libbitcoinconsensus.so` consensus library. Could you upload that file (for linux and osx, of course) to your https://aois.blob.core.windows.net/public/libbitcoinconsensus/ site?

It would be good if you host the files in an url such that it can be built dinamically, similar to:
https://aois.blob.core.windows.net/public/libbitcoinconsensus/{libraryVersion}/{0peratingSystem}/{environment}/libbitcoinconsensus{extention}

**Comment by NicolasDorier** [comment]
I think those should be downloaded from bitcoin core website really.
If I remember I did something clean with NBitcoin.TestFramework which download the right bitcoin core depending on the runtime. I think that the .so/.dll is in the folder.

A good solution might be to port this.

**Comment by nopara73** [comment]
You could also have the pubkey uploaded to GitHub and check against that. This way an attacker would have to compromise both bitcoin.org and NBitcoin GitHub repo.

**Comment by lontivero** [comment]
That's unnecesary because we can use the HASH256SUMS.asc file to verify the downloaded bitcoin core node's integrity. Take into account that that file is PGP signed so, we download the HASH256SUMS.asc file and verify it is authentic. 

Those devs that want to be sure they are downloading the right binaries just have to verify the PGP signed file that contains the hashes.
