### ISSUE TITLE
Two ideas for verifying authenticity of downloaded files

### ISSUE THREAD

**Issue by lontivero** [MetacoSA/NBitcoin#374]
I would like to share two ideas:

1) Looking at the code I can see we `check the consensus library file hash` against the correct ones that are hardcoded, that is the correct thing to do. However, if we upload new versions of the consensus library, every time you upload a new version you have to modify the code (i know that that is something that doesn't change often). I think a better approach would be that we `digitally sign the files and validate it with Nicolas's public key` in the code. In that way we don't need to hardcode the hashes and change them when new versions are uploaded

2) The `NodeBuilder` downloads the bitcoin core node zip file and doesn't perform any authenticity verification, that means developers could download and run fake bitcoin core nodes. This is not very crazy IMO. We could verify the authenticity of the files here too.

What do you think?

**Comment by NicolasDorier** [comment]
I saw your approach in the other PR of just using the SHASUM256 file hashes of the packages. This is just perfect!
