### ISSUE TITLE
Lighting Network

### ISSUE THREAD

**Issue by spegase** [MetacoSA/NBitcoin#376]
Hi Nicolas,

Do you plan an integration with the Lighting Network? 

I'm using your great lib in my projects!

**Comment by nopara73** [comment]
I think @NicolasDorier is planning it. I am planning it myself, too. It's just we are busy with other stuff at the moment.

But it also worth defining what "integration with the Lighting Network" means. I think there are two ways to do this:

1. Implement a client that connects to a lightning daemon, it'd be equivalent to the `RPCClient` class, which is connecting to Bitcoin Core's daemon. Today `lnd` is considered to be the most stable LN daemon. Yesterday `lnd` launched on the mainnet. That being said, a month ago I played around with it and it was terribly buggy. Nevertheless you can do this work yourself easily.
2. Implement the Lightning Primitives.

**Comment by NicolasDorier** [comment]
I think integration with LN would be done in a separate repository. But yeah today I have not started working on it.

**Comment by NicolasDorier** [comment]
I have done some of this work inside BTCPay I may extract it into reusable lib once it stabilize.
