### ISSUE TITLE
Fee is heigher than blockchain.info,I am using rpcClient.GetFee()

### ISSUE THREAD

**Issue by AbhinavJKJ** [MetacoSA/NBitcoin#380]
Hi Nic,How are you?
I am little bit confused of how to calculate fee rate as we are currently calculating it by 
rpcClient.GetFee() method but it is giving high rate than blockchain.info site,Please suggest what could I use? My client complaining the below problem.

" I have compared our fees with blockchain.info and we are charging more than them . They don’t even have Segwit implemented,
Like for a transaction of 0.0028 we are charging 0.00003939 for express fee and 0.00007679 for standard fee. Blockchain.info charging .00001130 for same transaction"

Thanks,
Abhinav Kumar

**Comment by NicolasDorier** [comment]
hey, use `rpcClient.EstimateSmartFeeAsync`, it allows you to configure in how much block you expect to be confirmed, and has two mode, conservative and non conservative.

**Comment by AbhinavJKJ** [comment]
Thanks for so much fast reply :)
So for using rpcClient.EstimateSmartFeeAsync what needs to be changed, i.e i have to update anything?
And "**it allows you to configure in how much block you expect to be confirmed, and has two mode, conservative and non conservative."** this point is not clear.

**Comment by AbhinavJKJ** [comment]
Thanks,
One thing i am not clear,Is Segwit also reduces fee cost OR just for separating the signature part to prevent from malleability?

**Comment by NicolasDorier** [comment]
@AbhinavJKJ yes segwit reduce cost. This call send back a feeRate on the amount of "virtual bytes" of a transaction. A transaction spending segwit ouptuts has a lower "virtual size" than a normal transaction.

If you use the TransactionBuilder with `SetEstimateFees(feeRate)`, then this is all calculated for you.

**Comment by AbhinavJKJ** [comment]
Ohk thanks,
So SetEstimateFees(feeRate) will automatically deduce the fee cost?
Actually in our scenario we are calculating two rates one is standard and another one is Express by looping through blocks on rpcClient,And on transaction building process,I am passing the selected one by user.
I will try the suggested way and let you know,Is it working or not,Actually one day i checked with rpcClient.EstimateFee but it was unresponsive,Do you have any idea why it happened?

**Comment by NicolasDorier** [comment]
`EstimateFee` is depcrecated by core now. So use `EstimateSmartFee`, map the user choose to a `confirmationTarget`. (Express = 1, Normal = 6)

Then pass this feeRate to the transactoinBuilder with `SetEstimatedFees(feeRate);`.

**Comment by AbhinavJKJ** [comment]
Hi nic,

I have not applied this yet because of some more other task but i will try to apply it soon and let you know if i am getting any difficulty into that so thanks for your support.

**Comment by NicolasDorier** [comment]
Reopening, please close if it fixes your issue.

**Comment by AbhinavJKJ** [comment]
Thanks for reopening,really appreciable support from you 😊

**Comment by NicolasDorier** [comment]
got fixed?

**Comment by nopara73** [comment]
@AbhinavJKJ 
For the record, conservative will give you higher feerate, economical will give you lower. This is used in Bitcoin Core that, when you make an RBF-able transaction, it will do economical fee estimation, if you don't make it RBF-able, then it'll do conservative fee estimation.

**Comment by AbhinavJKJ** [comment]
Nic, when i tried to apply it,its giving an error for mnemonic code that is being used for HD wallet, currently i am just figuring out,there are some dll error, today is my holiday, i will ask if this error will not got fixed.

Thanks
Abhinav

**Comment by AbhinavJKJ** [comment]
Hi Nic,
For EstimateSmartFeeAsync  method i used NBitcoin latest version(4.1.0.13) but its throwing error with (ExtKey masterKey = new ExtKey();) ,Screenshot is attached.

I just stucked here cant understand why its coming.

Please help.

Thanks,
Abhinav Kumar
![errorwithlatestbitcoindll](https://user-images.githubusercontent.com/21276445/40194576-8798891c-5a28-11e8-89c6-37fe95d97eb1.PNG)

**Comment by AbhinavJKJ** [comment]
Hi Nic,

Did you get chance to look into above posted problem?

Thanks,
Abhinav Kumar

**Comment by NicolasDorier** [comment]
@AbhinavJKJ sorry for late reply, I was quite sick. Are you referencing NBitcoin from Nuget? and if yes, check you are using 4.5.2 at least. 4.5 is not supported.

**Comment by AbhinavJKJ** [comment]
No problem Nic, please take care of yourself,
I am using 4.1 from nuget this is latest one i got from there,now more releases has introduced? Ok let me check that and let you know. 

Thanks, 
Abhinav

**Comment by NicolasDorier** [comment]
I mean the .net version of the project you created. Can you paste here the content of your csproj file?

**Comment by NicolasDorier** [comment]
Yes should be able to. I think you should try visual studio 2017 it is quite cool.

**Comment by AbhinavJKJ** [comment]
Yes i am using that in one of my project, i will try this one as well. As there are many other dependencies as well so i will check with all that and let you know tomorrow.😊

Thanks,
Abhinav Kumar

**Comment by AbhinavJKJ** [comment]
Hi Nic,

I have upgraded the project and its successfully resolved one problem now other problem arouse its just getting stuck on var feerate=rpcClient.EstimateSmartFee(4,samrtfeeoptions.Economical).
Any suggestion why this new one? 

Thanks,
Abhinav Kumar

**Comment by NicolasDorier** [comment]
what do you mean by getting stuck

**Comment by AbhinavJKJ** [comment]
Means not responding when debugger come on that line of code

**Comment by NicolasDorier** [comment]
and without debugger does it throws an exception?

**Comment by NicolasDorier** [comment]
can you do

`var feerate = await rpcClient.EstimateSmartFeeAsync(4, SmartFeeOptions.Economical);`

And add `async` to the method calling this?

**Comment by AbhinavJKJ** [comment]
Ok i will try this and let you know .

**Comment by NicolasDorier** [comment]
strange, what `feeRate` are you receiving? what is your code?

**Comment by AbhinavJKJ** [comment]
Hi Nic,
Actually i am receiving approx 0.00000370 for 0.00100000 BTC value.
Below is the code:
      var rPCClientObject = new RPCClient(_credentials.UserName + ":" + _credentials.Password, new Uri(_coinParameters.SelectedDaemonUrl), _coinParameters.NetworkType);
                EstimateSmartFeeResponse fee = await rPCClientObject.EstimateSmartFeeAsync(6, EstimateSmartFeeMode.Economical);

  var moneyFee1 = transactionBuilder.EstimateFees(feeRate1);
 var result = objCustomTransactionHistory.TransactionBuilder.Verify(objCustomTransactionHistory.Tranasction, out errors);
and result is returning false and the errors value is "Fee too low, actual is 0.00000370, policy minimum is 0.00000612".

Thanks,
Abhinav

**Comment by NicolasDorier** [comment]
You can workaround this error with `transactionBuilder.StandardPolicy.CheckFee = false`.

However I will take a look I was not expecting that to happen.

**Comment by NicolasDorier** [comment]
Wait how do you get `feeRate1` ?

**Comment by AbhinavJKJ** [comment]
I am getting feerate1 through below method as per your suggestion:
EstimateSmartFeeResponse fee = await rPCClientObject.EstimateSmartFeeAsync(6, EstimateSmartFeeMode.Economical);

**Comment by AbhinavJKJ** [comment]
I have already used transactionBuilder.StandardPolicy.CheckFee = false;
and it resolved error but i think this is the problem with verify method,What you think? As per my understanding verify method is not verifying according to fee mode. 
There is one more strange problem came into the scenario when i brodcasted the transaction its not showing on blocktrail but its showing on btc.com and after one confirmation on btc.com it started showing on blocktrail as well. 
I workaround this and found that when i am using fee mode economical and block size 6 this scenario occuring but when i changed the fee mode to second type and decresed block size to 2 its not coming.
Please suggest why this is happening?
Please let me know if anything is not clear to you.

Thanks for your great support.

**Comment by NicolasDorier** [comment]
`fee` is different from `feeRate1` can you just show me the line where you affect?

**Comment by AbhinavJKJ** [comment]
Hi Nic,

Below is the whole method:
  public async Task<List<TransactionFeeRates>> TransactionFeeRates()
        {
            List<TransactionFeeRates> result = new List<TransactionFeeRates>();
            try
            {
                var rPCClientObject = new RPCClient(_credentials.UserName + ":" + _credentials.Password, new Uri("localhost:18332"), Network.Main);
                EstimateSmartFeeResponse fee = await rPCClientObject.EstimateSmartFeeAsync(6, EstimateSmartFeeMode.Economical);
                result.Add(new TransactionFeeType { Fee = Convert.ToString(fee.FeeRate).Replace("BTC/kB",string.Empty), FeeType = "Fee Rate" });
            }
            catch (Exception ex)
            {
                throw;
            }
            return result;
        }

And the  tx.ToHex() value is: 

0100000000010125660f319984e49c1018c087afa443b4df40391272a853e1d2c244811d4ba3a101000000232200202549bd1aae3ddf20365db062c812f40b4cf67bfb268b3919c2d393bcb6c2c37cffffffff02b0e100000000000017a91449dfb58e6586538c5d2b1b2705350b63c4cb6c0887a08601000000000017a914fe68bdcadde5d5c9fc036384fcdba1d8551b9e24870500473044022070434043ab80adabb10004dbc952034ed1d1b0a76b14ccdc83a83d0f8ef4e2b2022064343cc470bd76cc92abc317157d73f4229f32c2a1596ce99b59a95528718b0201483045022100f3800567a1e9b4c5a0eac838cee5a9570431dffb5894ffd3666da79bec7733bf0220512b25f6f2567cd043ea042557af34bb7da7026b280d0b8bd4118eb76317832601483045022100bb7ae144046fa5c6617ae6be8eb3780e12368a36075b0ea44a0deadf2bfd9d6302205ea8a283937eab64699da9aa8c477232e2cbb8413b4f70da88acc924a12dd04f0169532102905f69d5da7987d10535979b13d88427204b08f1373dbb4d70da350d773c77e221027881e05233d522ee3962fd7986ff96d6e856d0409b56ae963a0ec9a9f08d864a21024a647b0ed3b910225bf9c9f4f9df673f59914154b6d910d86b492ac093c904a153ae00000000

**Comment by NicolasDorier** [comment]
Do not do that.
```
result.Add(new TransactionFeeType { Fee = Convert.ToString(fee.FeeRate).Replace("BTC/kB",string.Empty), 
```
Transform your Fee property into a `FeeRate` type, don't use string. You are probably having a bug due to dodgy conversions.

**Comment by AbhinavJKJ** [comment]
Actually this is not being used here result list is just for showing in view means to the end user. 
In actual calculation its value is being used like feeRate1=0.00000367 in below:
var moneyFee1 = transactionBuilder.EstimateFees(feeRate1);
var result = objCustomTransactionHistory.TransactionBuilder.Verify(objCustomTransactionHistory.Tranasction, out errors);

**Comment by NicolasDorier** [comment]
Please tell me where you get `feeRate1` do not tell me it come from `EstimateSmartFee`  and show me where it comes from in code.

**Comment by AbhinavJKJ** [comment]
EstimateSmartFeeResponse fee = await rPCClientObject.EstimateSmartFeeAsync(6, EstimateSmartFeeMode.Economical);
feeRate1=fee.FeeRate;

**Comment by AbhinavJKJ** [comment]
feeRate1 is just a decimal value like 0.00000045
In above 
feeRate1 is being calculated by removing "BTC/kb" string from actual fee. FeeRate.

**Comment by NicolasDorier** [comment]
> feeRate1 is being calculated by removing "BTC/kb" string from actual fee. FeeRate.

Is not equivalent to 

> EstimateSmartFeeResponse fee = await rPCClientObject.EstimateSmartFeeAsync(6, EstimateSmartFeeMode.Economical);
feeRate1=fee.FeeRate;

**Comment by NicolasDorier** [comment]
so which one you use?

**Comment by NicolasDorier** [comment]
because if you do your strange string manipulation, this is a bug. You should not do this.

**Comment by NicolasDorier** [comment]
You need to do `txBuilder.SendEstimatedFee(fee.FeeRate)`

**Comment by AbhinavJKJ** [comment]
yes i did that (txBuilder.SendEstimatedFee(fee.FeeRate)) as well but same problem. I analyzed fee calculated as well by both way fee was coming same.

**Comment by AbhinavJKJ** [comment]
As per my understanding verify method is not synched with this fee mode,that may be the problem.

**Comment by NicolasDorier** [comment]
Can you tell me the value returned by `fee.FeeRate`.

**Comment by AbhinavJKJ** [comment]
Actually fee rate i not remembered but fee do,I can tell you fee rate when on my system  around 4 PM IST.
Actually i am receiving approx 0.00000370 for 0.00100000 BTC value. This is fee calculated through txBuilder.SendEstimatedFee(fee.FeeRate);

**Comment by NicolasDorier** [comment]
I need you do give me `fee.FeeRate` exactly.

**Comment by AbhinavJKJ** [comment]
Hi Nic,
How are you,hope you are well,Sorry for not replied your last comment.
You can close this ticket.
Thanks for your great support. 🥇 
Thanks,
AbhinavJKJ
