### ISSUE TITLE
Recursive BuildTransaction for change

### ISSUE THREAD

**Issue by dthorpe** [MetacoSA/NBitcoin#39]
Why does TransactionBuilder.BuildTransaction call itself recursively after the change amount has been determined?  The recursive call repeats the coin selection process, but (should) always arrive at the same result (same coin selection) as the first call.

**Comment by NicolasDorier** [comment]
@dthorpe do I close it ? it is gathering dust :p

**Comment by dthorpe** [comment]
It still seems redundant. In debugging through that fn, I've never seen it make any decisions that weren't already decided in the caller.  But, my code may not cover all the cases that fn is intended to cover.

**Comment by NicolasDorier** [comment]
Closing it, was opened 2 years ago, and not really an issue. :p
