### ISSUE TITLE
Can't parse litecoin mainnet extended address

### ISSUE THREAD

**Issue by mjwaddell** [MetacoSA/NBitcoin#390]
I'm using the following code to parse extended keys for Litecoin:
```NBitcoin.Altcoins.Litecoin.EnsureRegistered();
string LTCExtKeyTest = "tpubDDgVusZ6cnZ5uQGiDptUFuuchnRG6Hg9oPCheGTdrPpVicUZQGMwJmcmLUj5EKUz8hSkehqzBTSD1KogM3bLa8iHVTBV8RMd5XVTHjEZvJE";
var ky1 = Network.Parse<BitcoinExtPubKey>(LTCExtKeyTest, NBitcoin.Altcoins.Litecoin.Testnet); //okay

string LTCExtKeyMain = "Ltub2ZjyrGwSnwudsyMoN7uNurgUTTeArghEP2pP7o9bsyuJhhSez41ayySNTKAKNDvzw1KRdFifVPFYREgBs5qYXd3QizKe7aTRz4fPSCWXQrW";
var ky2 = Network.Parse<BitcoinExtPubKey>(LTCExtKeyMain, NBitcoin.Altcoins.Litecoin.Mainnet); //error - Invalid base58 string
```

The testnet address works correctly, but the mainnet address throws an error. I'm sure the mainnet address is valid. Is there an issue with the code?

**Comment by NicolasDorier** [comment]
The issue is that many wallet are using many different standard for parsing a ExtKey. NBitcoin follows only what is coded into the official source of LTC (I don't know what the official version byte are).

**Comment by mjwaddell** [comment]
The bitcoinjs library creates a usable mainnet extended key when using the bitcoin network settings:
```
var bitcoin = require('bitcoinjs-lib');
var bip39 = require('bip39');
//mnemonic generated at https://iancoleman.io/bip39/
var mnemonic = "walnut mule reflect smart sniff empower dove female cycle student soap trash total involve divide";
var seed = bip39.mnemonicToSeed(mnemonic); 
var node = bitcoin.HDNode.fromSeedBuffer(seed, bitcoin.networks.bitcoin); //bitcoin ntwk
var BIP44Node = node.deriveHardened(44).deriveHardened(2).deriveHardened(0); //litecoin=2
var AcctExtPvtKey = BIP44Node.toBase58();
var AcctExtPubKey = BIP44Node.neutered().toBase58();
```
The created extended keys derive correctly using the NBitcoin library.
Thanks for your help.

**Comment by NicolasDorier** [comment]
Update to 1.0.0.8 it should be fixed with 74e0da6cfe05716ff4babd8a5e1925ffbc1aa3a8 and close this issue once you confirmed.

**Comment by mjwaddell** [comment]
The update works correctly. I generated keys using https://iancoleman.io/bip39/ which generates Ltpv\Ltub keys. NBitcoin derived the child keys correctly.

Thanks again for your help.

**Comment by NicolasDorier** [comment]
@mjwaddell by doing this commit I broke people who used the previous, official format.

In order to not break your code, now you can parse `Ltpv/Ltub` BUT when you call BitcoinExtKey.ToString() it will give you back the offical format!
