### ISSUE TITLE
BitcoinAddress.Create(string) is obsolete

### ISSUE THREAD

**Issue by bazooka70** [MetacoSA/NBitcoin#391]
It was kinda cool feature.
I'm guessing this is b/c of the alt coins support?
Is it true for BTC also?
From my initial test there is no problem with it with BTC addresses.

**Comment by nopara73** [comment]
I think there's another way to do this. Maybe new BitcoinAddress() or BitcoinAddress.Parse() or BitcoinAddress.FromWif() or something like this, being familiar with Nicolas's patterns. If you cannot find it, I'll dig it up for you.

**Comment by bazooka70** [comment]
@nopara73 , I'm almost sure there will be no such capability b/c detecting all altcoins addresses now is a pain in the ass. But hopefully you might know better!
if I'm right I only hope that `BitcoinAddress.Create(string, null)` will work as before for BTC, and wont be completely deprecated later. I can detect other alt coins with some effort.

**Comment by nopara73** [comment]
Is it deprecated with expected Network provided, too?

**Comment by bazooka70** [comment]
@nopara73, No. as far as I can tell `BitcoinAddress.Create(string, expectedNetwork)` parses any network as expected.

**Comment by nopara73** [comment]
The difference is: if the expected network doesn't match, it throws an exception.  

It turns out `BitcoinAddress.Create(string)` is deprecated and you must use `BitcoinAddress.Create(string, Network)`. If you want the same that you have with `BitcoinAddress.Create(string)`, but you don't want the compiler to complain about deprecation, then simply do something like this:

```cs
public static class BitcoinAddressParser
{
	public static BitcoinAddress Parse(string address)
	{
		try
		{
			return BitcoinAddress.Create(address, Network.Main);
		}
		catch
		{
			try
			{
				return BitcoinAddress.Create(address, Network.TestNet);
			}
			catch
			{
				return BitcoinAddress.Create(address, Network.RegTest);
			}
		}
	}
}
```

Then call:
```cs
BitcoinAddressParser.Parse("12345678asdfghj");
```

**Comment by bazooka70** [comment]
@NicolasDorier , an easier way is to simply call 

BitcoinAddress.Create(string, null)

The compiler won't complain and will do the same job.

**Comment by bazooka70** [comment]
Why do you think it's a bug? (but i agree later it could break the code if Nicolas deprecate it completly no allowing null as the second parameter...)

Internally ` BitcoinAddress.Create()` calls `Network.Parse<BitcoinAddress>("xyz", expectedNetwork)` unless I missed something...

**Comment by nopara73** [comment]
> Why do you think it's a bug?

Because that's what had been deprecated. Btw I'm not exactly sure if `Network.Parse<BitcoinAddress>("xyz");` is correct way to do things. They may very well just forgot to deprecate this function without provided network, too.

**Comment by NicolasDorier** [comment]
It is obsolete for two reasons:

1. It is very slow
2. On the backend you should NEVER store bitcoin addresses, only scriptPUbKey. There is no reason to store addresses
3. On the frontend, you must send an error message to the user if he is sending an address with incorrect format
4. With the multiplication of shitcoin, lot's of them share the same base58 prefixes, if you use `BitcoinAddress.Create(String)` it might break when you add another shitcoin later.

**Comment by bazooka70** [comment]
@NicolasDorier , You got very strong points. but still it was a nice feature. 
I will really try to get rid of all `BitcoinAddress.Create(address)` in the backend (I used it mainly with QBitNinja).
Am I right about my assumption for `BitcoinAddress.Create(address, null)`? will it work fine for BTC?

**Comment by NicolasDorier** [comment]
@bazooka70 `QBitNinjaClient` know his `Network`, so you can easily use this data to parse your address.

Yes it will work but I might remove this one day.

**Comment by bazooka70** [comment]
The same goes for `ExtPubKey.Parse(string, expectedNetwork)` now?

**Comment by NicolasDorier** [comment]
yes

**Comment by bazooka70** [comment]
The main usage I think that I will be missing is when I send funds to a  raw address, I could validate that the destination address is valid for my wallet network. think about it...

**Comment by NicolasDorier** [comment]
well you still can valid, this is the whole point.

**Comment by bazooka70** [comment]
Ahhh yes, I can see your point now!
