### ISSUE TITLE
Cleanup PRC estimatefee

### ISSUE THREAD

**Issue by nopara73** [MetacoSA/NBitcoin#402]
Currently the estimatefee methods of the RPCClient are quite confusing.

![](https://i.imgur.com/tfd5WXH.png)

I have three suggestions:

## 1. Remove `estimatefee` related deprecated by functions

So everything that has no "smart" in its name.

## 2. Replace try pattern:

Now we are left with four methods:

![](https://i.imgur.com/jMuzmfw.png)

We can make it two if we utilize the pattern that's used in many rpc call has: a `bool throw` parameter specifies if exception should be thrown or null should be returned.  

## 3. Opt-in simulate RegTest

Finally I am using a handy extension of estimatesmartfee, where, with a parameter I can set if I want the regtest fee to be simulated:  

```cs
public static async Task<EstimateSmartFeeResponse> EstimateSmartFeeAsync(this RPCClient rpc, int confirmationTarget, EstimateSmartFeeMode estimateMode = EstimateSmartFeeMode.Conservative, bool simulateIfRegTest = false)
{
	if(simulateIfRegTest && rpc.Network == Network.RegTest)
	{
		int staoshiPerBytes;
		if (estimateMode == EstimateSmartFeeMode.Conservative)
		{
			staoshiPerBytes = 6 + confirmationTarget;
		}
		else // Economical
		{
			staoshiPerBytes = 5 + confirmationTarget;
		}

		var resp = new EstimateSmartFeeResponse { Blocks = confirmationTarget, FeeRate = new FeeRate(new Money(staoshiPerBytes * 1000, MoneyUnit.Satoshi)) };
		return resp;
	}

	return await rpc.EstimateSmartFeeAsync(confirmationTarget, estimateMode);
}
```

I think adding it to NBitcoin would be useful.

**Comment by knocte** [comment]
> Remove estimatefee related deprecated by functions

How about marking them as [Obsolete] instead.

> a bool throw parameter specifies if exception should be thrown or null should be returned.

But the Try prefix is more .NET-idiomatic.

**Comment by NicolasDorier** [comment]
Actually there is a way to hide it from intellisense without removing them with [EditorBrowsable(EditorBrowsableState.Never)]

**Comment by NicolasDorier** [comment]
Actually I think `BrowsableAttribute` is better.

**Comment by NicolasDorier** [comment]
Actually I don't know, one of them should work :p

**Comment by lontivero** [comment]
I've pushed a PR for your consideration https://github.com/MetacoSA/NBitcoin/pull/404  (not found :joy:)

**Comment by NicolasDorier** [comment]
I merged, @lontivero 's PR, closing this.

**Comment by nopara73** [comment]
@NicolasDorier What do you think of my 3rd suggestion? The `bool simulateIfRegTest = false` parameter?

**Comment by NicolasDorier** [comment]
I don't like it, not having estimations available is part of the things that should be tested and handled correctly.

**Comment by NicolasDorier** [comment]
Note that you may be able to use `-fallbackfee` in bitcoin core for getting an estimate on regtest

**Comment by NicolasDorier** [comment]
Shit fallbackfee does not work for estimate

**Comment by NicolasDorier** [comment]
btw I don't know if you care too much about shitcoin, but if you make sure to not hardcode `Network.Main/Testnet/Regtest` in wasabi wallet, then your wallet will be shitcoin compatible.

**Comment by nopara73** [comment]
> I don't like it, not having estimations available is part of the things that should be tested and handled correctly.

I know, that's why a) it's an optional parameter and b) it defaults to false. But fair enough.
