### ISSUE TITLE
Attempting to Decrypt Encrypted Bitcoin Secret Error 

### ISSUE THREAD

**Issue by Grey007** [MetacoSA/NBitcoin#409]
Hi,

I am attempting to decrypt encrypted bitcoin secret by using the password set when encrypting the project.  When I call the: 

`var encryptedKey = ReadLine();
  var secret = new BitcoinEncryptedSecretEC(encryptedKey, BitcoinNetwork);` 

The following error gets returned: 
`System.FormatException: The version prefix does not match the expected one 1,67
   at NBitcoin.Base58Data.SetString[T](String psz)`

Not sure what I'm doing wrong?

**Comment by NicolasDorier** [comment]
use `NBitcoin.BitcoinEncryptedSecret.Create("blahblag", Network.Main)` instead

**Comment by Grey007** [comment]
Perfect, that worked! Thanks :-)
