### ISSUE TITLE
Bitcoin Gold Tx error -> mandatory-script-verify-flag-failed

### ISSUE THREAD

**Issue by mjwaddell** [MetacoSA/NBitcoin#410]
I'm using the latest version of NBitcoin to create and broadcast a BTG transaction on mainnet. I'm creating the transaction using the TransactionBuilder.  When I broadcast the transaction, I receive an error from the BTG core server: **tx mandatory-script-verify-flag-failed (Signature hash type missing or not understood)**. I tested on 2 mainnet nodes.

Is there a step I'm missing when creating the transaction? I'm using the same code flow as bitcoin, litecoin, and dash which all work correctly.

Thanks

**Comment by NicolasDorier** [comment]
@mjwaddell yes or you will have the same issues for coin which has different signature algorithm than Bitcoin.
