### ISSUE TITLE
AltCoin overrideable tx serialization process

### ISSUE THREAD

**Issue by mikedennis** [MetacoSA/NBitcoin#411]
I'm looking at integrating Stratis to the altcoin framework which adds some data to the transaction serialization (POS date). Not sure how best to handle this with the AltCoin framework. Any ideas?

**Comment by NicolasDorier** [comment]
Check with BGold and BCash how I support a custom class of Transaction. Just need to overrides ReadWrite and implement your own parsing.

**Comment by mikedennis** [comment]
Ah I see - this looks to be new since I last checked. Thanks! Will give that a try.
