### ISSUE TITLE
Network Initialization Error

### ISSUE THREAD

**Issue by rony4d** [MetacoSA/NBitcoin#417]
Network network = NBitcoin.Altcoins.Litecoin.Testnet;
 should be changed to  Network network = NBitcoin.Altcoins.Litecoin.Instance.Testnet;

**Comment by NicolasDorier** [comment]
yes, where?

**Comment by lontivero** [comment]
README.md is the only place that I've found

```bash
$ git grep -n "Network network = NBitcoin.Altcoins.Litecoin.Testnet"
NBitcoin.Altcoins/README.md:27:Network network = NBitcoin.Altcoins.Litecoin.Testnet;
```
