### ISSUE TITLE
Can't sign a Transaction

### ISSUE THREAD

**Issue by compilenewbe** [MetacoSA/NBitcoin#418]
so I have been working on this, and I can basically get all the information to fill the transaction builder, the only problem is getting the bitcoinSecret to sign it, I can't seen to figure it out.
var priv = mbwallet.SelectedWallet.PrivateKeys[0].ToWif();
            // priv = tprv8ZgxMBicQKsPdyamkZnBjh8kG4kW6ZAtzkonTCeeNCuWMH5K2jqJAMac1rwct3iG1ygu4tM8Zh1jnQVAh2hGMAEUXATmj48JpeP3J3z42Wt
            // file = tprv8ZgxMBicQKsPdyamkZnBjh8kG4kW6ZAtzkonTCeeNCuWMH5K2jqJAMac1rwct3iG1ygu4tM8Zh1jnQVAh2hGMAEUXATmj48JpeP3J3z42Wt
            //var ool = new BitcoinSecret(base58, App.Network);
            var privkey = mbwallet.SelectedWallet.PrivateKeys[0].PrivateKey.GetBitcoinSecret(App.Network).ToWif();
            var key = Key.Parse(privkey, App.Network);
            var keysT = key.GetWif(App.Network);
            //var myaddress = mbwallet.SelectedWallet.PrivateKeys[0].PrivateKey.PubKey.GetAddress(App.Network);
            var myaddress = mbwallet.SelectedWallet.CurrentAddress;
            var tttt = WalletViewModel.Load();

            string address = Address.Text;
            var destination = BitcoinAddress.Create(address, App.Network);
            decimal value = Convert.ToDecimal(Value.Text);

            var coins2 = GetCoins(value);

            TransactionBuilder txBuilder = new TransactionBuilder();
            var tx = txBuilder.AddCoins(coins2)
                .AddKeys(keysT)
                .SetChange(myaddress)
                .Send(destination, new Money(value, MoneyUnit.BTC))
                .SendFees("0.0002");
            //.BuildTransaction(true);
            var tx2 = txBuilder.BuildTransaction(true);
            //Console.WriteLine(txBuilder.Verify(tx));

            var hello = tx2.ToHex();
            var txRepo = new NoSqlTransactionRepository();
            //txRepo.Put(tx.GetHash(), tx);
            //Assert(txBuilder.Verify(tx)); //check fully signed

            List<ICoin> GetCoins(decimal sendAmount)
            {
                //var mbwallet = (root.DataContext as MainWindowViewModel);
                var amountMoney = new Money(sendAmount, MoneyUnit.BTC);
                var client = new QBitNinjaClient(App.Network);
                var txInAmount = Money.Zero;
                var coins1 = new List<ICoin>();
                foreach (var balance in client.GetBalance(mbwallet.SelectedWallet.CurrentAddress,//MBWallet.Wallet.Address,
            true).Result.Operations)
                {
                    var transactionId = balance.TransactionId;
                    var transactionResponse =
            client.GetTransaction(transactionId).Result;
                    var receivedCoins = transactionResponse.ReceivedCoins;
                    foreach (Coin coin in receivedCoins)
                    {
                        if (coin.TxOut.ScriptPubKey ==
                            mbwallet.SelectedWallet.CurrentAddress.ScriptPubKey)//MBWallet.Wallet.BitcoinPrivateKey.ScriptPubKey) // this may not be necessary
                        {
                            coins1.Add(coin);
                            txInAmount += (coin.Amount as Money);
                        }
                    }
                }
                return coins1;
            }
Please someone help

**Comment by NicolasDorier** [comment]
If `Key` is in hex `new Key(Encoders.Hex.DecodeData(hex))`.
If `Key` is base58 `new BitcoinSecret(base58, Network.Main)`.

There is no other format supported by NBitcoin.

**Comment by compilenewbe** [comment]
i will i get that hex to decode?
