### ISSUE TITLE
Trsanction.Sign(ISecret, bool) is obsolete

### ISSUE THREAD

**Issue by JayricMok** [MetacoSA/NBitcoin#419]
I am new and I try to follow this tutorial https://www.youtube.com/watch?v=X4ZwRWIF49w, but facing an issue about `Trsanction.Sign(ISecret, bool) is obsolete` , it say use `Trsanction.Sign(ISecret, ICoin[] instead)`.

            var secret = new BitcoinSecret("thekey");
            var privateKey = secret.PrivateKey;

            Transaction tx = new Transaction();
            var input = new TxIn();
            input.PrevOut = new OutPoint(new uint256("thetransaction"), 1);
            input.ScriptSig = secret.GetAddress().ScriptPubKey;
            tx.AddInput(input);

            TxOut output = new TxOut();
            var destination = BitcoinAddress.Create("thereceiveraddress", Network.TestNet);
            Money fee = Money.Satoshis(1000);
            output.Value = Money.Coins(0.275m) - fee;
            output.ScriptPubKey = destination.ScriptPubKey;
            tx.AddOutput(output);
            tx.Sign(secret, false);

**Comment by NicolasDorier** [comment]
Yes, `.Sign` is just used to teach you, but it should not be used in production. Instead use TransactionBuilder as documented in https://programmingblockchain.gitbooks.io/programmingblockchain/content/

**Comment by Grey007** [comment]
What happens in the case when you want to sign a transaction offline? If you add a key to transaction builder offline and pass the transaction back to your application, the keys are now available in the application ?

**Comment by NicolasDorier** [comment]
You need to pass the Transaction + the coins to spend.

This is in anycase important, so the signer can know how much is actually spent.
