### ISSUE TITLE
How to go about testing if a ScriptPubKey is standard or not?

### ISSUE THREAD

**Issue by nopara73** [MetacoSA/NBitcoin#420]
There is a `Script.IsValid`. As I see that looks at all the opcodes if they are individually valid. I don't think that's what I need.

**Comment by nopara73** [comment]
I guess the only sure way to do this, that'll pass the test of time if I simply use `BitcoinAddress` instead of `Script` whenever I can.

**Comment by NicolasDorier** [comment]
No, BitcoinAddress is only for UI layer. The easiest is to try `script.GetDestination() != null`
