### ISSUE TITLE
Different Inputs to Same Output.

### ISSUE THREAD

**Issue by fcoskun** [MetacoSA/NBitcoin#422]
Hi,

How can i use different received inputs which has different private keys as input in transactionbuilder and send them to only an address. 

Example, 
https://www.blocktrail.com/BTC/tx/244404864b923bfaafcec670cd05b536d364d53df74328508a173b1ccc047a70 

Different address as inputs, sign with different keys and sent to an address.

**Comment by lontivero** [comment]
Create and broadcast a transaction with those inputs and only two outputs (one consolidating the amounts and other with the fee).

**Comment by fcoskun** [comment]
I tried. It works when two inputs are same but when private keys are different in input only one of the inputs is entered the the input. You can see my transaction builder in below:

    var builder = new TransactionBuilder();
            Transaction tx = builder
                .AddCoins(receivedCoins1[0])
                .AddKeys(extKey1.PrivateKey)
                .Send(extKey3.ScriptPubKey, receiverAmount)
                .SendFees(minerFee)
                .SetChange(extKey1.PrivateKey.PubKey)
                .Then()
                .AddCoins(receivedCoins2[0])
                .AddKeys(extKey2.PrivateKey)
                .Send(extKey3.ScriptPubKey, Money.Coins(0.01m))
                .SetChange(extKey1.PrivateKey.PubKey)
                .Then()
                .BuildTransaction(sign: true);

**Comment by lontivero** [comment]
Why do you use groups? Try with a simple transaction:

```c#
var builder = new TransactionBuilder();
var tx = builder
            .AddCoins(receivedCoins1[0], receivedCoins2[0])
            .AddKeys(extKey1.PrivateKey, extKey2.PrivateKey)
            .Send(extKey3.ScriptPubKey, receiverAmount)
            .SendFees(minerFee)
            .SetChange(extKey1.PrivateKey.PubKey)
            .BuildTransaction(true);
```

**Comment by NicolasDorier** [comment]
The reason why using several group is when you want 1 transaction where different people pay different things.

I think it is valid usage, checking this.
I don't think that's broken though as I did lot's of tests on it... but checking now.

**Comment by NicolasDorier** [comment]
ah got it... same address! probably a bug. Replicating and fixing it now...

**Comment by NicolasDorier** [comment]
I checked it it work as expected. Only bad point is that it uses 4 txout instead of 3.

**Comment by NicolasDorier** [comment]
In this commit https://github.com/MetacoSA/NBitcoin/commit/2c1f23db77a88407c29b6eae668aaffc28ff13c4 I added a test for your case (https://github.com/MetacoSA/NBitcoin/commit/2c1f23db77a88407c29b6eae668aaffc28ff13c4#diff-4f1e72c1603b4d4b5ca2a70996c9a4b2R157). 

The test is passing fine. Can you check I am reproducing correctly the problem?

I also changed TransactionBuilder to automatically merge outputs with the same destination into the same output.

**Comment by fcoskun** [comment]
Thanks for your reply but i already tried this example in below but when i decode the transaction, i see only one input.  Think us as an exchange, we hold our customers private key, we want to send to some bitcoin or consolidate our inputs to an address. 

var builder = new TransactionBuilder();
var tx = builder
            .AddCoins(receivedCoins1[0], receivedCoins2[0])
            .AddKeys(extKey1.PrivateKey, extKey2.PrivateKey)
            .Send(extKey3.ScriptPubKey, receiverAmount)
            .SendFees(minerFee)
            .SetChange(extKey1.PrivateKey.PubKey)
            .BuildTransaction(true);

i just want to build a transaction from my inputs to an address, there is an example in this link. 

https://www.blocktrail.com/BTC/tx/244404864b923bfaafcec670cd05b536d364d53df74328508a173b1ccc047a70

**Comment by NicolasDorier** [comment]
@fcoskun your code seemed correct with the groups, but I can't replicate your bug.
This tests works as expected:

https://github.com/MetacoSA/NBitcoin/commit/2c1f23db77a88407c29b6eae668aaffc28ff13c4#diff-4f1e72c1603b4d4b5ca2a70996c9a4b2R157

**Comment by NicolasDorier** [comment]
I am not sure what you want, please replicate your problem in code I can run. 

If you want to send all the money to one  address:

```
var tx =
    new TransactionBuilder()
    .AddCoins(coins)
    .AddKeys(keys)
    .Send(destination, coins.Select(c => c.Amount).Sum())
    .SubtractFees()
    .SendEstimatedFees(feeRate)
    .BuildTransaction(true);
```

should do the trick.
