### ISSUE TITLE
Bitcoin Cash Version Handshake error

### ISSUE THREAD

**Issue by bijakatlykkex** [MetacoSA/NBitcoin#427]
Hello,

It seems because of recent upgrade of Bitcoin ABC daemon (version 0.17.1 - the hardfork of bitcoin cash), while connecting to the node I get version handshake error from NBitcoin: "The node is not in a connected state".

``
Unhandled Exception: System.InvalidOperationException: The node is not in a connected state
   at NBitcoin.Protocol.NodeListener.ReceivePayload[TPayload](CancellationToken cancellationToken)
   at NBitcoin.Protocol.Node.VersionHandshake(NodeRequirement requirements, CancellationToken cancellationToken)
   at NBitcoin.Protocol.Node.VersionHandshake(CancellationToken cancellationToken)
``

If I run the node in regtest mode, in debug.log of daemon I get "PROCESSMESSAGE: INVALID MESSAGESTART version peer=x"

Helps appreciated.
Thank you

**Comment by Kukks** [comment]
You most likely need to send a different `ProtocolVersion` when connecting to the bcash node

**Comment by bijakatlykkex** [comment]
Thank you for the comments.

The relationship between the reported problem and the daemon version upgrade is not directly connected to the hard fork, but the upgrade on my side happened to conform with the hard fork and as a result the above mentioned problem showed up.

It seems the enforcement of magic numbers for Bitcoin cash has started in https://github.com/Bitcoin-ABC/bitcoin-abc/commit/ee128b3dd0dc4b9f0f4b067540f62cfd9ac37ebe which is a commit after the release, I was running on my side. 

As declared above to look in chainparams.cpp, I was able to locate two sets of magic numbers in https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/src/chainparams.cpp , diskMagic and netMagic. I changed the look at diskMagic in places like here https://github.com/MetacoSA/NBitcoin/blob/BCCtemp/NBitcoin/Network.cs#L752 to netMagic values and it solved the problem.

**Comment by NicolasDorier** [comment]
BCCtemp branch is way out of date.

**Comment by bijakatlykkex** [comment]
Yes, but for example it was required to have indexer to support Bitcoin Cash to some degree, and NBitcoin.Altcoins seems to be a recent addition, with the indexer having a version bump 5 days ago after Nov 2, 2017 commit. The integration of the indexer with AltCoins support should to be studied from my side, yet.

Thank you for the continuous improvement.
