### ISSUE TITLE
p2sh-convert with NBitcoin?

### ISSUE THREAD

**Issue by dmorris99** [MetacoSA/NBitcoin#430]
Hi all, sorry not an "issue" but a question: 

Can I use NBitcoin to convert from legacy LTC "3" addresses to "M" addresses? 

i.e. https://litecoin-project.github.io/p2sh-convert/#
e.g. 3HCM6iZErFJmeh5jUUMGJVCpFqaoMHhkmu -> MPQVQbyCoNACTCMdaMLc88TDaYBFGfSGYy

I guess probably yes, but my knowledge is not advanced enough.   The JS for this using bitcoin.js is as follows. 

```
address = document.getElementById('address').value;
decoded = bitcoin.address.fromBase58Check(address);
version = decoded['version']
switch (version) {
	case 5:
		message = "Mainnet p2sh address: ";
		version = 50;
		break;
	case 50:
		message = "Mainnet p2sh address (deprecated): ";
		version = 5;
		break;
	case 196:
		message = "Testnet p2sh address: ";
		version = 58;
		break;
	case 58:
		message = "Testnet p2sh address (deprecated): ";
		version = 196;
		break;
	default:
		throw "unknown";
}
// 5 <-> 50
// 196 <-> 58
address = bitcoin.address.toBase58Check(decoded['hash'], version);
```

**Comment by NicolasDorier** [comment]
`var newAddress= BitcoinAddress.Create(oldAddress, Network.Main).ToNetwork(NBitcoin.Altcoins.Litecoin.Instance.Mainnet)`

**Comment by dmorris99** [comment]
Thanks Nicolas :)

**Comment by dmorris99** [comment]
@NicolasDorier - sorry Nicolas, I should have thought to ask in the OP: but how to do the inverse, M addr --> 3 addr?

**Comment by NicolasDorier** [comment]
```
var oldAddress= BitcoinAddress.Create(newAddress, NBitcoin.Altcoins.Litecoin.Instance.Mainnet)
                              .ToNetwork(Network.Main)
```
