### ISSUE TITLE
Support new opcodes for Bitcoin Cash

### ISSUE THREAD

**Issue by GSPP** [MetacoSA/NBitcoin#432]
Bitcoin Cash recently forked to add new opcodes and to restore old ones. I'm not sure to what extent these are supported by NBitcoin at this time. I noticed that script evaluation does not support them.

I understand that currently there is not much interest by the project maintainers to support Bitcoin Cash. But it seems useful to have a tracking issue for these features in case someone volunteers. So I'm opening one. Bitcoin Cash has a nontrivial market cap at this point and it looks like the project is not going away any time soon. Supporting this currency would certainly find some interest from NBitcoin users.

**Comment by NicolasDorier** [comment]
The ScriptEvaluator will always only support Bitcoin.

I might consider allowing custom implementation of ScriptEvaluator later, but this is not a priority for me (I can review PRs though), and I will not do such heavy refactoring for BCash.
