### ISSUE TITLE
Question: Is there any way to know if an address is segwit?

### ISSUE THREAD

**Issue by bazooka70** [MetacoSA/NBitcoin#435]
Given an input address like `2Mwz3RpGzCUfdA9Fr1nnU56uoib84A4cKj4` (Type = SCRIPT_ADDRESS) 
Can I somehow know it is a segwit address or not? i.e:

```csharp
var bitcoinAddress = BitcoinAddress.Create("2Mwz3RpGzCUfdA9Fr1nnU56uoib84A4cKj4", Network.TestNet);
bitcoinAddress.IsSegwitAddress(); // <- pseudo
```

**Comment by nopara73** [comment]
To my understanding no. Wrapped segwit and p2sh cannot be diferentiated at this point. It can only be known when funds are spent.  

There's native segwit: bech32, which you can of course.

**Comment by NicolasDorier** [comment]
As nopara said, you can't for p2sh segwit.
