### ISSUE TITLE
(new NBitcoin.Transaction(hex_str)).ToString() != expected // (DCR)

### ISSUE THREAD

**Issue by dmorris99** [MetacoSA/NBitcoin#436]
Hi all, 

I'm trying to use NBitcoin to add an op_return output to a raw transaction created by Decred RPC.

Issue I'm facing is when creating the NBitcoin.Transaction from the raw hex, it seems to be losing information. The original raw hex ("0100000001c35dd4fab521cd3e79cc76d2ad7d7334cd76b922545f86a08d332add15db0b3e0700000000ffffffff01a08601000000000000001976a9142c7f9985f2ebe79380924ea6a8b04ef49fc426f188ac000000000000000001ffffffffffffffff00000000ffffffff00") produces this decoded JSON on RPC:

> {
  "txid": "907a6375b31e39635b3e34b9b48d9ef530b58c02899b7f554af2b74a6ee6bfcd",
  "version": 1,
  "locktime": 0,
  "expiry": 0,
  "vin": [
    {
      "txid": "3e0bdb15dd2a338da0865f5422b976cd34737dadd276cc793ecd21b5fad45dc3",
      "vout": 7,
      "tree": 0,
      "sequence": 4294967295,
      "amountin": -1e-8,
      "blockheight": 0,
      "blockindex": 4294967295,
      "scriptSig": {
        "asm": "",
        "hex": ""
      }
    }
  ],
  "vout": [
    {
      "value": 0.001,
      "n": 0,
      "version": 0,
      "scriptPubKey": {
        "asm": "OP_DUP OP_HASH160 2c7f9985f2ebe79380924ea6a8b04ef49fc426f1 OP_EQUALVERIFY OP_CHECKSIG",
        "hex": "76a9142c7f9985f2ebe79380924ea6a8b04ef49fc426f188ac",
        "reqSigs": 1,
        "type": "pubkeyhash",
        "addresses": [
          "DsV2C5es3sDrkZbQdaTVfwZbSvef3r8St37"
        ]
      }
    }
  ]
}

When I create new NBitcoin.Transaction from this hex:

            var start_tx_hex = "0100000001c35dd4fab521cd3e79cc76d2ad7d7334cd76b922545f86a08d332add15db0b3e0700000000ffffffff01a08601000000000000001976a9142c7f9985f2ebe79380924ea6a8b04ef49fc426f188ac000000000000000001ffffffffffffffff00000000ffffffff00";
            NBitcoin.Transaction tx = new NBitcoin.Transaction(start_tx_hex);
            var start_tx_str = tx.ToString(); 

I get the following ToString() representation, which seems wrong:

> {
  "hash": "67c2f6642de22fbbaa01df65496991e1a00cb75209797b772d17a8fcdd61dab5",
  "ver": 1,
  "vin_sz": 1,
  "vout_sz": 1,
  "lock_time": 2843089152,
  "size": 60,
  "in": [
    {
      "prev_out": {
        "hash": "2020100d06cd102e15f478b5afd90f96c7d33bef15d186c6528e20a499874a74",
        "n": 15
      },
      "scriptSig": ""
    }
  ],
  "out": [
    {
      "value": "0.00600000",
      "scriptPubKey": ""
    }
  ]
}

I guess if I can fix this, the rest of the code might work: ?!

            var data_output = new TxOut();
            data_output.ScriptPubKey = new Script() + OpcodeType.OP_RETURN + Encoders.Hex.DecodeData("ffeeaa0099");
            tx.AddOutput(data_output);

            var new_tx_hex = tx.ToHex();
            var new_tx_str = tx.ToString();

Thanks in advance.

**Comment by NicolasDorier** [comment]
Seems to me more a bug in Decred API. https://blockchain.info/fr/decode-tx is giving me same result as NBitcoin.
