### ISSUE TITLE
How to verify whether public address is a child of ExtPubKey?

### ISSUE THREAD

**Issue by ArtjomP** [MetacoSA/NBitcoin#442]
Hi there!
I have a transaction with TxOuts ScriptPubKey & I know the root ExtPubKey.

Can I verify that transaction's addresses are children of an the ExtPubKey?

ExtPubKey has methods .IsParentOf(ExtPubKey ...) but I can't get PubKey from Transaction because ScriptPubKey is a function of hash from a PubKey is it correct?

Thx!

**Comment by NicolasDorier** [comment]
You can't. You need to maintain a mapping (scriptPubKey => KeyPath)

**Comment by ArtjomP** [comment]
Thank you for your support. 
Just one more thing for the clarification.

Is it correct that having the root ExtPubKey and knowing path to check transaction address I need to this:

```cs
var derivedPublicAddress = extPubKey.Derive(new KeyPath(path)).PubKey.GetAddress(network);

//VERIFICATION
txOut.ScriptPubKey.GetDestinationAddress == derivedPublicAddress
```

Thank you in advance

**Comment by NicolasDorier** [comment]
correct.
