### ISSUE TITLE
The value of Difficulty calculated in Target class is wrong

### ISSUE THREAD

**Issue by shwuhk** [MetacoSA/NBitcoin#445]
https://github.com/MetacoSA/NBitcoin/blob/9843ab333f93394d70287bec3f3754610abe7897/NBitcoin/Target.cs#L90-L111

All leading zeros in the decimal part will be omited due to decimalPart.Multiply(BigInteger.Ten); as decimalPart is initialized as zero.

**Comment by NicolasDorier** [comment]
You are right. I am surprised no tests caught this. Luckily this number is only used for human consumption.

I wonder where I took this code from. Even the `double.Parse` is really fishy.

**Comment by NicolasDorier** [comment]
Reviewing https://www.youtube.com/watch?v=6TDLMkOCQkU that's embarassing... ;p

**Comment by NicolasDorier** [comment]
fixed in 4.1.1.12
