### ISSUE TITLE
Cannot correctly derive P2SH addresses for xpub from a Segwit-enabled Trezor account

### ISSUE THREAD

**Issue by djnicholson** [MetacoSA/NBitcoin#449]
I am attempting to extract the xpub for a single Bitcoin account on a Trezor (using the Trezor COnnect API), and then derive receive/change addresses for that Trezor within C# code (using the NBitcoin library).

My code works correctly for legacy accounts, but for segwit accounts I cannot match the address generated in the web wallet.

JavaScript code to extract the XPub:
`TrezorConnect.getXPubKey(undefined, console.log)`
(asks the user to click on an account, then reports a string of the form "xpub...")

C# code to generate addresses for a legacy Trezor account (**works fine**)
`            var xpub = NBitcoin.ExtPubKey.Parse("xpub...");
            for (uint i = 0; i < 2; i++)
            {
                for (uint j = 0; j < 5; j++)
                {
                    Console.WriteLine(xpub.Derive(i).Derive(j).PubKey.GetAddress(Network.Main));
                }
            }`

C# code to generate addresses for a non-legacy (segwit) Trezor account (**does not work** - generates valid 3... addresses, but not the same ones shown in the Trezor wallet interface)
`            var xpub = NBitcoin.ExtPubKey.Parse("xpub...");
            for (uint i = 0; i < 2; i++)
            {
                for (uint j = 0; j < 5; j++)
                {
                    Console.WriteLine(xpub.Derive(i).Derive(j).PubKey.GetScriptAddress(Network.Main));
                }
            }`

Any idea what I am doing wrong?

See also: https://github.com/trezor/connect/issues/143

**Comment by djnicholson** [comment]
Oops, I should have done:
Console.WriteLine(xpub.Derive(i).Derive(j).PubKey.GetSegwitAddress(Network.Main).GetScriptAddress());
(the **GetSegwitAddress** call was missing)
Leaving this here in case anyone else makes a similar mistake.

**Comment by NicolasDorier** [comment]
cool :)
