### ISSUE TITLE
Verify/Sign messages for another coin

### ISSUE THREAD

**Issue by mathis1337** [MetacoSA/NBitcoin#451]
I have been trying to track down how to sign/verify a message for other coins using this. I see it works perfect for bitcoin, but lets say if I wanted to use with BTG, or BCI, how would I go about modifying this, so that when it decrypts the signature it doesn't return a BTC address.

**Comment by mathis1337** [comment]
Also I have already modified the network file for the correct PUBKEY: base58Prefixes[(int)Base58Type.PUBKEY_ADDRESS] = new byte[] { (102) };

This does indeed return the correct public addresses. However, when trying to run VerifyMessage I believe it is still comparing it to a BTC address.

Thanks!

**Comment by mathis1337** [comment]
Here Is what I am trying currently. Also I know it says BTG, but I am testing current against BCI (Bitcoin Interest)

var address = new NBitcoinBTG.BitcoinPubKeyAddress("i8LfuQQq78gZSPf5WRouEDGkWLuqicuTP8", NBitcoinBTG.Network.Main);
	address.Type.Dump();
	address.VerifyMessage("hey", "HyTKojA59gTMtg1on8rD6CWsQMzZ2dcWH8YOVqb5VhjmFYKp5DFE/dgd8RqoI+/EqJO1pnHbY48+g34Tuzgrkug=")

I tested in wallet and this message verifies just fine, but does not in this code. 
![image](https://user-images.githubusercontent.com/20599614/41816716-b6bf5572-7751-11e8-8448-4d754f1d83c3.png)

**Comment by NicolasDorier** [comment]
I don't understand, Verify/Sign does not have any Base58 related data. Can you send me code reproducing that?

**Comment by NicolasDorier** [comment]
ah Maybe it is the header of the message being signed which is different depending on the crypto.

**Comment by mathis1337** [comment]
Just take your NBitcoin on here. Only line I changed was one above. And yes that is possible. It always converts signature to BTC address starting with number 1. Here is what I am working with. 

address: i8LfuQQq78gZSPf5WRouEDGkWLuqicuTP8
var message = "hey";
	var signature = "HyTKojA59gTMtg1on8rD6CWsQMzZ2dcWH8YOVqb5VhjmFYKp5DFE/dgd8RqoI+/EqJO1pnHbY48+g34Tuzgrkug=";

Those have been tested in wallet to work, but when I use NBitcoin I can't do it. It always says false unless I verify from within NBitcoin, but that won't work

**Comment by mathis1337** [comment]
![image](https://user-images.githubusercontent.com/20599614/41828378-8cbf3da6-77fa-11e8-82a0-17a41135713b.png)

**Comment by mathis1337** [comment]
Where can I edit the source to allow for this? This is the only function I really need from NBitcoin and would love to use this as its the best C# solution out there hands down, especially with your documentation.

**Comment by mathis1337** [comment]
Here is the source code for the coin I am working with: https://github.com/BitcoinInterestOfficial/BitcoinInterest

**Comment by NicolasDorier** [comment]
Yeah, it is because of the Header I think. I could fix this, to have the Verify/Sign message at the BitcoinAddress/BitcoinSecret level instead so I can use Network to fetch the expected header.

That said, I think it is overkill to do, why are you still using this?

**Comment by mathis1337** [comment]
I need to create a way to prove ownership of an address through an online tool. I also need to give users a way to create these messages if they are using the online web wallet. We provide a staking platform, and right now there is nothing to prove a user owns an address and I don't want to make them send coins to prove it. This would be the ideal approach. I think this would be great if you could do that!

**Comment by mathis1337** [comment]
If you have another solution that is C# based where I can verify/sign messages with private keys or public key to verify I am open, but this is really the only C# solution out there that you can do this without the need of the core wallet.

**Comment by NicolasDorier** [comment]
I see, yes I can do it but I am rather busy. So if you are in a rush:

* Add a "Name" parameter to NetworkSet,
* Create a Verify/SignMessage methods inside BitcoinAddress/BitcoinSecret.
* Use the Network's set name of the network to create the message header.

**Comment by NicolasDorier** [comment]
Sorry, actually I am not even sure it is the issue.

**Comment by mathis1337** [comment]
I just wanted to point out the only change I made to code. That may be confusing you. I am not sure where the issue it. I tried to trace code down and extract and run it manually, but I could not determine the actual method that takes the signature and extracts the public key. When do you think you'd have time to take a peak at this?

**Comment by NicolasDorier** [comment]
I already pointed you out above.

**Comment by mathis1337** [comment]
I know you said in BitcoinSecret to make two new methods in there. THats what I am saying is I am not as familiar. There are a ton of methods you seem to use to do this verify/sign process. I am just now getting into it. It would probably take me quite a while to actually learn how to create those methods. I could also be not understanding you. I am not in a super rush, so if you had time to help it would be greatly appreciated and a good learning opportunity for me.

**Comment by mathis1337** [comment]
I appreciate the comments so far. I will try and do more research. though I am just now kind of going through your book programming the blockchain, and learning, and there isn't much on the actual code behind signing/verify. I don't image I will figure it out soon, but I will try I suppose and see if I can understand what you are telling me to do.

**Comment by mathis1337** [comment]
Issue was with header, being handled by Nicolas, closing issue.

**Comment by ajeethhacki** [comment]
the same issue am having Please help me buddies am BTCBZ, Litcoin, and Bitcoin only the bitcoin alone verifying in the same application , litcoin is working(verifying) different application like coinomi.. and the BTCBZ not available in coinomi so i didn't checked in that .... please help me why litcoin is not working in my application

**Comment by ajeethhacki** [comment]
Please help it veryh urgent
