### ISSUE TITLE
Can i look for transactions using an address or it needs to be a SriptPubKey?

### ISSUE THREAD

**Issue by compilenewbe** [MetacoSA/NBitcoin#453]
Can I use NBitcoin to look for transactions using just the addresses or it only works with ScriptPubKey

**Comment by NicolasDorier** [comment]
NBitcoin is just a framework. The bitcoin protocol has no concept of address. If your question is: `Can I convert a scriptPubKey to an address?`, then the answer is yes. (`Script.GetDestinationAddress(Network.Main)`)

https://programmingblockchain.gitbooks.io/programmingblockchain/content/

**Comment by compilenewbe** [comment]
And can I turn and address into a scriptPubKey.

**Comment by NicolasDorier** [comment]
yes. Not all scriptPubKey can be expressed as an address though.

**Comment by compilenewbe** [comment]
ok, thank you so much, I will look through your guide i find how to do that process.
