### ISSUE TITLE
Not getting any transaction nor Blocks

### ISSUE THREAD

**Issue by compilenewbe** [MetacoSA/NBitcoin#455]
So i am trying to get information from a trusted node that i am running on a server, but i cant seen to be able to get any blocks or even connect, and I doing something wrong?

using System;
using System.IO;
using System.Reflection;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Net;
using NBitcoin;
using NBitcoin.Protocol;
using NBitcoin.Protocol.Behaviors;
using NBitcoin.SPV;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace TestingBlocksExplorer
{
	[TestClass]
	public class UnitTest1
	{
		static Network network = Network.Main;

		public static string ChainFile => Path.Combine(Directory.GetCurrentDirectory(), ChainName());

		static string ChainName()
		{
			if (network == Network.Main)
				return "chainmain.data";
			return "chaintest.data";
		}

		[TestMethod]
		public void TestMethod1()
		{
			// parse address from command line
			var addr = BitcoinAddress.Create("1JmjsGZrKdRTiodeLy85kU8zPK1WsqTKc");

			// use local trusted node
			NetworkAddress peer = new NetworkAddress(IPAddress.Parse("192.168.10.51"), network == Network.Main ? 8333 : 18333); ;

			// initial scan location
			var scanLocation = new BlockLocator();
			scanLocation.Blocks.Add(network.GetGenesis().GetHash());
			var skipBefore = DateTimeOffset.MinValue;
			//skipBefore = DateTimeOffset.Now.AddMonths(-1);

			// load chain
			var chain = new ConcurrentChain(network);
			if (File.Exists(ChainFile))
				chain.Load(File.ReadAllBytes(ChainFile));

			// connect node 
			ConnectNode(addr, peer, chain, scanLocation, skipBefore);

			int chainHeight = 0;
			while (true)
			{
				
				if (chain.Height != chainHeight)
				{
					chainHeight = chain.Height;
					Console.WriteLine("Chain height: {0}", chain.Height);
					using (var fs = File.Open(ChainFile, FileMode.Create))
						chain.WriteTo(fs);
				}
				System.Threading.Thread.Sleep(5000);
			}
		}

		private static void ConnectNode(BitcoinAddress addr, NetworkAddress peer, ConcurrentChain chain, BlockLocator scanLocation, DateTimeOffset skipBefore)
		{
			var script = addr.ScriptPubKey; // standard "pay to pubkey hash" script

			var parameters = new NodeConnectionParameters();

			// ping pong
			parameters.TemplateBehaviors.FindOrCreate<PingPongBehavior>();

			// chain behavior keep chain in sync
			parameters.TemplateBehaviors.Add(new ChainBehavior(chain));

			// tracker behavior tracks our address
			parameters.TemplateBehaviors.Add(new TrackerBehavior(new Tracker(), chain));

			var addressManager = new AddressManager();
			addressManager.Add(peer, IPAddress.Loopback);

			parameters.TemplateBehaviors.Add(new AddressManagerBehavior(addressManager));
			var group = new NodesGroup(network, parameters);
			group.AllowSameGroup = true;
			group.MaximumNodeConnection = 1;
			group.Requirements.SupportSPV = true;
			group.Connect();
			group.ConnectedNodes.Added += (s, e) =>
			{
				var node = e.Node;

				node.Disconnected += n =>
				{
					var _trackerBehavior = n.Behaviors.Find<TrackerBehavior>();
					scanLocation = _trackerBehavior.CurrentProgress;
					Console.WriteLine("Node disconnected, chain height " + chain.Tip.Height + ".");
				};

				// Start tracker scanning.
				var trackerBehavior = node.Behaviors.Find<TrackerBehavior>();
				Console.WriteLine("Tracking {0}", addr);
				trackerBehavior.Tracker.Add(addr.ScriptPubKey);
				trackerBehavior.Tracker.NewOperation += (Tracker sender, Tracker.IOperation trackerOperation) =>
				{
					var walletTransaction = trackerOperation.ToWalletTransaction(chain, "default");
					Console.WriteLine("TX ID: {0}.", walletTransaction.Transaction.GetHash());
				};

				trackerBehavior.Scan(scanLocation, skipBefore);
				trackerBehavior.SendMessageAsync(new MempoolPayload());

				trackerBehavior.RefreshBloomFilter();
			};
		}
	}
}

https://github.com/djpnewton/NBitcoin.SPV.TrackAddressBasic/blob/master/NBitcoin.SPV.TrackAddressBasic/Program.cs

i am using that code as a reference, I also tried to use the code you did on the SPVWallet Example, but failed big time

**Comment by NicolasDorier** [comment]
SPV stuff is now deprecated, do not use it.

Try `var node = Node.ConnectToLocal(Network.Main);` then `node.Handshake();`, the you can do what you want with `node`.

**Comment by compilenewbe** [comment]
And is there a way to track addresses without using spv?

**Comment by NicolasDorier** [comment]
The only way I can recommend is by having your own full node, running [NBXplorer](https://github.com/dgarage/NBXplorer) and call the API.

**Comment by NicolasDorier** [comment]
Check https://programmingblockchain.gitbooks.io/programmingblockchain/content/wallet/ for an introduction.

**Comment by compilenewbe** [comment]
if SPV is deprecated, how does your example of SPVWallet still works?

**Comment by compilenewbe** [comment]
Btw, Thanks for your help.

**Comment by NicolasDorier** [comment]
It is based on very old code. SPV will disappear, it has too much practical problem and privacy issues.

**Comment by compilenewbe** [comment]
So the best solution is to use NBXplorer, do you know if that can also run on linux servers?

**Comment by NicolasDorier** [comment]
@compilenewbe yes it can. It has a docker image if you need as well.
