### ISSUE TITLE
Script parsing is giving wrong address

### ISSUE THREAD

**Issue by ejholdings** [MetacoSA/NBitcoin#458]
I am getting very strange results when trying to parse scripts.  Here is an example:

`//Get Data from DB
SqlCommand cmd = new SqlCommand();
cmd.CommandText = "SELECT OutputScript FROM [BTC].[dbo].[TransactionOutput] WHERE TransactionOutputId = 5";
cmd.Connection = conn;
byte[] arr = (byte[])cmd.ExecuteScalar();

//Instantiate Script object
NBitcoin.Script script = new Script(arr);

//Get the address
BitcoinAddress ba2 = script.PaymentScript.GetDestinationAddress(Network.Main);`

The result I get in ba2?  "3P25dtEAem88Ek5FdA5otddoDb2FjrxgCY"

The raw script (as my SQL query above suggests) corresponds with the fifth transaction output in the blockchain (which is the output in block #5 / block hash: 000000009B7262315DBF071787AD3656097B892ABFFD1F95A1A022F896F533FC

The hex represenatation of the output script I'm passing in is:
0x410456579536D150FBCE94EE62B47DB2CA43AF0A730A0467BA55C79E2A7EC9CE4AD297E35CDBB8E42A4643A60EEF7C9ABEE2F5822F86B1DA242D9C2301C431FACFD8AC

I a truly confused as to why I would get 3P25dtEAem88Ek5FdA5otddoDb2FjrxgCY as the public address.  This is a bogus result (compare to: https://blockexplorer.com/block/000000009B7262315DBF071787AD3656097B892ABFFD1F95A1A022F896F533FC).

**Comment by NicolasDorier** [comment]
`script.PaymentScript.GetDestinationAddress(Network.Main);` is giving you P2SH version of the script.

`script.GetDestinationAddress(Network.Main);` will give you the expected result.

**Comment by ejholdings** [comment]
Hi Nicolas,

Thank you very much for your response.

I tried what you suggested as below:

```
//Get Data from DB
SqlCommand cmd = new SqlCommand();
cmd.CommandText = "SELECT OutputScript FROM [BTC].[dbo].[TransactionOutput] WHERE TransactionOutputId = 5";
cmd.Connection = conn;
byte[] arr = (byte[])cmd.ExecuteScalar();

//Instantiate Script object
NBitcoin.Script script = new Script(arr);

//Address
BitcoinAddress addr = script.GetDestinationAddress(Network.Main);
```

When I step through the debugger, I get:
script == {0456579536d150fbce94ee62b47db2ca43af0a730a0467ba55c79e2a7ec9ce4ad297e35cdbb8e42a4643a60eef7c9abee2f5822f86b1da242d9c2301c431facfd8 OP_CHECKSIG}

This seems right -- I get the same results if I run this through an old Python script I have.  

However, when I step through `addr = script.GetDestinationAddress(Network.Main);`  I get 'null' as the result instead of an address.  Given that the return type of GetDestinationAddress() is a BitcoinAddress, I would expect the result of the method is the address.  Am I doing something else wrong?

**Comment by NicolasDorier** [comment]
`0456579536d150fbce94ee62b47db2ca43af0a730a0467ba55c79e2a7ec9ce4ad297e35cdbb8e42a4643a60eef7c9abee2f5822f86b1da242d9c2301c431facfd8 OP_CHECKSIG` is an old style `scriptPubKey` which can't be represented as an address. Block explorer telling you it can be an address are lying to you by using `script.GetDestinationPublicKeys()[0].Hash.GetAddress(Network.Main);`.

To understand why it is a lie, read https://programmingblockchain.gitbooks.io/programmingblockchain/content/

**Comment by ejholdings** [comment]
Thank you much for your help.  I have started reading your book, as well.  It looks to be a great resource!  Many thanks.
