### ISSUE TITLE
Missing height in BlockHeader or Block Entity

### ISSUE THREAD

**Issue by arkoc** [MetacoSA/NBitcoin#461]
I was trying to retrieve Block by RPC or REST Client. But unfortunately I can't get Height of retrieved block nor from retrieved block header.

Is `Height` property missing from that entities?
Is there other way for retrieving it ?

Also is there any way to get block hash or block number from `Transaction` entity ?

**Comment by NicolasDorier** [comment]
Yes, the `GetBlock` of RPCClient send you the block and only the block.

If you update your package to `4.1.1.25` you can use `Block.GetCoinbaseHeight` (which I did for you just now).

That said, in the future, if you want to access to the raw json of `RPCClient`, use the following example.
```
var resp = await SendCommandAsync(RPCOperations.getblock, blockId, true).ConfigureAwait(false);
```
