### ISSUE TITLE
Can I share NoedGroup between several SPV Wallets?

### ISSUE THREAD

**Issue by Kikimora** [MetacoSA/NBitcoin#462]
Hi All!

I know SPV deprecated but for some reasons I cannot migrate from it just yet. I wonder if I can share same NodeGroup object between multiple Wallet instances to track different addresses.

Any help much appreciated.

**Comment by nopara73** [comment]
Did you try it? I'm using NodesGroup, too and I am reusing the NodesGroup during many unit test on the regtest without issues. Of course regtest is not the same, still. https://github.com/zkSNACKs/WalletWasabi

**Comment by NicolasDorier** [comment]
Yes it should be OK.

**Comment by Kikimora** [comment]
Thanks. After some research I found this was as issue in my code.

**Comment by nopara73** [comment]
Happy to hear it. You can close this issue then.
