### ISSUE TITLE
Can we add more BouncyCastle?

### ISSUE THREAD

**Issue by nopara73** [MetacoSA/NBitcoin#463]
We are using some BouncyCastle classes those are not in NBitcoin: https://github.com/zkSNACKs/WalletWasabi/blob/master/WalletWasabi/Crypto/BlindingRsaKey.cs

This requires us to include BouncyCastle to our project as a dependency, which creates a lot of duplicated namespaces. We would like to fix this.

@NicolasDorier Can we add a few more BouncyCastle classes?

**Comment by NicolasDorier** [comment]
All the classes of BouncyCastle are internal to prevent conflict if a project referencing NBitcoin also have BouncyCastle dependency.

Why not using the BouncyCastle.Portable nuget package?

**Comment by nopara73** [comment]
> All the classes of BouncyCastle are internal to prevent conflict if a project referencing NBitcoin also have BouncyCastle dependency.

That's good. So you'd just have to make 2 classes public, no need to add new code.

> Why not using the BouncyCastle.Portable nuget package?

That's what we are doing. But we don't want to duplicate dependencies for 2 classes. Because NBitcoin is already doing that and our code has matured already for a year we'd rather use NBitcoin than another NuGet.

**Comment by NicolasDorier** [comment]
Which class do you need? I would really prefer keeping everything private though.

**Comment by nopara73** [comment]
Maybe more than two classes :)

```
RsaBlindingEngine
RsaEngine
PssSigner

RsaKeyParameters
RsaKeyGenerationParameters
RsaBlindingParameters
AsymmetricCipherKeyPair

RsaKeyPairGenerator
RsaBlindingFactorGenerator

Sha256Digest
SecureRandom
```

**Comment by NicolasDorier** [comment]
Why not just copy paste them in your project, it is not so big.
