### ISSUE TITLE
Digibyte (DGB) Support

### ISSUE THREAD

**Issue by Stevenkingx** [MetacoSA/NBitcoin#464]
Can any of you guys have the time and the kindness to add support for Digibyte, Please i was trying but i get lost with some parameters loke the PowLimit in digibyte it looks different for example  

Litecoin look like this: PowLimit = new Target(new uint256("00000fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff")),
But Digibyte like this: consensus.powLimit = ArithToUint256(~arith_uint256(0) >> 20);

thanks a lot

**Comment by lontivero** [comment]
`~arith_uint256(0) >> 20` is equal to:
`0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff >> 20`which is equal to:
`0x00000fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`

Now you can do it.

**Comment by NicolasDorier** [comment]
I don't have time to add support for hundredth altcoins, I depend on their respective community to add their own support. You don't have to get the PoW stuff right, it is not really used by anybody.

**Comment by shtse8** [comment]
I am still waiting DGB. Anyone can help?

**Comment by NicolasDorier** [comment]
Ask DGB devs to add their support, the PoW part is optional.
