### ISSUE TITLE
AddressManager with small number of peers burns CPU

### ISSUE THREAD

**Issue by Kikimora** [MetacoSA/NBitcoin#466]
I came across this while investigating why our tests consume so much CPU. I found that AddressManager has Select method which generate random indexes into large table until it succeed and fine one peer. In my tests i have only 1 peer and this method burns most of dev machine CPU. 

In the past Kubernetes has shut down few of our staging nodes due to high CPU consumption. I think that AddressManager was the actual reason for this. 

I wonder if there is a better way to select random peers?

**Comment by NicolasDorier** [comment]
@Kikimora this need to be fixed indeed. The best would be to sync AddressManager implementation from the Bitcoin Core implementation, as it probably changed a lot, and see if this problem is still here.

**Comment by lontivero** [comment]
@NicolasDorier I think my last PR fixes this problem. https://github.com/MetacoSA/NBitcoin/pull/499
