### ISSUE TITLE
How to parse Bitcoin cash address?

### ISSUE THREAD

**Issue by Kikimora** [MetacoSA/NBitcoin#471]
Maybe I'm missing something obvious but I think there is a bug in Bitcoin Cash address parsing. Below test cases fails with exception with valid BCH main net address.

```
       [Fact]
        public void Parse1()
        {
            NBitcoin.Altcoins.BCash.Instance.Mainnet.Parse<BitcoinAddress>("bitcoincash:1NubKTUGUuGNwATXKLbzdAYNDtJieaSroN");
        }
        
        [Fact]
        public void Parse2()
        {
            NBitcoin.Altcoins.BCash.Instance.Mainnet.Parse<BitcoinAddress>("1NubKTUGUuGNwATXKLbzdAYNDtJieaSroN");
        }
```

**Comment by Kikimora** [comment]
For anyone who stumble with same issue this is what I found. Bitcoin cash has 2 types of addresses - old one inherited from Bitcoin and new one called CashAddr. Pretty much everybody now use CashAddr format and above code can parse it. Old Bitcoin style addresses can be parsed with Network.Main instance.

I think this is an issue in Bitcoin Cash implementation. Ideally it should be able to parse both type of addresses.

**Comment by NicolasDorier** [comment]
Yes, I don't allow parsing of normal bitcoin address, it results into people loosing money.

If you really want to do it, you can convert to bcash address this way:

```
var addr = BitcoinAddress.Create("1NubKTUGUuGNwATXKLbzdAYNDtJieaSroN", Network.Main);
var bcashAddr = addr.ToNetwork(NBitcoin.Altcoins.BCash.Instance.Mainnet);
```
