### ISSUE TITLE
BitcoinCash MissingMethodException is latest version (4.1.1.26)

### ISSUE THREAD

**Issue by mjwaddell** [MetacoSA/NBitcoin#472]
I'm testing using the latest version of NBitcoin (4.1.1.26) and Altcoins (1.0.1.11). The call to txbldr.AddKnownSignature(...) throws an exception:
**'System.MissingMethodException' occurred in NBitcoin.dll: 'Method not found: 'Int32 NBitcoin.Script.FindAndDelete(NBitcoin.OpcodeType)'.'**

This error does not occur with the previous NBitcoin version (4.1.1.20).

Here is the full test code:

```
ExtKey RootKey = ExtKey.Parse("xprv9y.....");

TransactionBuilder bldr = new TransactionBuilder();
bldr.SetConsensusFactory(NBitcoin.Altcoins.BCash.Instance.Mainnet);
bldr.Send(new BitcoinPubKeyAddress("1Cx...."), Money.Satoshis(200000));
bldr.SetChange(new BitcoinPubKeyAddress("1Q8...."));
bldr.SendFees(Money.Satoshis(4000));
Coin cn;
bldr.AddCoins(cn = new Coin(
    new OutPoint(new uint256("c72...."), 0), 
    new TxOut(Money.Satoshis(396000), new BitcoinPubKeyAddress("15J...."))));

Transaction tx = bldr.BuildTransaction(false); 

//Error here
bldr.AddKnownSignature(new PubKey("03809...."), tx.SignInput(
     new BitcoinSecret(RootKey.Derive((uint)1).Derive(1).PrivateKey,
           NBitcoin.Altcoins.BCash.Instance.Mainnet), cn));
```

Please take a look and let me know what the issue is.

Thanks

**Comment by NicolasDorier** [comment]
Oops, I just pushed new version of NBitcoin.Altcoins and NBitcoin to fix that, update and it should work.
