### ISSUE TITLE
Bitcoin cash SPV fails to load chain beyond certain block

### ISSUE THREAD

**Issue by Kikimora** [MetacoSA/NBitcoin#479]
This method fails to load BCH blocks after hard fork block (1188698). After this block it returns false.

```
public bool CheckProofOfWorkAndTarget(Consensus consensus)
{
    AssertHasHeader();
    return Height == 0 || (Header.CheckProofOfWork() && Header.Bits == GetWorkRequired(consensus));
}
```

This is how bitcoin cash does it.
```
uint32_t GetNextWorkRequired(const CBlockIndex *pindexPrev,
                             const CBlockHeader *pblock, const Config &config) {
    const Consensus::Params &params = config.GetChainParams().GetConsensus();
   <...>
    if (IsDAAEnabled(config, pindexPrev)) {
        return GetNextCashWorkRequired(pindexPrev, pblock, config);
    }
    return GetNextEDAWorkRequired(pindexPrev, pblock, config);
}
```

**Comment by NicolasDorier** [comment]
It is currently impossible to customize `GetWorkRequired` for altcoins, so I will not fix it.
I accept PRs which would allow such customization and one which fix BCash.

However, I think NBitcoin should not have to validate PoW as I advise against connecting to untrusted node with NBitcoin. All components of NBitcoin has the ability to ignore PoW.
