### ISSUE TITLE
Partially signing an Unsigned Multisig Transaction

### ISSUE THREAD

**Issue by felipegtx** [MetacoSA/NBitcoin#481]
Hello everybody,

I'm using a code that's very similar to what was suggested [here](https://github.com/MetacoSA/NBitcoin/issues/288#issuecomment-336079751) but I keep getting an error: `throw new InvalidOperationException("You need to provide P2WSH or P2SH redeem script with Coin.ToScriptCoin()");`.

In my case I have a single transaction that contains coins from several different Multisig wallets and I'm sending this transaction to be signed by the owners of those wallets. I'm even sending the coins grouped by the owner wallet address so I easily find the ones each participant can sign but, as soon as I call the `SignTransaction` method, providing the current unsigned transaction I get the exception. 

Here's an excerpt from the code I'm using:

```csharp
var builder = new TransactionBuilder();
var newTransaction = builder
                    .AddCoins(coinsFromThisWallet)
                    .AddKeys(new BitcoinSecret(privateKey, _network))
                    .SignTransaction(unsignedTransaction);
```

And here's the Hex for the `unsignedTransaction` object:

```
010000000f85369d94509e439716dea7801d54752e146aa7396fa4746a45226b8481d7a67c0100000000ffffffff926755034a637ff14721c02b1874c6397f1ebe08d48dbb6cc9dfcd032c8430410100000000ffffffff939984eb73b5f2e44c9cdfb74f837532bc3135f0026b9731105341231fedd56c0100000000ffffffffe80766ddadc553f31679e6d79509516fbd2539b7c5e8e153b2e8698b40af81e40100000000fffffffff510571759794d4a677b52239d5e3444a780ac362bf519dd71e1a3f0188e5b220100000000ffffffff7d6f4e19b8516660aa0896acfe10025cbd86c5c21d9f644f98e64259050fe3030000000000ffffffff218c5828d9617eb609055885332f6e26ba5a9067865d82af8b54fd033699a1fc0100000000ffffffff2c233d3d9af2e711a2d7515decee07c240b48fa20a13ecea48d1935c4f538d340100000000ffffffff33019ee5dc24c054f12e95c4825af15ecee48e4451d2ec0fab18501f6686973b0000000000ffffffff5d466fa35ce0ac4e2e8d219de62106c0cb3259be9b2ff95362ee069a98c6898b9800000000ffffffff5e3b9f20fd0c867909f4aa0db3576ab1abaca2aab036e34f8b293fd42d9bd9870100000000ffffffff617c401cadeaf95d077949473b982734ce84ca5a4b1bdc7f743294a5d62a29300000000000ffffffff8a87942f6f056a9e17d34e1cf61f34194cbc1624a582ce32ed4d9ddcb211bef40000000000ffffffffbd3a324f84e794c3417388746e7d5e75a7a29b2b95b79be87794cd7e8e21870f0000000000fffffffff4f2d12f8dba20a1340bc743b8632fc2931c62384d6f5a93618283c8346ee8a70000000000ffffffff01a7adcc32000000001976a9142a29ebedf9c527beee8465df27efcfbca9a8a23588ac00000000
```

**Comment by NicolasDorier** [comment]
As it says, you need to provide the redeem script (`ScriptCoin`) for those `coinsFromThisWallet`.

See https://programmingblockchain.gitbooks.io/programmingblockchain/content/other_types_of_ownership/p2sh_pay_to_script_hash.html what a Redeem Script is

**Comment by Ilchuk-Mihail** [comment]
You only need 

```
Script redeemScript =
    PayToMultiSigTemplate
    .Instance
    .GenerateScriptPubKey(2, new[] { bob.PubKey, alice.PubKey, satoshi.PubKey });

ScriptCoin coin = received.Outputs.AsCoins().First()
                                    .ToScriptCoin(redeemScript);
```

I'm not  sure, but maybe is better to use P2WSH ? This will reduce the fee
I do not know how to do it exactly(

**Comment by NicolasDorier** [comment]
If you get the same error it means you are passing some coins which are not `ScriptCoin`.

**Comment by felipegtx** [comment]
@NicolasDorier Actually, now I'm getting the following exception `The redeem provided does not match the scriptPubKey of the coin` when building the unsigned transaction.

**Comment by felipegtx** [comment]
@NicolasDorier Also, I even tried a different approach to get the `redeemScript` but I got the same exception message (`The redeem provided does not match the scriptPubKey of the coin`).

```csharp
var sourceWallet = "2 03867a55377913963d47ed7ec2400f9fb9da960d5f1047f40592791ca7f2c27bcf 03d888de6e47c5b9d07e72ba240567019ac4ae25d6ea25e33ecfd60e4ef3dec16a 039bf7c587ddd2292dfd304de3f4dc69c6e199f7e52d14bc3648aaf3b57c5fc536 3 OP_CHECKMULTISIG";
var owners = new Script(sourceWallet)?.GetDestinationPublicKeys();
var redeemScript = PayToMultiSigTemplate.Instance.GenerateScriptPubKey(owners.Length, owners);
currentTransactionBuilder.AddCoins(coin.ToScriptCoin(redeemScript));
```

**Comment by felipegtx** [comment]
@NicolasDorier So I got this figured out.

Here's what I learned in case someone else runs into the same issue:

 - I was getting the wrong Redeem Script because I was assuming a format where all of the `n` owners of the wallet would need to sign the transaction. In my case, it was actually `2` out of `3`;
 - I wasn't actually (de)serializing the `Coins` as `ScriptCoins` but as *regular* `Coins`.

Got those two things sorted out and voilà! 

Thank you once again for the tips!

**Comment by NicolasDorier** [comment]
Note that for serialization, NBitcoin has a bunch of `JsonConverter` which you can use with `Serializer.RegisterFrontConverters(JsonSerializerSettings)`. 

It automatically tell to json.net how to properly convert lot's of basic NBitcoin types into json.
