### ISSUE TITLE
INSUFFICIENTFEE error but transaction went thru

### ISSUE THREAD

**Issue by Kikimora** [MetacoSA/NBitcoin#483]
I just came cross the case when NBitcoin reported rejected transaction but it actually went thru. NBitcoin connected to a few nodes and broadcaster transaction. One of peers reported INSUFFICIENTFEE and I get rejection from NBitcoin. While other nodes accepted transaction and successfully processed it. I don't know if this is intended but it is definitely confusing.

**Comment by NicolasDorier** [comment]
Indeed, would you mind sharing this transaction? Are you using latest version of NBitcoin? I fix a bug this week which may have made you pay less fee than you should.

**Comment by NicolasDorier** [comment]
@Kikimora so here is the issue: 1000 Satoshis  per KB should be accepted almost everywhere.

999 Satoshis per KB will be accepted nowhere. And there was a bug I fixed like 1 week ago where 999 could happen in some conditions.

> When I received report that transaction rejected I assume it is failed. But since other nodes might have accepted it my assumption is wrong. With current API it is hard to say if transaction actually went to blockhain or not and this is my primary concern.

Do not try to broadcast by sending to random nodes, it is difficult to get right. Instead use https://github.com/dgarage/NBXplorer and use NBXplorer.Client to connect to it.

> With current API it is hard to say if transaction actually went to blockhain or not and this is my primary concern.

There is no API which can tell you that, before you actually see it in a block.
