### ISSUE TITLE
Question: Is it possible to use GetBalance() with NBitcoins.Altcoins? 

### ISSUE THREAD

**Issue by TJvrDev** [MetacoSA/NBitcoin#484]
Is it possible to use GetBalance() with NBitcoins.Altcoins? 

These are the steps I took:
 
Added the Nbitcoin.Altcoins DLL
Changed Nbitcoin.Network.Testnet to Nbitcoin.Altcoins.Litecoin.Instance.Testnet;
Updated my private key from a Bitcoin private key to a Litecoin private key.
 
When I tried to retrieve my balance, I got this error:
FormatException: The version prefix does not match the expected one 239
NBitcoin.Base58Data.SetString[T] (System.String psz) (at <e76609dad26e47e786f4c0edd5ecb8f2>:0)
NBitcoin.Base58Data.Init[T] (System.String base64, NBitcoin.Network expectedNetwork) (at <e76609dad26e47e786f4c0edd5ecb8f2>:0)
NBitcoin.BitcoinSecret..ctor (System.String base58, NBitcoin.Network expectedAddress) (at <e76609dad26e47e786f4c0edd5ecb8f2>:0)

**Comment by NicolasDorier** [comment]
`var ltcKey = new BitcoinSecret("bitcoinKey", Network.Main).ToNetwork(Altcoins.Litecoin.Instance.Testnet);`
