### ISSUE TITLE
Exception Invalid password (or invalid Network) Key.Parse

### ISSUE THREAD

**Issue by sixjac** [MetacoSA/NBitcoin#485]
e = {System.Security.SecurityException: Invalid password (or invalid Network)
   at NBitcoin.BitcoinEncryptedSecretNoEC.GetKey(String password)
   at BTCLib.KeyManagement.Safe.LoadAsync(String password, String walletFilePath, String filename, Network network)}

Exception thrown when Key.Parse called with encrypted seed (private key)

**Comment by nopara73** [comment]
Could you show code that reproduces it?

**Comment by sixjac** [comment]
internal static Safe LoadAsync(string password, string walletFilePath, string filename, Network network)
        {
            //if (!File.Exists(walletFilePath + filename))
            //  throw new ArgumentException($"No wallet file found at {walletFilePath}");

            var fullpath = walletFilePath + filename;
            var walletFileRawContent = WalletFileSerializer.DeserializeAsync(walletFilePath, filename);

            var encryptedBitcoinPrivateKeyString = walletFileRawContent.EncryptedSeed;
            var chainCodeString = walletFileRawContent.ChainCode;

            var chainCode = Convert.FromBase64String(chainCodeString);

            DateTimeOffset creationTime = DateTimeOffset.ParseExact(walletFileRawContent.CreationTime, "yyyy-MM-dd", CultureInfo.InvariantCulture, DateTimeStyles.AssumeUniversal);

            var safe = new Safe(password, filename, network, creationTime);

            Key privateKey = null;
            foreach (var n in Network.GetNetworks())
            {
                 //Exception
                privateKey = Key.Parse(encryptedBitcoinPrivateKeyString, password, n);
                if( privateKey != null )
                    break;
            }
            // if private key still null throw the 
            privateKey = privateKey ?? Key.Parse(encryptedBitcoinPrivateKeyString, password, safe.Network);

            var seedExtKey = new ExtKey(privateKey, chainCode);
            safe.SetSeed(seedExtKey);

            return safe;
        }

**Comment by nopara73** [comment]
What is the `password` and the `network` you are using?

**Comment by sixjac** [comment]
Password i made was just Schleutte and Testnet

Regards,
Sean Ryan

________________________________

**Comment by nopara73** [comment]
Oh, I also need the `encryptedBitcoinPrivateKeyString`.

**Comment by sixjac** [comment]
Contents of wallet

{
  "EncryptedSeed": "6PYUfqX19h7icjQDXxHRs36MQY2ApiCzLAWuFtmTg65579FoKfPbr9i1Lm",
  "ChainCode": "zZZ8f0gbnVqK009XT7GCYQQRFHechV3tAqi/TiaiCHE=",
  "CreationTime": "2018-07-25"
}

**Comment by nopara73** [comment]
It doesn't throw any exception:

```cs
var encryptedBitcoinPrivateKeyString = "6PYUfqX19h7icjQDXxHRs36MQY2ApiCzLAWuFtmTg65579FoKfPbr9i1Lm";
var password = "Schleutte";
var n = Network.TestNet;
Key.Parse(encryptedBitcoinPrivateKeyString, password, n);
```

**Comment by sixjac** [comment]
If i use the following it works but if i actually use the 'n' variable from Network.GetNetworks() it throws :

Key privateKey = null;
foreach (var n in Network.GetNetworks())
{
     privateKey = Key.Parse(encryptedBitcoinPrivateKeyString, password, Network.TestNet);
     if( privateKey != null )
         break;
}

**Comment by sixjac** [comment]
No neet to loop networks anyway, using the network the wallet was built with suffices.
