### ISSUE TITLE
Tx.ToString(...) produces bad E-notation for small amounts

### ISSUE THREAD

**Issue by mjwaddell** [MetacoSA/NBitcoin#486]
For a Bitcoin transaction with a small send amount (0.00005), Tx.ToString creates json with the amount formatted as 5E-05.0. The E-notation is incorrect (trailing .0) and it would be preferred if the json was created with the expanded number (0.00005).

How do I get this done?

The function call is 
`var decodedTx = tx.ToString(NBitcoin.RawFormat.Satoshi, network);`

Here is a block from the output (note the value field): 

```
"vout": [ {
"value": 5E-05.0,
"n": 0,
"scriptPubKey": { ..... }
}, .... ]
```

Thanks

**Comment by NicolasDorier** [comment]
I agree, please, make a PR for it. That said I plan to deprecate the Satoshi format.

**Comment by NicolasDorier** [comment]
Closing this as the satoshi format is deprecated.
