### ISSUE TITLE
QBitNinjaClient support for LiteCoin

### ISSUE THREAD

**Issue by EstebanGameDevelopment** [MetacoSA/NBitcoin#487]
Hello Nicolas,

A friend is interested to develop a project in Unity using LiteCoin and he is interested to use as a starting point the work I did last year (https://github.com/EstebanGameDevelopment/YourBitcoinController). I have imported the NBitcoin.Altcoin.DLL and selected the network:
 
NBitcoin.Altcoins.Litecoin.Instance.Testnet

I was able to create new keys with NBitcoin API and make transactions with web like (http://testnet.litecointools.com/), but when I try to get the balance with (QBitNinjaClient) I'm not able to recover the right information. Is there any way to find a solution for that?

There is a growing interested of Unity developers to use cryptocurrencies and the Blockchain for their applications. I have developed also a Unity wallet with NEthereum and I got to know a little bit about smart contracts. And the number of downloads in the Unity Asset Store are growing as the time goes on.

Also, I don't know it's related to LiteCoin, but recently I've heard nice things about Dash cryptocurrency and maybe I will explore that option in the future.

Best

**Comment by NicolasDorier** [comment]
hey, I don't have time to adapt QBitNinja for Litecoin.
That said it should be easy for someone motivated to do.

**Comment by NicolasDorier** [comment]
it should now, you need to host your own server though. Also I did not tested it.
