### ISSUE TITLE
How do I parse the blockchain?

### ISSUE THREAD

**Issue by tzachshabtay** [MetacoSA/NBitcoin#488]
I see that you marked the bitcoin core stuff obsolete, and also mention it is obsolete in this article: https://www.codeproject.com/Articles/784519/NBitcoin-How-to-scan-the-Blockchain

But I can't find any reference to what it was replaced with. How do we parse the blockchain with NBitcoin now?

Thanks.

**Comment by NicolasDorier** [comment]
Use `Node.GetBlocks` on one of your trusted node.

**Comment by tzachshabtay** [comment]
@NicolasDorier thanks, but I'm confused: how do I point the node to the blocks folder I've downloaded with bitcoin core?
Looking at the class, the only constructor for Node gets a network address? https://github.com/MetacoSA/NBitcoin/blob/91aa6ece75249b3a4fcf9651cb037d88839bc0e5/NBitcoin/Protocol/Node.cs#L705
I don't see any overload for setting a path?

Also (side note), why would I even need a node if I don't intend to interact with the network? I just want to parse the files.

Thanks.

**Comment by tzachshabtay** [comment]
Ok, I think I got it, by trusted node you meant running a node via bitcoin core itself,  and then I can do `Node.ConnectToLocal(Network.Main).GetBlocks()`. Thanks, this works for me (though I'm still curious if there's a way to parse it offline).

I've got another problem now, when I iterate through the blocks, even with an empty foreach, memory gets higher and higher until my machine completely dies.
I tried forcing a full gc, doing something like this:

```csharp
var node = Node.ConnectToLocal(Network.Main);
var blocks = node.GetBlocks();
long count = 0;
foreach (var block in blocks)
{
    count++;
    if (count % 10000 == 0)
    {
         GCSettings.LargeObjectHeapCompactionMode = GCLargeObjectHeapCompactionMode.CompactOnce;
         GC.Collect(2, GCCollectionMode.Forced);
         GC.WaitForPendingFinalizers();
    }
}
```

That didn't work, though, so it seems like there's an actual leak? Around 150K blocks it reachs 4-5 GB so I kill the process before my computer dies again.

I'm running on a linux box (ubuntu 16.04), so there's no simple way to profile the memory. I tried running with LLDB, but it doesn't seem to resolve NBitcoin's symbols (is the nuget package using a symbol server? Not sure exactly how to make it work).
Here's the top memory consumers from what sos DumpHeap -stat gives me on about ~500MB dump (killed the process at 120K blocks), in case it helps:

```
00007fab87e29be8   110318      6177808 System.Threading.CancellationTokenSource+CallbackPartition[]
00007fab87e3dc50   110381      6181336 System.Threading.CancellationTokenSource+CallbackPartition
00007fab889fbe50   123761      6930616 UNKNOWN
00007fab8855e280   120360      8601192 UNKNOWN
00007fab87e4d610   120067      9605360 System.Threading.CancellationTokenSource+Linked1CancellationTokenSource
0000000001a6fe30   448076     10755812      Free
00007fab87e3f488   119346     11457216 System.Threading.CancellationTokenSource+Linked2CancellationTokenSource
00007fab882550b0   244360     13684160 UNKNOWN
00007fab8825a618   662405     15897720 UNKNOWN
00007fab8855e590   630996     20191872 UNKNOWN
00007fab8855d860   439254     21084192 UNKNOWN
00007fab8855c910   439254     21084192 UNKNOWN
00007fab8855b558   662404     21196928 UNKNOWN
00007fab88255898   439254     24598224 UNKNOWN
00007fab8855e108   440514     24823656 UNKNOWN
00007fab8855d650   440515     25579664 UNKNOWN
00007fab8855b320   630996     30287808 UNKNOWN
00007fab87e3f408   469075     37526000 System.Threading.CancellationTokenSource+CallbackNode
00007fab88259cf8  1243692     59697216 UNKNOWN
00007fab8825d6b8  1293401     62083248 UNKNOWN
00007fab87e19c38  1414695    125111539 System.Byte[]
Total 11218602 objects
```

**Comment by NicolasDorier** [comment]
@tzachshabtay can I ask you what you want to do exactly? `GetBlocks` is rarely used, and depending on your goal I can orient you with better solutions.

That said, `GetBlocks` leaking is definitively a bug I should fix. Looking to it now.

**Comment by NicolasDorier** [comment]
Thanks to your dump, I probably identified the leak. I am pushing 4.1.1.33 package, can you do a try?

**Comment by tzachshabtay** [comment]
@NicolasDorier thanks, the situation is a little better now, but still leaking.
It reaches 180K blocks now before getting to 4-5 GBs.

The dump now is even more cryptic (dumping at 140K blocks, something like 1.5GB):

```
00007f4cf02a08a8      106         2544 System.Object
00007f4cf0f441d0       43         2752 UNKNOWN
00007f4cf0f416d8       44         2816 UNKNOWN
00007f4cf1370d70       71         2840 UNKNOWN
00007f4cf02a3030       44         3168 System.IO.MemoryStream
00007f4cf0aabd78      135         3240 UNKNOWN
00007f4cf0aa9ff0       90         3600 UNKNOWN
00007f4cf12d97d8       86         4128 UNKNOWN
00007f4cf06c1f48        2         4144 UNKNOWN
00007f4cf09c4b90        1         4752 UNKNOWN
00007f4cf0e6ee78       15         6360 UNKNOWN
00007f4cf0289f40      108         7514 System.Char[]
00007f4cf02876b0       28         7736 System.String[]
00007f4cf09c5958       88         8448 UNKNOWN
00007f4cf02a3940      136        14144 System.Reflection.RuntimeMethodInfo
00007f4cf0aa2d40        2        16432 UNKNOWN
00007f4cf02566a0      308        19712 System.Action
00007f4cf02ac3a0      237        20856 System.TimeZoneInfo+AdjustmentRule
00007f4cf0f48328       12        21640 UNKNOWN
00007f4cf06c1658      517        24816 UNKNOWN
00007f4cf02a0908     1100        44000 System.RuntimeType
00007f4cf0f45ef8     1382        44224 UNKNOWN
00007f4cf02806b0      162        47992 System.Int32[]
00007f4cf0286778      131        78296 System.Object[]
00007f4cf029eae8     1656       123196 System.String
00007f4cf1371280       72      1164992 UNKNOWN
00007f4cf0f46b78   140067      3361608 UNKNOWN
00007f4cf0e6f068       15      4327272 UNKNOWN
00007f4cef8594f8   140110      4483520 UNKNOWN
00007f4cf09cb628   140110      5604400 UNKNOWN
00007f4cf0e6b640   140153      5606120 UNKNOWN
00007f4cf0e01680   140152      6727296 UNKNOWN
00007f4cf0e6be50   140979      7894824 UNKNOWN
00007f4cf09ce280   140111     15461344 UNKNOWN
00007f4cf06c50b0   282111     15798216 UNKNOWN
0000000000d73e30   982693     23586282      Free
00007f4cf09cd860  1234329     59247792 UNKNOWN
00007f4cf09cc910  1234329     59247792 UNKNOWN
00007f4cf06ca618  2711097     65066328 UNKNOWN
00007f4cf09ce590  2094564     67026048 UNKNOWN
00007f4cf06c5898  1234329     69122424 UNKNOWN
00007f4cf09cd650  1236362     72787344 UNKNOWN
00007f4cf09ce108  1236362     73817208 UNKNOWN
00007f4cf09cb558  2711096     86755072 UNKNOWN
00007f4cf09cb320  2094564    100539072 UNKNOWN
00007f4cf06c9cf8  2799963    134398224 UNKNOWN
00007f4cf06cd6b8  4805660    230671680 UNKNOWN
00007f4cf0289c38  4946602    461594793 System.Byte[]
Total 30594217 objects
```

> can I ask you what you want to do exactly?

I want to do analysis on the whole blockchain, plotting charts and stuff like that (for example, plot a chart for number of new unique addresses added per day).
