### ISSUE TITLE
Mnemonic creation from Wordlist exception, proper usage

### ISSUE THREAD

**Issue by sixjac** [MetacoSA/NBitcoin#491]
Hi,

the Mnemonic is throwing in the constructor when it reads from the Wordlis.

e = {System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at NBitcoin.Wordlist.<GetWords>b__48_0(Int32 i)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at NBitcoin.Mnemonic..ctor(Wordlist wordList, Byte[] entropy)
...

 stacktrace:

StackTrace = "   at NBitcoin.Wordlist.<GetWords>b__48_0(Int32 i)\r\n   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()\r\n   at NBitcoin.Mnemonic..ctor(Wordlist wordList, Byte[] entropy)\r\n 

Code:
    {
        Wordlist wl = new Wordlist(words, ' ', "");
        var menemonic = new Mnemonic(wl, FindWordCountInWords(ref words)); // Throwing here
    }

    private WordCount FindWordCountInWords(ref string[] words)
    {
        if( words.Length == 12 )
        {
            return WordCount.Twelve;
        }
        else if( words.Length == 15 )
        {
            return WordCount.Fifteen;
        }
        else if( words.Length == 18 )
        {
            return WordCount.Eighteen;
        }
        else if( words.Length == 21 )
        {
            return WordCount.TwentyOne;
        }
        else if( words.Length == 24 )
        {
             return WordCount.TwentyFour;
        }
        return WordCount.Twelve;
    }

**Comment by NicolasDorier** [comment]
What do you want to do? You should not create your own wordlist, use `Wordlist.English`.

**Comment by sixjac** [comment]
The wordlist is the one i get back from the Mnemonic object at wallet creation, i need those words to recover a lost wallet, I am testing recovery....

Cheers

**Comment by NicolasDorier** [comment]
Can you look how to properly use this on https://programmingblockchain.gitbooks.io/programmingblockchain/content/key_generation/key_generation.html#mnemonic-code-for-hd-keys-bip39

**Comment by sixjac** [comment]
Ok thanks for the link, all fine now.
