### ISSUE TITLE
Conducting Transactions using Altcoin

### ISSUE THREAD

**Issue by TJvrDev** [MetacoSA/NBitcoin#497]
I've got my litecoin app almost working, the last piece of this puzzle is broadcasting a transaction. 
I've made changes to acquire exchange rate, connecting to the litecoin.Testnet, but when I broadcast a transacition, it just hangs.

Before I was checking the balance before broadcasting a transaction but for now I commented out that logic until I can refactor QBitNinja to work with Litecoin. 

Is it possible to broadcast a transaction without using QBitNinja? Do you have some example logic that utilizes transaction from NBitcoin.Altcoins you might be able to share?

**Comment by darkfriend77** [comment]
I'm really interested in this also (Broadcasting Altcoin Tx), I tryed to broadcast over a connected Node, but it fails ...

**Comment by NicolasDorier** [comment]
Yes, you can broadcast a transaction with another block explorer like https://smartbit.com.au

**Comment by NicolasDorier** [comment]
I advise you all to rely on https://github.com/dgarage/NBXplorer/ which allows you to have a light block explorer for sending and receiving transaction that you can self host.
