### ISSUE TITLE
Signing Segwit Transaction Offline

### ISSUE THREAD

**Issue by Grey007** [MetacoSA/NBitcoin#500]
Hi, 

I am trying to sign a Segwit Transaction offline. How do I do it? I'm currently not using the transaction builder, do I need to use the transaction builder to sign a Segwit transaction offline?

I get confused on how to use the "AddCoins" in the builder.

Here is my code for fetching the coins:

//Unspent Coins:

```
private static List<Coin> GetUnspentCoins(QBitNinjaClient clientBTC, string pubKey)
        {
            var clientAddress = BitcoinWitPubKeyAddress.Create(pubKey, BitcoinNetwork);

            List<Coin> coinsCustomer = new List<Coin>();         
            var balanceModel = clientBTC.GetBalance(clientAddress, true).Result;
            if (balanceModel.Operations.Count == 0)
            {
                coinsCustomer = null;
            }
            List<Coin> unspentCoins = new List<Coin>();

            foreach (var operation in balanceModel.Operations)
            {
                unspentCoins.AddRange(operation.ReceivedCoins.Select(coin => coin as Coin));
            }
            var balance = unspentCoins.Sum(x => x.Amount.ToDecimal(MoneyUnit.BTC));
            coinsCustomer = unspentCoins;
            return coinsCustomer;
        }```
// input coins 

```private static List<Coin> GetTransactionInputCoins(BitcoinAddress _customerAddress, List<Coin> _coinsCustomer, decimal _totalAmount)
        {
            List<Coin> coinsToSpend = new List<Coin>();
            decimal acumulated = 0;
            //throw new Exception("TOTAL COINS TO ANALIZE[" + _coinsCustomer.Count + "]");
            for (int i = _coinsCustomer.Count - 1; i >= 0; i--)
            {
                var coin = _coinsCustomer[i];
                if (acumulated < _totalAmount)
                {
                    if (coin.TxOut.ScriptPubKey == _customerAddress.ScriptPubKey)
                    {
                        decimal realAmountCoin = coin.Amount.ToUnit(MoneyUnit.BTC);
                        acumulated += realAmountCoin;
                        coinsToSpend.Add(coin);
                    }
                }
            }
            if (coinsToSpend.Count == 0)
            {
                //  throw new Exception("TxOut doesn't contain our ScriptPubKey");
                return null;
            }
            else
            {
                //  throw new Exception("We want to spend " + coinsToSpend.Count + " outpoints");
                for (int k = 0; k < coinsToSpend.Count; k++)
                {
                    //   throw new Exception("    [COIN:" + k + "][AMOUNT:" + coinsToSpend[k].Amount.ToUnit(MoneyUnit.BTC) + "][OUTPOINT:" + coinsToSpend[k].Outpoint.N + "]");
                }

                return coinsToSpend;
            }
        }
```

From there I add the inputs and outputs to the transaction, send it offline to another application that signs the transaction with the private key.

Any suggestions on a better way to do it?

**Comment by NicolasDorier** [comment]
You fetch the `Coin` that you want to spend. Then pass the Coins + the unsigned transaction to the other machine (you can serialize `Coin` and Transaction easily via the `Serializer` class, there is also a bunch of JsonConverters)

**Comment by NicolasDorier** [comment]
```
My problem now comes in when trying to find the redeem script of address: 2My5uj95JwSU225BVup6TDgWTjwbWmscJws.
```

If you know the private key, the redeem script is probably `privateKey.Pubkey.ScriptPubKey`.

**Comment by NicolasDorier** [comment]
How do you generate the address `2My5uj95JwSU225BVup6TDgWTjwbWmscJws`?

**Comment by Grey007** [comment]
`Key privateKey = new Key();
            BitcoinAddress address = privateKey.PubKey.WitHash.GetAddress(BitcoinNetwork);
            var p2sh = address.GetScriptAddress();`

**Comment by NicolasDorier** [comment]
If you use
```
BitcoinAddress address = privateKey.PubKey.WitHash.GetAddress(BitcoinNetwork);
```
Your redeem script is
```
privateKey.PubKey.WitHash.ScriptPubKey
```

**Comment by NicolasDorier** [comment]
Your redeem script is
```
privateKey.PubKey.WitHash.ScriptPubKey
```

**Comment by pozdnyakovasp** [comment]
Hi All!
I need help...
I created p2sh address:

C# create address
            var key = new Key();
            var address = new BlockchainAddress
            {
                Address = key.PubKey.GetScriptAddress(network).ToString(),
                PrivateKey = key.ToString(network);
            };

Have:
    "Address" : "2N85zmWShdzNgbLHsq1vY4dEZt7Sce6BPLy",
    "PrivateKey" : "cPn6Y7ucJtfcXWa9AVRBW4iDUwy3fQ6DpTuL5XAYMj1RiDeSSzsN",

And UTXO
            "Address" : "2N85zmWShdzNgbLHsq1vY4dEZt7Sce6BPLy",
            "TransactionId" : "7ab3dbbfd44f00c92da0e201c95dadef0505dc54a15910dcd38acdf3ca0c25a5",
            "Vout" : 0,
            "Amount" : "0.1"
            "BlockNumber" : 1440316,

Create transaction:
// in
var builder = network.CreateTransactionBuilder();
var txInHash = new uint256("7ab3dbbfd44f00c92da0e201c95dadef0505dc54a15910dcd38acdf3ca0c25a5");
var amount = Money.FromUnit(0.1m, MoneyUnit.BTC);
var bitcoinSecret = new BitcoinSecret("cPn6Y7ucJtfcXWa9AVRBW4iDUwy3fQ6DpTuL5XAYMj1RiDeSSzsN", network);

var coin = new Coin(txInHash, 0u, amount, bitcoinSecret.PubKey.WitHash.ScriptPubKey); // try bitcoinSecret.ScriptPubKey and etc.
var key = Key.Parse(bitcoinSecret.ToWif());

builder.AddCoins(coin);
builder.AddKeys(key);
// out
var amountOut = Money.FromUnit(0.099 MoneyUnit.BTC);
var destination = BitcoinAddress.Create("2N85zmWShdzNgbLHsq1vY4dEZt7Sce6BPLy", network);
builder.Send(destination, amountOut);
// fee
var fee = Money.Coins(0.001u);
builder.SendFees(fee);

// sign
var signedTx = builder.BuildTransaction(true);

// send
var result = await rpcClient.SendRawTransactionAsync(signedTx);

Receive next
16: mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element)

I can not solve this problem for a long time. Please help me.

Use NBitcoin 4.1.1.66

**Comment by NicolasDorier** [comment]
`var coin = new Coin(txInHash, 0u, amount, bitcoinSecret.PubKey.WitHash.ScriptPubKey.Hash.ScriptPubKey).ToScriptCoin(bitcoinSecret.PubKey.WitHash.ScriptPubKey);`

**Comment by pozdnyakovasp** [comment]
Thanks for the response. But it did not help me :-(

Why this code works for `key.PubKey.GetAddress(network).ToString()` and does not work for `GetScriptAddress`.
Maybe I incorrectly use `GetScriptAddress`?

**Comment by NicolasDorier** [comment]
When you do this

```
var address = new BlockchainAddress
{
Address = key.PubKey.GetScriptAddress(network).ToString(),
PrivateKey = key.ToString(network);
};
```

You are not creating a P2WPKH-P2SH address but a plain P2PKH-P2SH address.

**Comment by NicolasDorier** [comment]
`key.PubKey.WitHash.ScriptPubKey.GetAddress(network)` gives you the P2WPKH-P2SH

**Comment by pozdnyakovasp** [comment]
Thank you very much! It works! 
=)
