### ISSUE TITLE
Block size/weight not present inside block object

### ISSUE THREAD

**Issue by AntoineXBTO** [MetacoSA/NBitcoin#501]
Hi

I tried to get the size and weight info from the block object but couldn't find it. Why is it not one of the properties?

**Comment by lontivero** [comment]
Because the can depend on many factors. Did you try looking at the code base? Try this:
```
git grep -ni GetSerializedSize
```

**Comment by AntoineXBTO** [comment]
Thanks for your reply.
Yes I saw that but thought it would include extra data, looks like it doesn't, thx.

What factors is it depending on? I mean the block size calculation is universal no?

**Comment by AntoineXBTO** [comment]
These are for transactions, not blocks (at least I don't see it on the block object but I do on transaction).

**Comment by NicolasDorier** [comment]
For block, use `GetSerializedSize()`

**Comment by AntoineXBTO** [comment]
Didn't see you could add a TransactionOption
Used b.GetSerializedSize(TransactionOptions.None) * 3 + b.GetSerializedSize(TransactionOptions.All) and it worked perfectly to get the weight!
Thanks!

**Comment by NicolasDorier** [comment]
I just added `Block.GetWeight()` in `4.1.1.43`.
