### ISSUE TITLE
Node/network payload code fails

### ISSUE THREAD

**Issue by misternode** [MetacoSA/NBitcoin#502]
I have tried this on several coins, and several nodes (all of which are functioning).  Vis Studio 2017 15.7.6, with .NET Core 2.1.

results in: throw new InvalidOperationException("The node is not in a connected state");  (in 		public TPayload ReceivePayload<TPayload>(CancellationToken cancellationToken = default(CancellationToken))
)

How do I get your library to work?

```
using NBitcoin;
using NBitcoin.Protocol;
using System;
using System.Threading;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            var node = Node.Connect(Network.Main, "52.14.153.105:8333");

            node.VersionHandshake();
        }
    }
}
```

**Comment by misternode** [comment]
I HAVE tried my own nodes.  It fails on EVERY node.

**Comment by knocte** [comment]
Are you sure the port is open from your location?

**Comment by misternode** [comment]
Yes. 100%.

**Comment by NicolasDorier** [comment]
I ran exactly the same code and it worked.

```
static void Main(string[] args)
{   
    var node = Node.Connect(Network.Main, "52.14.153.105:8333");
    Console.WriteLine("Handshaking");
    node.VersionHandshake();
    Console.WriteLine("Connected");
}
```

What OS ?

**Comment by misternode** [comment]
Windows 10, 32 bit.

The TCP connection is made, but no data is sent.  .NET throws InvalidOperationException("The node is not in a connected state") and drops the connection with no data transfered.

**Comment by NicolasDorier** [comment]
Can you try with a local node of yours? You run `bitcoind.exe -regtest` then use `Node.ConnectToLocal(Network.RegTest)`.

**Comment by rnewsham** [comment]
Ran regtest locally and using ConnectToLocal().  Same issue.

**Comment by misternode** [comment]
Just to be thorough, also installed .NET Core 2.1 on linux.

Same results:  Unhandled Exception: System.InvalidOperationException: The node is not in a connected state

**Comment by NicolasDorier** [comment]
Trying to reproduce

**Comment by NicolasDorier** [comment]
```bash
mkdir temp
cd temp
dotnet --version  #2.1.4
dotnet new console
dotnet add package NBitcoin
vim Program.cs
```

Copy pasting 
```bash
using System;
using NBitcoin.Protocol;
using NBitcoin;

namespace temp
{
    class Program
    {
        static void Main(string[] args)
        {
            var node = Node.Connect(Network.Main, "52.14.153.105:8333");
            Console.WriteLine("Handshaking");
            node.VersionHandshake();
            Console.WriteLine("Connected");
            node.Disconnect();
        }
    }
}
```
Then

```bash
dotnet run
# Output: Handshaking, Connected
```
Maybe your locale ? What does `Console.WriteLine(System.Globalization.CultureInfo.CurrentUICulture);` print you ?

**Comment by NicolasDorier** [comment]
or a bug of `dotnet` new version? What does

```
dotnet --version
dotnet --info
```

Show you?

**Comment by NicolasDorier** [comment]
I tried fresh dotnet install:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.302/

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.302 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
What is yours?

**Comment by misternode** [comment]
I didn't 'dotnet add package' NBitcoin. I compiled it from your repo, linked it by editing the xml in the .proj file (in linux) or by using the Dependencies context menu item in Windows VS 2017.

I'll get you version numbers and locale info later today, but it was a fresh install of VS on linux (and my VS on windows was also freshly install just to start with your code a few days ago):


-----------

# build core NBitcoin library on linux with netcoreapp2.1

# https://www.microsoft.com/net/download/linux-package-manager/ubuntu16-04/sdk-current
wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo apt-get install apt-transport-https
sudo apt-get update
sudo apt-get install dotnet-sdk-2.1
dotnet --help  # verify dotnet exists 

git clone https://github.com/MetacoSA/NBitcoin.git
cd NBitcoin/
cd NBitcoin  # the NBitcoin project 

dotnet build -c Debug  -f netcoreapp2.1


# make project that uses NBitcoin 
# https://www.microsoft.com/net/learn/get-started-with-dotnet-tutorial
cd ../../
dotnet new console -o MyNBitcoin
mkdir MyNBitcoin


# add code 
vi Program.cs 

using NBitcoin;
using NBitcoin.Protocol;
using System;
using System.Threading;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {

            var node = Node.Connect(Network.Main, "52.14.153.105:8333");

            Console.WriteLine("Before handshake");
            node.VersionHandshake();
            Console.WriteLine("After handshake");
        }
    }
}

# add reference to NBitcoin.dll in MyNBitcoin.proj
  <ItemGroup>
    <Reference Include="NBitcoin">
      <HintPath>[path]/NBitcoin/NBitcoin/bin/Debug/netcoreapp2.1/NBitcoin.dll</HintPath>
    </Reference>
  </ItemGroup>


dotnet build
dotnet run

**Comment by misternode** [comment]
### $ dotnet --version
2.1.302


locale:   en-US

### $ dotnet --info

.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.302/

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.302 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download


### with dotnet add package NBitcoin

if I use dotnet add package, I don't see the exception.  (but the program doesn't return.  process never completes.  is this normal?  is it running as a node?)

**Comment by NicolasDorier** [comment]
> if I use dotnet add package, I don't see the exception. (but the program doesn't return. process never completes. is this normal? is it running as a node?)

Yes it is normal, you need to run `node.Disconnect()`. Background thread prevent the program from finishing.

**Comment by NicolasDorier** [comment]
> add reference to NBitcoin.dll in MyNBitcoin.proj

This is your project. NBitcoin depends on some other dll, which you did not referenced.
Instead of doing this, run

```bash
dotnet add MyNBitcoin/MyNBitcoin.csproj reference NBitcoin/NBitcoin.csproj
```

This will correctly compile NBitcoin when you compile MyNBitcoin and copy all needed dependencies.

**Comment by misternode** [comment]
Thank you,  that is what I was missing and misunderstanding.
