### ISSUE TITLE
RPC "importpubkey" is missing

### ISSUE THREAD

**Issue by osagga** [MetacoSA/NBitcoin#505]
https://bitcoincore.org/en/doc/0.16.0/rpc/wallet/importpubkey/

I can't even find it in the `RPCOperations` class. Is there a specific reason to why it's not included?

**Comment by nopara73** [comment]
No, many RPC commands are missing, due to simply none of us needed it. Feel free to implement.

**Comment by NicolasDorier** [comment]
you can pass a string instead "importpubkey"

**Comment by osagga** [comment]
Thanks!
