### ISSUE TITLE
Adding pre computed signature to multisig transaction 

### ISSUE THREAD

**Issue by sigHash** [MetacoSA/NBitcoin#506]
Hi! I have a multisig transaction (2 of 3 legacy) and I use hardware wallet to generate the first signature. My hardware wallet can sign each input and return the corresponding signature like:

`3044022051c7546ff919248badd1012317066cc0edd3e5f49050ac54ef52b66a8e80e17b02201dd65963551e0dc7d8ce5721fbd3125fa9272a98bad1ed5df91488a462eac123
`
For the second signature I wanna use NBitcoin and my private key but I don't know how to combine these signatures. 

Is manually manipulating ScriptSig in TxIn the way to go?

Thanks!

**Comment by NicolasDorier** [comment]
You can easily do this with
```csharp
txBuilder.AddCoins(coins)
              .AddKnownSignature(pubKey, signature)
              .AddKeys(otherKey)
              .SignTransactionInPlace(tx);`.
````

**Comment by sigHash** [comment]
Beautiful!

**Comment by sigHash** [comment]
I tried doing this:

```
var AlicePubKey = new PubKey("0280af822a0ff1b1ee295b29d298cae9cd4ff07176cad58b6f47912986fb53abc4");
var BobPubKey = new PubKey("039c32030d923c98f650238d4a7af774982c94dfecbaaf380b81a15cf84d65d8c0");

var AliceKnownSig =  new TransactionSignature(ECDSASignature.FromDER(Encoders.Hex.DecodeData("30440220332839884167be377210de05ead2cdcb638f568f37dd5d5635c4c0bc03c8bb010220068b4d19c2e6a3a3f080823d5a651ba97704ead3ac5ddb29533cf8567973f377")));
var BobKnownSig = new TransactionSignature(ECDSASignature.FromDER(Encoders.Hex.DecodeData("3044022011f34db9dbc20f572ae8bf645c03a9ffb04be6cb318a4c400b0b331ed4589d0002204915232e3d0b4d3be089b8d873d7ff39f5aead22899599171e42dded8fc9e2db")));

var unsignedTx = Transaction.Parse("01000000018e9301345366fb5bd795459667acf5e38d23675f54afa7a70513e46e4eb609d00000000000ffffffff02bd190f000000000017a9144ccc6ea00fa8759f286e53785a84af5396fe401c87102700000000000017a91434cfd88d4600c364b6336378ca807395cab2a5108700000000", Network.TestNet);

var previousTx = Transaction.Parse("020000000001012036e728b61384c8042452f92edd703593a0b481a1283bc4c3f3c2cafd7a66760200000017160014778375a8fda6651885512cb4ba758cff6bc266f2feffffff0240420f000000000017a9144b32c087a2afe703e99c4173a4e641368071fcd987009510000000000017a914959743d95df1e1dd08961e3d1a206eb3747b78948702473044022078a1e09b65a09a0ce945e0ee8d527af131f01263fd64969ecf42a0e6967864b002204bb3ad0f5b0af89ebe720ead13d7c125bc5f11f1324b4816e74f6824a51e8773012103fcb8716d8370ab44b6fc7540a684103629bee77b36b225e7de22701d6681e992dfef1500", Network.TestNet);
var previousTxHash = "d009b64e6ee41305a7a7af545f67238de3f5ac67964595d75bfb66533401938e";

var redeemScript = new Script(Encoders.Hex.DecodeData("5221039c32030d923c98f650238d4a7af774982c94dfecbaaf380b81a15cf84d65d8c0210280af822a0ff1b1ee295b29d298cae9cd4ff07176cad58b6f47912986fb53abc4210365eb4ac3addadfe8af7c66d3ebb969293e957ac86863fccc8224a3d5df2d7f1453ae"));

var scriptCoinToSpend = new ScriptCoin(previousTx, 0, redeemScript);

var builder = new TransactionBuilder();

var signedTx = builder
.AddCoins(scriptCoinToSpend)
.AddKnownSignature(AlicePubKey, AliceKnownSig)
.AddKnownSignature(BobPubKey, BobKnownSig)
.SignTransactionInPlace(unsignedTx);
```

However, 
```
builder.Verify(signed)
```

returns false. Am I missing something?

**Comment by NicolasDorier** [comment]
Seems good to me, have you checked `signedTx` if the ScriptSig was properly filled?

**Comment by NicolasDorier** [comment]
Checking this, it is not signed.

**Comment by sigHash** [comment]
```
{
  "hash": "045c982a9538beea42311924f6d637923f3054d89cfb5ff722f5bf6703a1a0fb",
  "ver": 1,
  "vin_sz": 1,
  "vout_sz": 2,
  "lock_time": 0,
  "size": 226,
  "in": [
    {
      "prev_out": {
        "hash": "d009b64e6ee41305a7a7af545f67238de3f5ac67964595d75bfb66533401938e",
        "n": 0
      },
      "scriptSig": "0 0 0 0 5221039c32030d923c98f650238d4a7af774982c94dfecbaaf380b81a15cf84d65d8c0210280af822a0ff1b1ee295b29d298cae9cd4ff07176cad58b6f47912986fb53abc4210365eb4ac3addadfe8af7c66d3ebb969293e957ac86863fccc8224a3d5df2d7f1453ae"
    }
  ],
  "out": [
    {
      "value": "0.00989629",
      "scriptPubKey": "OP_HASH160 4ccc6ea00fa8759f286e53785a84af5396fe401c OP_EQUAL"
    },
    {
      "value": "0.00010000",
      "scriptPubKey": "OP_HASH160 34cfd88d4600c364b6336378ca807395cab2a510 OP_EQUAL"
    }
  ]
}

```

Is there a problem with signatures?

**Comment by NicolasDorier** [comment]
Yes, I stepped by stepped. The expected signature hash is 22e65a621c8f7e23ab7aaf78ee37c1fe9777ca665786f817582ecf843e6683b9, your signature is not valid.

**Comment by NicolasDorier** [comment]
You can easily get the same signature hash with `unsignedTx.Inputs.AsIndexedInputs().First().GetSignatureHash(scriptCoinToSpend)`

**Comment by sigHash** [comment]
Does that mean my sig doesn't belong to the specified pub key or wrong data has been signed?

**Comment by NicolasDorier** [comment]
It can be one or the other.

**Comment by NicolasDorier** [comment]
Maybe you mixed Alice and Bob sig?

**Comment by sigHash** [comment]
I'm using ledgerjs 

> Maybe you mixed Alice and Bob sig?

I just tried the other way around and didn't work. Have to check my signing

**Comment by sigHash** [comment]
How can I check a provided sig against a pubkey?

**Comment by NicolasDorier** [comment]
something like `pubkey.Verify(signature, hash)`

**Comment by NicolasDorier** [comment]
With hash taken from `unsignedTx.Inputs.AsIndexedInputs().First().GetSignatureHash(scriptCoinToSpend)`

**Comment by sigHash** [comment]
Well, the problem is the garbage output script that ledgerjs returns which generates wrong signatures!!
 
Looks like our friends at Ledger have a long way to match the quality and clarity of what you have created with C# ;)

**Comment by NicolasDorier** [comment]
@sigHash are you using https://github.com/LedgerHQ/ledger-dotnet-api/ ? This is a lib I did for signing with ledger, integrated with NBitcoin so it is quite easy to use.

**Comment by sigHash** [comment]
@NicolasDorier I'm signing in browser

**Comment by NicolasDorier** [comment]
@sigHash you can consider the same strategy I did with BTCPay.

Basically I sign by using my API server side. The APDU get sent to websocket, which get forwarded to U2F.

By doing that, I can still sign with my lib. :D

**Comment by sigHash** [comment]
You mean using Ledger in a web app and sign with your api server side?

**Comment by NicolasDorier** [comment]
I mean I generates all the APDUs server side, and forward them to the ledger in the browser.

So all the code for signing with ledger are server side.

**Comment by sigHash** [comment]
and your server never sees private keys?

**Comment by NicolasDorier** [comment]
Nop

**Comment by sigHash** [comment]
Love that approach! Can you show me some code? must be out there with BTCPay server right?

**Comment by NicolasDorier** [comment]
The only part coupled with my ledger library are here


https://github.com/btcpayserver/btcpayserver/blob/57bb980526516339af4b0f29b5b1e9bdefdbab75/BTCPayServer/Services/HardwareWalletService.cs

As you can see I developped a simple `WebSocketTransport` which send the APDUs through websocket

**Comment by NicolasDorier** [comment]
Here is where it is used https://github.com/btcpayserver/btcpayserver/blob/da2fb876cb5bc9b1237b3112aef358172f8d44a0/BTCPayServer/Controllers/WalletsController.cs#L251

**Comment by NicolasDorier** [comment]
On my client side I use my small bridge ledgerwebsocket.js as you can see on 

https://github.com/btcpayserver/btcpayserver/blob/da2fb876cb5bc9b1237b3112aef358172f8d44a0/BTCPayServer/Views/Stores/AddDerivationScheme.cshtml

**Comment by NicolasDorier** [comment]
Here is all the client side stuff

https://github.com/btcpayserver/btcpayserver/blob/87678c58ac4dc50b81607b463e02cf9087f690a8/BTCPayServer/wwwroot/js/StoreAddDerivationScheme.js

**Comment by sigHash** [comment]
This is the yum yum solution of all yum yum solutions!!!! :D

**Comment by NicolasDorier** [comment]
The bridge itself is here https://github.com/btcpayserver/ledgerwebsocket

**Comment by NicolasDorier** [comment]
you can just copy paste the compiled version on BTCPay though
