### ISSUE TITLE
Bitcoin cash addresses 

### ISSUE THREAD

**Issue by Ilchuk-Mihail** [MetacoSA/NBitcoin#507]
I want to create BCH multi sig address .

I get next addresses  with this code:
```
    //create 3 of 3 multi sig address
    var scriptPubKey = PayToMultiSigTemplate
                .Instance
                .GenerateScriptPubKey(3, generatedKeys);
```
` var address = scriptPubKey.WitHash.ScriptPubKey.Hash.ScriptPubKey.GetDestinationAddress(Network); // P2SH-P2WSH`

For testnet - bchtest:prk4z3k7rkc75r48x6ztx20vl6phqss9wqt58khzs9
For mainnet - bitcoincash:pr0rne4m7vk7xrql0tcepnyd7wm9h7n35qn4hyyvl9

Faucet, explorers, do not suport these addresses. 
How to convert new addresess to old format, wich all suport?

**Comment by bazooka70** [comment]
https://github.com/bazooka70/BCashAddr

**Comment by Ilchuk-Mihail** [comment]
Maybe NBitcoin have internal implementation ?

**Comment by NicolasDorier** [comment]
Use `BitcoinAddress.ToNetwork(Network.Main);` to convert into a BTC address.

**Comment by osagga** [comment]
Does NBitcoin by any chance give the option to display BCH addresses without the network prefix? Something like `prk4z3k7rkc75r48x6ztx20vl6phqss9wqt58khzs9` instead `bchtest:prk4z3k7rkc75r48x6ztx20vl6phqss9wqt58khzs9`? 
The idea here is that the network is already encoded in the address, so it might not need to be written.

I can manually slice the string, but I'm wondering if there's a flag in NBitcoin where I can specify for the network prefix option.

**Comment by lontivero** [comment]
@osagga, put some effort from your side before asking for help, please. You can answer your own question simply by doing something like:

```
git grep -i noprefix
```

**Comment by osagga** [comment]
Haha sorry about that, I just couldn't point this function from the unit tests or any examples (it has `0` references). 

Thanks, my bad. NBitcoin always has my back :D

**Comment by NicolasDorier** [comment]
It might be internal, @osagga this is bad idea. All their software/wallet assume you have the prefix. Deal with stupidity.
