### ISSUE TITLE
Bitcoin Cash - Rpc methods

### ISSUE THREAD

**Issue by Ilchuk-Mihail** [MetacoSA/NBitcoin#509]
I use Bitcoin ABC node, and this node does not support all new methods, 
like estimate smart fee, list unspent with query options ...

NBitcoin altoins does not have implementation for old method EstimateFee, only for Estimate SmartFee.

Can you add this support? Or maybe we recommend other bitcoin cash node ?

How best way to implement this functions: 
1) how to accumulate inputs sending amount ? Which algorithm ?
2) Implement estimate fee with SendCommandAsync ? 

Do you reccommend store new bitcoin cash addresses (and get to user converted legacy address) or convert to legacy, and store legacy addresses ?

**Comment by NicolasDorier** [comment]
Here is what I recommend you do:

* Create a namespace NBitcoin.Altcoins.BCash
* Create a class inside, `RPCClientExtension`.
* Create the `EstimateFee` etc... by using `SendCommandAsync`

NBitcoin only support new bcash address to limit the risk of people loosing money. It is better they fail to send than risking sending to wrong chain.

**Comment by Ilchuk-Mihail** [comment]
@NicolasDorier how to accumulate inputs for sending amount ? Which algorithm ?

**Comment by NicolasDorier** [comment]
Use RPC and figure out or use NBXplorer and read https://programmingblockchain.gitbooks.io/programmingblockchain/content/wallet/web-api.html
