### ISSUE TITLE
Dogecoin GetChain never returns (NBitcoin.Altcoins)

### ISSUE THREAD

**Issue by hawthornetr** [MetacoSA/NBitcoin#521]
I can issue this command for Dash, BTC, LTC and it all works fine. When I issue this for Dogecoin, it simply never comes back. 

` ChainData.Chain = _connector.Node.GetChain(new NBitcoin.Protocol.SynchronizeChainOptions { SkipPoWCheck = true });`

My handshake to the node seems fine as the node reports it
`receive version message: /NBitcoin:4.0.1/: version 70012, blocks=0, us=127.0.0.1:22556, peer=10`

Anyone have any idea as to why I am not getting back blocks? Not getting anything for that matter, just hangs until I break the app.

**Comment by hawthornetr** [comment]
It came back, after a long while ;)

**Comment by NicolasDorier** [comment]
@hawthornetr yep, this is because DOGE chain is huge.

If you can, I advise you to use SlimChain which only keep the block hashes in memory. As the size of the chain is what has the most impact on RAM.
