### ISSUE TITLE
TransactionBuilder fails to build the change address

### ISSUE THREAD

**Issue by robermann** [MetacoSA/NBitcoin#523]
Hello, 
Just wondering why the following code does not generate the change address output:

`TransactionBuilder builder = new TransactionBuilder();`
`builder.AddCoins(coins); `
`builder.AddKeys(bitcoinPrivateKey);`
`builder.Send(destinationAddress, new Money(0.000000015m, MoneyUnit.BTC));`
`builder.SendFees(Money.Coins(0.001m));`
`builder.SetChange(address.ScriptPubKey);`
`var signedTx = builder.BuildTransaction(true);`
`Boolean b = builder.Verify(signedTx);`

What I'm missing?
Transaction's hex (Testnet):

01000000000101e38fd8de708abdb8eddd0e47d1369f44d4e2de0d5407cf277d4dfc73a0a922875300000017160014a017d15c9cfacea59c4a3984b32f2282e617de8effffffff01f6b4b600000000001976a914a017d15c9cfacea59c4a3984b32f2282e617de8e88ac02473044022028f8440e4d85eca57a99fadda133fc9ce48b523a4b4d2438aaaad0a296d8d7270220112eb54f7e8a1f311b6b4dc0a15c4b3a5311948724a8aa0657da52da6b26fc68012102b6d3f00966c6797c69b98cc7d4f7ec0e9ec8aee68f2fccb5cec061eeaee47f8900000000

**Comment by NicolasDorier** [comment]
Because `0.000000015` BTC is below the dust limit, which mean that if the transaction builder was adding this output, then your transaction would fail to broadcast.

You can disable this behavior by using `builder.DustPrevention = false`, but you will be unable to broadcast the transaction.

**Comment by knocte** [comment]
@NicolasDorier can I provide a PR to change DustPrevention to be an enum of 3 states instead of a boolean? The way I see it: Automatic(current behaviour for `true`) | Disabled (current behaviour for `false`) | Exception (so that wallets can catch the problem without having to guess).

**Comment by NicolasDorier** [comment]
@knocte I don't like it for 2 reasons:

1. Breaking change
2. If you are interested into the issue, you just have to call `builder.Verify(tx, out var errors)`, which will report the issue.

**Comment by robermann** [comment]
Firstly let's review it.

So what I asked in the code is:

> from:                        0,12073879
> fees:                         0,001
> to:                            0,000000015
> expected change:    0,119738775

But the transaction was built in the following way:

> from:               0,12073879
> fees:               0,00100001
> to:                 0,11973878
> change:             0,0

So you are suggesting that:
1) the destination didn't got 0,000000015 because too low
2) that amout has been summed up to the fees (so fees are now 0,00100001 instead of 0,001)
3) the remaining (0,11973878) went all to the destination, and the change address couldn't get anything

In the end it turned out to be a very different transaction than what I intended to. I would even suspect there is a bug there, but you are instead suggesting it is the automatic behaviour? If so has to change in some way.

By the way, shoud it be builder.SetChange(address.ScriptPubKey) or builder.SetChange(address)? I broadcasted an almost transaction using the latter, and looks ok (https://live.blockcypher.com/btc-testnet/tx/4761929185a3dd80f23670efb854ba3d7ab5a151f296ea7c38015ceb821ee838/).

**Comment by knocte** [comment]
> Breaking change

That's only if we make `DustPrevention.Exception` the default. We could make it opt-in first.

**Comment by robermann** [comment]
In my opinion, the library shoud not change automatically the transaction as intended by the programmer (such as changing the values).  In case of issues, it should throw an exception.

**Comment by robermann** [comment]
Perhaps just add a parameter to a new overloaded constructor:

> bool throwExceptionIfDetectError = true
> TransactionBuilder builder = new TransactionBuilder(throwExceptionIfDetectError);

The existing constructor may have the default to false, so doesn't break the existing client code.

**Comment by robermann** [comment]
Or even:

Make the actual constructors deprecated and introduce two factory methods:

- TransactionBuilder.buildCanRaiseExcepion()
- Transaction.buildAdjustAutomatically() //the default

**Comment by NicolasDorier** [comment]
@robermann 

```
from: 0,12073879
fees: 0,00100001
to: 0,11973878
change: 0,0
```
No, it did

```
from: 0,12073879
fees: 0,00100001
to: 0,0
change: 0,11973878
```

**Comment by NicolasDorier** [comment]
If you don't want the transaction to touch your transaction, you have to remove `DustPrevention` and check the error in `txbuilder.Verify` (which you should already do).

`txBuilder` is preventing foot shooting, those kind of case are so extreme that nobody test for it, so the default behavior should be to not crash, given it does not make you loose money.

**Comment by robermann** [comment]
I see your point,  thanks for the explanation. What about the question: 

> By the way, shoud it be builder.SetChange(bitcoinPrivateKey.GetAddress().ScriptPubKey) or builder.SetChange(bitcoinPrivateKey.GetAddress())? I broadcasted an almost identical transaction using the latter, and looks ok (https://live.blockcypher.com/btc-testnet/tx/4761929185a3dd80f23670efb854ba3d7ab5a151f296ea7c38015ceb821ee838/).

Also, which "reference examples" would you suggest for the use of TransactionBuilder? Somewhere I saw the use of SendEstimatedFees.

**Comment by NicolasDorier** [comment]
`builder.SetChange(bitcoinPrivateKey.GetAddress())` is the same as `builder.SetChange(bitcoinPrivateKey.GetAddress()).ScriptPubKey`

**Comment by NicolasDorier** [comment]
@robermann I think the best reference examples are inside the tests now. And in the book https://programmingblockchain.gitbooks.io/programmingblockchain/content/

**Comment by robermann** [comment]
ok, thank you. great work.

**Comment by hitjariwala** [comment]
TransactionBuilder builder = new TransactionBuilder();
It give error TransactionBuilder' dows not contain a constructor that takes 0 agrguments

**Comment by yahiheb** [comment]
@hitjariwala Using `var builder = Network.Main.CreateTransactionBuilder();` should solve your problem.

**Comment by hitjariwala** [comment]
@yahiheb 
Thanks for fast reply. another error is
var _transaction = NBitcoin.Transaction();
Non-invocable member 'Transaction' cannot be used like a miethod.

**Comment by knocte** [comment]
You forgot the `new` keyword. Are you new to C#? :)

**Comment by hitjariwala** [comment]
@knocte @yahiheb 
after use new keyword give error.

var _transaction =new NBitcoin.Transaction();
Transaction.Transaction() is inaccessible due to its protection level

**Comment by knocte** [comment]
well you have to use the parameters needed for that constructor, seems you're not using an IDE that can tell you these things?

**Comment by hitjariwala** [comment]
can you give sample code for sending btc using rpc client?

**Comment by knocte** [comment]
Read this book: https://programmingblockchain.gitbook.io/programmingblockchain/ it has a lot of samples

**Comment by hitjariwala** [comment]
well you have to use the parameters needed for that constructor, seems you're not using an IDE that can tell you these things?

i cant understand what you say.

**Comment by hitjariwala** [comment]
@knocte 

I am using visual studio 2015

**Comment by hitjariwala** [comment]
@knocte 
Now i am getting error in 
var signTx = rpcClient.SignRawTransaction(_transaction);
"Method Not Found"
