### ISSUE TITLE
How to send all with NBitcoin?

### ISSUE THREAD

**Issue by ArtjomP** [MetacoSA/NBitcoin#525]
How to build a transaction with the TransactionBuilder to send all coins?

**Comment by NicolasDorier** [comment]
on top of my head

```csharp
var tx = txBuilder
.AddCoins(coins)
.AddKeys(keys)
.Send(destination, coins.Select(c=>c.TxOut.Value).Sum())
.SubstractFees()
.SendEstimatedFees(feeRate)
.BuildTransaction(true);
```

**Comment by ArtjomP** [comment]
I wrote a Unit test and it doesn't work.
Before fixing it I want to ask @NicolasDorier  does it make sense?

```cs
[Fact]
[Trait("UnitTest", "UnitTest")]
public void EstimateFeesWhenSendingAllToTwoDestinationsCoins()
{
   var alice = new Key();
   var bob = new Key();
   var bib = new Key();
   var fee = new TransactionBuilder()
	.AddCoins(new Coin(new OutPoint(Rand(), 1), new TxOut(Money.Coins(1.0m), alice.ScriptPubKey)))
	.AddKeys(alice)
	.Send(bib, Money.Coins(0.00001m))
	.Send(bob, Money.Coins(0.00082840m))
	.SubtractFees()
	.SetChange(alice)
	.EstimateFees(new FeeRate(1000m));
}
```

Could you please give me some tip how to fix it if it makes sense?
I think the problem is in the BuildTransaction method of the TransactionBuilder class.

**Comment by NicolasDorier** [comment]
`SendEstmatedFee` not EstimateFee

**Comment by NicolasDorier** [comment]
https://github.com/MetacoSA/NBitcoin/blob/4b989108b44d7add50f28b777e0495d09949f311/NBitcoin.Tests/sample_tests.cs#L55

**Comment by ArtjomP** [comment]
I changed it to:
```cs
[Fact]
[Trait("UnitTest", "UnitTest")]
public void EstimateFeesSendingToTwoDestinationsCoins()
{
	var alice = new Key();
        var bob = new Key();
	var bib = new Key();
	var fee =	new TransactionBuilder()
	.AddCoins(new Coin(new OutPoint(Rand(), 1), new TxOut(Money.Coins(1.0m), alice.ScriptPubKey)))
	.AddKeys(alice)
	.Send(bib, Money.Coins(0.00001m))
	.Send(bob, Money.Coins(0.00082840m))
	.SubtractFees()
	.SetChange(alice)
	.SendEstimatedFees(new FeeRate(1000m));
}
```

And got the same NBitcoin.NotEnoughFundsException with message:
`
Can't substract fee from this output because the amount is too small with missing amount 0.00177160
`

Should I add private keys if I want to estimate fee only?

Thx!

**Comment by NicolasDorier** [comment]
The error message is pretty explicit. You ask to remove the fee from `0.00082840m` but the fees are larger than this.
