### ISSUE TITLE
Is a double-spend transaction (already mined) detected?

### ISSUE THREAD

**Issue by robermann** [MetacoSA/NBitcoin#526]
Hello, I was trying to resend a transaction of mine, already present in the blockchain (testnet) - a double-spending test. 

I'd expected that either `builder.Verify(signedTx, out errors);` or `client.Broadcast(signedTx).Result;` would give me back an error, such as "_transaction already in block chain_". On the contrary, I got no errors and both methods returned true. Is that behaviour correct? Where is a double-spend detected?

If I push the same transaction on https://testnet.smartbit.com.au/txs/pushtx, I get the message: _PUSH TRANSACTION ERROR: TRANSACTION ALREADY IN BLOCK CHAIN_

**Comment by NicolasDorier** [comment]
The builder does not have enough information to know if your transaction is on the blockchain. For this you need a block explorer or your own bitcoin node.

**Comment by robermann** [comment]
@NicolasDorier 
Do I have to use a raw RPC Client, right? The following code fails as expected.

>             try
>             {
>                 RPCClient rc = new RPCClient(Network.TestNet);
>                 rc.SendRawTransaction(transaction);
>             }
>             catch (Exception e)
>             {
>                 String msg = e.Message;
> 
>                 Console.WriteLine("error: " + msg); //error code: -27, msg: transaction already in block chain
>             }

**Comment by NicolasDorier** [comment]
Yes, you have to use this; `TransactionBuilder` can only check if you signed right, with right amount of fees along some other rules, but it can't verify any rule that require a full node. For this you can use `SendRawTransaction`
