### ISSUE TITLE
Why A private key can create more bitcoin addr?

### ISSUE THREAD

**Issue by chengmiaook** [MetacoSA/NBitcoin#529]
i create one private key by nbitcoin  :
  Key privatekey = new Key();
  PubKey publicKey = privatekey.PubKey;
  BitcoinSecret testNetPrivateKey = privatekey.GetBitcoinSecret(Network.TestNet);
  var testNetAddress = publicKeyHash1.GetAddress(Network.TestNet);
   i get 
  testNetPrivateKey ="cW3AYA13z1TBEKtpqyw8VeLSJqBZZUssg1nKLDg8TF5qSNqcNHoa"
  testNetAddress  = "mzfcQtUpaJdJM4E2H1Fq3zHpJo81k69BeX"
  
  so, i import this private key into bitcoin-qt,result,wo get three  bitcoin addr

  "mzfcQtUpaJdJM4E2H1Fq3zHpJo81k69BeX";
  "2Mz6GhZTfm1F1J1cuuMkwkjCC8LuaQrEWH4";
  "tb1q6gxcj6yvldmh80vchpel5lvnrq5ksf9rfa6ar2";

   help me ,please

**Comment by ArtjomP** [comment]
[List of addresses](https://en.bitcoin.it/wiki/List_of_address_prefixes)

**Comment by chengmiaook** [comment]
what can i do ,can make one privatekey one address, i am a Novice

**Comment by ArtjomP** [comment]
Your public key is:
1. "tb1q6gxcj6yvldmh80vchpel5lvnrq5ksf9rfa6ar2" - never publish it because one day when quantum computing will be here it could be possible to get private key from it.
You can easy get Script Hash or PublicKey hash from it.
2. 2Mz6GhZTfm1F1J1cuuMkwkjCC8LuaQrEWH4 - script hash good for sending coins here
3. mzfcQtUpaJdJM4E2H1Fq3zHpJo81k69BeX - PublicKey has good for sending coins here

**Comment by ArtjomP** [comment]
[Programming blockchain book](https://programmingblockchain.gitbooks.io/programmingblockchain/)

**Comment by chengmiaook** [comment]
> [Programming blockchain book](https://programmingblockchain.gitbooks.io/programmingblockchain/)

thank you

**Comment by NicolasDorier** [comment]
> "tb1q6gxcj6yvldmh80vchpel5lvnrq5ksf9rfa6ar2" - never publish it because one day when quantum computing will be here it could be possible to get private key from it.
You can easy get Script Hash or PublicKey hash from it.

Not vulnerable to quantum computing, this is still a hash.


Closing this, you need to read the book as @ArtjomP advised.
