### ISSUE TITLE
Retrieve Blocks by Date

### ISSUE THREAD

**Issue by saurabhs2t** [MetacoSA/NBitcoin#536]
Hi, I am trying to develop a desktop application, which connects to Bitcoin Core, and retrieves the Block Info by date. 
So is there any way I can achieve this?

Thank you!!

**Comment by saurabhs2t** [comment]
I have figured it out anyway using this:

`var latestChain = node.GetChain(); `       
`var blocks = latestChain .ToEnumerable(false)
.SkipWhile(x => x.Header.BlockTime.DateTime < from)
.TakeWhile(x => x.Header.BlockTime.DateTime < to)
.ToList();`

But I have another issue, whenever I am trying to parse longer date ranges, I am getting this exception:

> The node is not in a connected state

So how to I parse large number of records without getting above exception.
Thanks in advance!

**Comment by NicolasDorier** [comment]
`blockA.BlockTime > blockB.BlockTime` does not mean that BlockA is older than BlockB. BlockTime can be in disorder.

Use `Node.ConnectToLocal` after running your bitcoin core node and made sure it synched.

**Comment by saurabhs2t** [comment]
Hi @NicolasDorier Thanks for the response. Yes I finally connected to local using `Node.ConnectToLocal`
and able to retrieve block information.

Thank you.
