### ISSUE TITLE
TraceSourceFactory / TraceSource -> ILogger

### ISSUE THREAD

**Issue by danystem** [MetacoSA/NBitcoin#538]
Hi @NicolasDorier,

I noticed in a previous issue (https://github.com/MetacoSA/NBitcoin/issues/345) there was a mention of the use of TraceSource on Netcore. 

There seems to be a problem in that if you enable the NOTRACESOURCE directive then the NBitcoin implementation of TraceSource clashes with the Netcore version in System.Diagnostics which is now implemented.

Could we change the namespace of the NBitcoin implementation to enable implementation of custom TraceSource (which you enabled in the previous issue) from the outside?
Or
Would you accept a pull request to enable the ILogger abstraction to be used? I refer to your previous comment around injecting this into NodeConnectionParameters - but alternatively is could be more globalised than that?

Let me know your thoughts?

Cheers,

Dan

**Comment by danystem** [comment]
I've done this so far which will allows me to inject a custom TraceSource from the outside.

I have changed the namespace of your stub implementation and also created a wrapper around the 'real' tracesource if it exists...

https://github.com/MetacoSA/NBitcoin/commit/7de59222b9786c76a8b2c8a61bb67b77a1861850

Haven't submitted PR yet I my working base includes my previous PR.

**Comment by NicolasDorier** [comment]
Yeah, this code should probably go and have something more modern. I was thinking of using the same pattern I use in NBXplorer for logging. What do you think?

**Comment by danystem** [comment]
I've had a look at NBXplorer and using the ILogger abstraction definitely would be grand. 

Were you thinking this should this be a breaking change? I.e. should all traces of TraceSource be removed?

**Comment by NicolasDorier** [comment]
yeah this will be breaking change. But almost nobody use it, so I think it is ok.

**Comment by danystem** [comment]
Ok cool - Is this something you were going to do anyway or shall I make a start and submit a PR?

**Comment by NicolasDorier** [comment]
Yes I am open for a PR. Don't hesitate to simplify stuff. The TraceSource is here only because I was using WCF Trace Viewer in the past...

**Comment by danystem** [comment]
@NicolasDorier I've made a start - but question for consideration before I get to deep in if you don't mind? 

Should we utilise Serilog so we can implement a structured logging capability? Obviously that introduces an additional dependency which might not be desirable - but structured logging would be a massive gain considering the volume of logging that occurs?

Thoughts?

**Comment by danystem** [comment]
Ahh actually it seems Microsoft.Extensions.Logging actually supports templates now so we can actually implement structured logging without the direct dependency on Serilog.

**Comment by NicolasDorier** [comment]
Yeah, no direct dependencies.
