### ISSUE TITLE
About NodeBehavior

### ISSUE THREAD

**Issue by TurgutBtc** [MetacoSA/NBitcoin#539]
Hello,

We wrote our transaction listener from .net project and we were implement the NodeBehavior class. But when I update version of NBitcoin v3.0.0.60 to v4.1.1.46 I can't use the NodeBehavior. Because Nbitcoin can not support to Protocol.Behaviors. What can i do ? Are there another auxiliary class ? Or can you suggest me another way for listen to transactions ??

Thank you for now.

**Comment by nopara73** [comment]
What do you mean? I'm listening for transactions with this and no issue with new NBitcoin releases: https://github.com/zkSNACKs/WalletWasabi/blob/master/WalletWasabi/Services/MemPoolBehavior.cs

**Comment by TurgutBtc** [comment]
It's looks like below.
I can not get reference **NBitcoin.Protocol.Behaviors** 
![image](https://user-images.githubusercontent.com/16779158/46081632-ab26a000-c1a5-11e8-84eb-0fa86cafdab2.png)

**Comment by NicolasDorier** [comment]
this is strange. Are you using 4.5.2 at least?

**Comment by nopara73** [comment]
That is indeed strange. Can be something basic, don't give up the tinkering.

![image](https://user-images.githubusercontent.com/9156103/46136003-e75e0d00-c246-11e8-9cf2-498bb5b0be0a.png)

**Comment by TurgutBtc** [comment]
Ahh I changed the .Net Framework 4.5.1 to 4.5.2 and I updated again the NBitcoin after that the problem solved.

Thank you for attention.
