### ISSUE TITLE
GetHeaders

### ISSUE THREAD

**Issue by danystem** [MetacoSA/NBitcoin#540]
In BTC/Dash getheaders returns a headers response.

However in the PIVX fork I'm working with getheaders returns an inv? Obviously this is causing GetChain to not work.

Can you advise of a suitable approach to override the Node class?

Dan

**Comment by NicolasDorier** [comment]
You can't override Node class without refactoring NBitcoin. (which you can try)

**Comment by danystem** [comment]
Looking further into this - hoping to create some additional calls in Node in order to support retrieval by Pivx forks - the aim would be to enable alternative approach via a switch in SynchronizeChainOptions if you are cool with that?

**Comment by NicolasDorier** [comment]
I think you should add proper `header` support to Pivx forks. Because this is not the only place where I depends on header first sync. NBXplorer for example depends on it.

**Comment by danystem** [comment]
@NicolasDorier I've added getheaders support to our codebase and now GetChain() works perfectly and fast now. Thanks for the steer on this.
