### ISSUE TITLE
Hash functions are not thread safe

### ISSUE THREAD

**Issue by dangershony** [MetacoSA/NBitcoin#542]
Note this code was taken before we found that the hash functions are not thread safe.
https://github.com/MetacoSA/NBitcoin/blob/master/NBitcoin.Altcoins/HashX11/X11.cs#L33

This needs to be change similar to the code in Stratis
https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/src/NBitcoin/Crypto/HashX13.cs#L57

Basically this needs a lock
```
   private readonly object hashLock;
```

**Comment by dangershony** [comment]
I think in that case you will have to create a new instance for every algo, but yeah that will probably also work. if you get any metrics on perf let me know, if its better I will change stratis as well

**Comment by NicolasDorier** [comment]
For NBitcoin checking PoW is not that important. But I am quite sure that recreating all the instances for every algo is more efficient than locking.

**Comment by dangershony** [comment]
Normally you are right (in case this method is called in under lots of threads), I just seem to remember there was some setups involved with creating each instance of a hash function type, but you are probably right this is likely negligent.

**Comment by NicolasDorier** [comment]
Closing this as there is no bug, and it is for PoW code which is almost not used in NBitcoin.
