### ISSUE TITLE
GetBlockchainInfoAsync() fails on certain blockchains

### ISSUE THREAD

**Issue by Aify** [MetacoSA/NBitcoin#546]
There seems to be a bug using NBitcoin.Altcoins nuget package when trying to connect to a Dogecoin or BCash client across a vpn. 

The GetBlockchainInfoAsync() call throws an argument null exception (parameter name "source"), but when I tried the same code without using the nuget packages (instead substituting downloaded copies of the master branch of NBitcoin), it works fine.

**Comment by NicolasDorier** [comment]
Closing it, reopen if you still have an issue after updating.
