### ISSUE TITLE
Derive bip32 address for DASH

### ISSUE THREAD

**Issue by izzycoder18** [MetacoSA/NBitcoin#559]
Hi,
I am trying to generate HD addresses from a DASH wallet public key (xpub) using NBitcoin.

Here it is the code I use to successfully generate Bitcoin addresses from BTC wallet xpub:

`var newAddress = pubkey.Derive(0).Derive(0).PubKey.GetAddress(Network.Main);`

Unfortunately this only works for Bitcoin.
Any suggestion about how to derive a DASH compatible address?

Thanks in advance.

**Comment by NicolasDorier** [comment]
`var newAddress = pubkey.Derive(0).Derive(0).PubKey.GetAddress(NBitcoin.Altcoins.AltNetworkSets.Dash.Mainnet);` after adding the `NBitcoin.Altcoins` nuget package to your project.

**Comment by izzycoder18** [comment]
Perfect! It worked pretty nicely. I would suggest to add a wiki to show how the derivation mechanism works for BTC and all the supported altcoins  in your library. 
Thanks again. This library is extremely useful.
