### ISSUE TITLE
Making SubtractFees() act on change output 

### ISSUE THREAD

**Issue by sigHash** [MetacoSA/NBitcoin#560]
Hi there,

I use transactionBuilder like:

```
           TransactionBuilder builder = new TransactionBuilder();
            var unsignedTx = builder
                .AddCoins(scriptCoins)
                .Send(recipientAddr, amountToSend)
                .SetChange(changeAddr)
                .SubtractFees()
                .SendEstimatedFees(rate.FeeRate)
                .BuildTransaction(false);
```

I was expecting the fee being subtracted from the change TxOut, not the recipient TxOut. How can I achieve that without manually setting the transaction fee?

**Comment by NicolasDorier** [comment]
Hey, `.SubstractFees()` act on the last output. So if you move this line above `SetChange`, then it will substract from `recipientAddr`.

**Comment by NicolasDorier** [comment]
If you want the sender to pay for the fee, then remove `SubstractFees()`.

**Comment by NicolasDorier** [comment]
Note also that there is a privacy feature in the `TransactionBuilder` which spend all the coins who has the same address. You can disable it, but I don't advise to.
