### ISSUE TITLE
Doc generation permissions leak

### ISSUE THREAD

**Issue by NicolasDorier** [MetacoSA/NBitcoin#562]
@Kukks  I just removed the documentation generation as part of the build process. (It generated once though https://metacosa.github.io/NBitcoin/api/index.html)

The reason is that pull requests are firing for pull request anybody can do:

* Either the pull request run in the account of the person making the PR and in this case the build would fail because he can't decrypt my credentials.
* Either the pull request run in my account, in which case anybody get push access to NBitcoin.

Both case seems bad.

**Comment by Kukks** [comment]
Hmm crap, we need a different hook then

**Comment by NicolasDorier** [comment]
I am unsure if there is a way to solve the situation.

**Comment by Kukks** [comment]
But isn't the GitHub token contained and will only be used when you merge a
pull request and would only be used to push to a specific branch? Shouldn't
that be safe as long as we can check that the appveyor script has not been
touched in the PR?

**Comment by NicolasDorier** [comment]
I am not sure about that. But if true, it means that the PRs will fail because they will fail pushing the docs.

**Comment by Kukks** [comment]
They shouldn't fail because they use the global keys you set in the appveyor settings? We can try and do a test today if you want but imo as long as the appveyor script has not been modified in a PR you should not be compromised.

**Comment by Kukks** [comment]
Ok I identified the issues: 
* PRs to master always run appveyor
* PRs run their own branch's version of the yml

So I fixed the first issue now so that PRs do not generate docs on my master. Not sure how the second one can be tackled though.

**Comment by Kukks** [comment]
Heya! It turns out it is not an issue at all. Encryped vars are not decrypted for pull requests so we should be good. :) 

```
Secure variables
When you work with OSS projects and you’d like to hide some sensitive data from everyone’s eyes you can use secure variables in appveyor.yml.

AppVeyor generates a unique encryption key for every account. To encrypt variable values go to Settings → Encrypt YAML page.

To use encrypted variable in appveyor.yml:

environment:
  my_variable:
    secure: <encrypt_value>
“Secure” variables means you can safely put them into appveyor.yml that is visible to others. Other than that they are just regular environment variables in a build session that could be easily displayed in a build log by simple Get-ChildItem env:.

However, secure variables are not decoded during Pull Request builds which prevents someone from submitting PR with malicious build script displaying those variables. In more controlled environment through with a trusted team and private GitHub repositories there is an option on General tab of project settings to allow secure variables for PRs.
```
