### ISSUE TITLE
Derive Ethereum addresses from master public key

### ISSUE THREAD

**Issue by izzycoder18** [MetacoSA/NBitcoin#565]
Hi,
I wonder if I could derive valid Ethereum addresses from its master public key (xpub, tpub). 
If yes, how?

**Comment by eabz** [comment]
Yes. It is possible. But I don't know if NBitcoin is capable of it. Maybe try with NEthereum. 
I use to do it with javascript libraries and worked perfectly. The hard part is getting a HD wallet tracker.

**Comment by izzycoder18** [comment]
Any suggestion about how to do this in NBitcoin or any other .net library?

**Comment by NicolasDorier** [comment]
probably NEthereum

**Comment by knocte** [comment]
But take in account that HD wallets in Ethereum are not so useful because you cannot send from many addresses at the same time in the same transaction. You need to create a transaction per address where you want to move funds from.

**Comment by izzycoder18** [comment]
@NicholasDorier , any suggestion about how to implement the address derivation logic for ERC20 tokens (Ethereum)? Unfortunately Nethereum doesn't expose any method that given an xpub , returns a valid address.

**Comment by NicolasDorier** [comment]
no idea, I don't touch ETH, even with radiation protective gloves.

**Comment by sigHash** [comment]
> no idea, I don't touch ETH, even with radiation protective gloves.

What if BTCPayServer customers insist? :D 

To me BTCPayServer is about empowering people to be their own payment processor. The choice of currency is really up to them (merchants and customers). If we _assume_ ETH and ERC20 are here to stay, I'd rather see those transactions go through BTCPayServer. 

Is that just you personally have no interest in ETH ecosystem(which I totally understand as I myself entered the space when there was no ETH), or you think coming up with a secure implementation that seamlessly integrates with NBItcoin, NBXplorer,  and BTCPayServer is just not possible yet.

**Comment by knocte** [comment]
I work in a wallet which uses NBitcoin and Nethereum, therefore it supports both (and ERC20). To get BtcPayServer integrate with Ethereum well enough, you would need the equivalent to NBXplorer in the Ethereum world first.

**Comment by NicolasDorier** [comment]
> What if BTCPayServer customers insist? :D

They are free to integrate it, because I will not do it myself.

**Comment by kennethhutw** [comment]
This is my way to generate ethereum address with Nethereum. 

```
Mnemonic mnemo = new Mnemonic(Wordlist.English, WordCount.Twelve);
ExtKey masterKey= mnemo.DeriveExtKey();
var ETH_keyPath = new KeyPath("m/44'/60'/0'/0/");
ExtKey ETH_derived = masterKey.Derive(ETH_keyPath);
ExtPubKey derivedETHPublicKey = ETH_derived.Neuter();
ExtPubKey ExtendedPublicKey = derivedETHPublicKey.Derive((uint)0);
PubKey ETH_publickKey = ExtendedPublicKey.GetPublicKey();
byte[] byte_ETH_publicKey = ETH_publickKey.Decompress().ToBytes();
var PubKeyNoPrefix = new byte[byte_ETH_publicKey.Length - 1];
Array.Copy(byte_ETH_publicKey, 1, PubKeyNoPrefix, 0, PubKeyNoPrefix.Length);
var initaddr = new Nethereum.Util.Sha3Keccack().CalculateHash(PubKeyNoPrefix);
var addr = new byte[initaddr.Length - 12];
Array.Copy(initaddr, 12, addr, 0, initaddr.Length - 12);
var hex_addr = BitConverter.ToString(addr).Replace("-", "");
string public_address =  new Nethereum.Util.AddressUtil().ConvertToChecksumAddress(hex_addr);
Console.WriteLine("Generated address  " + i + ": " + public_address);       
```

**Comment by NicolasDorier** [comment]
closing this issue, it is 2 years old already

**Comment by xpayserver** [comment]
https://github.com/btcpayserver/btcpayserver/pull/1730
