### ISSUE TITLE
old NBitcoin.TestFramework version

### ISSUE THREAD

**Issue by dalijolijo** [MetacoSA/NBitcoin#577]
My test with NBXplorer failed because the changes (https://github.com/MetacoSA/NBitcoin/pull/569) in NBitcoin.TestFramework v1.6.17 not available. Please update NBitcoin.TestFramework to v1.6.18. Thanks.

**Comment by NicolasDorier** [comment]
The 1.6.17 is available https://www.nuget.org/packages/NBitcoin.TestFramework

**Comment by NicolasDorier** [comment]
try to do `dotnet restore --no-cache`

**Comment by NicolasDorier** [comment]
Ah sorry I just understood.

**Comment by NicolasDorier** [comment]
Pushed new version
