### ISSUE TITLE
Omitting POW for NBXplorer

### ISSUE THREAD

**Issue by eabz** [MetacoSA/NBitcoin#585]
Hello Nicolas.
I am working with some integrations for NBXplorer. But all my integrations seems to get stuck upon loading chain from node.
This issue seems to be related with block headers algo. Can you give a hand on this. Is there a way to omit integrating the algo or need to integrate it?
If that's the case, can we just submit a wrapper for a C module?

**Comment by NicolasDorier** [comment]
NBXplorer does not check PoW

**Comment by eabz** [comment]
Ok.
And what can be the reasons of NBXplorer not syncing?
RPC and node is correctly connected.

**Comment by eabz** [comment]
Getting this when running TestFramework:
```
Failed   NBitcoin.Tests.AltcoinTests.HasCorrectGenesisBlock
Error Message:
 Assert.Equal() Failure
Expected: 78195662058e37934b9120943cc970b6083df4771c88d81a84e53d3d29483225
Actual:   36ac141154aed8fd8cf2a5948a06c4225e818105898c0d87944720cfed11aaa2
Stack Trace:
   at NBitcoin.Tests.AltcoinTests.HasCorrectGenesisBlock() in /root/Documents/NBitcoin/NBitcoin.Tests/AltcoinTests.cs:line 80
Failed   NBitcoin.Tests.AltcoinTests.CanParseBlock
Error Message:
 Assert.Equal() Failure
Expected: 0dbcd5c6d8af1b0de49b0550cb4c32017990696c17af8e626c9a923cfadca65f
Actual:   fcb95a5bd10b001033c685e260f0877af173f7ee2bc38c58881b2a358b1ab4ed
Stack Trace:
   at NBitcoin.Tests.AltcoinTests.CanParseBlock() in /root/Documents/NBitcoin/NBitcoin.Tests/AltcoinTests.cs:line 97
```

**Comment by NicolasDorier** [comment]
ok, can you fix it?

**Comment by eabz** [comment]
Yes. To fix it I'll need to create the C# module of the NeoScrypt algo. But I was thinking if is possible to simply pass the genesis hash instead.

**Comment by NicolasDorier** [comment]
not sure what you mean, I thought POLIS was hashing things correctly, because if it did not the tests should never have passed in the first place.

**Comment by eabz** [comment]
Yes, sorry if I didn't explain correctly. For some reason, NBXplorer is not parsing blocks correctly if the hashing module is not implemented. I mean, I want to integrate an altcoin named Gin, and they started using NeoScrypt and switched to Lyra2z, which means we need to include two new hashing modules into NBitcoin.Altcoins. I try to sync without POW, but I am getting the same error I posted you above. 
Is there any way to omit this. I think the only problem is on the genesis construction, but I don't know were to start.

**Comment by NicolasDorier** [comment]
There is zero dependency to POW in NBXplorer. Your issue is not this.

**Comment by eabz** [comment]
Ok. Seems you are correct.

**Comment by eabz** [comment]
Hello @NicolasDorier
