### ISSUE TITLE
BitcoinCash transaction sign  and submit TX decode failed

### ISSUE THREAD

**Issue by pozdnyakovasp** [MetacoSA/NBitcoin#587]
Hello.

I can't submit signed BCash transaction to network.
I created address:

> 
> address: bchtest:pql8vc6kldxfkhwna7kw0knrq5ze8jkz0s0u52dh7w
> privKey: cPZq9ktoDqowL7fa6rbiog8UDPja8MCsAdofT5t7QGGsr7jj8dqH

Have one Unspent transaction ->

>         txId: "e44619b84ca03e28e2b4bee8eb895e9d41d4522737ef18755a586b05fd686f5f",
>         amount: 0.22996573,
>         vout: 0

In code create TransactionBilder
```
var Network = NBitcoin.Altcoins.BCash.Instance.Testnet;

var builder = Network.CreateTransactionBuilder();
// in
var scriptPubKey = Network.CreateBitcoinSecret(addressKey).PubKey.WitHash.ScriptPubKey
var key = Key.Parse(secret.ToWif());
var coin = new Coin(txInHash, (uint)vout, amount, scriptPubKey.Hash.ScriptPubKey).ToScriptCoin(scriptPubKey);
builder.AddKeys(key);
builder.AddCoins(coin);

// out
 var amount = Money.FromUnit(0.2299, MoneyUnit.BTC);
 builder.Send(BitcoinAddress.Create(outAddress, Network), amount);

// fee
builder.SendFees(Money.FromUnit(sendFee, MoneyUnit.BTC));

var signedTransaction = builder.BuildTransaction(true);

await RpcClient.SendRawTransactionAsync(signedTransaction); 

```
builder.Verify - return true

I get "TX decode failed"

But i can use this code for LTC and BTC.
What could be the problem?

**Comment by NicolasDorier** [comment]
Note that you can use `Network.Consensus.SupportSegwit` to check if the currency support segwit.

**Comment by pozdnyakovasp** [comment]
Give thanks! You helped me a lot.
