### ISSUE TITLE
missing -whitelist and -listen options

### ISSUE THREAD

**Issue by MithrilMan** [MetacoSA/NBitcoin#593]
I notice you miss to handle two important options : -whitelist and -listen
any particular reason for this?

**Comment by NicolasDorier** [comment]
where

**Comment by MithrilMan** [comment]
these are options that bitcoin has (in bitcoin.conf or as arguments)
https://en.bitcoin.it/wiki/Running_Bitcoin

```
-listen | Accept connections from outside (default: 1 if no -proxy or -connect/-noconnect)
-whitelist=<IP address or network> | Whitelist peers connecting from the given IP address (e.g. 1.2.3.4) or CIDR notated network (e.g. 1.2.3.0/24). Can be specified multiple times. Whitelisted peers cannot be DoS banned and their transactions are always relayed, even if they are already in the mempool, useful e.g. for a gateway
```

But I just realized that probably you don't handle these options at all so you can close this

**Comment by NicolasDorier** [comment]
Because NBitcoin is a library, not an application
