### ISSUE TITLE
How to add data in OP_RETURN

### ISSUE THREAD

**Issue by utarn** [MetacoSA/NBitcoin#603]
I'm using Digibyte. Altcoin class is written. I'm writing an application to create a raw transaction by getting unspent TX from Insight explorer.

Here is what I get from Insight explorer.
`[{"address":"DCzmzkMBqEz2tLn47W9YuNAV9cFzuWCydW","txid":"2d28620cd7b973a01719d30e07d4bab24d0321fb0506226fdf7feb0d937fa847","vout":0,"ts":1543376986,"scriptPubKey":"76a914562e330d8879eeaf17c72c8ad7f3acb4ebb6262c88ac","amount":9.87006,"confirmations":15,"confirmationsFromCache":false}]`

I managed to serialize to my custom class and create a Coin class.

```
public class UTXO
    {
        public string address { get; set; }
        public string txid { get; set; }
        public int vout { get; set; }
        public string scriptPubKey { get; set; }
        public decimal amount { get; set; }
        public ICoin ToCoin()
        {
            var newCoin = new Coin(
                new OutPoint(uint256.Parse(txid), (uint)vout),
                new TxOut(new Money((long)(amount * Money.COIN)), new Script(Encoders.Hex.DecodeData(scriptPubKey))));
            return newCoin;
        }
    }

```
So After that, I created a transaction using TransactionBuilder as follow.
 ```
            Network network = NBitcoin.Altcoins.Digibyte.Instance.Mainnet;
            BitcoinSecret tsc = new BitcoinSecret("xxx", network);
            var mytarget = new BitcoinPubKeyAddress("xxx", network);

            var myTransaction = Transaction.Create(network);
            var fee = new Money(100000);
            var allUtxo = await GetReceivedCoinFromDigibyte(tsc.GetAddress().ToString());
            var utxo = allUtxo[0].ToCoin();
            var toSend = utxo.Amount.Sub(fee);
            var txBuilder = network.CreateTransactionBuilder();
            tx = txBuilder
                .AddCoins(utxo)
                .AddKeys(tsc)
                .Send(mytarget, toSend)
                .SetChange(tsc.GetAddress())
                .SendFees(fee)
                .BuildTransaction(true);

```

Everything works fine. I read some StealthCoin class but still don't understand what information is used to create the class. Could you please guide me how to convert my Coin class to StealthCoin by adding data in OP_RETURN?

**Comment by NicolasDorier** [comment]
In which way this is related to `StealthCoin`?

`Send(new Script("OP_RETURN ab5612"), Money.Coins(1.0m))` will send 1 coins to unspendable op return

**Comment by utarn** [comment]
Hi Nicolas, 
I'm not sure if it is related to StealthCoin. I just found that It contains StealthMetaData that can write the OP_RETURN

```
public StealthMetadata(Key ephemKey, uint nonce)
		{
			var data = new MemoryStream();
			data.WriteByte(6);
			var b = Utils.ToBytes(nonce, true);
			data.Write(b, 0, b.Length);
			data.Write(ephemKey.PubKey.Compress().ToBytes(), 0, 33);
			Fill(this, new Script(OpcodeType.OP_RETURN, Op.GetPushOp(data.ToArray())));
		}
```

Anyway, your answer seems to be straightforward. Thank you so much.

**Comment by NicolasDorier** [comment]
don't use StealthCoin it is unrelated.
