### ISSUE TITLE
Redundant varint switch case

### ISSUE THREAD

**Issue by vishrayne** [MetacoSA/NBitcoin#606]
@NicolasDorier You are doing the same check on line 117 and here
https://github.com/MetacoSA/NBitcoin/blob/d21f31311180041a15524588b443767cf95951ec/NBitcoin/Protocol/VarInt.cs#L116

Is this a mistake or some validation on purpose. Bear with me if this is a stupid question

**Comment by NicolasDorier** [comment]
This seems a bug. Curious no test catched it, thanks.
