### ISSUE TITLE
BIP67 support?

### ISSUE THREAD

**Issue by joemphilips** [MetacoSA/NBitcoin#608]
I've been trying to implement a support for [BIP67](https://github.com/bitcoin/bips/blob/master/bip-0067.mediawiki) to `PayToMultiSigTemplate.Instance.GenerateScriptPubKey` 
So that generated redeem script will always be deterministic regardless of order of its parameter pubkeys.
(This was byproduct of BIP174. It was useful for a PSBT since PSBT has to sort the public key anyway to check the equality of two PSBTs by their bytes representation)
It worked OK but two test fails. That is 
1. `CanPartiallySignTransaction` which tests against [gavinandresen's gist](https://gist.github.com/gavinandresen/3966071)
2. `script_combineSigs`

I'm planning to tweak these two tests so that it expects redeem script with pubkey sorted. but before that. I wanted to make sure that this is fine thing to do.
Any thoughts?

Note: This doesn't make validation of multisig (in any sense) more strict than currently is. It just makes difference to newly created multisig redeem script.

**Comment by NicolasDorier** [comment]
Do you need to test PSBT equality?
What about just adding an optional parameter default to `false` which would sort if `true`? This would be sure nothing is broken.

**Comment by joemphilips** [comment]
> Do you need to test PSBT equality?
Yes testing equality is necessary to pass the test vector in the bip.

 `PayToMultiSigTemplate.Instance.GenerateScriptPubKey` takes PubKey[] with `params` so I don't know how to add optional parameter.

**Comment by joemphilips** [comment]
I think it is fine when once you've reviewed the test tweaked by me  carefully.
It is nice for wallet developers to have bip67 compatible redeem script without knowing the existence of bip. So I think changing the default behavior is good way to go.

**Comment by NicolasDorier** [comment]
If you broke the test, this update will break somebody's code. So I don't want to teak the tests.
Just make a different overload for `GenerateScriptPubKey`.

**Comment by joemphilips** [comment]
fair enough, I've made a PR #609

**Comment by NicolasDorier** [comment]
I adapted the PR a bit so it result in less object creation, and follow .NET best practices 4a938296c7616e6951bd52053d0a0fbabcc9c303

**Comment by joemphilips** [comment]
Cool, Thanks for letting me know.
