### ISSUE TITLE
Derivate from bip84 xpub

### ISSUE THREAD

**Issue by izzycoder18** [MetacoSA/NBitcoin#619]
Hi,
When I try to derivate an address from an xpub which have been generated following the bip84 segwit format, even though the address is valid, is not actually part of the original wallet. 

I tested with Coinomi wallet, which can generate segwit compliant xpub with derivation path: m/84/0, and unfortunately when I generate addresses, they just don't belong to that wallet.

m/44/0 path works perfectly instead.

Can someone help me shine some light on this and how to work around this issue in the code?
Thanks in advance.

**Comment by NicolasDorier** [comment]
Please provide:

* A XPUBKey
* Which address you expect to have on this XPUBKey
* Which address you get instead
* What code did you use to get this address.

**Comment by izzycoder18** [comment]
@NicolasDorier, i found the way to properly generate segwit addresses. thanks anyway.
