### ISSUE TITLE
Groestlcoin - Unable to parse XPUB

### ISSUE THREAD

**Issue by izzycoder18** [MetacoSA/NBitcoin#620]
Hi @NicolasDorier , 

I am trying to parse an XPUB for Groestlcoin. I tried multiple wallets and multiple keys but the parse method always fails for Groestlcoin. Here it is some more insights:

`var xpub="xpub661MyMwAqRbcGDs3JTDbwVSh3STYCP1YPLJpPAWZYtEQz4ERnCcBa1d66agUWV4ujwPpEWfoVQfTFUDFEy9NRUcWTofowdef7BYiqCUFfk4";
var pubkey = ExtPubKey.Parse(xpub);`

This generates an exception:

`Exception thrown: 'System.FormatException' in NBitcoin.dll`

Any ideas?

**Comment by NicolasDorier** [comment]
Reference NBitcoin.Altcoins
```
var extpub = ExtPubKey.Parse("xpub...", NBitcoin.Altcoins.AltNetworkSets.Groestlcoin.Mainnet);
```

**Comment by izzycoder18** [comment]
@NicolasDorier , thanks a lot.
