### ISSUE TITLE
Smarter TransactionBuilder for estimating fee?

### ISSUE THREAD

**Issue by knocte** [MetacoSA/NBitcoin#624]
I see that TransactionBuilder got smarter by not needing ToScriptCoin() call thanks to this change: 56bfd1cbca535424b160d8a40688a79de4800630.

However, this doesn't seem to help when the keys have not been supplied yet. That is, when estimating the transaction fees first. As I get:

```
[ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidOperationException: You need to provide P2WSH or P2SH redeem script with Coin.ToScriptCoin()
  at NBitcoin.Coin.GetScriptCode () [0x00008] in <eca5e81223844486a0e4d39c73cb396e>:0 
  at NBitcoin.TransactionBuilder.EstimateScriptSigSize (NBitcoin.ICoin coin, System.Int32& witSize, System.Int32& baseSize) [0x000d1] in <eca5e81223844486a0e4d39c73cb396e>:0 
  at NBitcoin.TransactionBuilder.EstimateSizes (NBitcoin.Transaction tx, System.Int32& witSize, System.Int32& baseSize) [0x000ba] in <eca5e81223844486a0e4d39c73cb396e>:0 
  at NBitcoin.TransactionBuilder.EstimateSize (NBitcoin.Transaction tx, System.Boolean virtualSize) [0x0000e] in <eca5e81223844486a0e4d39c73cb396e>:0 
  at NBitcoin.TransactionBuilder.EstimateFees (NBitcoin.Transaction tx, NBitcoin.FeeRate feeRate) [0x00022] in <eca5e81223844486a0e4d39c73cb396e>:0 
  at NBitcoin.TransactionBuilder.EstimateFees (NBitcoin.FeeRate feeRate) 
```

Can this improvement cover fee estimation too?

**Comment by knocte** [comment]
Mmm, but then how do other bitcoin libraries do it? I mean, majority of wallets I've tested (not C# based) estimate the fee before asking the user to input his encryption passphrase (that is, whole transaction details are known before supplying the private key).

**Comment by knocte** [comment]
> You can, you just need the ScriptCoin and not the Coin

Can I? How? Only way I've found to get the ScriptCoin is when having access to the key, e.g.: `coin.ToScriptCoin(privKey.PubKey.WitHash.ScriptPubKey)`. How to get the ScriptCoin without using the key?

**Comment by knocte** [comment]
Let's say we're talking about no HD usage. Are you saying the wallet should store the public key?

**Comment by NicolasDorier** [comment]
More generally, the wallet need to store `ScriptCoin`, they need to keep the redeem script for each UTXO, not necessarily the public key. (`privKey.PubKey.WitHash.ScriptPubKey` in your case)

**Comment by NicolasDorier** [comment]
```
You mean, everytime the wallet detects a new incoming payment (input), it would need to store its ScriptCoin for it? That would be a no-no from a UX point of view, i.e. it would need to ask for the encryption passphrase to the user everytime it receives a payment.
```

No that's not what I mean.

When your wallet generate a new address, you need to store in a database a mapping `ScriptPubKey => (RedeemScript)` when you detect a transaction which has `ScriptPubKey` you extract the Coin from the transaction.
When you spend this coin you do `Coin.ToScriptCoin(RedeemScript)`.

**Comment by knocte** [comment]
> you need to store in a database a mapping ScriptPubKey => RedeemScript

So, I store ScriptPubKey, which is generated from `privKey.PubKey.WitHash.ScriptPubKey`. But if I store the public key I can also get the ScriptPubKey, why is it better to store the ScriptPubKey instead of the PubKey?

**Comment by NicolasDorier** [comment]
This would work, but storing the RedeemScript is more generic. If you store the pubkey, you have `PubKey.WitHash.ScriptPubKey` need to be repeated at 2 places in your code: 
1. When you generate the address
2. When you want to spend the UTXO of this address.

Storing the redeemScript instead of the pubkey mean that only the code generating the address need to know how to generate the redeemScript, so your code is way more flexible.

**Comment by NicolasDorier** [comment]
right

**Comment by knocte** [comment]
Ok, but this that I said before kept me thinking:

> I guess all redeem scripts are equally long (if we're talking about non-multisig), cannot really the size of the transaction (and as a consequence, the fees to be spent) estimated without the public key?

If this change was committed to NBitcoin: 

https://github.com/knocte/NBitcoin/commit/ff442f76fb0a0047a17c3038e3b6e2eb3e0a03a4

Then the code would use this two heuristic method which happens afterwards:

```
if(scriptSigSize == -1)
	scriptSigSize += coin.TxOut.ScriptPubKey.Length; //Using heurestic to approximate size of unknown scriptPubKey
```

Because it seems that fee estimation capability only requests the ScriptCoin when dealing with BuilderExtensions. Are those really needed? or extensions is only for altcoins?

**Comment by NicolasDorier** [comment]
Don't use heuristic, if you undervalue the size of a transaction, this transaction might end up rejected by the network. BuildExtensions is for custom built RedeemScript

**Comment by knocte** [comment]
> BuildExtensions is for custom built RedeemScript

But if I don't use custom-built RedeemScripts, would the heuristic always work for me?

**Comment by NicolasDorier** [comment]
No it won't it will underestimate your transaction size.

**Comment by NicolasDorier** [comment]
Please use `ScriptCoin` not using them is very fragile design. There is simply no reason to not use ScriptCoin.

**Comment by knocte** [comment]
Ok fair enough, thanks for the info.
