### ISSUE TITLE
Adding Wordlist in another language

### ISSUE THREAD

**Issue by utarn** [MetacoSA/NBitcoin#635]
Hi, 

I'm trying to create my own set of wordlist in my language. How do I add another language to WordList class? or How do I plug my own WordList class to NBitcoin?

I tried cloning NBitcoin and adding codes in WordList class, but I wanted to add another class and install-package NBitcoin instead. 

Regards,
Utarn

**Comment by NicolasDorier** [comment]
```csharp
var wordlist = new NBitcoin.Wordlist(words, ' ', "mywordlist");
```

**Comment by knocte** [comment]
@NicolasDorier but we should encourgage contributing this dict to NBitcoin itself right? :)

**Comment by utarn** [comment]
Thank you. It's a Thai language :) Yet it's not been proposed to BIP. So, i'm just learning for myself
