### ISSUE TITLE
`new FeeRate(Money.Zero).ToString()` throws `System.DivideByZeroException`

### ISSUE THREAD

**Issue by osagga** [MetacoSA/NBitcoin#648]
I've recently updated `NBitcoin` from `4.1.1.8` -> `4.1.1.80` and this behaviour

```c#
new FeeRate(Money.Zero).ToString()
```

throws an exception with the following stack trace
```
Unhandled Exception: System.DivideByZeroException: Attempted to divide by zero.
   at System.Decimal.FCallDivide(Decimal& d1, Decimal& d2)
   at NBitcoin.FeeRate.ToString()
```

Is this expected? 

Thanks

**Comment by knocte** [comment]
Maybe it should rather throw an ArgumentException because a zero fee rate is useless?

**Comment by lontivero** [comment]
`DivideByZeroException`s are never expected. Make a PR for fixing it. The problem is in here:
https://github.com/MetacoSA/NBitcoin/blob/550d10c34a29aa432d1173aaf3c470dfa1f6bf19/NBitcoin/FeeRate.cs#L108

I think changing it by the following line could work (test it): 
```c#
if(rounded == 0 || (Math.Abs(rounded - value) / value) < 0.001m)
```

**Comment by knocte** [comment]
@lontivero is a zero fee-rate useful for anything?

**Comment by knocte** [comment]
What use case do those unit tests cover? IMO NBitcoin should prevent devs to shoot themselves in the foot so maybe it's better to throw an ArgumentException here to make an invalid state unrepresentable.

**Comment by osagga** [comment]
I use it to test the case where the RPC `estimateFee` returns `0`, I make sure that my MiningFee logic doesn't go crazy

**Comment by lontivero** [comment]
@knocte this is not about use cases, this is about zero being is a perfectly valid number for fee rate. 
Anyawy, remember that there were thousands of transactions that paid exactly zero fee rate.

**Comment by knocte** [comment]
> Anyawy, remember that there were thousands of transactions that paid exactly zero fee rate.

Good point.
