### ISSUE TITLE
Using NBitcoin on iOS/Android

### ISSUE THREAD

**Issue by sigHash** [MetacoSA/NBitcoin#652]
Hi - Is there anyway to use NBitcoin in native mobile applications?

**Comment by sigHash** [comment]
I was trying to use in xcode/ios.

**Comment by knocte** [comment]
Why doing such a complex thing? Ew!
But anyway, then you could probably use this: https://github.com/mono/Embeddinator-4000

**Comment by NicolasDorier** [comment]
Yeah, I advise against using NBitcoin with native languages. Use xamarin.

**Comment by sigHash** [comment]
I don't know how xamarin interacts with ios, but is there possible to handle private keys using apple's secure enclave? Is it going to page memory to disk?

**Comment by NicolasDorier** [comment]
Yes, xamarin gives you access to the native APIs.

**Comment by NicolasDorier** [comment]
> is there possible to handle private keys using apple's secure enclave? Is it going to page memory to disk?

You can store your keys there, but you can't sign without having your key going into RAM and maybe getting paged to disk.
