### ISSUE TITLE
Any way to validate bitcoin address?

### ISSUE THREAD

**Issue by bojan96** [MetacoSA/NBitcoin#658]
Question says it all.

**Comment by nopara73** [comment]
I'm not sure it does. So you want a `bool IsBitcoinAddress()` function?

**Comment by NicolasDorier** [comment]
``` try { BitcoinAddress.Create("myaddress", Network.Main); return true; } catch { return false; } ```

**Comment by nopara73** [comment]
We use this in Wasabi:

```cs
public static bool TryParseBitcoinAddress(string text, out BitcoinAddress address, Network network)
{
	address = null;

	if (string.IsNullOrEmpty(text) || text.Length > 100)
	{
		return false;
	}

	text = text.Trim();
	try
	{
		address = BitcoinAddress.Create(text, network);
		return true;
	}
	catch (FormatException)
	{
		return false;
	}
}
```

**Comment by bojan96** [comment]
@nopara73 It would be nice if we had one function for address validation, also checksum check would be nice, in meantime I will use the provided code.

**Comment by NicolasDorier** [comment]
his code is doing the checksum
