### ISSUE TITLE
WEBGL Support

### ISSUE THREAD

**Issue by Gamerios** [MetacoSA/NBitcoin#659]
Hi

**i try atm use it at WBEGL but it not work right 
Is there a problem with the DLL in WEBGL or so ?**

Hope someone can help me  thanks   

Kind Regards

**Comment by NicolasDorier** [comment]
You mean you try to use Unity and targeting WebGL and it does not work?

**Comment by Gamerios** [comment]
### Yes when i use your Description for UNity with NET 2.0 is say the DLL not work to build in / not allowed.

When i use at Unity Api NET 4.0 build work but in Build when test it can work with NBitcoin its says no Wallet , Wrong Keys etc.


In Unity Editor or at Mobile and PC it work but not at WEBGL BUild.





Kind Reagerds

**Comment by NicolasDorier** [comment]
Please do not compile NBitcoin in Unity, do this instead https://github.com/MetacoSA/NBitcoin#how-to-use-in-unity

**Comment by Gamerios** [comment]
yes as you see in error and as said i done like that its in unity asset folder as DLL already compiled but not work as wrote above.

please read what i wrote thanks

**Comment by NicolasDorier** [comment]
`its says no Wallet , Wrong Keys etc.` I need more details about the errors you encounter.

**Comment by Gamerios** [comment]
Thanks yes i not find whats the Problem in WEBGL i use the DLL from this free asset and the asset because when i compile like with your unity instructions i get the errors below


https://assetstore.unity.com/packages/add-ons/services/billing/your-bitcoin-controller-118493




Yes when i use your Description for UNity with NET 2.0 is say the DLL not work to build in / not allowed.
This with your method for unity:

#ArgumentException: The Assembly Microsoft.Extensions.Logging.Abstractions is referenced by NBitcoin ('Assets/NBitcoin/NBitcoin.dll'). But the dll is not allowed to be included or could not be found.#

And:
Unloading broken assembly Assets/NBitcoin/NBitcoin.dll, this assembly can cause crashes in the runtime

When i use at Unity Api NET 4.0 build work but in Build when test it can work with NBitcoin its says no Wallet , Wrong Keys etc.

In Unity Editor or at Mobile and PC it work but not at WEBGL BUild.

Kind Regards

**Comment by NicolasDorier** [comment]
Did you copied `Microsoft.Extensions.Logging.Abstractions` in the unity assets?

**Comment by Gamerios** [comment]
Yes had tried and also with the others.

hmm

**Comment by Gamerios** [comment]
> 
> 
> Did you copied `Microsoft.Extensions.Logging.Abstractions` in the unity assets?

 **Thanks any other ideas also when cpmpile newest NBitcoin get allways: in unity: **
 **Unloading broken assembly Assets/NBitcoin/NBitcoin.dll, this assembly can cause crashes in the runtime**

hmm

**Comment by NicolasDorier** [comment]
Sorry I can't really debug from this, and I don't have unity :(

**Comment by Gamerios** [comment]
hmm 

i use unity 2018.2.18f1 you can get for free 

dont know why this error with new dll but wit old build included asset not this error


Unloading broken assembly Assets/NBitcoin/NBitcoin.dll, this assembly can cause crashes in the runtime

**Comment by Gamerios** [comment]
You cant help somehow ?

**Comment by NicolasDorier** [comment]
If you want me to help you need to help me with better error message than this.

**Comment by Gamerios** [comment]
Yes but there is nothing more that its says with this asset at PC and EDitor and Mobile  work but at WEBGL says wrong KEY .

and with newest DLL it says:
Unloading broken assembly Assets/NBitcoin/NBitcoin.dll, this assembly can cause crashes in the runtim


**think it cant work because at WEBGL it converts always to IL2CCP !!
Can that be the problem.**


Regards

**Comment by NicolasDorier** [comment]
NBitcoin works on mono, yeah I doubt it work on IL2CPP. That said, the mono runtime is also available in WEBGL afaik.

**Comment by EstebanGameDevelopment** [comment]
The best option if you want to work in the web browser with Bitcoin is to choose a web based library. Recently I needed something like this and I choose this one:

https://github.com/Bit-Wasp/bitcoin-php

But there are a lot more out there. Just choose the one that you feel more comfortable with. The Unity solution is mostly a solution for mobile smartphones. Their support for web solutions is not the best. 

I'm pretty sure that a hard worker like you will find a solution in the existing open source libraries. Let us know when you have finished your project.

Good Luck!!!

**Comment by Gamerios** [comment]
> 
> 
> NBitcoin works on mono, yeah I doubt it work on IL2CPP. That said, the mono runtime is also available 
in WEBGL afaik.

At:

**WEBGL always use IL2CPP :(**


ANd at Unity 2018 webGL can only chosse NET 4 and at Api Compatiile also only NET 4 if use NET 2 build for WEBGL not work getting only errors because needed for the  Newtonsoft.Json etc

**Comment by NicolasDorier** [comment]
I would be interested to make a Il2CPP compatible version. But not being a gamedev myself I can't do and the errors does not seem good enough for me having any clue about where to start.

**Comment by Gamerios** [comment]
Hello,

**Here when i try to BUild it with the newest NBitcoin.dll  with old from asset build work but in WEBGL not work bitcoin say wrong key but with newest DLL with the  decstiption from ReadMe here i compiled the dll and added other dll that are alos in the folder** 

**i get at build this errors**



`Failed running E:\Program Files\Unity\2018.2.18f1\Editor\Data\il2cpp/build/il2cpp.exe --convert-to-cpp --dotnetprofile="unityjit" --compile-cpp --libil2cpp-static --platform="WebGL" --architecture="EmscriptenJavaScript" --configuration="Release" --outputpath="E:\Assets /../Temp/StagingArea/Data\Native\build.bc" --cachedirectory="E:\Assets\..\Library/il2cpp_cache" --compiler-flags="-Oz -DIL2CPP_EXCEPTION_DISABLED=1 " --emit-method-map --map-file-parser="E:\Program Files\Unity\2018.2.18f1\Editor\Data\Tools\MapFileParser\MapFileParser.exe" --assembly="E:\Temp\StagingArea\Data\Managed\Assembly-CSharp-firstpass.dll" --assembly="E:\Temp\StagingArea\Data\Managed\Assembly-CSharp.dll" --assembly="E:\Temp\StagingArea\Data\Managed\UnityEngine.UI.dll" --assembly="E:\Temp\StagingArea\Data\Managed\UnityEngine.Analytics.dll" --assembly="E:\Temp\StagingArea\Data\Managed\UnityEngine.dll" --assembly="E:\Temp\StagingArea\Data\Managed\mscorlib.dll" --assembly="E:\Temp\StagingArea\Data\Managed\System.dll" --generatedcppdir="E:\Temp\StagingArea\Data\il2cppOutput" 

stdout:
Building build.bc with EmscriptenToolChain
	Output directory: E:\Temp\StagingArea\Data\Native
	Cache directory: E:\Library\il2cpp_cache
il2cpp.exe didn't catch exception: Unity.IL2CPP.Building.BuilderFailedException: E:\Temp\StagingArea\Data\il2cppOutput\Bulk_QBitNinja.Client_0.cpp:10902:33: error: no matching function for call to 'BitcoinSerializableExtensions_ToBytes_m1440712144'
                ByteU5BU5D_t4116647657* L_2 = BitcoinSerializableExtensions_ToBytes_m1440712144(NULL /*static, unused*/, L_1, ((int32_t)70012), /*hidden argument*/NULL);
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
E:\Temp\StagingArea\Data\il2cppOutput\Bulk_QBitNinja.Client_0.cpp:9395:55: note: candidate function not viable: no known conversion from 'int32_t' (aka 'int') to 'ProtocolVersion_t2986654513' for 3rd argument
extern "C" IL2CPP_METHOD_ATTR ByteU5BU5D_t4116647657* BitcoinSerializableExtensions_ToBytes_m1440712144 (RuntimeObject * __this /* static, unused */, RuntimeObject* p0, ProtocolVersion_t2986654513  p1, const RuntimeMethod* method);
                                                      ^
1 error generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting


Invocation was: Executable: "E:\Program Files\Unity\2018.2.18f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten_Win\python\2.7.5.3_64bit\python.exe"
Arguments: "E:\Program Files\Unity\2018.2.18f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\em++" -Wno-unused-value -Wno-invalid-offsetof -nostdinc -fno-strict-overflow -std=c++11 -Oz -DIL2CPP_EXCEPTION_DISABLED=1  -DNET_4_0 -DUNITY_JIT -DGC_NOT_DLL -DRUNTIME_IL2CPP -DNDEBUG -I"E:\Program Files\Unity\2018.2.18f1\Editor\Data\il2cpp\libil2cpp" -I"E:\Program Files\Unity\2018.2.18f1\Editor\Data\il2cpp\external\boehmgc\include" -I"E:\Temp\StagingArea\Data\il2cppOutput" "E:\Temp\StagingArea\Data\il2cppOutput\Bulk_QBitNinja.Client_0.cpp" -o "E:\\Library\il2cpp_cache\7947FF9BC1465A93F5F84D1BB583925D.o"

   bei Unity.IL2CPP.Building.CppProgramBuilder.BuildAllCppFiles(IEnumerable`1 sourceFilesToCompile, IBuildStatisticsCollector statisticsCollector)
   bei Unity.IL2CPP.Building.CppProgramBuilder.Build(IBuildStatistics& statistics)
   bei il2cpp.Program.DoRun(String[] args)
   bei il2cpp.Program.Run(String[] args)
   bei il2cpp.Program.Main(String[] args)
stderr:

Unbehandelte Ausnahme: Unity.IL2CPP.Building.BuilderFailedException: E:\Temp\StagingArea\Data\il2cppOutput\Bulk_QBitNinja.Client_0.cpp:10902:33: error: no matching function for call to 'BitcoinSerializableExtensions_ToBytes_m1440712144'
                ByteU5BU5D_t4116647657* L_2 = BitcoinSerializableExtensions_ToBytes_m1440712144(NULL /*static, unused*/, L_1, ((int32_t)70012), /*hidden argument*/NULL);
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
E:\Temp\StagingArea\Data\il2cppOutput\Bulk_QBitNinja.Client_0.cpp:9395:55: note: candidate function not viable: no known conversion from 'int32_t' (aka 'int') to 'ProtocolVersion_t2986654513' for 3rd argument
extern "C" IL2CPP_METHOD_ATTR ByteU5BU5D_t4116647657* BitcoinSerializableExtensions_ToBytes_m1440712144 (RuntimeObject * __this /* static, unused */, RuntimeObject* p0, ProtocolVersion_t2986654513  p1, const RuntimeMethod* method);
                                                      ^
1 error generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting


Invocation was: Executable: "E:\Program Files\Unity\2018.2.18f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten_Win\python\2.7.5.3_64bit\python.exe"
Arguments: "E:\Program Files\Unity\2018.2.18f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\em++" -Wno-unused-value -Wno-invalid-offsetof -nostdinc -fno-strict-overflow -std=c++11 -Oz -DIL2CPP_EXCEPTION_DISABLED=1  -DNET_4_0 -DUNITY_JIT -DGC_NOT_DLL -DRUNTIME_IL2CPP -DNDEBUG -I"E:\Program Files\Unity\2018.2.18f1\Editor\Data\il2cpp\libil2cpp" -I"E:\Program Files\Unity\2018.2.18f1\Editor\Data\il2cpp\external\boehmgc\include" -I"E:\Temp\StagingArea\Data\il2cppOutput" "E:\Temp\StagingArea\Data\il2cppOutput\Bulk_QBitNinja.Client_0.cpp" -o "E:\Library\il2cpp_cache\7947FF9BC1465A93F5F84D1BB583925D.o"

   bei Unity.IL2CPP.Building.CppProgramBuilder.BuildAllCppFiles(IEnumerable`1 sourceFilesToCompile, IBuildStatisticsCollector statisticsCollector)
   bei Unity.IL2CPP.Building.CppProgramBuilder.Build(IBuildStatistics& statistics)
   bei il2cpp.Program.DoRun(String[] args)
   bei il2cpp.Program.Run(String[] args)
   bei il2cpp.Program.Main(String[] args)

UnityEngine.Debug:LogError(Object)
UnityEditorInternal.Runner:RunProgram(Program, String, String, String, CompilerOutputParserBase) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:128)
UnityEditorInternal.Runner:RunManagedProgram(String, String, String, CompilerOutputParserBase, Action`1) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:73)
UnityEditorInternal.IL2CPPBuilder:RunIl2CppWithArguments(List`1, Action`1, String) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:380)
UnityEditorInternal.IL2CPPBuilder:ConvertPlayerDlltoCpp(ICollection`1, String, String, Boolean) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:361)
UnityEditorInternal.IL2CPPBuilder:Run() (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:178)
UnityEditorInternal.IL2CPPUtils:RunIl2Cpp(String, IIl2CppPlatformProvider, Action`1, RuntimeClassRegistry) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:42)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
`



And this:  

`Exception: E:\Program Files\Unity\2018.2.18f1\Editor\Data\il2cpp/build/il2cpp.exe did not run properly!
UnityEditorInternal.Runner.RunProgram (UnityEditor.Utils.Program p, System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:130)
UnityEditorInternal.Runner.RunManagedProgram (System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser, System.Action`1[T] setupStartInfo) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:73)
UnityEditorInternal.IL2CPPBuilder.RunIl2CppWithArguments (System.Collections.Generic.List`1[T] arguments, System.Action`1[T] setupStartInfo, System.String workingDirectory) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:380)
UnityEditorInternal.IL2CPPBuilder.ConvertPlayerDlltoCpp (System.Collections.Generic.ICollection`1[T] userAssemblies, System.String outputDirectory, System.String workingDirectory, System.Boolean platformSupportsManagedDebugging) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:361)
UnityEditorInternal.IL2CPPBuilder.Run () (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:178)
UnityEditorInternal.IL2CPPUtils.RunIl2Cpp (System.String stagingAreaData, UnityEditorInternal.IIl2CppPlatformProvider platformProvider, System.Action`1[T] modifyOutputBeforeCompile, UnityEditor.RuntimeClassRegistry runtimeClassRegistry) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:42)
UnityEditor.WebGL.WebGlBuildPostprocessor.CompileBuild (UnityEditor.Modules.BuildPostProcessArgs args) (at /Users/builduser/buildslave/unity/build/PlatformDependent/WebGL/Extensions/Unity.WebGL.extensions/BuildPostprocessor.cs:367)
UnityEditor.WebGL.WebGlBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at /Users/builduser/buildslave/unity/build/PlatformDependent/WebGL/Extensions/Unity.WebGL.extensions/BuildPostprocessor.cs:936)
UnityEditor.Modules.DefaultBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at C:/buildslave/unity/build/Editor/Mono/Modules/DefaultBuildPostprocessor.cs:27)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:287)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
`



**And BUILD say successfully but the folder is empty because the above BUILD errors.** 




**when try build with net 2.0 WEBGL it say build faild and much more errors.**



Regards

**Comment by NicolasDorier** [comment]
From where did you get QBitNinjaClient?

**Comment by Gamerios** [comment]
****Is included here:**
https://assetstore.unity.com/packages/add-ons/services/billing/your-bitcoin-controller-118493

**Also NBitcoin.dll  with that its compile able but not work when try in Broswer**

**and with the Newest NBitcoin i get the erorrs at compile above.****

**Comment by NicolasDorier** [comment]
Contact the add-on guy. He need to update NBitcoin dependency.

**Comment by EstebanGameDevelopment** [comment]
With the latest NBitcoin  DLLs the add-on doesn't work anymore. The DLLs that work are around 1 year old. Sorry, but I don't have time to look the reason why the current DLLs don't work anymore. I can not work for free anymore. I've a family and I need to pay the bills.

Maybe you should try the Bitcoin access with a different technology. Feel free to do it native foreach platform you want to develop your solution.

Good Luck!
