### ISSUE TITLE
Process is terminating due to StackOverflowException.

### ISSUE THREAD

**Issue by oripio** [MetacoSA/NBitcoin#661]
There is impossible to generate new passphrase, the process is being terminated due to StackOverflowException. Since this is uncatchable exception, this is critical stopper.

example of code:
var passphraseCode = new BitcoinPassphraseCode("my super puper secret", Network.TestNet, null);

Target framework: netcoreapp2.2
NBitcoin version: 4.1.1.82

**Comment by oripio** [comment]
Additional info: it seems the problem in Jetbrains Rider 2018.3.3 (Build #RD-183.5619.41).
'Run' configuration works fine but 'Debug' fails to the StackOverflowException.

**Comment by nopara73** [comment]
I've done a quick test: It works properly in Wasabi Wallet (Debug mode, mainnet through GUI (the wallet password is also the passphrase.)
