### ISSUE TITLE
Support for Bitcoin SV ?

### ISSUE THREAD

**Issue by arkoc** [MetacoSA/NBitcoin#667]
Are there any plans to support new Bitcoin Cash fork, Bitcoin SV?
Can BCash altcoin be used for this new fork?

**Comment by NicolasDorier** [comment]
BCash is supported. Bitcoin SV is not supported because it goes above the P2P size limit of 32MB and because C# have significant overhead where one block would have a size in RAM of more than 500MB.

**Comment by FrozDark** [comment]
Hi!
Can you make Bitcoin SV support for at least Transaction builder and Node connection for sumbitting transaction?

**Comment by NicolasDorier** [comment]
no
