### ISSUE TITLE
Altcoin Tests CanSignTransactions() problem with Stratis Altcoin wallet confirmations

### ISSUE THREAD

**Issue by mikedennis** [MetacoSA/NBitcoin#678]
This may be a behaviour difference between Bitcoin and Stratis wallets.

When the P2SH coin spend is attempted:
```
// Let's try P2SH with 2 coins
aliceAddress = alice.PubKey.ScriptPubKey.GetScriptAddress(builder.Network);
txid = rpc.SendToAddress(aliceAddress, Money.Coins(1.0m));
```

The Stratis node throws and exception saying "No spendable transactions found."

It looks like this is because the previous transaction sent to the wallet doesn't have enough confirmations yet so the coins are still locked.

If I change the blocks generated to this:
```
node.Generate(builder.Network.Consensus.CoinbaseMaturity + 3);
``` 
Instead of coinbase+1 then I don't have problems with the confirmation as there are enough coins for the transactions.

If this is a valid change let me know and I can submit a PR.

**Comment by NicolasDorier** [comment]
Which mean that the CoinbaseMaturity setting of stratis in NBitcoin.Altcoins is incorrect

**Comment by NicolasDorier** [comment]
However, this is strange as there is another test testing the correctness of this setting. I think there is another explanation.

**Comment by mikedennis** [comment]
Ok, I will investigate further. I suspect maybe it is to do with the way the change for a transaction is being handled in Stratis vs Bitcoin. Will close this out until I can find some more concrete explanation.
