### ISSUE TITLE
Why is parse JSON transaction obsolate?

### ISSUE THREAD

**Issue by nopara73** [MetacoSA/NBitcoin#688]
![image](https://user-images.githubusercontent.com/9156103/56985685-31b2be00-6b89-11e9-8957-5ea63cbdea8c.png)

In Wasabi we're implementing transaction building and broadcasting. I thought it'd be fun to let the user to mess with the JSON and broadcast that instead.

I don't feel strongly about this feature, but I wanted to ask why JSON tx parse is obsolate?

![image](https://user-images.githubusercontent.com/9156103/56985834-8b1aed00-6b89-11e9-919c-fe468b4a7b40.png)

![image](https://user-images.githubusercontent.com/9156103/56985896-b271ba00-6b89-11e9-86d5-486c9a2ea5d7.png)

**Comment by nopara73** [comment]
Ops, that's a PSBT json in the screenshots, nevermind you get the idea.

**Comment by NicolasDorier** [comment]
Because I did not see any reason to use this. But this seems a good reason.
I think though it is way better that you make a JSON parser for PSBT, as it is likely people will want to mess around with it.

**Comment by nopara73** [comment]
Thanks! I'll think about it. We have a feature freeze right now, because Wasabi is not very user friendly anymore, but in the future it'd would be fun to add an IDE for this and we can rename it to Wasabi Studio :)
