### ISSUE TITLE
Tell me how to get script from P2SH Hash.

### ISSUE THREAD

**Issue by Dewazakura** [MetacoSA/NBitcoin#689]
Hi. I have a question.
How do I get the bitcoin script from the variable pubParams below?

Use P2SH.

```
var pubParams = PayToScriptHashTemplate.Instance
    .ExtractScriptPubKeyParameters(new Script(BTCAddress.ScriptPubKey.ToString()));
// pubParams is "eebe246b4ec0075a8dc145de96f6fd799151dc79"
```

I want to get OP_CODE from this hash value.

**Comment by NicolasDorier** [comment]
Please read https://programmingblockchain.gitbooks.io/programmingblockchain/content/

Your question show too much misunderstanding about what you want to achieve.
