### ISSUE TITLE
Using BTCPay as Full Node for Liquid 

### ISSUE THREAD

**Issue by lrgeoemtry** [MetacoSA/NBitcoin#693]
Hi
Im setting up a Liquid Sidechain and id like to use my NBitcoin from my Azure PayServer to be the full node for the Liquid Side chain.

Any tuts in getting this moving are appreciated.

Thanks

**Comment by NicolasDorier** [comment]
Wrong repository. Post on btcpayserver https://github.com/btcpayserver/btcpayserver-docker please.

The best is that you put liquid in a docker image then you add a custom fragment with Liquid container inside.

**Comment by Kukks** [comment]
You can close this, already done: https://github.com/btcpayserver/btcpayserver-docker/blob/master/docker-compose-generator/docker-fragments/liquid.yml
