### ISSUE TITLE
How do you get receiving addresses from a raw transaction?

### ISSUE THREAD

**Issue by Yokomoko** [MetacoSA/NBitcoin#699]
I am trying to decode a transaction generated by nBitcoin, with nBitcoin. 

I am using:

```
NBitcoin.Transaction.Parse(hex, Groestlcoin.Instance.Mainnet);
```

This provides me with a NBitcoin.Transaction. Looking through the TxOut records within that transaction, there doesn't seem to be an easy way to get the public addresses from the TxOut record? 

Please excuse my ignorance.

**Comment by NicolasDorier** [comment]
Read https://programmingblockchain.gitbooks.io/programmingblockchain/content/

var address = tx.Outputs[0].ScriptPubKey.GetDestinationAddress(Groestlcoin.Instance.Mainnet);

Note that all outputs don't have necessarily addresses.

**Comment by Yokomoko** [comment]
Thank you!
