### ISSUE TITLE
Using AzureKeyVault as an external signer with a transaction builder

### ISSUE THREAD

**Issue by tehnetaholic** [MetacoSA/NBitcoin#706]
I have implemented signing P2SH transactions with Azure Key Vault as a private key storage. My aim is for the private keys to never leave the storage and to be created there from the start.

Now I am trying to implement P2W over P2SH and I have a hard time figuring out how to do it. Articles at programmingblockchain.gitbook.io recommend using TransactionBuilder, but in order to use it I have to have an access to private keys. Is it possible to use an external signer with a transaction builder?

If no, could you hint me on what exactly do I have to change in order for transactions to become P2W over P2SH? I would really appreciate any help here. I read throught the docs many times but I am still running in circles :sweat_smile:
I simply want to pay less fees and to be able to receive and transfer funds.

Here is how I generate an address from x and y:
```c#
            var uncompressedPubKey = new byte[] { 0x4 }.Concat(x).Concat(y).ToArray();
            var pubKey = new PubKey(uncompressedPubKey).Compress(true);
            var address = pubKey.Hash.ScriptPubKey.Hash.GetAddress(_network.GetNetwork());
```
And here is how I am signing
```c#
            foreach (var utxo in unsignedTransaction.Utxos)
            {
                ...
                var pubKeyBytes = new byte[] { 0x4 }.Concat(keyBundle.Result.Key.X).Concat(keyBundle.Result.Key.Y).ToArray();
                var storedPubKey = new PubKey(pubKeyBytes).Compress(true);
                var scriptPubKey = storedPubKey.Hash.ScriptPubKey;

                var utxoTxId = uint256.Parse(utxo.TransactionId);
                var signatureHash = unsignedTransaction.Transaction.GetSignatureHash(
                    new Coin(utxoTxId,(uint)utxo.Vout, new Money(utxo.Amount, MoneyUnit.BTC), 
                        scriptPubKey));
                var signature = await _kvc.SignAsync(keyBundle.Result.Key.Kid, "ECDSA256", signatureHash.ToBytes());
                var encodedSignature = EncodeSignature(signature.Result, SigHash.All);

                var input = unsignedTransaction.Transaction.Inputs.First(x => x.PrevOut.Hash == utxoTxId && x.PrevOut.N == utxo.Vout);
                input.ScriptSig = new Script(
                    Op.GetPushOp(encodedSignature),
                    Op.GetPushOp(storedPubKey.ToBytes()),
                    Op.GetPushOp(scriptPubKey.ToBytes()));
            }
```

I would really appreciate any help. Thank you!

**Comment by NicolasDorier** [comment]
> I have implemented signing P2SH transactions with Azure Key Vault as a private key storage.

This is useless, AzureKeyVault does not know what it is signing, a hacker could ask it to sign a hash transmitting all the money to himself and the vault would happily sign.

Though yes it is possible to use transaction builder `builder.AddKnownSignature(sig, pubkey)`.

**Comment by tehnetaholic** [comment]
@NicolasDorier I am sorry, but what you are saying is that if a hacker can get an access to a private key then a hacker got an access to a private key. Anyway, I figured it out

**Comment by r-anjirabi** [comment]
I also have implemented signing transactions with HSM as a private key storage, 
but i encounter some errors!

 `   
var network = Network.TestNet;
            
            var destination = BitcoinAddress.Create(receiverAddress, network);
            var sender = BitcoinAddress.Create(senderAddress, network);

            var unspentCoins = (await GetUnSpentCoins(senderAddress, network));
            var builder = network.CreateTransactionBuilder();
            var tx = builder
                .AddCoins(unspentCoins)
                .Send(destination, Money.Coins(0.00001M))
                .SubtractFees()
                .SendEstimatedFees(new FeeRate(1m))
                .SetChange(sender.ScriptPubKey)
                .BuildTransaction(false);

            var wallet = HSMWallet.Load(walletName);
            var signedTx = wallet.SignTransaction(tx.ToHex());

            var pubKey = new NBitcoin.PubKey(wallet.PubKey.RawPubKey);
            var signature = new TransactionSignature(Encoders.Hex.DecodeData(signedTx));
            builder
                .AddKnownSignature(pubKey, signature, unspentCoins[0].Outpoint)
                .SetSigningOptions(SigHash.All);

            builder.SignTransactionInPlace(tx);

            var error = builder.Check(tx);

            var verify = builder.Verify(tx);
            if (verify)
            {
                var result = await BroadcastTransaction(tx.ToHex(), Settings.BlockcypherToken, network);
                return result;

            }`

check method `(builder.Check(tx))` i get two errors :
0. {Script error on input 0 (SigHashType)}
1. {Fee too low, actual is 0.00000226, policy minimum is 0.00000258}

How can I make this work? 
Thanks a lot
