### ISSUE TITLE
Allow to set version of jsonrpc

### ISSUE THREAD

**Issue by reximus** [MetacoSA/NBitcoin#708]
![image](https://user-images.githubusercontent.com/3177765/59969682-6d03b480-955c-11e9-9646-1c52fdc6298c.png)

Inside request payload there is
"jsonrpc":"1.0"

but server does not support 1.0 version.
only 2.0
There is no way to set new version.

**Comment by reximus** [comment]
it requires implementation of rpc 2.0 version.
replacing this value does not solve the issue

**Comment by NicolasDorier** [comment]
how is it possible? Bitcoin core use RPC v1
