### ISSUE TITLE
TransactionBuilder's default Shuffle doesn't work

### ISSUE THREAD

**Issue by nopara73** [MetacoSA/NBitcoin#713]
Neither on the inputs, nor on the outputs.

**Comment by NicolasDorier** [comment]
This is not possible. Checking that

**Comment by NicolasDorier** [comment]
It is because you create the transaction outside of the transaction builder (using `.Continue(tx)`). Yes, the transaction builder does not change your transaction.

**Comment by nopara73** [comment]
Thanks, that explains why it works on normal transactions. I'll shuffle outside with coinjoins.
