### ISSUE TITLE
PSBT ignores sighashType

### ISSUE THREAD

**Issue by junderw** [MetacoSA/NBitcoin#714]
Signing functions all take a sighash type as an arg with SIGHASH_ALL as default.

The BIP says that if sighash type is present you must sign with that type or fail.

Also finalizers must fail if they see a PartialSig with a sighash that is different than the type in the PSBTInput

perhaps the easy and secure way to do it is throw error if the passed arg and the input sighash type don't match, and in error message say "please pass the same sighash type as the input if you want to sign"

**Comment by NicolasDorier** [comment]
What do you mean by ignores the `sighashType`? My sign function do not sign if the sighash of the signer conflict with what is in the input.

**Comment by junderw** [comment]
https://github.com/MetacoSA/NBitcoin/blob/master/NBitcoin/BIP174/PartiallySignedTransaction.cs#L506

Is there some other sign function?

**Comment by NicolasDorier** [comment]
@junderw yes, look in `TrySign` of the input.

**Comment by NicolasDorier** [comment]
It goes eventually here https://github.com/MetacoSA/NBitcoin/blob/master/NBitcoin/BIP174/PSBTInput.cs#L799

**Comment by junderw** [comment]
Ok, I see it now.

**Comment by NicolasDorier** [comment]
No bug in my code

![image](https://user-images.githubusercontent.com/3020646/61050269-95772400-a421-11e9-951a-3a1641a70e37.png)

**Comment by junderw** [comment]
Oh there are bugs!

They are just hiding... lol
