### ISSUE TITLE
ToHex throws exception when transaction is too large

### ISSUE THREAD

**Issue by MJeorrett** [MetacoSA/NBitcoin#715]
Hi,

When we call `ToHex` on transactions above a certain size (few hundred K) we get an exception thrown.  I have traced the exception to the `BitcoinStream` that is being written to when converting the Tx to bytes.  It seems that the public `MaxArraySize` property on the stream is too small - it is defaulted to `1024 x 1024`.

Would you consider either;
A) bumping up the default `MaxArraySize` to `int.MaxValue`.
B) adding an optional parameter to the ToHex method that takes a max size that is set on the BitcoinStream that is written to.

Option A) seems simplest, though not sure what the reason behind the chosen default or consequences of increasing it are?

Happy to put a PR up for either of these, or an other fix, if I can get a steer on best approach.

Thanks

Matthew

**Comment by NicolasDorier** [comment]
@MJeorrett can you give me a repro?

`MaxArraySize` is about the size of an array (number of items in an array). There should be no case of transaction exceeding this.

**Comment by MJeorrett** [comment]
Hi @NicolasDorier, thanks for getting back.  I have uploaded a minimal repro here.

We are using the NBitcoin in a custom network where we are looking to allow larger transactions than those that are allowed in the bitcoin network.  I have forked NBitcoin project and just changed the hard coded default for BticoinStream.MaxArraySize and this seems to be the only change required in order to support large transactions throughout NBitcoin.

**Comment by NicolasDorier** [comment]
@MJeorrett why don't you just instantiate the BitcoinStream and change the `MaxArraySize`?
More pain than just `.ToHex()` but you would not need to fork.

I would advise you against removing the `MaxArraySize` completely, as it would be trivial to crash your software.

**Comment by MJeorrett** [comment]
Thanks for the advice on MaxArraySize @NicolasDorier.

Following my initial raising of the issue I also quickly bumped in to the same problem with `GetHash` and `Transaction.Parse` i.e. the `MaxArraySize` of the underlying `BitcoinStream` not being big enough or being configurable from the calls.

Is the suggested workaround to implement custom implementations of these three methods which copy the implementation from NBitcoin but increase the `MaxArraySize` in the used `BitcoinStream`?

**Comment by NicolasDorier** [comment]
I don't want to do it. It would open people using it to denial of services.

If you use NBitcoin to listen an untrusted peer and `.Parse` has no limit, it is trivial for this peer to make your process crash.

I advise you to do this:

Copy and paste the methods that interest you into extensions methods in your project like `Transaction.Parse2` or `Transaction.ToHex2`.
In the implementation, you have access to the BitcoinStream, so you can configure it as you see fit.

**Comment by MJeorrett** [comment]
Sorry, I didn't explain well, I meant exactly what you have said.  I'll do that and see how I get on.
