### ISSUE TITLE
key.ScriptPubKey Error

### ISSUE THREAD

**Issue by wasimjee** [MetacoSA/NBitcoin#717]
Getting Following Error

> 'key.ScriptPubKey' threw an exception of type 'System.TypeInitializationException'

on the Code 

```
Key key = new Key(); 
var secretkey = key.GetBitcoinSecret(Network.Main);
```

**Comment by knocte** [comment]
> 'key.ScriptPubKey' threw an exception of type 'System.TypeInitializationException'

Please post **full exception** (what you get with `ex.ToString()`).

**Comment by wasimjee** [comment]
Getting this on ex.message

> The type initializer for 'NBitcoin.Network' threw an exception.

**Comment by NicolasDorier** [comment]
I need the stack trace.

**Comment by wasimjee** [comment]
Thanks for your Reply.

I found the Issue.

The System.Buffers dll was not loading.

now it is working fine

**Comment by knocte** [comment]
> Getting this on ex.message

ex.Message is just the message, ex.ToString() is always preferred when reporting bugs because it includes details about all inner exceptions
