### ISSUE TITLE
SetGenesis for Altcoins

### ISSUE THREAD

**Issue by Silverwizard80** [MetacoSA/NBitcoin#720]
Hi, sorry if this ends up being a dumb question, but I am trying to add support for a Bitcoin 18 based altcoin. When I try to instantiate the network I get the error "Invalid Hex String" I have generated the genesis hex using the console of the coin using getblock [genesis hash] 0. I also modified the CreateGenesisBlock method in Bitcoin's Network.cs in NBitcoin and got the same hex value when I converted the block to hex. Im not sure if this is an issue with my implementation, but I would really appreciate some insight into this issue. 
Thanks in advance!

**Comment by NicolasDorier** [comment]
Sorry I don't know, look the example for the other altcoins in NBitcoin.Altcoins.

**Comment by Silverwizard80** [comment]
Thanks for the response. I tried following the other altcoins examples, I mainly looked at Bcash when I tried to convert it over. Not sure if I am missing something major here, but It seems odd to me. I think the issue occurs in Consensus Factory, but not sure why.
`public class VimeeCoin : NetworkSetBase
	{
		public static VimeeCoin Instance { get; } = new VimeeCoin();

		public override string CryptoCode => "VME";

		private VimeeCoin()
		{

		}

		public class VimeeCoinConsensusFactory : ConsensusFactory
		{
			private VimeeCoinConsensusFactory()
			{
				
			}

			public static VimeeCoinConsensusFactory Instance { get; } = new VimeeCoinConsensusFactory();

			public override ProtocolCapabilities GetProtocolCapabilities(uint protocolVersion)
			{
				var capabilities = base.GetProtocolCapabilities(protocolVersion);
				capabilities.SupportWitness = false;
				return capabilities;
			}
		}

		protected override NetworkBuilder CreateMainnet()
		{
			System.UInt32 nTime = 1231006505;
			System.UInt32 nNonce = 1632967096;
			System.UInt32 nBits = 0x1d00ffff;
			int nVersion = 1;
			var money = NBitcoin.Money.Coins(50);
			var gen = CreateGenesisBlock(nTime, nNonce, nBits, nVersion, money).ToBytes();
			var encoded = Encoders.Hex.EncodeData(gen);
			var builder = new NetworkBuilder();

			builder.SetConsensus(new Consensus()
			{
				SubsidyHalvingInterval = 210000,
				MajorityEnforceBlockUpgrade = 750,
				MajorityRejectBlockOutdated = 950,
				MajorityWindow = 1000,
				BIP34Hash = new uint256(0x0),
				PowLimit = new Target(new uint256("00000000ffffffffffffffffffffffffffffffffffffffffffffffffffffffff")),
				PowTargetTimespan = TimeSpan.FromSeconds(60),
				PowTargetSpacing = TimeSpan.FromSeconds(20),
				PowAllowMinDifficultyBlocks = false,
				PowNoRetargeting = false,
				RuleChangeActivationThreshold = 1916,
				MinerConfirmationWindow = 2016,
				CoinbaseMaturity = 100,
				MinimumChainWork = new uint256("0x0"),
				ConsensusFactory = VimeeCoinConsensusFactory.Instance
			})
			.SetBase58Bytes(Base58Type.PUBKEY_ADDRESS, new byte[] { 70 })
			.SetBase58Bytes(Base58Type.SCRIPT_ADDRESS, new byte[] { 71 })
			.SetBase58Bytes(Base58Type.SECRET_KEY, new byte[] { 198 })
			.SetBase58Bytes(Base58Type.EXT_PUBLIC_KEY, new byte[] { 0x04, 0x88, 0xB2, 0x1E })
			.SetBase58Bytes(Base58Type.EXT_SECRET_KEY, new byte[] { 0x04, 0x88, 0xAD, 0xE4 })
			.SetBech32(Bech32Type.WITNESS_PUBKEY_ADDRESS, Encoders.Bech32("vme"))
			.SetBech32(Bech32Type.WITNESS_SCRIPT_ADDRESS, Encoders.Bech32("vme"))
			.SetMagic(0x8c3efdc9)
			.SetPort(9777)
			.SetRPCPort(8332)
			.SetName("vme-main")
			.SetMaxP2PVersion(70015)
			.AddDNSSeeds(new DNSSeedData[0])
			.AddSeeds(new NetworkAddress[0])
			.SetGenesis(encoded);
			return builder;
		}

		protected override NetworkBuilder CreateTestnet()
		{
			throw new NotImplementedException();
		}

		protected override NetworkBuilder CreateRegtest()
		{
			throw new NotImplementedException();
		}

		public Block CreateGenesisBlock(uint nTime, uint nNonce, uint nBits, int nVersion, Money genesisReward)
		{
			string pszTimestamp = "Formula 1 legend Niki Lauda dies age 70";
			Script genesisOutputScript = new Script(Op.GetPushOp(Encoders.Hex.DecodeData("04678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38c4f35504e51ec112de5c384df7ba0b8d578a4c702b6bf11d5f")), OpcodeType.OP_CHECKSIG);
			return CreateGenesisBlock(pszTimestamp, genesisOutputScript, nTime, nNonce, nBits, nVersion, genesisReward);
		}

		private Block CreateGenesisBlock(string pszTimestamp, Script genesisOutputScript, uint nTime, uint nNonce, uint nBits, int nVersion, Money genesisReward)
		{
			//Consensus.ConsensusFactory.CreateTransaction();
			Transaction txNew = VimeeCoinConsensusFactory.Instance.CreateTransaction();
			txNew.Version = 1;
			txNew.Inputs.Add(scriptSig: new Script(Op.GetPushOp(486604799), new Op()
			{
				Code = (OpcodeType)0x1,
				PushData = new[] { (byte)4 }
			}, Op.GetPushOp(Encoders.ASCII.DecodeData(pszTimestamp))));
			txNew.Outputs.Add(genesisReward, genesisOutputScript);
			//Consensus.ConsensusFactory.CreateBlock();
			Block genesis = VimeeCoinConsensusFactory.Instance.CreateBlock();
			genesis.Header.BlockTime = Utils.UnixTimeToDateTime(nTime);
			genesis.Header.Bits = nBits;
			genesis.Header.Nonce = nNonce;
			genesis.Header.Version = nVersion;
			genesis.Transactions.Add(txNew);
			genesis.Header.HashPrevBlock = uint256.Zero;
			genesis.UpdateMerkleRoot();
			return genesis;
		}
	}`

**Comment by NicolasDorier** [comment]
I don't know, you should step by step in.

**Comment by Silverwizard80** [comment]
Ok, I just setup a new solution with NBitcoin, NBitcoin.Altcoins, and my console app. When I run `Network net = NBitcoin.Altcoins.VimeeCoin.Instance.Mainnet` I get "Invalid Hex String" when I look at `DecodeData(string encoded)` in HexEncoder.cs encoder is 0 so obviously I get the error for invalid hex string. When I put a break point at the Network instantiation and step into it I get the error "It seems like you are recursively accessing a Network which is not yet built" in NetworkSet.cs with `bool _Registered = false;` and `Registering = true;` I do have the coin registered in AltcoinNetworkSets.cs, but is there another place I need to register?

**Comment by Silverwizard80** [comment]
I figured out what the issue was. `BIP34Hash = new uint256(0x0),` and `MinimumChainWork = new uint256("0x0"),` couldnt be set with only 0 substituted for `BIP34Hash = new uint256("0000000038e697712a0d83c18bb2a09a0a53f7bcaf5ff4c2050c7102c37d8ae2")` and `MinimumChainWork = new uint256("0000000000000000000000000000000000000000000000000000000000000000")` which seems to be functioning for now!
