### ISSUE TITLE
How do I generate Bip38 paper wallets / private keys suitable for ECMultiplyLotSequence?

### ISSUE THREAD

**Issue by FreeSMIME** [MetacoSA/NBitcoin#726]
I see in the unit tests the following line that appears to solve my need (a raw signature over arbitrary data)

How do I create a strSecret suitable for import in the following line:

 BitcoinSecret bsecret1C = Network.Main.CreateBitcoinSecret(strSecret1C);

**Comment by NicolasDorier** [comment]
see https://github.com/MetacoSA/NBitcoin/issues/727
