### ISSUE TITLE
Unsupported scriptPubKey

### ISSUE THREAD

**Issue by Bassist067** [MetacoSA/NBitcoin#735]
Hi everyone! Thanks for good library and nice doc book - I've read it multiple times. 

When I'm running just the basic example, I'm stuck at the "Unsupported scriptPubKey" exception when trying to partially sign the transaction.

I was able to retrieve the last transaction with the real satoshis, but signing it seems to be impossible.

The code looks pretty straightforward and the exception is not documented anywhere. I've looked at the source code and it seems somehow the **CanGenerateScriptSig** method always returns false.

Can you please assist?

![Capture](https://user-images.githubusercontent.com/19996164/63720130-b46a3200-c878-11e9-8eae-9244cace3581.PNG)

**Comment by knocte** [comment]
Paste the whole `ex.ToString()` here.

**Comment by Bassist067** [comment]
There you have it.

```
System.NotSupportedException: Unsupported scriptPubKey
   at NBitcoin.TransactionBuilder.CreateScriptSig(TransactionSigningContext ctx, ICoin coin, IndexedTxIn txIn)
   at NBitcoin.TransactionBuilder.Sign(TransactionSigningContext ctx, ICoin coin, IndexedTxIn txIn)
   at NBitcoin.TransactionBuilder.SignTransactionInPlace(TransactionSigningContext ctx)
   at NBitcoin.TransactionBuilder.SignTransaction(Transaction transaction)
   at ConsoleApp1.Program.Main(String[] args)
```

also,           
 ` PayToMultiSigTemplate.Instance.CheckScriptPubKey(alice.ScriptPubKey);` 

returns false.

**Comment by NicolasDorier** [comment]
@Bassist067 you should not `AddCoins` twice to the same builder, instead, create a new builder.

**Comment by NicolasDorier** [comment]
Looking at your code I don't see anything wrong though. Can you share on pastebin?

**Comment by NicolasDorier** [comment]
Oh I know.

**Comment by NicolasDorier** [comment]
The `redeemScript` should not be `GenerateScritPubKey(...).PaymentScript` but `GenerateScritPubKey(...)`

**Comment by Bassist067** [comment]
> @Bassist067 you should not `AddCoins` twice to the same builder, instead, create a new builder.

Thank you Nicolas, that wouldn't make sense for me anyway. It's natural to load coins just once. And there's the [code sample](https://pastebin.com/20MquwDJ)

**Comment by NicolasDorier** [comment]
@Bassist067 if you used `GenerateScritPubKey(...).PaymentScript` as the redeem script and want to recover your money, this is an interesting excercise, but you can't do it with `TransactionBuilder`.

Basically  `GenerateScritPubKey(...).PaymentScript` is `OP_HASH160 <hash_of_the_multisig_script> OP_EQUAL`. Which mean that if you need to push to the scriptSig `<GenerateScritPubKey(...)> <GenerateScritPubKey(...).PaymentScript>`. Notice that you don't need any signature, so a miner can theorically steal it.

**Comment by Bassist067** [comment]
Thank you so much Nicolas, now it works without that error! Basically, what I want to achieve there is just creating the Multisig wallet on fly. receive bticoins from outside and then send bitcoins to some 3rd party, like ESCROW.

**Comment by NicolasDorier** [comment]
Second issue, your fees are less than 1 satoshi, minumum is 216 . I am getting back your money one sec

**Comment by NicolasDorier** [comment]
I recovered your money

https://blockstream.info/tx/55c3516d8c85856b2ae63ffceebfc7db6c1427773df2c8b064a7a7912b3afef6

```
010000000197c2ae7a2d06e6e4e28e225418d45949db0c02c739a57cb02c0dbbe355ae33a700000000834c6952210248976b7c4009c5152a79fb5d4e150fe16416b3fb50ab682db16a302bb05b5e6321037aa3ccc7a9a07ba601d9a4a43d4fe8cd6c71cb7f8c66de58d614b493b61c41a12103fb15e4bf69081e61e53de70049c0e9c875666d27e84f3913411d5835d4c850b753ae17a91469f8ee14a27ff5886327a8d4fb8215bec072d16a87ffffffff01f1110000000000001976a9149f904fac967ef95afe8ae0d0fec5b177ab3a63e988ac0000000055c3516d8c85856b2ae63ffceebfc7db6c1427773df2c8b064a7a7912b3afef6
```

**Comment by Bassist067** [comment]
no worries. Also, there's the guide where I've initially discovered the NBitcoin library - dude there uses .PaymentScript for some reasons

**Comment by NicolasDorier** [comment]
`.PaymentScript` is the scriptPubKey you want to set for your multisig if you want to do a p2sh payment. This is from that that your P2SH address is generated.

**Comment by NicolasDorier** [comment]
Here is the code I used to recover your money, as an exercise: https://pastebin.com/0GeyFSXq
