### ISSUE TITLE
AddressManager uses almost 100% CPU when no internet

### ISSUE THREAD

**Issue by lontivero** [MetacoSA/NBitcoin#736]
This problem happens in Wasabi Wallet and I think there is no workaround. The details are here: 
https://github.com/zkSNACKs/WalletWasabi/issues/2193

**Comment by NicolasDorier** [comment]
on it

**Comment by NicolasDorier** [comment]
Should be fixed on version 4.2.5 https://github.com/MetacoSA/NBitcoin/commit/78b2f07a22c5f190ef01e0c424f8628cfebc1724
