### ISSUE TITLE
TransactionBuilder performance

### ISSUE THREAD

**Issue by MithrilMan** [MetacoSA/NBitcoin#737]
I'm working on a code that was using transactionbuilder in a sub-optimal way and I'm trying to see what's the best approach to have the least performance impact 

Imagine you are an exchange (they are the ones with the biggest wallets) and you have lots of UTXO (assume just 10_000 but I expect way more to handle) and of course lot of addresses these utxo belongs to (for simplicity imagine 1 utxo per address)

Imagine now you need to send coins to multiple recipients in a single transaction.
Which approach would you take?

Actually legacy code was done this way:

giving a transactionbuilder instance called `tb`
- adding all utxo using tb.AddCoins
- adding all utxo secrets using tb.AddKeys
- using multiple tb.Send for each destination
- build the transaction with tb.BuildTransaction(true) so actually build and sign in a single call

to be precise the code I had to fix was even doing a kind of coin preselection but I removed that because otherwise CoinSelection algo would be bypassed

now in the scenario above, the problem is that adding 10_000 coins and their relative keys mean spending minutes just to add keys so what I wanted to do was to add keys only for selected coins.

Digging in the code I saw that keys are required during Sign process (of course) and so I had to call BuildTransaction(false) in order to trigger the coinselection without signing it yet and then feed the transactionbuilder with the required keys before SignInPlace
The problem is that there isn't any built-in facilitation to fill only needed keys, so I did this change: https://github.com/stratisproject/StratisBitcoinFullNode/blob/f8f749ca26b16af7722c5c5f67cd71c881caf1c7/src/NBitcoin/TransactionBuilder.cs#L1120-L1184

Basically I created an overload of BuildTransaction that will return me the used Coins, this way I can then add required keys and nothing more (I changed transactionbuilder for this test purpose but I would like to not touch that file)

What's your suggested approach to this problem?
An alternative approach I may think about is iterating through every tx input of the generated transaction but it's more limited

What about adding a callback that would be called by the TransactionBuilder in case a key is missing? (something that can be set like `tb.SetKeyFetcher(actionThatFetchACoinKey)`)
This way we could even use the tb.BuildTransaction(true) requiring it to sign already and our callback will feed the transactionbuilder with missing keys

About performance, in my test I see it took around 35 seconds to sign a transaction that had 1300 utxos but we are running old NBitcoin code on Stratis, so do you know if that performance has improved making use of Span<> or other improvements?
Thanks

**Comment by NicolasDorier** [comment]
> so I did this change: 

I think it is not needed. This is an obscure overload that can be solved in the following way.

1. You first `TransactionBuilder.BuildTransaction(false)`
2. Use `TransactionBuilder.FindSpentCoins(unsignedTx)` (I think this point you did not know)
3. Fetch only the keys that you want
4. `TransactionBuilder.AddKeys(usedkeys)`
5. `TransactionBuilder.SignInPlace`

>  tb.SetKeyFetcher(actionThatFetchACoinKey))

It does not seem to me easier than above.

**Comment by MithrilMan** [comment]
oh yeah you are right, missed the FindSpentCoins
That's basically doing the other approach I wanted to do, inspect the built transaction inputs
> An alternative approach I may think about is iterating through every tx input of the generated transaction but it's more limited

This won't allow me to call BuildTransaction(true) (sign when building) but it's not a stopping point
thanks

**Comment by NicolasDorier** [comment]
Cool @MithrilMan there is no point to call with `true` for your usecase, so I don't see any downside.
