### ISSUE TITLE
incorrect bitcoin core code reference

### ISSUE THREAD

**Issue by MithrilMan** [MetacoSA/NBitcoin#739]
https://github.com/MetacoSA/NBitcoin/blob/0f0af7cffa0b31079a953289378c71d12999ff56/NBitcoin/TransactionBuilder.cs#L30

this url resolve to a 404, would be nice to have a permalink reference or a link to the code/description of the implemented algo

**Comment by yahiheb** [comment]
This is the [line](https://github.com/bitcoin/bitcoin/blob/5b40d8868820265adb24fec097905e84edb85762/src/wallet.cpp#L1276) when that link was add, but it doesn't look correct.

**Comment by NicolasDorier** [comment]
yeah need to be replace with a link not referencing master

**Comment by MithrilMan** [comment]
I leave here about the algo that I found looking on google searching for same comment text
https://bitcoin.stackexchange.com/a/29962/45107

I suppose this was the source of everything
In the comment you see a (broken too) url that point to L1129
Looking at the date I found the right spot to point it:
https://github.com/bitcoin/bitcoin/blob/3015e0bca6bc2cb8beb747873fdf7b80e74d679f/src/wallet.cpp#L1129

so I think you could update that comment with the url above 

btw about the algoritm itself I did some tests and I'm not that happy with the result current coin selection (I'm working with lot of utxos) both in terms of speed and accuracy, I'll try to implement different coin selection algos and then I'll share my benchmark (both in term of speed and selected coin)

**Comment by MithrilMan** [comment]
for example, an improvement I'm testing is caused by the fact that DefaultCoinSelector pick up more utxos than needed, so I added this code before returning result in `Select` method

```
// optimize the set of used coins, removing unnecessary small inputs
List<ICoin> sortedUsedCoins = result.OrderBy(c => c.Amount).ToList();
IMoney excess = total.Sub(target);
for (int i = 0; i < sortedUsedCoins.Count; i++)
{
    // if the smallest coin in the set is smaller or equal to the difference between the excess of
    // the total and its amount, we can safely remove it
    ICoin coin = sortedUsedCoins[i];
    if (coin.Amount.CompareTo(excess) <= 0)
    {
        result.Remove(coin);
        excess = excess.Sub(coin.Amount);
    }

    if (excess.CompareTo(zero) <= 0)
        break;
}
```

**Comment by yahiheb** [comment]
> In the comment you see a (broken too) url that point to L1129

The broken url points to L1276.

**Comment by MithrilMan** [comment]
I'm talking about the stackoverflow comment I linked above, where comments in code have been taken from, so maybe it's better to point to the same line
