### ISSUE TITLE
Should remove dependency on System.Net.Http nuget

### ISSUE THREAD

**Issue by knocte** [MetacoSA/NBitcoin#743]
As discussed here (https://github.com/dotnet/corefx/issues/19914#issuecomment-529113925) it is deprecated, and makes NBitcoin break in Mono (unless an ugly workaround is used).

**Comment by NicolasDorier** [comment]
@knocte can you check? I tried removing it but it would not compile.

**Comment by NicolasDorier** [comment]
it seems to work that way.... I am unsure about the behavior with binding redirects.

**Comment by NicolasDorier** [comment]
check https://github.com/MetacoSA/NBitcoin/commit/3310cf0efaec5a0070e920138edfa6e3607996dd

**Comment by knocte** [comment]
> I tried removing it but it would not compile.

Seems to compile fine with https://github.com/MetacoSA/NBitcoin/commit/3310cf0efaec5a0070e920138edfa6e3607996dd right?

> can you check?

If it compiles I think it should be fine. Anyway, to be 100% sure and test from my side, I guess we need to bump and publish new nuget version of NBitcoin? So that I can test from my wallet, removing the System.Net.Http workaround I had.
