### ISSUE TITLE
How to send USDT by multiple addresses?

### ISSUE THREAD

**Issue by LeeDeil** [MetacoSA/NBitcoin#744]
I have implemented send USDT by single address, but I can't deal with a situation that a address have enough USDT and don't have enough BTC to send fee, so I want to send fee with another address's BTC . And I do it in my program, but it's error "[0] = {Script error on input 0 (NullFail)}" in TransactionBuilder.Verify.

It's success if I comment out the code between //*****// in my test program. 

Here I'm generating the transaction:
```
public bool SendUsdt(string toAddress, decimal amount, out string changeAddress, out decimal changeAmount, decimal fee = 0)
        {
            var usdtNode = new RPCClient("*****", "*****", Network.Main);
            try
            {
                var sendCoins = new HashSet<Coin>();
                var det = BitcoinAddress.Create(toAddress, Network.Main);
                Money feeMoney = new Money(Fee, MoneyUnit.BTC);
                if (fee != 0)
                    feeMoney = new Money(fee, MoneyUnit.BTC);
                var sendAssert = new List<MutiTransaction>();
                //get enough usdt and btc to sendAssert
                var builder = Network.CreateTransactionBuilder();
                NBitcoin.Transaction tx = null;
                foreach (var item in sendAssert)
                    builder = builder.AddCoins(item.Coins);
                tx = builder
                    .AddKeys(sendAssert.Select(x => x.Key).ToArray())
                    .Send(det, new Money(0.00000546m, MoneyUnit.BTC))
                    .SetChange(sendAssert[sendAssert.Count - 1].Address)
                    .SendFees(feeMoney)
                    .BuildTransaction(true);

                //****//
                string opreturn = "OP_RETURN 6f6d6e69000000000000001f" + Convert.ToString((int)amount * 100000000, 16).PadLeft(16, '0');
                tx.Outputs.Add(new Money(0m, MoneyUnit.BTC), new Script(opreturn));
                //****//

                changeAddress = sendAssert[sendAssert.Count - 1].Address.ToString();
                changeAmount = sendAssert.Sum(x => x.Coins.Sum(p => p.Amount.ToDecimal(MoneyUnit.BTC))) - feeMoney.ToDecimal(MoneyUnit.BTC) - 0.00000546m;
                tx.Outputs.Add(new Money(changeAmount, MoneyUnit.BTC), sendAssert[sendAssert.Count - 1].Address);
                if (!builder.Verify(tx, out var error))
                {
                    throw new Exception($"Create Transaction Failed! {error[0].ToString()}");
                }
                var cmd = new RPCRequest("sendrawtransaction", new object[] { tx.ToHex(), false });
                var r = usdtNode.SendCommand(cmd);
                return true;
            }
            catch (Exception e) { throw new NodeServerException(e.Message); }
        }

private class MutiTransaction
        {
            public MutiTransaction(HashSet<Coin> coins, ISecret key, BitcoinAddress address, decimal amount = 0)
            {
                Coins = coins;
                Key = key;
                Address = address;
                Amount = amount;
            }
            public BitcoinAddress Address { get; private set; }
            public decimal Amount { get; private set; }
            public HashSet<Coin> Coins { get; set; } = new HashSet<Coin>();
            public ISecret Key { get; set; }
        }
```

The broadcast response returns:
`e = {"16: mandatory-script-verify-flag-failed (Signature must be zero for failed CHECK(MULTI)SIG operation)"}`

Transaction hex:
`0100000007c77438ce9ab68885ea7ed3bb94df3c2219750d068909dc005206fe845d0b8bc6030000006a4730440220458d8ccaf9aa64fa2b5bc118ce80b241ae0299cb6357c97fdf6443da26d37ec602203e7166b8ca83bc533feaeaf38a0729ba60394fd54dfedfc303fa4583b3300c64012102b8ba4eb98aafbcf340fb7a1e48fb30ff83e3ec8cf4b3edde143c28a29fa209d2ffffffffe76204367cbc77f6cca6feaa4cafb2b941dcffa3f1a4d299d6bc9453020e6d13030000006a473044022069146430f2abb2fc2a9eb005437084848be91f73a172bf17ed4fb87f9e8dd616022015f8e8bab58b502570346a3d7b300f152e0177e3673be13031cacb59a755a35b012102c6dd0e9b47a5853a2ce8c3d722d754d17dc86179681a7dd43bb9c60190071686ffffffffd375509ecd0ba55f0d6e5b73bca09d25a56cee0b8ab5ba03e5902d9dcc3aabb7030000006a473044022005263ae88ddcdb41d695cd9bc994b049861791d04ddaa680234a7cf6eb7946e80220402620188b19d0ad46d186f54f9c8af4033d014bc4b344945b7170d5c7d8c35b012102026f586ee700b08816f29374f0153aafe72dddab0d10ea3125234c190e43322fffffffff16c27061bcd2f5aeb1bc4c36fab847a0098e8b8d01e24e858c904868897f3669030000006a47304402205656bbfdf3b45c8bc04246f4636de08922dd99d65c141731342afc85df14905d0220692ed409a0a034eee11ad34d3f47daa3e613d17e4375f45cfef8ec2f0afb556c0121022ed6f3be1a0555b180ee39fe03918129051864e6cfbd49ab64cbcb00e1018f52ffffffff2d40c0628d107d04cbf284b5db2f8c7275d830a10119561f5fb14b3fa405958f030000006a473044022066722bffa94d251009fe6cc369d03404d7acb20098ff74d3883aa347e93b47d102203b0605bf877fa8f58617e04ac3cfa6f2cccc2d5c40901bfd5f287f4047cdbf2a012102b19c9e33ea5cad42d5a01683837b266eb9a9c97c15f0bab73f50fc31b7dfb57effffffff10eeb37bc1bb6d6cec05c57ff96ee55bd463cd4ab9b59b753a6fbc9c57e1e75c020000006a47304402204d7af01f074f447c0b20cfd93c92500052362239f5ed267297d3823e4e2675ba0220487f70e521f5f04b31fa3830ccf22acc3f8819e4adc6e4f62b7d152d1adbeab601210294fd408dd61c3a9c13f1e237ac8602d38b15e6755fca41d4b0bb59f1692d0217ffffffffb4167109adab9be6d3a587478a502acd5b1e7dd11d0408af2297f814ce3fc087020000006a473044022050766f045a693665e0e00bc77ea5fa3490adaf8793a5305f25216c070db0928e022007b246a9a89a924c61e319c6131fc13b29f5078c13cac1e5deee21d6c22cbe3501210372ae0de718049e9708993b5f5ae7acc521fc772d1d5921d3ebdc87992019c98dffffffff0322020000000000001976a914a86c23803acdb5bdbaf34ba37e78e42284255a7f88ac0000000000000000166a146f6d6e69000000000000001f00000000a817c80036030000000000001976a9145198253ea904721b368623bd81f8e1fc1e9371f588ac00000000`

Decoded transaction:
```
{
  "txid": "9f1fb0c6ab098e803631bf79a92eee436099ddb4c4b6f6306abc2a0746130e04",
  "hash": "9f1fb0c6ab098e803631bf79a92eee436099ddb4c4b6f6306abc2a0746130e04",
  "version": 1,
  "size": 1138,
  "vsize": 1138,
  "weight": 4552,
  "locktime": 0,
  "vin": [
    {
      "txid": "c68b0b5d84fe065200dc0989060d7519223cdf94bbd37eea8588b69ace3874c7",
      "vout": 3,
      "scriptSig": {
        "asm": "30440220458d8ccaf9aa64fa2b5bc118ce80b241ae0299cb6357c97fdf6443da26d37ec602203e7166b8ca83bc533feaeaf38a0729ba60394fd54dfedfc303fa4583b3300c64[ALL] 02b8ba4eb98aafbcf340fb7a1e48fb30ff83e3ec8cf4b3edde143c28a29fa209d2",
        "hex": "4730440220458d8ccaf9aa64fa2b5bc118ce80b241ae0299cb6357c97fdf6443da26d37ec602203e7166b8ca83bc533feaeaf38a0729ba60394fd54dfedfc303fa4583b3300c64012102b8ba4eb98aafbcf340fb7a1e48fb30ff83e3ec8cf4b3edde143c28a29fa209d2"
      },
      "sequence": 4294967295
    },
    {
      "txid": "136d0e025394bcd699d2a4f1a3ffdc41b9b2af4caafea6ccf677bc7c360462e7",
      "vout": 3,
      "scriptSig": {
        "asm": "3044022069146430f2abb2fc2a9eb005437084848be91f73a172bf17ed4fb87f9e8dd616022015f8e8bab58b502570346a3d7b300f152e0177e3673be13031cacb59a755a35b[ALL] 02c6dd0e9b47a5853a2ce8c3d722d754d17dc86179681a7dd43bb9c60190071686",
        "hex": "473044022069146430f2abb2fc2a9eb005437084848be91f73a172bf17ed4fb87f9e8dd616022015f8e8bab58b502570346a3d7b300f152e0177e3673be13031cacb59a755a35b012102c6dd0e9b47a5853a2ce8c3d722d754d17dc86179681a7dd43bb9c60190071686"
      },
      "sequence": 4294967295
    },
    {
      "txid": "b7ab3acc9d2d90e503bab58a0bee6ca5259da0bc735b6e0d5fa50bcd9e5075d3",
      "vout": 3,
      "scriptSig": {
        "asm": "3044022005263ae88ddcdb41d695cd9bc994b049861791d04ddaa680234a7cf6eb7946e80220402620188b19d0ad46d186f54f9c8af4033d014bc4b344945b7170d5c7d8c35b[ALL] 02026f586ee700b08816f29374f0153aafe72dddab0d10ea3125234c190e43322f",
        "hex": "473044022005263ae88ddcdb41d695cd9bc994b049861791d04ddaa680234a7cf6eb7946e80220402620188b19d0ad46d186f54f9c8af4033d014bc4b344945b7170d5c7d8c35b012102026f586ee700b08816f29374f0153aafe72dddab0d10ea3125234c190e43322f"
      },
      "sequence": 4294967295
    },
    {
      "txid": "69367f896848908c854ee2018d8b8e09a047b8fa364cbcb1aef5d2bc6170c216",
      "vout": 3,
      "scriptSig": {
        "asm": "304402205656bbfdf3b45c8bc04246f4636de08922dd99d65c141731342afc85df14905d0220692ed409a0a034eee11ad34d3f47daa3e613d17e4375f45cfef8ec2f0afb556c[ALL] 022ed6f3be1a0555b180ee39fe03918129051864e6cfbd49ab64cbcb00e1018f52",
        "hex": "47304402205656bbfdf3b45c8bc04246f4636de08922dd99d65c141731342afc85df14905d0220692ed409a0a034eee11ad34d3f47daa3e613d17e4375f45cfef8ec2f0afb556c0121022ed6f3be1a0555b180ee39fe03918129051864e6cfbd49ab64cbcb00e1018f52"
      },
      "sequence": 4294967295
    },
    {
      "txid": "8f9505a43f4bb15f1f561901a130d875728c2fdbb584f2cb047d108d62c0402d",
      "vout": 3,
      "scriptSig": {
        "asm": "3044022066722bffa94d251009fe6cc369d03404d7acb20098ff74d3883aa347e93b47d102203b0605bf877fa8f58617e04ac3cfa6f2cccc2d5c40901bfd5f287f4047cdbf2a[ALL] 02b19c9e33ea5cad42d5a01683837b266eb9a9c97c15f0bab73f50fc31b7dfb57e",
        "hex": "473044022066722bffa94d251009fe6cc369d03404d7acb20098ff74d3883aa347e93b47d102203b0605bf877fa8f58617e04ac3cfa6f2cccc2d5c40901bfd5f287f4047cdbf2a012102b19c9e33ea5cad42d5a01683837b266eb9a9c97c15f0bab73f50fc31b7dfb57e"
      },
      "sequence": 4294967295
    },
    {
      "txid": "5ce7e1579cbc6f3a759bb5b94acd63d45be56ef97fc505ec6c6dbbc17bb3ee10",
      "vout": 2,
      "scriptSig": {
        "asm": "304402204d7af01f074f447c0b20cfd93c92500052362239f5ed267297d3823e4e2675ba0220487f70e521f5f04b31fa3830ccf22acc3f8819e4adc6e4f62b7d152d1adbeab6[ALL] 0294fd408dd61c3a9c13f1e237ac8602d38b15e6755fca41d4b0bb59f1692d0217",
        "hex": "47304402204d7af01f074f447c0b20cfd93c92500052362239f5ed267297d3823e4e2675ba0220487f70e521f5f04b31fa3830ccf22acc3f8819e4adc6e4f62b7d152d1adbeab601210294fd408dd61c3a9c13f1e237ac8602d38b15e6755fca41d4b0bb59f1692d0217"
      },
      "sequence": 4294967295
    },
    {
      "txid": "87c03fce14f89722af08041dd17d1e5bcd2a508a4787a5d3e69babad097116b4",
      "vout": 2,
      "scriptSig": {
        "asm": "3044022050766f045a693665e0e00bc77ea5fa3490adaf8793a5305f25216c070db0928e022007b246a9a89a924c61e319c6131fc13b29f5078c13cac1e5deee21d6c22cbe35[ALL] 0372ae0de718049e9708993b5f5ae7acc521fc772d1d5921d3ebdc87992019c98d",
        "hex": "473044022050766f045a693665e0e00bc77ea5fa3490adaf8793a5305f25216c070db0928e022007b246a9a89a924c61e319c6131fc13b29f5078c13cac1e5deee21d6c22cbe3501210372ae0de718049e9708993b5f5ae7acc521fc772d1d5921d3ebdc87992019c98d"
      },
      "sequence": 4294967295
    }
  ],
  "vout": [
    {
      "value": 0.00000546,
      "n": 0,
      "scriptPubKey": {
        "asm": "OP_DUP OP_HASH160 a86c23803acdb5bdbaf34ba37e78e42284255a7f OP_EQUALVERIFY OP_CHECKSIG",
        "hex": "76a914a86c23803acdb5bdbaf34ba37e78e42284255a7f88ac",
        "reqSigs": 1,
        "type": "pubkeyhash",
        "addresses": [
          "1GMY4qPv7kY1258hgdrY4AMcTiXpjsVWZH"
        ]
      }
    },
    {
      "value": 0.00000000,
      "n": 1,
      "scriptPubKey": {
        "asm": "OP_RETURN 6f6d6e69000000000000001f00000000a817c800",
        "hex": "6a146f6d6e69000000000000001f00000000a817c800",
        "type": "nulldata"
      }
    },
    {
      "value": 0.00000822,
      "n": 2,
      "scriptPubKey": {
        "asm": "OP_DUP OP_HASH160 5198253ea904721b368623bd81f8e1fc1e9371f5 OP_EQUALVERIFY OP_CHECKSIG",
        "hex": "76a9145198253ea904721b368623bd81f8e1fc1e9371f588ac",
        "reqSigs": 1,
        "type": "pubkeyhash",
        "addresses": [
          "18SRznwU2mvAqNkVfpjCbWpJVSQwfMLpE6"
        ]
      }
    }
  ]
}
```

**Comment by NicolasDorier** [comment]
The library don't support USDt

**Comment by LeeDeil** [comment]
> The library don't support USDt

The library support add output by script, so we can add usdt script

**Comment by NicolasDorier** [comment]
The problem is that you are modifying the transaction AFTER having signed. You can't do this.

You should create the transaction without signing, add the output then sign.

**Comment by LeeDeil** [comment]
> The problem is that you are modifying the transaction AFTER having signed. You can't do this.
> 
> You should create the transaction without signing, add the output then sign.

thx, I try it just now, it's success by your idea

**Comment by lzimm** [comment]
@LeeDeil is there any chance you ended up using this? i'm trying to do the same thing and would love to see your final code if you don't mind? :)

**Comment by LeeDeil** [comment]
> @LeeDeil is there any chance you ended up using this? i'm trying to do the same thing and would love to see your final code if you don't mind? :)
you just changed '.BuildTransaction(true);' to '.BuildTransaction(false);' and insert 'tx = bd.SignTransaction(tx, SigHash.All);' before  'if (!builder.Verify(tx, out var error))'.This function only used when one address have enough usdt but don't have btc,and another address have enough btc

**Comment by LeeDeil** [comment]
> @LeeDeil is there any chance you ended up using this? i'm trying to do the same thing and would love to see your final code if you don't mind? :)

you just changed '.BuildTransaction(true);' to '.BuildTransaction(false);' and insert 'tx = bd.SignTransaction(tx, SigHash.All);' before 'if (!builder.Verify(tx, out var error))'.This function only used when one address have enough usdt but don't have btc,and another address have enough btc

**Comment by LeeDeil** [comment]
> @LeeDeil is there any chance you ended up using this? i'm trying to do the same thing and would love to see your final code if you don't mind? :)

you just changed '.BuildTransaction(true);' to '.BuildTransaction(false);' and insert 'tx = builder.SignTransaction(tx, SigHash.All);' before 'if (!builder.Verify(tx, out var error))'.This function only used when one address have enough usdt but don't have btc,and another address have enough btc
