### ISSUE TITLE
It broke building of my project from 4.2.8

### ISSUE THREAD

**Issue by ArtjomP** [MetacoSA/NBitcoin#747]
Hello there!
I use NBitcoin in my Xamarin.Forms project. And it broke building iOS project since 4.2.8 (4.2.7 is the last version witch doesn't break my build).
The error is:
**MTOUCH : error MT2002: Failed to resolve "System.Void System.Runtime.CompilerServices.IsReadOnlyAttribute::.ctor()" reference from "netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51"** 
I think it's because of this change: https://github.com/MetacoSA/NBitcoin/commit/f69a5cc072a7e6eeced103cb236a6f11813e29f2
Let me know if you need any additional information.
Thank you in advance!

**Comment by NicolasDorier** [comment]
Hey have you checked the last version I normally reverted this one?

**Comment by NicolasDorier** [comment]
4.2.14

**Comment by ArtjomP** [comment]
Yes, I have. 
Actually, I updated it to 4.2.14 at first.

**Comment by knocte** [comment]
netStandard2.1? were you using this target before Artjom? or .netStandard2.0?

**Comment by ArtjomP** [comment]
Always <TargetFramework>netstandard2.0</TargetFramework>

**Comment by knocte** [comment]
why does it say .netstandard2.1 now then?

**Comment by ArtjomP** [comment]
Good point. I don't know this is iOS project & there is no TargetFramework in the project file. 
This project references to a common .netstandard2.0 library witch reference NBitcoin. iOS project references NBitcoin either. It worked well before 4.2.8 :(

**Comment by ArtjomP** [comment]
All other Android & UWP projects build well even after updating

**Comment by ArtjomP** [comment]
When Nuget resolves referenes for iOS project it writes the next for NBitcoin:
**Checking compatibility for NBitcoin 4.2.14 with .NETStandard,Version=v2.0.**

**Comment by NicolasDorier** [comment]
@knocte I guess it uses .NETStandard 2.0. I will check what is going on @ArtjomP , it should not have break anything.

**Comment by NicolasDorier** [comment]
@ArtjomP can you try to get a better stacktrace or something? I can't find out what is the problem :(

**Comment by NicolasDorier** [comment]
wait a min

```
MTOUCH : error MT2002: Failed to resolve "System.Void System.Runtime.CompilerServices.IsReadOnlyAttribute::.ctor()" reference from "netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51"
```

It is using netstandard 2.1 that's not right, it should use netstandard 2.0.
Can you give us the logs of the build where you saw "Checking compatibility for NBitcoin 4.2.14 with .NETStandard,Version=v2.0."

**Comment by NicolasDorier** [comment]
It seems that it break after I added support to netstandard2.1.  However, xamarin does not support netstandard2.1 yet, so it should not be picked up by the build.

**Comment by NicolasDorier** [comment]
worse I will remove netstandard 2.1 support and just support netcoreapp3.0 but I want to check the logs befoer.

**Comment by ArtjomP** [comment]
Here is my log: https://quickfileshare.org/1053/build.log
Let me know if you need more information. Or I can create a new project and try with it.

**Comment by ArtjomP** [comment]
Thank you in advance!

**Comment by ArtjomP** [comment]
I would like to mention that it works well if I just downgrade NBitcion down to 4.2.7

**Comment by NicolasDorier** [comment]
@ArtjomP I think one of the difference between 4.2.7 and 4.2.8 is that I target netstandard2.1 instead of netcoreapp3.0 because it is more "general". But it is possible that xamarin has a bug and is taking netstandard2.1 while not supporting it.

**Comment by NicolasDorier** [comment]
Can you check if you have an update for xamarin? it seems like a bug there.

**Comment by NicolasDorier** [comment]
@ArtjomP can you try the following:
1. Update visual studio (if you can)
2. Create blank new xamarin iOS project
3. Try to replicate this bug.

If it happens again, I think I will stop targeting netstandard2.1.

**Comment by ArtjomP** [comment]
I'll try.
Thank you

**Comment by ArtjomP** [comment]
Sorry for the delay.
It seems I'm able to use NBitcoin 4.2.14.
It required me to update Mono runtime to the latest release 6.4.0.
Thank you for your support!
Sorry for bothering you.

**Comment by knocte** [comment]
@ArtjomP what version of Mono were you using before?

**Comment by ArtjomP** [comment]
It was 6.0.0.
Not very old one :)

**Comment by ArtjomP** [comment]
I also updated .Net Core SDK to 3.1.0 but it didn't help without the Mono update. 
It seems that it's required also as far it supports .Net Standard 2.1 https://docs.microsoft.com/en-us/dotnet/standard/net-standard
But I'm not sure. I can check it if you need.

**Comment by knocte** [comment]
What OS?

**Comment by ArtjomP** [comment]
OS X 10.14.6 (18G95) Mojave

**Comment by ArtjomP** [comment]
This is my build machine: https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.14-Readme.md#xamarin

**Comment by NicolasDorier** [comment]
Thanks for the report.

This is still quite strange. So Mono 6.4 support netstandard2.1, but I guess this was added like 1 week ago, as I am quite sure that when you opened the issue, it was not supported in Mono.

The fact that Mono 6.0 tries to use netstandard2.0 is a bug from Mono. Since 6.4 should be a non breaking update, I will keep supporting netstandard2.1 though.
