### ISSUE TITLE
Performance issue with coin selection

### ISSUE THREAD

**Issue by maciejzaleski** [MetacoSA/NBitcoin#751]
When we are attempting to create a transaction from a wallet containing 2000+ UTXOs it takes a very long time to build a transaction.

**Comment by NicolasDorier** [comment]
@maciejzaleski thanks for the report, it should not. Can you help me identify the problem by creating a small repro?

**Comment by nopara73** [comment]
(Or a unit test.)

**Comment by NicolasDorier** [comment]
I could reproduce the issue when I ported the KnapsackSolver from core, should have happen when grouping by scriptPubKey was disabled. I was instead creating new keys and this is expensive operation.
