### ISSUE TITLE
Don't use .Reverse()

### ISSUE THREAD

**Issue by ianadavies** [MetacoSA/NBitcoin#757]
https://github.com/MetacoSA/NBitcoin/blob/cb02607e1fadd7c81b1003312f5465db8165273f/NBitcoin/UInt2561.cs#L245

Just allocate pn7 -> pn0 as this will allocate a new array.

**Comment by NicolasDorier** [comment]
`Array.Reverse` should not allocate a new array. And even if I did, this would not be equivalent.

**Comment by ianadavies** [comment]
Ah yeah sorry my bad, previous implementation was using the linq reverse.
