### ISSUE TITLE
add tweaking functions for privkeys/pubkeys

### ISSUE THREAD

**Issue by ysangkok** [MetacoSA/NBitcoin#758]
libsecp256k1 includes [a couple of functions for doing point/scalar arithmetic](https://github.com/bitcoin-core/secp256k1/blob/870a977644de7f7d7c47c6928d0dac3381fa8b70/src/eckey_impl.h#L55).

since the bigintegers of pubkeys and privkeys are not exposed, i can't add this functionality myself.

so it would be nice to have this functionality to bring the pubkey/privkey classes to feature parity with libsecp256k1.

**Comment by NicolasDorier** [comment]
We decided to not expose cryptographic functions from NBitcoin because, contrary to libsecp256k1, NBitcoin is not meant for mathematician, exposing more mean people will end up shooting themselves in the foot. I would advise to instead depend on BouncyCastle directly.

**Comment by NicolasDorier** [comment]
See https://github.com/MetacoSA/NBitcoin/issues/716#issuecomment-515352997
