### ISSUE TITLE
Private key to WIF 

### ISSUE THREAD

**Issue by ragekillen** [MetacoSA/NBitcoin#762]
Is there any way to convert the priv key to wif format. I have been trying to figure this out for 2 days

**Comment by yahiheb** [comment]
https://programmingblockchain.gitbook.io/programmingblockchain/bitcoin_transfer/private_key

**Comment by ragekillen** [comment]
thanks that works if i want to get a new key but how can i do this with a key i already have

what i tried is (and no its not my priv key im using a random key lol"
string privkey = "756bcbdd0def50800b82f399bf31f0636b914a1bb5e412eefc5a8911e0d5608c"'
Key privateKey = privkey;

this throws the error cannot implicitly  convert type string to NBitcoin.Key

which

**Comment by ragekillen** [comment]
i figured it out first convert string to a byte array then return the array then pass array to 
key privatekey = new key(byte[] btckey)
