### ISSUE TITLE
ECDSASignature.ToDER() makes invalid DER from some r, s values

### ISSUE THREAD

**Issue by DanGould** [MetacoSA/NBitcoin#773]
For example, given the raw 64 byte `r|s` signature `E1AC191AA300507C6EB94A0F77717E6523FA523CE06F19904C970F4F1B1167AA6FC193416BF35B38EFA47EBDA9BB93681206BC7B6FFF49BC045B2D7491EFD394`
such that bytes 0-31 are `r` and 32-63 are `s`

```csharp
var realSig = "E1AC191AA300507C6EB94A0F77717E6523FA523CE06F19904C970F4F1B1167AA6FC193416BF35B38EFA47EBDA9BB93681206BC7B6FFF49BC045B2D7491EFD394";
var r = new NBitcoin.BouncyCastle.Math.BigInteger(StringToByteArray(realSig.Substring(0, 64)));
var s = new NBitcoin.BouncyCastle.Math.BigInteger(StringToByteArray(realSig.Substring(64)));
var ecdsa = new ECDSASignature(r, s).MakeCanonical();
Assert.True(ECDSASignature.IsValidDER(ecdsa)); // false
var der = new ECDSASignature(ecdsa.ToDER());
Assert.True(ECDSASIgnature.IsValidDER(der)); // false

// ...
// The above relies on the following helper:
public static byte[] StringToByteArray(string hex)
{
	return Enumerable.Range(0, hex.Length)
		 .Where(x => x % 2 == 0)
		 .Select(x => Convert.ToByte(hex.Substring(x, 2), 16))
		 .ToArray();
}
```

Because both `r` and `s`'s top bytes `0xE1` and `0x6F` begin with 1, for them to be valid DER a `0x00` byte must be appended to the front. They pass the `IsValidDER` tests if imported as follows:

```csharp
var r = new NBitcoin.BouncyCastle.Math.BigInteger(StringToByteArray("00" + realSig.Substring(0, 64)));
var s = new NBitcoin.BouncyCastle.Math.BigInteger(StringToByteArray("00" + realSig.Substring(64)));
```

but isn't the whole point of `ToDER()` or `MakeCanonical()` to right these wrongs and make a valid DER? Happy to PR to add this check if my understanding of these methods is in line with NBitcoin's intention for them.

**Comment by zeptin** [comment]
Unless I am missing something, that example does not compile.

`MakeCanonical` only affects the S value, per the method's comment.

**Comment by DanGould** [comment]
You're missing
```csharp
public static byte[] StringToByteArray(string hex)
{
	return Enumerable.Range(0, hex.Length)
					 .Where(x => x % 2 == 0)
					 .Select(x => Convert.ToByte(hex.Substring(x, 2), 16))
					 .ToArray();
}
```

which I will add to the original.
I suppose the crux of this issue is `ToDer` (https://github.com/MetacoSA/NBitcoin/blob/a615d201aff38b55e954fa3a184a0a439f202b12/NBitcoin/Crypto/ECDSASignature.cs#L78) rather than `MakeCanonical`. I will update the title as well

**Comment by NicolasDorier** [comment]
@DanGould I am unsure how this can be the case, NBitcoin is signing tons of transaction with this `ToDer`.

How could you come across this issue?

**Comment by DanGould** [comment]
The `realSig` I listed is the sig for [this](https://blockstream.info/testnet/tx/5bdc2cf3cf21f38d65324273820ece7ca6687077c414bc60ff8172ba0474f90e?output:1) transaction. I got the output in 64 byte `r|s` format from [Unbound's CASP](https://www.unboundtech.com/cryptoasset-security-platform/)  which I returns an ECDSA signature from what I believe to be OpenSSL. Is it possible the other working applications of `ToDER` are all getting 0-prefixed values? Most crypto coin libraries (and bitcoin core) will give signatures in the correct DER format. I'm not sure why CASP is returning this format of signature instead of DER, but it is for sure a valid signature when prefixed and formatted to DER correctly.

**Comment by dangershony** [comment]
Are you sure you are converting the HEX correctly? in the method `StringToByteArray`

**Comment by DanGould** [comment]
@dangershony Yes. The above code with the "00" append results in `ecdsa.ToDER()).Replace("-", string.Empty)` evaluating to: `3045022100E1AC191AA300507C6EB94A0F77717E6523FA523CE06F19904C970F4F1B1167AA02206FC193416BF35B38EFA47EBDA9BB93681206BC7B6FFF49BC045B2D7491EFD394`

Serialized canonical DER:
- `30` - DER prefix
- `45` - Length of rest of Signature
- `02` - Marker for r value
- `21` - Length of r value
- `00E1...AA` - r value, Big Endian
- `02` - Marker for s value
- `20` - Length of s value
- `6FC1...94 - s value, Big Endian

without "00", `ecdsa.ToDER()).Replace("-", string.Empty)` evaluates to: `30440220E1AC191AA300507C6EB94A0F77717E6523FA523CE06F19904C970F4F1B1167AA02206FC193416BF35B38EFA47EBDA9BB93681206BC7B6FFF49BC045B2D7491EFD394`

Serialized non-canonical DER:
- `30` - DER prefix
- `44` - Length of rest of Signature
- `02` - Marker for r value
- `20` - Length of r value
- `E1AC...AA` - r value, Big Endian **THIS IS NON-CANONICAL DER**
- `02` - Marker for s value
- `20` - Length of s value
- `6FC1...94 - s value, Big Endian

According to the Strict DER Signatures (BIP66) outlined [here](https://github.com/libbitcoin/libbitcoin-system/wiki/ECDSA-and-DER-Signatures) "the DER standard does not allow r,s values with first byte values of >0x7F, whilst this is ignored by the OpenSSL implementation."

NBitcoin's implementation is also ignoring this on executing `ToDER` as shown by the serialized non-Canonical DER, but Bitcoin Core, thanks to BIP66 requires this since v0.8.0 as mentioned in the [compatibility section of the BIP writeup](https://github.com/bitcoin/bips/blob/master/bip-0066.mediawiki#compatibility).

The DER function should have a check for >0x7F and prepend a 0-byte if that is the case

**Comment by NicolasDorier** [comment]
This here is a minefield, so I don't want to fix until it is clear I am wrong.
It seems to me this is wrong.
```
var r = new NBitcoin.BouncyCastle.Math.BigInteger(StringToByteArray(realSig.Substring(0, 64)));
var s = new NBitcoin.BouncyCastle.Math.BigInteger(StringToByteArray(realSig.Substring(64)));
```
The `BigInteger` has another `ctor` with the `sign` parameter. Which point that you are converting `realSig` into the wrong integer. (effectively inversing the sign)

**Comment by NicolasDorier** [comment]
The `MakeCanonical` is only meant for the `S` value.

**Comment by DanGould** [comment]
@NicolasDorier `By adding zero manually you invert your bug, making it right.` You caught me right here. I constructed my exponents incorrectly by not specifying they were positive in the constructor and so they were interpreted as negative.

As far as the issue is concerned, `ToDER` still silently and happily makes an invalid DER from some r, s values even if they should be invalid inputs. If passing negative `R` is a bug and `R` `should *never* be negative`, does it make sense to throw an exception? Or auto convert to positive?

**Comment by NicolasDorier** [comment]
I don't want to auto convert, I don't know what kind of non obvious side effect it can have.

**Comment by dangershony** [comment]
@DanGould are there some tests from a widely used library to demonstrate invalid DER fails there and passes here?

**Comment by DanGould** [comment]
@dangershony Yes, I found this test in Bitcoin Core & BitcoinJ: Their DER Encoding functions make r and s values positive and fail negative exponent DER.

Relevant Test in BitcoinJ:
https://github.com/bitcoinj/bitcoinj/blob/73ddffb38f0a4c5eaee78b57d43d3892dc394438/core/src/test/resources/org/bitcoinj/script/script_tests.json#L1237

The same test is included in Bitcoin Core:
https://github.com/bitcoin/bitcoin/blob/feb162d500273040c8a2e5cdd3393edf34dff45b/src/test/data/script_tests.json#L1265

When I run the following NBitcoin code to test DER sig Bitcoin Core & BitcoinJ invalidates, it passes:
```csharp
var invalidStrictDER = "302402107777777777777777777777777777777702108777777777777777777777777777777701";
var der = new ECDSASignature(StringToByteArray(invalidStrictDER));
Console.WriteLine(BitConverter.ToString(der.ToDER()).Replace("-", string.Empty));
Console.WriteLine("IsValid? " + ECDSASignature.IsValidDER(der.ToDER()).ToString());
```
the output is 
```console
3024021077777777777777777777777777777777021087777777777777777777777777777777
IsValid? True
```

This to me confirms NBitcoin allows a user, given a properly encoded `r|s` signature , to create an improperly encoded BIP66 strict-DER

Here is the relevant bit of `IsValidSignatureEncoding` in Bitcoin Core's `interpreter.cpp` also stating `r` & `s` should never be negative:
https://github.com/bitcoin/bitcoin/blob/69a6f1ad1f7ca52b2524ab8322bfa89a9b0ee61b/src/script/interpreter.cpp#L149-L150
https://github.com/bitcoin/bitcoin/blob/69a6f1ad1f7ca52b2524ab8322bfa89a9b0ee61b/src/script/interpreter.cpp#L162-L163

Decode from DER stating the same in BitcoinJ:
https://github.com/bitcoinj/bitcoinj/blob/7629677103dbdd80f14c63b066ed27e1fad47014/core/src/main/java/org/bitcoinj/core/ECKey.java#L559-L589

**Comment by NicolasDorier** [comment]
`Here is the relevant bit of IsValidSignatureEncoding in Bitcoin Core's interpreter.cpp also stating r & s should never be negative:`

This mean Bitcoin Core does not allow negative R signature, not that this is an invalid though Der Signature in the strict mathematical sense.

**Comment by dangershony** [comment]
NBItcoin already enforces that (similar to core)

https://github.com/MetacoSA/NBitcoin/blob/a615d201aff38b55e954fa3a184a0a439f202b12/NBitcoin/ScriptEvaluationContext.cs#L1833

`ECDSASignature` is a citizen of BC it makes less sense to enforce it there, if anything if make the method `IsValidSignatureEncoding` more accessible (currently private)

**Comment by DanGould** [comment]
> This mean Bitcoin Core does not allow negative R signature, not that this is an invalid though Der Signature in the strict mathematical sense.

Agreed, current NBitcoin DER are always valid ASN.1 DER. The issue is that they don't follow the additional, stricter BIP66 standard. This means when importing valid, unsigned `R` and `S` exponents from for example OpenSSL results in invalid BIP66 DER output from NBitcoin which is outright rejected as improperly formatted when passed onto a full node and not formatted the same way other reference implementations do. ASN.1 DER is an insufficient standard for Bitcoin after Core v0.10.0.

If I'm understanding Dan Gershony's comment correctly, even if the aforementioned example DER was output from NBitcoin and handed to `ScriptEvaluationContext`, it would be invalid due to negative exponent.

The stricter BIP66 implementation is a stricter valid ASN.1 DER encoding with restrictions relevant to digital asset signatures. Why would we not follow those rules and continue with this headache?

**Comment by DanGould** [comment]
@dangershony I misread BC as Bitcoin Core instead of Bouncy Castle. Agreed it makes sense to either make `IsValidSignaturreEncoding` accessable or some method to output BIP66DER/strictDER rather than change ECDSASignature. Maybe sign coercion could happen in TransactionSignature construction?

**Comment by NicolasDorier** [comment]
> Maybe sign coercion could happen in `TransactionSignature` 

Yes, that would be ok

**Comment by DanGould** [comment]
the new Secp256k1 implementation of ECDSASignature appears to fix this. what was an invalid strict bip 66 der: 3024021077777777777777777777777777777777021087777777777777777777777777777777

is now the valid, positive sign coerced  "302502107777777777777777777777777777777702110087777777777777777777777777777777"

when passed to new ECDSASignature(derBytes) as a byte[]

Awesome to see secp included in this lib :> Merci

**Comment by NicolasDorier** [comment]
I forgot about the issue. I guess I will never understand the underlying issue, but I am glad this is fixed :)

Indeed, I am using now same code as bitcoin core or secp256k1 for parsing, so it may have fixed some bugs.

**Comment by NicolasDorier** [comment]
@DanGould can you write a test about it?
