### ISSUE TITLE
TX Witness data differs 

### ISSUE THREAD

**Issue by baranetharen** [MetacoSA/NBitcoin#788]
Why does a same transaction signed separately have different witness values?

I signed a bitcoin testnet transaction using nbitcoin library and got an output:

02000000000101853b6bcbc78cf4cd621abb7edca78383ce15a34b6617347258d72d13ecb8fcbc000000001716001487463af228c128aad9371c3df1236d0518c32f44ffffffff01604898000000000017a9141b16cfd66b7f084bf95baf36d14df67f03ef23048702473044022015499aee1e03fc9dd853abf3a9307ebd19dfd9e4f5209a7810be48dfed1c698002205d6c0da0a26918ca38d5aaf9629f7dd71119334e168aafd9f3363f05cb06c967012102739a2f893507714c7e1b37510dede5aad15862b018f6ad9e9402e0b7290a133300000000

Then I signed the same transaction with bitcoin-core and it returned an output :

02000000000101853b6bcbc78cf4cd621abb7edca78383ce15a34b6617347258d72d13ecb8fcbc000000001716001487463af228c128aad9371c3df1236d0518c32f44ffffffff01604898000000000017a9141b16cfd66b7f084bf95baf36d14df67f03ef23048702473044022015499aee1e03fc9dd853abf3a9307ebd19dfd9e4f5209a7810be48dfed1c698002205d6c0da0a26918ca38d5aaf9629f7dd71119334e168aafd9f3363f05cb06c967012102739a2f893507714c7e1b37510dede5aad15862b018f6ad9e9402e0b7290a133300000000

On comparing the outputs, the txwitness stack value differs.

Bitcoin-core witness data :-

"txinwitness": [
                "3044022015499aee1e03fc9dd853abf3a9307ebd19dfd9e4f5209a7810be48dfed1c698002205d6c0da0a26918ca38d5aaf9629f7dd71119334e168aafd9f3363f05cb06c96701",
                "02739a2f893507714c7e1b37510dede5aad15862b018f6ad9e9402e0b7290a1333"
            ]

nBitcoin witness data :-

"txinwitness": [
                "30440220376c73ba8bacbc791fc45ed596c8f973fe79ef0c1bb37a16fb2043dc0998ea62022027c7135359a103f243d865d89eb913e180ea751669b7a2f910b08eb3edcc76f501",
                "02739a2f893507714c7e1b37510dede5aad15862b018f6ad9e9402e0b7290a1333"
            ]

But still, I'm able to send the transaction signed by nBitcoin.

So my questions are:
1) what are the values in witness stack?
2) why the same transaction have different txwitness value?

**Comment by NicolasDorier** [comment]
No idea. We use deterministic ECDSA with grinding to get 72 bytes sig instead of 73, which is what bitcoin core do. Maybe bitcoin core grind in a different way.

**Comment by lontivero** [comment]
You should expect to get a different signature every time you sign something because a random number is used.

**Comment by NicolasDorier** [comment]
@lontivero no, this is deterministic ECDSA, should be the same sig.

**Comment by knocte** [comment]
> But still, I'm able to send the transaction signed by nBitcoin.

Are you sure you can send it? I mean, is it really accepted by the network?

I ask this because I think we found a case similar to this, but in our case `electrs` replied with this error message when trying to broadcast it (which we guess is forwarded from bitcoin-core):

```
 sendrawtransaction RPC error: {"code":-26,"message":"non-mandatory-script-verify-flag (Witness program hash mismatch)"}
```

/cc @canndrew

**Comment by dangershony** [comment]
> No idea. We use deterministic ECDSA with grinding to get 72 bytes sig instead of 73, which is what bitcoin core do. Maybe bitcoin core grind in a different way.  

Ah interesting I came across a similar issue in the BOLT test vectors, does NBitcoin allow to configure the grinding?

**Comment by NicolasDorier** [comment]
Closing this one, related to https://github.com/MetacoSA/NBitcoin/issues/1008
