### ISSUE TITLE
Support for BCash SLP? 

### ISSUE THREAD

**Issue by kennethhutw** [MetacoSA/NBitcoin#800]
Hello, Is there any plan to support BCash SLP?

**Comment by NicolasDorier** [comment]
Shitcoins support are added by the shitcoin community themselves.
If you want support, take a look at the README and other shitcoin integration and make a PR.

**Comment by kennethhutw** [comment]
@NicolasDorier  Thanks for reply.  Could you provide some information about shitcoin community?  I cannot google it.

**Comment by FyreDemonyte** [comment]
I had to lol on this :laughing:

**Comment by NicolasDorier** [comment]
@kennethhutw by shitcoin community in this case I mean the telegram/slack/twitter group knowing what "BCash SLP" is.
