### ISSUE TITLE
URL Authentication Possiblity Missing

### ISSUE THREAD

**Issue by Ilia101** [MetacoSA/NBitcoin#804]
Is it possible to utilize URL authentication to connect to BTC node? For example http://username:password@btcnode.com?

**Comment by NicolasDorier** [comment]
you mean to RPC? You can pass the creds to RPCClient.

**Comment by Ilia101** [comment]
> you mean to RPC? You can pass the creds to RPCClient.

Thanks. Will try it out. Cheers!

**Comment by Ilia101** [comment]
OK. RPCClient works. But I was searching for the same functionality in the Node.Connect(). Can I pass credentials via Node class?

**Comment by NicolasDorier** [comment]
@Ilia101 the P2P protocol of bitcoin does not have any user/pass authentication.

**Comment by Ilia101** [comment]
It is clear that RPC and Node have different implementation. Based on the code it is clear that you are creating listeners and waiting for responses from the server. I think is possible to modify Node class to add possibility to supply token. so, for example, this line of code 

var node = Node.Connect(Network.Main, "localhost");

could be looking like this:

var node = Node.Connect(Network.Main, "localhost", "user:<some token>");

Don't you think it is possible?

**Comment by NicolasDorier** [comment]
Node is using the P2P protocol of Bitcoin, RPC is a different interface.

The P2P protocol do not have any auth.
You should try to read https://programmingblockchain.gitbook.io/programmingblockchain/ it may clarify things.

**Comment by Ilia101** [comment]
OK. Will read the book. Thanks!
