### ISSUE TITLE
 NBitcoin.RPC.SatoshiFormatter-->ValueFromAmount 

### ISSUE THREAD

**Issue by Soho-Rab** [MetacoSA/NBitcoin#806]
I'm a developer from china。when i used 【tx.ToString(RawFormat.Satoshi)】，this Format is not right。
eg：value:0.00001000------->value:1E-05.0。

**Comment by Soho-Rab** [comment]
![微信图片_20200203002904](https://user-images.githubusercontent.com/8097638/73611441-ded8cc00-461c-11ea-99da-c1d686046072.png)
![微信图片_20200203003233](https://user-images.githubusercontent.com/8097638/73611446-e9936100-461c-11ea-86fc-ca5140e326da.png)
![微信图片_20200203003238](https://user-images.githubusercontent.com/8097638/73611449-ef894200-461c-11ea-9cd0-46f9dd59269b.png)

**Comment by NicolasDorier** [comment]
Thanks for the report, the Satoshi Formatter is deprecated, so I don't think this is very useful to fix.
But if you do a pull request, I will merge it.

**Comment by Soho-Rab** [comment]
done!
