### ISSUE TITLE
Proposal: if some capabilities work, interpret failures of others as missing

### ISSUE THREAD

**Issue by Kixunil** [MetacoSA/NBitcoin#808]
Background
---------------

After pointing NBitcoin-based NBXplorer at [`btc-rpc-proxy`](https://github.com/Kixunil/btc-rpc-proxy) I [found out](https://github.com/dgarage/NBXplorer/issues/239) that it's failing despite the calls being non-essential to NBXplorer. The reason is NBitcoin is treating all authentication failures as fatal, not as missing capabilities.

Proposed solution
-----------------------

If some checks succeed and some fail, treat the failed checks as missing capabilities, rather than fatal failures. If all capabilities fail, treat it as failure (we don't want to silently pretend there's a working node that can do nothing).

I'm willing to try to implement it and make a PR despite my ~zero C# skills.

**Comment by NicolasDorier** [comment]
Yes, will fix that.

**Comment by NicolasDorier** [comment]
I think the best is to fix in NBX, not doing the check if it throw.

**Comment by NicolasDorier** [comment]
nevermind, should be fixed here.
