### ISSUE TITLE
Key.Parse disregarding non-nullable parameter of Network.Parse

### ISSUE THREAD

**Issue by soraphis** [MetacoSA/NBitcoin#810]
Key.Parse:

https://github.com/MetacoSA/NBitcoin/blob/1ee1c9b6a4acbed510b1290a3848783e52ed8b5a/NBitcoin/Key.cs#L15-L23

define a default parameter for network, to be null, they call Network.Parse

https://github.com/MetacoSA/NBitcoin/blob/1ee1c9b6a4acbed510b1290a3848783e52ed8b5a/NBitcoin/Network.cs#L2491-L2507

which expect Network to be non-nullable.
wrapping Key.Parse in `#nullable enable` will show the expected compiler warnings

**Comment by NicolasDorier** [comment]
ugh, good catch, this is a constructor I should have removed.
