### ISSUE TITLE
Key comparison

### ISSUE THREAD

**Issue by lontivero** [MetacoSA/NBitcoin#818]
I was reviewing what changed in the latest days and I found there is a performance optimization in the Key/PubKey comparison. I have a few questions here:

### Key equality depending on pubey enconding
https://github.com/MetacoSA/NBitcoin/blob/599d52a1559cff2dd4a1d94f3ac21571c0796bed/NBitcoin/Key.cs#L316-L323

Here two keys are equal if their public keys are equal byte by byte but the public keys comes in two formats: compressed and uncompressed. It is possible then to have one key `k1` exactly (byte by byte) to another key `k2` and the comparison could be true or false depending on what format their public keys will be represented. Is this okay and why?

### PubKey comparison is not time constant

https://github.com/MetacoSA/NBitcoin/blob/599d52a1559cff2dd4a1d94f3ac21571c0796bed/NBitcoin/PubKey.cs#L414-L421

The previous implementation was in some way time constant while this new one is not. This means that the `Key` comparisons are not time constant neither. I think this is not a problem for NBitcoin itself because i don't see private keys comparisons anywhere and the signing/verification is not affected however this could be dangerous for those that could use NBitcoin without knowing how the comparison is implemented. I think key material operations should be time constant.

**Comment by NicolasDorier** [comment]
> It is possible then to have one key k1 exactly (byte by byte) to another key k2 and the comparison could be true or false

Yes. It is expected.
Frankly I have mixed feeling about even overriding the equality on key and pubkey... I am thinking of maybe remove it.

**Comment by NicolasDorier** [comment]
Actually I can't remove it, it may break people :(
