### ISSUE TITLE
Need fix verge and dogecash

### ISSUE THREAD

**Issue by NicolasDorier** [MetacoSA/NBitcoin#831]
I removed support from verge and dogecash based on a test failing because of those
@justinvforvendetta  @Liquid369 

Please fix 

https://github.com/MetacoSA/NBitcoin/commit/cf2454d5f47a63a0317955ba6f40c878208f39e7

**Comment by artem03** [comment]
When will Verge start working again?

**Comment by NicolasDorier** [comment]
when somebody fix it

**Comment by Liquid369** [comment]
New PR pushed, did not get the tag here to my email sorry.

**Comment by Liquid369** [comment]
With #920 merged DogeCash should now be working.
