### ISSUE TITLE
DefaultCoinSelector Issue

### ISSUE THREAD

**Issue by eugeniuLivandovschi** [MetacoSA/NBitcoin#835]
Hi, not sure if this is a issue and would really appreciate if you guys can help me with this.
Suppose I have an address that receives funds from 3 different transactions. (suppose 1 BTC each)
Now, when sending funds (suppose 0.5BTC) from this address I was expected than only one coin will be used for this transaction. But, in my case all 3 coins(outputs from previous transactions) where used. As I understand, the DefaultCoinSelector implementation should minimize the change, thus inly 1 coin should be used. I can provide the real transactions in testnet that I created and discovered this issue.
Thanks in advanced

**Comment by lontivero** [comment]
Different users have different requirements. From my point of view the `DefaultCoinSelector` should spend all the 3 coins to protect my privacy and for that reason the default behavior is ok to me. In your case, if privacy is not on the top of your requirements then you can use:  
Use `DefaultCoinSelector.GroupByScriptPubKey = false`, this will spend only one of your 0.5 received  coins as you expected.

**Comment by eugeniuLivandovschi** [comment]
Thank you for your reply
