### ISSUE TITLE
Can't update NBitcoin since 5.0.15

### ISSUE THREAD

**Issue by ArtjomP** [MetacoSA/NBitcoin#840]
Hello there! 
I can't update NBitcoin bc my project stop building in release config. For example, I got this one after updating to 5.0.26 (strange error with some reference to 4.1.2.36):
**iOS:**
`Can't resolve the reference 'NBitcoin.BouncyCastle.Math.BigInteger NBitcoin.Crypto.ECDSASignature::get_R()', referenced from the method 'System.Void QBitNinja.Client.Models.WhatIsTransactionSignature::.ctor(NBitcoin.TransactionSignature)' in 'NBitcoin, Version=4.1.2.36`

**Android:**
`Mono.Linker.MarkException: Error processing method: 'System.Void QBitNinja.Client.Models.WhatIsTransactionSignature::.ctor(NBitcoin.TransactionSignature)' in assembly: 'QBitNinja.Client.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve NBitcoin.BouncyCastle.Math.BigInteger NBitcoin.Crypto.ECDSASignature::get_R()
`

The last version that works for me is 5.0.15

Let me know if you need some more info.

Thank you in advance!

**Comment by nopara73** [comment]
I think @NicolasDorier has to update NBitcoin in `QBitNinja` and things will be resolved. (Although you can resolve it yourself too, but I'd suggest you to wait if it's not absolutely necessary as that's the clean solution.)

**Comment by ArtjomP** [comment]
The same is with 5.0.27

**Comment by NicolasDorier** [comment]
@ArtjomP will update QBitNinja.

**Comment by NicolasDorier** [comment]
Can you try with version 1.0.3.52 of QBitninja.Client?

**Comment by ArtjomP** [comment]
Sure. I'll do it today. 
Thx!

**Comment by ArtjomP** [comment]
It works! 
NBitcoin 5.0.15 -> 5.0.27
QBitNinja.Client 1.0.3.50 -> 1.0.3.52
NBXplorer.Client 3.0.3 -> 3.0.8
Thank you!
