### ISSUE TITLE
Is QBit Ninja down ?

### ISSUE THREAD

**Issue by Ashish81** [MetacoSA/NBitcoin#847]
hi cant access https://api.qbit.ninja/transactions/38d4cfeb57d6685753b7a3b3534c3cb576c34ca7344cd4582f9613ebf0c2b02a.

it seems its down,

**Comment by NicolasDorier** [comment]
checking

**Comment by NicolasDorier** [comment]
should be good now. Azure pooped in its pants.

**Comment by NicolasDorier** [comment]
It failed again.

**Comment by NicolasDorier** [comment]
I don't know why, Azure is acting strange... works again

**Comment by Ashish81** [comment]
It failed again, just run only one time,

**Comment by NicolasDorier** [comment]
@Ashish81 I frankly have no idea. I checked the profiler, the CPU usage come from a process specific to azure, not from our code. So I guess it is Azure that suddenly lose its mind. I will take a look tomorrow if that persist.

**Comment by Ashish81** [comment]
Is it hosted in as APP Service ?? or in vm? just curious

**Comment by NicolasDorier** [comment]
app service

**Comment by Ashish81** [comment]
Do you post repo for qbit server code, i mean suppose i want to host at my own what should i do. Please suggest me

**Comment by Ashish81** [comment]
Api seems working now, Qbitninja I read the setup process.

**Comment by NicolasDorier** [comment]
I think it is always better to have your own instance if you can take the time to set it up.
If it fails, you can just reuse the public one as fallback.
