### ISSUE TITLE
Could not Deserialize RawTransactionInfo correctly.

### ISSUE THREAD

**Issue by chaoyebugao** [MetacoSA/NBitcoin#850]
As we can see `RawTransactionInfo` all setters of its properties is `internal`. This is a hard problem to deserialize as a RawTransactionInfo instance.

**Comment by NicolasDorier** [comment]
I can make it public, but I think a better way if you just need to call the method and serialize immediately is to instead use `RPCClient.SendCommand` and get the json out of the response instead of the deserialized form.
