### ISSUE TITLE
Batched test RPC calls cause incorrect reports

### ISSUE THREAD

**Issue by Kixunil** [MetacoSA/NBitcoin#864]
Batching various calls during RPC test causes that if one of them fails, all of them fail. This interferes with ability to discover the capabilities correctly.

**Comment by NicolasDorier** [comment]
This is not the case, see the test I just added.

**Comment by NicolasDorier** [comment]
I think your problem is that you send an HTTP error code if any of the request does not work.
Batched request never send HTTP error code

**Comment by Kixunil** [comment]
Hmm, this is interesting. It actually looks like a bug in `bitcoind` - someone missed [a comment about not using error code publicly](https://github.com/bitcoin/bitcoin/blob/99813a9745fe10a58bedd7a4cb721faf14f907a4/src/rpc/protocol.h#L29) and it looks like [the mapping code](https://github.com/bitcoin/bitcoin/blob/25ad2c623af30056ffb36dcd203a52edda2b170f/src/httprpc.cpp#L79) doesn't iterate over results, but it should. The new version of `bitcoind` with native command filtering will [apparently behave same](https://github.com/bitcoin/bitcoin/blob/25ad2c623af30056ffb36dcd203a52edda2b170f/src/httprpc.cpp#L213) as my proxy, so the code will still break eventually.

I'd agree that it'd be nicer to be able to batch the requests. I guess the discussion should be handled with core devs.

**Comment by NicolasDorier** [comment]
@Kixunil do I understand correctly that their code mean that if one of the batched request fails for permission, then ALL the response of the requests are not sent out?

**Comment by Kixunil** [comment]
Yes, exactly that. You can see in [the linked code](https://github.com/bitcoin/bitcoin/blob/25ad2c623af30056ffb36dcd203a52edda2b170f/src/httprpc.cpp#L213) that it pre-checks all the methods in a [for loop](https://github.com/bitcoin/bitcoin/blob/25ad2c623af30056ffb36dcd203a52edda2b170f/src/httprpc.cpp#L215) and if it hits any forbidden method, it [bails out right away](https://github.com/bitcoin/bitcoin/blob/25ad2c623af30056ffb36dcd203a52edda2b170f/src/httprpc.cpp#L224) with 403.

**Comment by Kixunil** [comment]
I've been thinking about it and since 0.20.0 is out, it basically means that using batching in NBitcoin for scanning is essentially a bug. There are at least two projects tight now that protect their nodes using whitelisting. As a result NBXplorer, which uses NBitcoin doesn't have the correct information about capabilities which in turn causes BTCPayServer to disable PayJoin.

So we have to either sacrifice privacy or security.

Un-batching would resolve the issue and the performance penalty should be reasonably low. Capabilities are scanned only at the beginning, so it's constant increase. If the time becomes too long the requests could be launched in parallel. However I don't believe it will be needed.

Is there anything I, non-C# dev, can do to help getting un-batched scan into NBitcoin/NBXplorer as soon as possible?

**Comment by NicolasDorier** [comment]
@Kixunil I think that's OK to fallback to non-batched. I will check what I can do.

**Comment by NicolasDorier** [comment]
fixed in .51, we fallback to serial if batching fails.

**Comment by NicolasDorier** [comment]
pushed NBXplorer with the new nbitcoin on 2.1.41

**Comment by NicolasDorier** [comment]
please open issue on NBXplorer repo if you still have the problem

**Comment by Kixunil** [comment]
Thanks a lot! Just sent some sats. :)
