### ISSUE TITLE
Nbitcoin Derive Error "The key must be compressed"

### ISSUE THREAD

**Issue by akarimovbytewerk** [MetacoSA/NBitcoin#867]
Good day. After update of NBitcoin library update From verison "5.0.14" to version "5.0.40" we are getting error "The key must be compressed". Can you help us with this error?
We are using .NET Core 3.1 and .NET Standard 2.1.
Here is deriviation procedure code:

```var privKey = Key.Parse(masterPrivateKey, networkBitcoin);
                    var extKey = new ExtKey(privKeyWif, masterChainBytes);

                    var derivedKey = extKey.Derive(100).PrivateKey;
                    var secret = derivedKey.GetBitcoinSecret(Network.Main);

                    address = secret.GetAddress(ScriptPubKeyType.Legacy).ToString();`

**Comment by NicolasDorier** [comment]
mmm checking this. There was indeed something recently.

**Comment by NicolasDorier** [comment]
why `privKeyWif` is not compressed in your case? uncompressed keys should never be used normally.

The best would be that you migrate out of it.

**Comment by NicolasDorier** [comment]
Just to develop further: I check what I was doing before with uncompressed keys.
It turns out that it was broken and not really following the BIP. I can't silently fix it as people may lose money, so I decided to stop supporting it as there is no reason to in the first place.

**Comment by akarimovbytewerk** [comment]
Can you write sample with NBitcoin how to convert existing private key to compress variant if i have Wif key and masterChainBytes for this key?

**Comment by akarimovbytewerk** [comment]
Private key is stored inside server's HSM so loosing it is very unlikely. Thats the reason why it stored as it is now...

**Comment by NicolasDorier** [comment]
@akarimovbytewerk  just

```
key = key.Compress();
```

That said, this will derive different addresses so you need to sweep the funds.

**Comment by NicolasDorier** [comment]
The private key, uncompressed or not is always 32 bytes, there is nothing to change there.
The difference is how the public keys are derived. `key = key.Compress()` make sure that things derived from `key` will be compressed.

**Comment by akarimovbytewerk** [comment]
I've checked code and nether Nbitcoin.Key not NBitcoin.ExtKey have Compress() method.
It's available only for PublicKey.
I will be very grateful if you write sample code how to get derive key from PrivateWif and masterChainBytes.

**Comment by NicolasDorier** [comment]
@akarimovbytewerk how are you getting `privKeyWif`?

**Comment by NicolasDorier** [comment]
I guess in your code you have somewhere `new Key(hsmBytes, false)`. You change the `false` to `true`.

**Comment by akarimovbytewerk** [comment]
Key.Parse(WifKeyString, Network.Main)

**Comment by akarimovbytewerk** [comment]
WifKeyStringis something liek  "1234oUCstgf4nA6XhBJhBRAwSRbqvFFZCnn6KxCo9DKEgxJJJjj"

**Comment by NicolasDorier** [comment]
Ok try this:
just after
```
privKeyWif = new Key(privKeyWif.ToBytes(), fCompressedIn: true);
```

**Comment by akarimovbytewerk** [comment]
Thanks a lot that works perfect, but old derived addresses is useless and we need to recreate them...

**Comment by NicolasDorier** [comment]
yes but frankly that's a good thing.
Nobody use uncompressed key anymore, you were paying more money than needed in fee.
It was also probably trivial to identify your transactions.

**Comment by qergo** [comment]
Nicolas help to figure out such a code
var key1 = new Key (Encoders.Hex.DecodeData (hashedData)). GetWif (Network.Main) .ToString (); gives a compressed key, but how to get an uncompressed key?

**Comment by qergo** [comment]
I figured it out myself
