### ISSUE TITLE
Segwit extended pubkeys

### ISSUE THREAD

**Issue by FIVIL** [MetacoSA/NBitcoin#872]
Hi, I am trying to import my base85 formatted extended pubkey using `BitcoinExtPubKey` object to create a watch-only wallet. And this works perfectly with my `legacy` wallet extpubkey. However, for the `Segwit` wallet I keep getting `Invalid BitcoinExtPubKey` exception. Now considering, Nbitcoin supports `Segwit` addresses (at least it is possible to generate `Segwit` address with `PubKey.GetAddress(ScriptPubKeyType,Network)`  I was wondering if I am doing it wrong or importing `Segwit` extpubkeys is not supported yet.
TNX

**Comment by NicolasDorier** [comment]
`BitcoinExtPubKey` is always formatted as `xpub`. We do not support any other format that have not been specified. (those are in general home grown by software wallet which differ widely from one another)

So if they use other format than `xpub`, you need to do the conversion by yourself to xpub, then use `PubKey.GetAddress(ScriptPubKeyType,Network)` as you said.

**Comment by FIVIL** [comment]
Thank you.
