### ISSUE TITLE
Will NBitcoin implement MimbleWimble?

### ISSUE THREAD

**Issue by soraphis** [MetacoSA/NBitcoin#877]
I've just read this article:
https://cointelegraph.com/news/developer-predicts-litecoin-mimblewimble-testnet-launch-by-september

and was wondering about an implementation in NBitcoin and since I couldn't find anything about mimblewimble here i'd thought to start the discussion.

https://tlu.tarilabs.com/protocols/mimblewimble-1/MainReport.html#high-level-overview

**Comment by NicolasDorier** [comment]
no it won't. Design is completely different that bitcoin, and I am not interested to shitcoins.

**Comment by knocte** [comment]
Haha Nicolas I share your opinion about shitcoins but you cannot consider LTC one, thanks to Litecoin Segwit had some testing before it got activated in BTC. It's a good testbed for tech that might get eventually adopted by BTC.

**Comment by dangershony** [comment]
> thanks to Litecoin Segwit had some testing before it got activated in BTC. 

Not that I have anything against shitcoins but you don't need a shitcoin to test BTC protocol improvements (we have testnets for that)

**Comment by NicolasDorier** [comment]
sorry I am out of the loop, mimblewimble implementation for me is Grin and does not share Bitcoin's design. (no chain)

**Comment by soraphis** [comment]
rumors say Litecoin will get confidential transactions, and may use (something like) mimblewimble as protocol with 'extension blocks'.

the article I posted does states
> Mimblewimble will see a Litecoin testnet release before the end of summer.

also some other evidences in this direction:
https://twitter.com/SatoshiLite/status/1091957886031355905

I couldn't find anything on the litecoin repository for now, though.

**Comment by NicolasDorier** [comment]
Ok let's see when they actually shipped :p

**Comment by nopara73** [comment]
We're shipping something that relies on rangeproofs, preferably bulletproofs so you can implement them if you want :P

**Comment by NicolasDorier** [comment]
@nopara73 I suggested @lontivero to implement it. Actually I need it for signing elements transaction but I don't want to do this job. :p

**Comment by nopara73** [comment]
@lontivero, is that what you will do? Monkey code libsecp256?
