### ISSUE TITLE
The redeem provided does not match the scriptPubKey of the coin

### ISSUE THREAD

**Issue by veektorh** [MetacoSA/NBitcoin#878]
Trying to spend litecoin from a p2sh address, i get this error when trying to convert utxos to scriptcoin.

`
           var add1 = "MP3RwwmVDoHw3h25uKHn8PLA8DhjaZtooQ";
            var fromadd = BitcoinAddress.Create(add1, network);

            var add2 = "MVVftwwVt2KputjnVb858n4kzz8Wthrk3B";
            var destadd = BitcoinAddress.Create(add2, network);

            var utxos = GetUnSpentCoinsN($"{xpubstring}-[p2sh]").Result;

           // i have tried using the ScriptPubKey of from address and destination address still the same error
            var realredeem = PayToScriptHashTemplate.Instance.GenerateScriptPubKey(fromadd.ScriptPubKey);

          //i get the error at this point - The redeem provided does not match the scriptPubKey of the coin
            var utxoScriptCoin = utxos.Select(a => a.ToScriptCoin(realredeem)).ToList();
`

**Comment by NicolasDorier** [comment]
This can't be the redeem script.
```csharp
var realredeem = PayToScriptHashTemplate.Instance.GenerateScriptPubKey(fromadd.ScriptPubKey);
```
If you use NBXplorer, just use `GetUnspentCoin`.

```csharp
utxos = explorer.GetUTXOs(userDerivationScheme);
var coins = utxos.GetUnspentCoins();
```

**Comment by veektorh** [comment]
I'm using nbxplorer to get the utxos, it's a p2sh address so I need to convert to utxos to script coin, so I can use transaction builder to spend from the address 

utxos = explorer.GetUTXOs(userDerivationScheme);
var coins = utxos.GetUnspentCoins();

how do I get the **scriptcoin** from coins?

**Comment by NicolasDorier** [comment]
the coins in `GetUnspentCoins` already have the scripts inside.

**Comment by NicolasDorier** [comment]
Sorry it does not!

```csharp
var coins = utxos.GetUnspentUTXOs().Select(c => c.AsCoin(userDerivationScheme)).ToArray();
```

**Comment by veektorh** [comment]
Correct it worked! Thanks

here is my transaction builder code

```csharp
          
            var utxoScriptCoin = utxos.GetUnspentUTXOs().Select(c => c.AsCoin(userDerivationScheme)).ToArray();

            var builder = network.CreateTransactionBuilder();

            builder.AddCoins(utxoScriptCoin);

            builder.AddKeys(privateKey.PrivateKey);

            builder.Send(destadd, new Money(0.002m,MoneyUnit.BTC));

            builder.SubtractFees();

            builder.SetChange(fromadd);

            builder.SendEstimatedFees(new FeeRate(1m));
            
            var res = builder.BuildTransaction(true);

            var r = client.BroadcastAsync(res).Result;
```
although i couldnt broadcast the transaction, im getting the following error.

```csharp
RPCCode = RPC_TRANSACTION_REJECTED
RPCCodeMessage = "Transaction was rejected by network rules"
RPCMessage = bad-txns-nonstandard-inputs (code 64)
```

```csharp
//this return false also
var isVerified = builder.Verify(res);
```


when i try to broadcast the raw tranHex on block explorer api it says

```csharp
Rejected script for input 0 referencing f78fc0144f780737bcb754cde455a590336c15a2ab1b399820f608bd2d01f3ba 
```

**Comment by NicolasDorier** [comment]
The transaction builder have overloads for Verify or Check which give you more detailed information about what went wrong.

**Comment by veektorh** [comment]
this is what i get from transaction policy errors.

Script error on input 0 (Invalid stack Operation)

**Comment by NicolasDorier** [comment]
@veektorh if you can do an example I can copy/paste to test I can test.
This test https://github.com/dgarage/NBXplorer/blob/master/NBXplorer.Tests/UnitTest1.cs#L282 show a basic flow.

**Comment by veektorh** [comment]
i can do normal p2pkh payment. im just stuck on spending from this p2sh address. here's my full code

``` csharp
        public async Task MakePaymentp2sh()
        {
            var network = NBitcoin.Altcoins.Litecoin.Instance.Mainnet;
            var xnetwork = new NBXplorerNetworkProvider(NetworkType.Mainnet).GetLTC();

            var mnemo = new Mnemonic("xxx", Wordlist.English);
            ExtKey hdroot = mnemo.DeriveExtKey();
            var xpub = hdroot.Derive(new KeyPath("m/49'/2'/0'")).Neuter();
            var xpubstring = xpub.ToString(network);
            var privateKey = hdroot.PrivateKey.GetWif(network);
            var pubkey = xpub.Derive(new KeyPath("0/0")).PubKey;
            var fromadd = pubkey.GetAddress(ScriptPubKeyType.SegwitP2SH, network);

            var add2 = "MVVftwwVt2KputjnVb858n4kzz8Wthrk3B";
            var destadd = BitcoinAddress.Create(add2, network);

            var frmScript = destadd.ScriptPubKey;

            var userDerivationScheme = xnetwork.DerivationStrategyFactory.CreateDirectDerivationStrategy(xpub, new DerivationStrategyOptions()
            {
                ScriptPubKeyType = ScriptPubKeyType.SegwitP2SH
            });
            var client = new ExplorerClient(xnetwork);
            client.WaitServerStarted();
            var utxo = await client.GetUTXOsAsync(userDerivationScheme);
            var utxoScriptCoin = utxo.GetUnspentUTXOs().Select(c => c.AsCoin(userDerivationScheme)).ToList(); 

            var builder = network.CreateTransactionBuilder();
            builder.AddCoins(utxoScriptCoin);
            builder.AddKeys(privateKey.PrivateKey);
            builder.Send(destadd, new Money(0.002m, MoneyUnit.BTC));
            builder.SetChange(fromadd);
            builder.SendEstimatedFees(new FeeRate(1m));

            var res = builder.BuildTransaction(true);
            var err = new List<NBitcoin.Policy.TransactionPolicyError>().ToArray();
            var isVerified = builder.Verify(res, new FeeRate(1m), out err);

            var r = client.BroadcastAsync(res).Result;
        }
```

**Comment by NicolasDorier** [comment]
@veektorh my code above is testing all, p2pkh, segwit and wrapped.
Your problem is that `privateKey` is not the right key to sign. It is `m/49'/2'/0'` but you need `m/49'/2'/0'/0/0`.

**Comment by NicolasDorier** [comment]
That said, you are making it more complicated than it should be just use [Create PSBT endpoint](https://github.com/dgarage/NBXplorer/blob/master/docs/API.md#create-partially-signed-bitcoin-transaction).

Then 

```
response.PSBT.SignAll(ScriptPubKeyType.SegwitP2SH, extKey);
var txToBroadcast = respons.PSBT.ExtractTransaction();
```
