### ISSUE TITLE
Some valid Bech32/SegWit addresses cannot be created using NBitcoin.BitcoinAddress.Create(...)

### ISSUE THREAD

**Issue by Sofoca** [MetacoSA/NBitcoin#882]
I intend to use `BitcoinAddress.Create(...)` for validation of Bitcoin addresses that are later fed to NBitcoin for further processing. During testing, I noticed that some valid Bech32 addresses cannot be created. 

For example, calling `NBitcoin.BitcoinAddress.Create("bc1zw508d6qejxtdg4y5r3zarvaryvg6kdaj", NBitcoin.Network.Main)` yields a `System.FormatException : Invalid string`. However, this is actually the one of the test vector addresses in [BIP-0173](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki#test-vectors). 

Further addresses that I personally tried out and led to exceptions were the following: `bc1pw508d6qejxtdg4y5r3zarvary0c5xw7kw508d6qejxtdg4y5r3zarvary0c5xw7k7grplx`, `BC1SW50QA3JX3S`, and `bc1sw50qa3jx3s`. I am quite sure that they are all valid Bech32 addresses. 

Edit: I also noticed during investigating the issue that [BitcoinAddressTest.cs](https://github.com/MetacoSA/NBitcoin/blob/master/NBitcoin.Tests/BitcoinAddressTest.cs) is begging for some useful test cases. 🙂

**Comment by NicolasDorier** [comment]
checking that. Seems strange to me as I never had problem until now.

**Comment by NicolasDorier** [comment]
`bc1zw508d6qejxtdg4y5r3zarvaryvg6kdaj` is decoding into 16 bytes. It can't be an address.

**Comment by NicolasDorier** [comment]
I see what is the problem: Those are neither P2WPKH or P2WSH, so NBItcion does not consider them addresses.

**Comment by Sofoca** [comment]
You're right. Specifically, the above mentioned addresses that fail in NBitcoin do not include `0` as witness script version (those should have a length of 20 or 32 bytes) and therefore shouldn't be considered valid Bitcoin Mainnet addresses (for now). Certainly they wouldn't be spendable.

**Comment by NicolasDorier** [comment]
@Sofoca this is taproot address ? If those are I should probably include it soon.

**Comment by Sofoca** [comment]
No, those are actually also [32 bytes long](https://github.com/sipa/bips/blob/bip-schnorr/bip-taproot.mediawiki#script-validation-rules). Depending on how you do validation they could obviously still fail (e.g. if you validate the version field). Unfortunately there [aren't any example addresses](https://github.com/sipa/bips/blob/bip-schnorr/bip-taproot.mediawiki#test-vectors) in the BIP yet. 

On another note, while reading I just realized that that the addresses I supplied above are technically valid Bitcoin addresses. Most likely they are [interpreted by nodes as anyone-can-spend scripts](https://github.com/sipa/bips/blob/bip-schnorr/bip-taproot.mediawiki#script-validation-rules) for now. So it's probably not 100% correct for NBitcoin to reject them, however it might make sense for most users to not be able to spend to those addresses.

**Comment by NicolasDorier** [comment]
@Sofoca I am really wondering. I think it would be OK for NBItcoin to consider them as address. 

The downside of not considering them as address is that software will need to update when there is a segwit update.

The upside is that people won't shoot themselves in the foot.

I am really wondering.

**Comment by NicolasDorier** [comment]
Ping @lontivero @dangershony @nopara73 what do you think? Should NBitcoin be able to parse bech32 addresses that are not p2wpkh or p2wsh?
