### ISSUE TITLE
how to generate zpub instead of xpub

### ISSUE THREAD

**Issue by veektorh** [MetacoSA/NBitcoin#892]
Nbitcoin generates xpub irrespective of the script pub key type as master public key. 

But most wallet accepts zpub for segwit addresses as master public key , I'm trying to generate a master pub key (zpub) to track as a watch only wallet in blue wallet.

**Comment by nopara73** [comment]
I'd urge you to avoid that like fire as this whole `zpub`, `ypub`, etc.. thingy is controversial and there are huge inconsistencies between implementations. However, if you still want to do that, then here you go:

https://github.com/zkSNACKs/WalletWasabi/blob/abebff2b0703b0758ac8b97ba4b4f1cbd3a605eb/WalletWasabi/Extensions/NBitcoinExtensions.cs#L222-L230

**Comment by veektorh** [comment]
Thanks , works correctly. 

its for personal use, i dont really mind
