### ISSUE TITLE
[NBitcoin.Secp256k1] Operations involving Infinity  

### ISSUE THREAD

**Issue by lontivero** [MetacoSA/NBitcoin#896]
I think something is wrong with `NBitcoin.Secp256k1` code. The following test fails:

```c#
[Fact]
public void Comparison2()
{
	var inf = Scalar.One * GE.Infinity;
	Assert.True(inf.IsInfinity);
}
```

Other similar test involving the point at infinity also fail. Probably this is because a lack of understanding from my side about the library:

```c#
[Fact]
public void Comparison2()
{
	var inf = GE.Infinity.ToGroupElementJacobian() + GE.Infinity;
	Assert.True(inf.IsInfinity);
}
```

Related #871

**Comment by nopara73** [comment]
FTR `GE.Infinity.ToGroupElementJacobian().AddVariable(GE.Infinity, out _)` ugliness works as expected.

**Comment by NicolasDorier** [comment]
@lontivero are you sure that this should be tthe case? I really monkey coded this, so if there is this "bug" it is probably also in secp256k1

**Comment by lontivero** [comment]
> @lontivero are you sure that this should be tthe case?

Yes, I am sure. 

This can give you a clue: https://github.com/Metacosa/nbitcoin/blob/master/NBitcoin/BouncyCastle/math/ec/multiplier/AbstractECMultiplier.cs#L10

**Comment by NicolasDorier** [comment]
`secp256k1_ecmult_const` in secp256k1 does not seems to enforce that

**Comment by lontivero** [comment]
Yes, it does. Try this by yourself:

```c++
    secp256k1_ge_set_infinity(&point);
    secp256k1_ecmult_const(&res1, &point, &one, 256);
    CHECK(secp256k1_ge_is_infinity(&res1));
```

**Comment by lontivero** [comment]
It seems you are right, the `secp256k1_ecmult_const` in secp256k1 does not enforce it. The question is why? 

@jonasnick if `P` is the point at infinity and `a` is an scalar in the range `0 < a < N`, is `aP` also the point at infinity? and if so, why does `secp256k1_ecmult_const` fail when `P` = &#8734;?

**Comment by NicolasDorier** [comment]
I don't know. You may need to ask to secp256k1 repo.

`const` function mean they are constant time. The `Variable` (or `var` in their code) mean it is variable.
Maybe there is an assumption to those calling `const`.

**Comment by lontivero** [comment]
FYI https://github.com/bitcoin-core/secp256k1/issues/788

**Comment by NicolasDorier** [comment]
@lontivero so alternatives

* We should check for infinity and throw if it is passed
* Use `_var` functions (though unsure of consequences)
* In operator, use `_var` if infinity, else use `_const`

**Comment by lontivero** [comment]
No no, I think you ported perfectly well and you shouldn't change anything IMO. 
I shared that with you because it is something that it is important to know.

**Comment by lontivero** [comment]
Oh wait... the `*` operator is not something ported so it could be "fixed" in the same way we are doing in WabiSabi (or in BounceCastle code): `if (infinity) return Infinity;`

**Comment by NicolasDorier** [comment]
@lontivero imho it can be fixed at the operator level.
