### ISSUE TITLE
Transaction rejected?

### ISSUE THREAD

**Issue by dthorpe** [MetacoSA/NBitcoin#9]
I'm having trouble submitting transactions created with NBitcoin. I think I'm missing a step, but I don't know what. 

Here's the gist of it:

``` c#
var tx = new NBitcoin.Transaction();
var txIn = new TxIn(new OutPoint(new uint256(source.TransactionHash), source.OutputIndex));
tx.AddInput(txIn);

var destAddress = "mnDQg9yvKQv3u88favjCfGtDhfD5tpq9wa";
var payment = new Money(2000000);
var change = new Money((ulong)source.Amount) - payment - new Money(1000);
tx.AddOutput(payment, new BitcoinAddress(destAddress));
tx.AddOutput(change, new BitcoinAddress(sourceAddress));
tx.SignAll(key);

var txRawHex = Encoders.Hex.EncodeData(tx.ToBytes());
```

Submitting that txRawHex to the Testnet network results in a rejection error "invalid transaction". I've tried rpcClient.SendRawTransaction(tx) to my local bitcoind as well as multiple API services such as tbtc.Blockr.io and testnet3.toshi.io.

Is there an additional step that needs to be done to the transaction after tx.SignAll() before broadcasting it to the network?

Forensic details:
source transaction: http://tbtc.blockr.io/tx/info/cf9c8e5f1c16797804412cadf0be1a15ab873f19fdb20b7a02f170c32e9c0704
source address: http://tbtc.blockr.io/address/info/mobq38AbD1mwPxqKKXpgbNEfV7ezdsx6QR
Key is the private key from which the source address was generated.
new transaction raw hex value: 

```
010000000104079c2ec370f1027a0bb2fd193f87ab151abef0ad2c41047879161c5f8e9ccf010000006a473044022023baf359cf181a82d42c6355ff6b31513d7f16f14ab4c4e578226b3c46f3bc61022017d864ba551ed01aa39dccd1458495ed8c5ca279e1a2085bf65e031f33a2300901210346c834e355953c78c41eb6fc9a7d1a36c3ddb59ab3035c74d6376631b53595cbffffffff0280841e00000000001976a91449776a3be69fa71e2d12d14d0d7d696c28fd395e88ac18ef6f06000000001976a91458ad072475467f2bd9480d5591222214206c204588ac00000000
```

Thanks,
-Danny

**Comment by hitjariwala** [comment]
@dthorpe Hi,

can you tell me how to generate first source.TransactionHash?
var txIn = new TxIn(new OutPoint(new uint256(source.TransactionHash), source.OutputIndex));
tx.AddInput(txIn);

**Comment by dthorpe** [comment]
@hitjariwala See the source code example at the top of this thread.  Add inputs to the tx, add outputs to the tx, sign the tx.  You can then compute the transaction hash with `tx.GetHash()`.  

Make sure you compute the hash only after all changes have been made to the transaction AND the transaction is fully signed.
