### ISSUE TITLE
No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by BartolomeoItaliano** [MetacoSA/NBitcoin#911]
Hi I tried to execute following command:

```
            var Rpc = new RPCClient(Bitcoin.Instance.Testnet);
            var block = Rpc.GetBlock(2);

```

What I ending up getting is following error. I am wondering if it might be something with my firewall, but I turned it off and it was still occurring. 

> System.Net.Http.HttpRequestException: 'No connection could be made because the target machine actively refused it.'

**Comment by NicolasDorier** [comment]
do you run bitcoin core?

**Comment by BartolomeoItaliano** [comment]
No, I don't.

**Comment by nopara73** [comment]
![image](https://user-images.githubusercontent.com/9156103/92933400-7ec5c600-f446-11ea-93f5-2b652bc16ac5.png)

**Comment by BartolomeoItaliano** [comment]
So there is no way to "getBlock" or any info without having your own full node setup? Yep?

**Comment by nopara73** [comment]
Well, there're always ways: https://github.com/Blockstream/esplora/blob/master/API.md#get-blockhash
