### ISSUE TITLE
TransactionBuilder cs1729 error

### ISSUE THREAD

**Issue by slimhd** [MetacoSA/NBitcoin#912]
i am currently trying to use `var builder = new TransactionBuilder();` to build my transactions but visual studio gives out this error
`CS1729 C# does not contain a constructor that takes 0 arguments`

**Comment by yahiheb** [comment]
You should pass a `Network` argument. https://github.com/MetacoSA/NBitcoin/blob/master/NBitcoin/TransactionBuilder.cs#L708
Or maybe you meant to use https://github.com/MetacoSA/NBitcoin/blob/master/NBitcoin/Network.cs#L2567

**Comment by slimhd** [comment]
I tried passing a Network argument but it still gives the same error with different number. `CS1729 C# does not contain a constructor that takes 1 arguments`
if you want to see the code i can send that part

**Comment by yahiheb** [comment]
> if you want to see the code i can send that part

Yes that would help.

**Comment by slimhd** [comment]
> > if you want to see the code i can send that part
> 
> Yes that would help.

this is not the full code this is the part im having issues about 

`public async void Send_Button_Click(object sender, RoutedEventArgs e)//i don't know why this is not working.. send help!
        {
            
            if(!String.IsNullOrEmpty(PayTo.Text) && !String.IsNullOrEmpty(Amount.Text))
            {
                
                try
                 {

                     var addressToSend = BitcoinAddress.Create(PayTo.Text, Network.Main);
                     var amountToSend = new Money(Convert.ToDecimal(Amount.Text), MoneyUnit.BTC);
                     var signingKeys = new HashSet<ISecret>();
                     var builder = new TransactionBuilder(Network.Main); //This line gives cs1729
                     if (Txfee != null)
                     {
                         foreach (var coin in Model.UnspentCoins)
                             NotEmptyPrivateKeys.ForEach(key =>
                             {
                                 if (key.ScriptPubKey == coin.ScriptPubKey) signingKeys.Add(key);
                             });
                         var tx = builder

                              .AddCoins(Model.UnspentCoins)
                              .AddKeys(signingKeys.ToArray())
                              .Send(addressToSend, amountToSend)
                              .SetChange(Model.changeScriptPubKey)
                              .SendFees(Txfee)
                              .BuildTransaction(true);
`

**Comment by slimhd** [comment]
> > if you want to see the code i can send that part
> 
> Yes that would help.

And this is the whole send button https://pastebin.pl/view/be500752

**Comment by yahiheb** [comment]
Using `var builder = Network.Main.CreateTransactionBuilder();` should solve your problem.

**Comment by slimhd** [comment]
> Using `var builder = Network.Main.CreateTransactionBuilder();` should solve your problem.

You sir, just saved my life! Thank you!
