### ISSUE TITLE
Test doesn't pass

### ISSUE THREAD

**Issue by yahiheb** [MetacoSA/NBitcoin#919]
The test added in https://github.com/MetacoSA/NBitcoin/commit/8c859d527d9e5acf0c37f82c37136f860de18984 doesn't pass https://github.com/MetacoSA/NBitcoin/blob/master/NBitcoin.Tests/transaction_tests.cs#L3330-L3333

**Comment by NicolasDorier** [comment]
ah sorry this method is me testing some code snippets, will remove the test

**Comment by NicolasDorier** [comment]
done
