### ISSUE TITLE
Qbitninja : false Broadcast success response

### ISSUE THREAD

**Issue by Ashish81** [MetacoSA/NBitcoin#934]
Initiated a transaction broadcast by writing `builder.Verify ` and then  `broadcastResponse = Client.Broadcast(tx);` the response `broadcastResponse.Success` is `true`
but actually I cant see that TX ID in Bitcoin explorer.

TxID = a0efea86e619db52084991c85cdc9602e5de4151942abe79918b9e3967a49b7c

It happens quite a lot time, many times i get false successful response.

**Comment by ArtjomP** [comment]
I have something like this with the latest NBitcoin versions. I've downgraded it to check find the exact issue. I'll write here later

**Comment by Ashish81** [comment]
Is qbit service out of sync or what ??

**Comment by NicolasDorier** [comment]
4 days again there was a mempool peak, which mean that some transaction were not properly relaying. This may be why.

**Comment by Ashish81** [comment]
Well then we have to verify tx on explorer after push, before assuming success.
