### ISSUE TITLE
Transaction Builder Constructor Error - CS1927" does not contain a constructor that takes 0 arguments

### ISSUE THREAD

**Issue by CMcGorty** [MetacoSA/NBitcoin#936]
![image](https://user-images.githubusercontent.com/44318968/98825345-5d5f6700-2402-11eb-9ac2-f72330c04ea1.png)

**Comment by nopara73** [comment]
Give a network parameter to it: `Network.Main` for mainnet, `Network.TestNet` for testnet or `Network.RegTest` for regtest.

**Comment by CMcGorty** [comment]
Unfortunately, I tried that but got
![image](https://user-images.githubusercontent.com/44318968/98840047-56415480-2414-11eb-91c9-71b5d0fc7c0c.png)

**Comment by yahiheb** [comment]
Using `var builder = Network.Main.CreateTransactionBuilder();` should solve your problem.

**Comment by CMcGorty** [comment]
Thanks! that did it
