### ISSUE TITLE
Coins from QBitNinjaClient passed to Transaction Builder - Error: WitnessProgramMissmatch

### ISSUE THREAD

**Issue by CMcGorty** [MetacoSA/NBitcoin#937]
The goal is to look up the available coins that can be spent, determine if we have enough to cover the request and feed them into the spend transaction.

                    // use QBitNinja to get the blance on this address
                    var client = new QBitNinjaClient(network);
                    **var balanceModel = await client.GetBalance(spenderBitcoinAddress);**
                    var balance = balanceModel.Operations.Sum(x => x.Amount.ToDecimal(MoneyUnit.BTC));

                    // Do we have enough to spend?
                    if (balance < walletSpend.Amount)
                        throw new Exception("Insufficient Funds");

                    // Find the unspent transactions we need to use to fund this payment
                    List<ICoin> outputReceived = new List<ICoin>();
                    foreach (var op in balanceModel.Operations)
                    {
                        foreach (var coin in op.ReceivedCoins)
                        {
                            if (coin.TxOut.ScriptPubKey == spenderBitcoinAddress.ScriptPubKey)
                            {
                                outputReceived.Add(coin);
                            }
                        }
                    }
...

 var transactionToSpend = txBuilder
                        **.AddCoins(outputReceived)**
                        .AddKeys(spenderBitcoinSecret)
                        .Send(receiverBitcoinAddress, Money.FromUnit(walletSpend.Amount, MoneyUnit.BTC))
                        .SendFees(minerFee)
                        .SetChange(spenderBitcoinAddress)
                        .BuildTransaction(true);

**The error that comes back is WitnessProgramMissmatch**

**Comment by NicolasDorier** [comment]
what type of address is it ? segwit? p2sh?

**Comment by CMcGorty** [comment]
Solved:  You are correct, I was using the root private key instead of the derived private key for the transaction.  Thanks!
