### ISSUE TITLE
MaybeNullWhen is not needed anymore (causes errors)

### ISSUE THREAD

**Issue by dangershony** [MetacoSA/NBitcoin#941]
Hi MaybeNullWhenAttribute causes errors for projects that enable Nullable
https://github.com/MetacoSA/NBitcoin/blob/973fd31be570cb460518ffa268fd7b9c62b44105/NBitcoin/NullableShims.cs

This type exists in the namespace already under `System.Diagnostics.CodeAnalysis` maybe it can now be removed?

**Comment by nopara73** [comment]
Interesting, we haven't encounter the errors it causes.

**Comment by dangershony** [comment]
This is the error, a collision of ns types
```

Error	CS0433	The type 'MaybeNullWhenAttribute' exists in both 
'NBitcoin, Version=5.0.65.0, Culture=neutral, PublicKeyToken=null' and 
'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'	```

**Comment by nopara73** [comment]
Anyhow it seems to be functionally the same.

**Comment by NicolasDorier** [comment]
@dangershony in which target you have the problem? It does not always exists in `System.Diagnostics.CodeAnalysis`.

**Comment by NicolasDorier** [comment]
Find something that work @dangershony I can't build with it on my side :/

**Comment by NicolasDorier** [comment]
I can change the namespace though one moment.

**Comment by NicolasDorier** [comment]
ah no if I change namespace it is other problem to fix everywhere. If I put in internal maybe it works? Can you try @dangershony

**Comment by dangershony** [comment]
Hi @NicolasDorier for now I just stopped using he attribute (I can survive without it) but it will become a problem n the future I suspect.
Compiling against netcoreapp3.1 and NBitcoin Version=5.0.65

Perhaps internal will work indeed 
> If I put in internal maybe it works? Can you try

How do I try? ah I can reference NBitcoin locally and check yeah let me try and get back
