### ISSUE TITLE
QbitNinja not responds many times

### ISSUE THREAD

**Issue by Ashish81** [MetacoSA/NBitcoin#947]
its happening many times that http://api.qbit.ninja/ not responds and service unavailable or too slow response/ response time out or http statuscode 503 . Can you please help in.
Please help me in starting my own node, indexer and ninja service. which repos should I clone.

**Comment by NicolasDorier** [comment]
I don't know, qbit is slightly retiring, you can go on https://github.com/MetacoSA/QBitNinja/ to fork it and see instructions to set it up.

That said, I would advise you now to use https://github.com/dgarage/NBXplorer  instead.
Reason is that QBitNinja is very heavy. It index everything, depends on Azure and run only on Windows.

NBXplorer does not need indexing, have better API for HD wallets and works on linux.

**Comment by Ashish81** [comment]
Yes I agree for NBXplorer, QbitNinja is unreliable now i guess.
