### ISSUE TITLE
Error with creation Verge(XVG) Network

### ISSUE THREAD

**Issue by artem03** [MetacoSA/NBitcoin#958]
When I try create XVG network (Verge.Instance.Mainnet;) I got exception "System.ArgumentException: 'An item with the same key has already been added. Key: verge-mainnet'"
I use latest version NBitcoin and NBitcoin.Altcoins

**Comment by NicolasDorier** [comment]
released new version with fix.

**Comment by artem03** [comment]
The problem is not fixed

**Comment by artem03** [comment]
There was a slightly different error: System.ArgumentException: 'An item with the same key has already been added. Key: verge-main'

**Comment by NicolasDorier** [comment]
should be now
