### ISSUE TITLE
secp256k1 minor naming question 

### ISSUE THREAD

**Issue by dangershony** [MetacoSA/NBitcoin#959]
This is very minor point but I noticed the names are reversed and I wonder if its a mistake 

ECPubKey.TryMultTweak
ECPrivKey.TryTweakMul

I think on the original its 

secp256k1_ec_pubkey_tweak_mul
secp256k1_ec_privkey_tweak_mul

so ECPubKey.TryMultTweak should become ECPubKey.TryTweakMul

https://github.com/MetacoSA/NBitcoin/blob/d1331dc2fd9bc7de18f30e9ae3baf2a2c1eb1545/NBitcoin/Secp256k1/ECPrivKey.cs#L854
https://github.com/MetacoSA/NBitcoin/blob/3d00206f4b159e8dc6c2305b960fad50982db4a2/NBitcoin/Secp256k1/ECPubKey.cs#L350

**Comment by NicolasDorier** [comment]
fixing

**Comment by dangershony** [comment]
I cant stress by the way how awesome it is you implemented secp256k1 in c# netstandard
