### ISSUE TITLE
Bitcoin mining

### ISSUE THREAD

**Issue by cheaterNo1** [MetacoSA/NBitcoin#975]
Dear Nbitcoin's admin!
As title, I want to ask Could I use Nbitcoin to develop a mining bitcoin software?

**Comment by dangershony** [comment]
Quick answer NO.

A more detailed answer is: 
Bitcoin uses specialized computers to mine (called ASICs).
If you mean you want to write a software that will interact between a bitcoin fullnode and an ASIC then perhaps yes NBitcoin can be used.

**Comment by BigEpidemic** [comment]
Of course you can. The previous answer is patently incorrect. The implementation of your miner (asic, cpu, gpu, something new) wasn't part of your question.

**Comment by dangershony** [comment]
> The implementation of your miner wasn't part of your question.  

Right.. and how did you come to that  conclusion?

**Comment by cheaterNo1** [comment]
> Of course you can. The previous answer is patently incorrect. The implementation of your miner (asic, cpu, gpu, something new) wasn't part of your question.

I want to write an app that use cloud resource to mining. The problem is I don't want to download the whole bitcoin core (about 300gb), it is better if I can use a library that have proof of work method.

**Comment by NicolasDorier** [comment]
The mining industry is quite complex and use a wide different set of software to make it possible. I am not expert in it.

I can only say that validating proof of work is not enough. And that trying to do cloud mining will cost you more money than making you money.
