### ISSUE TITLE
DNS seed queries are not done over Tor 

### ISSUE THREAD

**Issue by lontivero** [MetacoSA/NBitcoin#977]
It would be good to query dns seeds using Tor. https://www.reddit.com/r/WasabiWallet/comments/lvld6s/wasabi_not_going_over_tor/

**Comment by NicolasDorier** [comment]
It should if `SocksSettingsBehavior.OnlyForOnionHosts` is set to `true`.

**Comment by NicolasDorier** [comment]
Can see the code related to this at `DefaultEndpointConnector`

**Comment by lontivero** [comment]
I didn't explain myself clearly enough. What I say is that NBitcoin queries the DNS servers in the clearnet, this is done with `Dns.GetHostAddressesAsync(dns.Host)`. 

Sadly, I don't see an easy way to route those request through a proxy.

**Comment by NicolasDorier** [comment]
ah shit I see. Yeah, I don't see how we can do that.
That said NBitcoin could disallow DNS endpoints if Tor must be used.
Those DNS seed are not really useful, most seeds are ips, hard coded to bitcoin.

**Comment by DemonRx** [comment]
I don't know if this might be of much help, but I think you need to have the seeds actually running over Tor as well.

Refer to this article: https://developers.cloudflare.com/1.1.1.1/fun-stuff/dns-over-tor

**Comment by nopara73** [comment]
One can ask Tor to resolve DNS through the socks port. See an old C# implementation of mine: https://github.com/nopara73/DotNetTor/blob/fc438daa573145b12d4ae1d93364797858bc244f/src/DotNetTor/TorSocks5Client.cs#L391

Spec: https://gitweb.torproject.org/torspec.git/tree/socks-extensions.txt#n44

> As an extension to SOCKS4A and SOCKS5, Tor implements a new command value,
  "RESOLVE" [F0].  When Tor receives a "RESOLVE" SOCKS command, it initiates
  a remote lookup of the hostname provided as the target address in the SOCKS
  request.  The reply is either an error (if the address couldn't be
  resolved) or a success response.  In the case of success, the address is
  stored in the portion of the SOCKS response reserved for remote IP address.
