### ISSUE TITLE
unable to parse LTCTEST BIP32 public key

### ISSUE THREAD

**Issue by nwasiq** [MetacoSA/NBitcoin#996]
`ExtPubKey.Parse("ttubxxxBIP32_PUB_KEY", NBitcoin.Altcoins.Litecoin.Instance.Testnet);`

The above code returns the error: `Unhandled exception. System.FormatException: Invalid base58 string`

What should I do differently? I'm able to parse LTC BIP32 pub key just fine

**Comment by DanGould** [comment]
"ttubxxxBIP32_PUB_KEY" is, as the error describes, NOT a valid [base58](https://en.bitcoin.it/wiki/Base58Check_encoding) string. You need to pass a valid pubkey.

**Comment by nwasiq** [comment]
ofcourse this is not my real pub key. That same pubkey is works fine on bitcoinjs-lib so I know that it's valid

**Comment by nwasiq** [comment]
Solved the issue by adding a LitecoinTestnetAddressStringParser like the LitecoinMainnetAddressStringParser in the Litecoin class.

**Comment by NicolasDorier** [comment]
you made a PR?

**Comment by nwasiq** [comment]
Just did:

https://github.com/MetacoSA/NBitcoin/pull/1023
